### ISSUE TITLE
smart table pagination First and Last buttons issue

### ISSUE THREAD

**Issue by testchandp** [lorenzofox3/Smart-Table#105]
How to go to last page and firstpage at time of clicking on first button and last button smart table pagination...smart table div in html and i had rowcollection,columncollection and globalconfig then how to get command pagination of smart table to visit first and last buttons to show first and last page?

**Comment by sayoojvv** [comment]
**I Think This will do ... It worked for me** 

$templateCache.put('template/smart-table/pagination.html',
        '<nav ng-if="numPages && pages.length >= 2"><ul class="pagination">' +
        '<li><a ng-hide="currentPage==1" class="fa fa-angle-double-left" ng-click="selectPage(1)"></a></li><li ng-repeat="page in pages" ng-class="{active: page==currentPage}"><a ng-click="selectPage(page)">{{page}}</a></li><li><a ng-hide="currentPage==numPages" class="fa fa-angle-double-right" ng-click="selectPage(numPages)"></a></li>' +
        '</ul></nav>');
}]);

**Comment by sayoojvv** [comment]
**I Think This will do ... It worked for me** 

//$templateCache.put('template/smart-table/pagination.html',
     //   '<nav ng-if="numPages && pages.length >= 2"><ul class="pagination">' +
      //  '<li><a ng-hide="currentPage==1" class="fa fa-angle-double-left" ng-click="selectPage(1)">//</a></li><li ng-repeat="page in pages" ng-class="{active: page==currentPage}"><a ng-click="selectPage(page)">{{page}}</a></li><li><a ng-hide="currentPage==numPages" class="fa fa-angle-double-right" ng-click="selectPage(numPages)"></a></li>' +
        '</ul></nav>');
//}]);

**Comment by sayoojvv** [comment]
**I Think This will do ... It worked for me** 

`$templateCache.put('template/smart-table/pagination.html',
        '<nav ng-if="numPages && pages.length >= 2"><ul class="pagination">' +
        '<li><a ng-hide="currentPage==1" class="fa fa-angle-double-left" ng-click="selectPage(1)"></a></li><li ng-repeat="page in pages" ng-class="{active: page==currentPage}"><a ng-click="selectPage(page)">{{page}}</a></li><li><a ng-hide="currentPage==numPages" class="fa fa-angle-double-right" ng-click="selectPage(numPages)"></a></li>' +
        '</ul></nav>');
}]);`
