### ISSUE TITLE
Row grouping (with collapse/expand button) would really bring it to the next level.

### ISSUE THREAD

**Issue by ghost** [lorenzofox3/Smart-Table#108]
Allowing 2 or more consecutive rows to be grouped and presenting an expand/collapse button for the group would be a really nice add-on.
Actually, we are using this feature in a project and were tinkering with the ideea of jumping ship to Smart-Table, but the lack of it is a show stopper for now - probably it isn't so much of a deal to find a workaround, but integrating it as a feature in the module would be great. 

Keep up the good work!

**Comment by JimmyBoh** [comment]
Any particular explanation as to why this was closed? Did someone implement a plugin that does it? Is it now a built in module?

**Comment by lorenzofox3** [comment]
this issue is related to the old version of smart-table.
There is a pull request about integrating it in the current version https://github.com/lorenzofox3/Smart-Table/pull/331 which I am not sure it is going to be merged as you can achieve grouping by simply adding an external filter as shown in this [plunker](http://plnkr.co/edit/qg4y7mtd7nnXtlRlc6SF?p=preview)

**Comment by abhilashpullelil** [comment]
But, this type of grouping is just grouped the rows in each page. That is, in the above plunker you can see that there is a group for "Super Man" in the first and second page. I need to group all the rows of the table under the grouping key.

More specific : If I group the data by name "all the rows which has name Super Man" should be displayed under the group "Super Man". If possible do a pagination under each group as it may be have 100 of records under a group.

Can I do this with Smart Table?

**Comment by aishuiyer2001** [comment]
@adrianvoica I have the exact same requirement. I am in search for a grid library and this missing 'row grouping with expand/collapse' feature is the only thing holding me back from recommending 'Smart Table' to my team. Did you ever figure out a work around for this?

**Comment by MijaelWatts** [comment]
Why is this issue closed? Did anyone find a solution?
