### ISSUE TITLE
Sorting with multiple fields

### ISSUE THREAD

**Issue by jay4smile** [lorenzofox3/Smart-Table#124]
Hello All,

I have table data in which I have following columns : ['filename','date','download']
I have one process which generates the file.. File can be "successfully generated" or "generation failed". For successfully generated I have successflag=3 and for generation failed I have successflag=4;

When user clicks on download to sort data. in descending order I want to display data in most recently failed ('date') with failed status('successflag'=4). and in ascending order I want to display files which most recently generated with success status ('successflag'=3).

So,How to achieve that? I had tried to provide sortPredicate on download column in belo way

sortPredicate: function(dataRow){
    return (-dataRow.date,dataRow.successflag);
}

but it's not working.
Can anyone help me?

Thanks in advance,
Jay Patel

**Comment by colegleason** [comment]
Hi, I also have this question but am unable to view the plunkr. Would you mind elaborating on what that showed?

**Comment by stefan-leye** [comment]
The plunkr is empty.

**Comment by SushantKadam008** [comment]
Hi,
The plunker is empty. Did any one find the solution for this ?
