### ISSUE TITLE
Searching removes lines with null values

### ISSUE THREAD

**Issue by zelk** [lorenzofox3/Smart-Table#161]
Create a table with a few columns and rows and add search boxes for each column. Make sure that some cells have text values, some cells have empty strings and some cells have nulls.

Notice than when you type in one of the search boxes and then remove the characters again, some lines will totally disappear. The ones that disappear are the ones with null values in the column you searched. Continuously doing this for each column means that you will eventually end up with very few lines.

The easiest way to fix the bug is probably to set the search criteria back to null instead of empty string when a search input box is empty.

**Comment by shaunakv1** [comment]
I am still seeing issue, accept my data initiates with a []  then loads over AJAX. However, I don't make any further modifications on the data
