### ISSUE TITLE
clear all filters button

### ISSUE THREAD

**Issue by clickwhit** [lorenzofox3/Smart-Table#164]
It might just be too late at night but I can't for the life of me figure out how to make this work.

I have several st-search inputs and I want to create a button that will clear all of them. I added ng-models to them (because I'm doing other functionality with these inputs) and a button that clears those models, but the filters just come back. 

```
---view.html---
<th>
  <input st-delay="100" st-search="'city'" placeholder="Filter or add city" class="input-sm form-control" ng-model="city" type="search"/>
</th>
<th>
  <input st-delay="100" st-search="'state'" placeholder="State" class="input-sm form-control" ng-model="state" type="search"/>
</th>
---controller---
$scope.clear = function() {
  $scope.city = '';
  $scope.state = '';
};
```

In stSearch.js I see this:

```
if (newValue.predicateObject && newValue.predicateObject[predicateExpression] !== element[0].value) {
                            element[0].value = newValue.predicateObject[predicateExpression] || '';
                        }
```

which I believe is changing the value of the element back to the original text, but I can't figure out what use case it would be for. 

Any help please?

**Comment by JanStevens** [comment]
A complete directive to clear any search form, include it on the clear button `st-reset-search`. Note that im programming in coffee script, it can be easily converted to plain JS.

```coffee
@appDirectives.directive 'stResetSearch', ->
  restrict: 'EA',
  require: '^stTable',
  link: (scope, element, attrs, ctrl) ->
    element.bind('click', ->
      scope.$apply( ->
        tableState = ctrl.tableState()
        tableState.search.predicateObject = {}
        tableState.pagination.start = 0
        ctrl.pipe()
      )
    )
```

I also reset the page back to 1 (incase they where on page 3)

I've also created a submit button search (in some edge cases quite useful)

```coffee
@appDirectives.directive 'stSubmitSearch', ->
  restrict: 'EA',
  require: '^stTable',
  link: (scope, element, attrs, ctrl) ->
    element.bind('click', ->
      scope.$apply( ->
        ctrl.pipe()
      )
    )
```

**Comment by lorenzofox3** [comment]
thanks for sharing !

**Comment by BobKurtis** [comment]
Here's the module if you want to tack it on to smart-table.js
```
 t.module("smart-table").directive("stResetSearch", function() {
    	 console.log("ah yeah");
    	 return {
    		    restrict: 'EA',
    		    require: '^stTable',
    		    link: function(scope, element, attrs, ctrl) {
    		      return element.bind('click', function() {
    		        return scope.$apply(function() {
    		          var tableState;
    		          tableState = ctrl.tableState();
    		          tableState.search.predicateObject = {};
    		          tableState.pagination.start = 0;
    		          return ctrl.pipe();
    		        });
    		      });
    		    }
    		  };
    })
```
and then calling it with a button like
```
<button type="button" st-reset-search>Clear Filters</button>
```
it needs to be in the table that your st-table is declared

**Comment by 4rlekin** [comment]
This really should be at least established in documentation if not included into project repo

**Comment by gnanaveln** [comment]
May i have working example for the above "<button type="button" st-reset-search>Clear Filters</button>" solution

**Comment by BobKurtis** [comment]
All you need to do is add the module that I wrote to your smart-table.js. Then anywhere that you have a functioning "smart table" you can call the reset function just like you would any other smart table method. I used a button to call the method as such
```<button type="button" st-reset-search>Clear Filters</button>```
Just as long as the button is within the declaration of your smart table in your html file it should work. Don't forget to clear browser cache in order to pull in the new code.

**Comment by SheelaJasmine** [comment]
This Directive just resets the smart table but not clearing the filter fields.

 t.module("smart-table").directive("stResetSearch", function() {
         return {
                restrict: 'EA',
                require: '^stTable',
                link: function(scope, element, attrs, ctrl) {
                  return element.bind('click', function() {
                    return scope.$apply(function() {
                      var tableState;
                      tableState = ctrl.tableState();
                      tableState.search.predicateObject = {};
                      tableState.pagination.start = 0;
                      return ctrl.pipe();
                    });
                  });
                }
              };
    })



Tried to clear each colunm using Javascript 
scope.name='';
scope.Age=''
....

Its clearing the fields.But causing problem when i try to search again already cleared fields are appearing again...

**Comment by b3nd** [comment]
@SheelaJasmine : We are experiencing exactly the same problem. Fields are getting cleared, but filled in again when entering a new search.
Did you already manage to solve this?

**Comment by russellpipal** [comment]
This directive is also not working for me. It resets the table but leaves the search field filled. Anyone have any ideas?

**Comment by BobKurtis** [comment]
This is what my table looks like for a drop down list 
 `<input st-search="'form_number'"
					ng-model="selectedFormNumber" id="formList"
					ng-model-options="{updateOn: 'default blur', debounce: {default: 500, blur: 0} }"
					class="input-sm form-control" type="text" /> 
					<select
					ng-model="selectedFormNumber" ng-change="simEnter()"
					ng-options="row as row for row in uFormNumbers | orderBy: row"></select>`

and this is what it looks like for a free form text 
`<input st-search="'first_name'" class="input-sm form-control" type="search" placeholder="First Name"/>`

this is what simEnter() is 
`$scope.simEnter = function() {
				var e = $.Event('keydown');
				e.which = 13; // Character 'A'
				$("#formList").trigger(e);
				console.log("sim hit");
			};`

This works with the reset search that i posted earlier in this thread

Noted i am using smartTable version 1.4.9,

**Comment by kameelyan** [comment]
Working great for me Bob, should definitely be added to the .js in my opinion.

**Comment by Xsmael** [comment]
@lorenzofox3 
> Actually it might be interesting to change stSearch code (and also stSort and stPagination) to work with ngModel so it can be controlled from outside the table, but it means keep in sync the view, the scope and the table state. I am going to think about it.

That would be great! are you still planning to do that ?

**Comment by azimuthdeveloper** [comment]
How do you do this programatically?  So, from the controller code in AngularJS.

**Comment by C5harp** [comment]
How do you do this programmatically? Any responses? I need to clear the search when checkboxes are selected and / or unselected.
