### ISSUE TITLE
Pagination not working when data gets updated through AJAX

### ISSUE THREAD

**Issue by premsh** [lorenzofox3/Smart-Table#169]
I created a sample where data is generated on client side and pagination works well. 

However, when I created another sample where data is loaded dynamically through AJAX, the pagination isn't working. The pagination control is hidden as it assumes there are less than 2 rows. 

I am not super new to AngularJS, but I couldn't figure it out.

**Comment by quardz** [comment]
It's working fine with 1.2.x but not with 1.3+

**Comment by zoolu1439** [comment]
I have the same problem - pagination is not working when I use an external api call to get the data. I did not try by using angularjs 1.2.22; but it is still not working. I would really appreciate if somebody can help me fix this problem.

**Comment by zoolu1439** [comment]
Never mind..Got it working..Thanks Laurent.

**Comment by richardblynd** [comment]
I try to use smart-table with Angular Material (ngMaterial) and when the page is changed the data in the table are momently duplicated.

[http://plnkr.co/edit/LoF8ivUZQ6v3NYaFsynK?p=preview](url)
