### ISSUE TITLE
Search not working against sub-elements

### ISSUE THREAD

**Issue by kikonen-fiksu** [lorenzofox3/Smart-Table#184]
I had model something like this

``` javascript
{
   name: 'xxx',
   child: {
     state: 'yyy',
   }
}
```

And tried to define search to match against "child.state". However, it doesn't seem to work. I was expecting that to work, since for same column st-sort="child.state", seems to work.

**Comment by eranimo** [comment]
The st-set-filter option doesn't appear to be working.
