### ISSUE TITLE
Controller 'stTable', required by directive 'stPagination', can't be found!

### ISSUE THREAD

**Issue by dmackerman** [lorenzofox3/Smart-Table#204]
I'm using ui-router, and I seem to run into this error quite a bit when loading a child state when it's parent has a `st-table` on it. 

Example:

`locations` (has an stTable)
`locations.detail` (no stTable, get the error)

**Comment by rscafi** [comment]
@lorenzofox3 I'm having the same issue when the child state changes the whole view.

```html
<div ui-view>
    st-table with pagination
</div:
```

**Comment by dmackerman** [comment]
Yeah, just started another project and running into this again :smile:

**Comment by dmackerman** [comment]
I've found a temporary solution is to just only render the table if the current state is active, something like `ng-if="app.state.is('app.whatever.state')"`.

**Comment by mattymess** [comment]
Did you ever figure out a better solution to this? I'm experiencing the exact same thing. I have two states, each with a `smart-table`, where when I transition between the states, the `Error: [$compile:ctreq] Controller 'stTable', required by directive 'stSelect', can't be found!` error is thrown.

**Comment by ganholete** [comment]
Same problem. I get same error when starting in a child state with ui-router

**Comment by Fredo182** [comment]
how about setting required in the directive to 

require: '?^stTable',

**Comment by ganholete** [comment]
I updated ui-router to the latest version and the problem was solved
