### ISSUE TITLE
Please use angular.equals while watching stSafeSrc Objects.

### ISSUE THREAD

**Issue by xunkutech** [lorenzofox3/Smart-Table#205]
Hi, 

The listener function of Angular $watch uses reference check when the watched target is an array object. So if I replace an element in the safe source array(the length of array is not changed), it will not trigger the listener function. The display array will not updated accordingly.

The solution is to set the third parameter as 'true' in $watch function, which will force the $watch function to compare for object equality using angular.equals instead of comparing for reference equality. And remove the unnecessary length check watching function.

Thanks.

**Comment by a11smiles** [comment]
FYI, the above doesn't entirely work if there is a custom directive on a table column (i.e. for a column that is "true" I'm displaying a green checkmark, for "false" nothing).  While the underlying arrays are updated correctly, the displayed results (formatting) is not.  There's two ways you can do it...

1) Reset the displayedData (this will force the current display to refresh)

        $scope.$on('setAuthorization', function (event, data) {
            angular.forEach($scope.usersData, function (u, i) {
                if (u.Id === data.UserId) {
                    $scope.usersData[i].IsAuthorized = data.IsAuthorized;
                }
            });

            $scope.displayedData = angular.copy($scope.displayedData);
        });

This way I'm only copying the displayed data and not the *entire* collection.

2) Use a directive on the column:

    mc.directive('csBoolean', function ($compile) {
        return {
            require: '^stTable',
            scope: {
                row: '=csBoolean'
            },
            link: function (scope, element) {
                scope.$watch('row.IsAuthorized', function (value) {
                    if (value)
                        element.html('<i class="fa fa-check fa-2x green"></i>');
                    else
                        element.html('<span />');
                });
            }
        }
    });

With my table row having:

    <td cs-boolean="row" class="text-center"></td>

If I use the second approach, I don't need the following line in my above code as the watcher will update the column's view:

            $scope.displayedData = angular.copy($scope.displayedData);

**Comment by SmallBookworm** [comment]
> Hello,
> 
> I have been waiting for this issue for a while now :D
> 
> The main reason the watch are built as they are at the moment is for performance.
> If you add a third parameter `true` to the watch function, angular will keep in memory a copy of the whole array for dirty checking (higher memory usage) and will go through every property of every item on each digest loop which will also impact the performances. So if you can afford it (your dataset is small), do it. It is less troublesome; but I am not going to change it in smart-table.
> 
> The main use case I see where it can be annoying is
> 
> 1. You edit one of the item (or a copy of it)
> 2. Send to the server.
> 3. The server send the updated item to you.
> 4. you want to replace it your collection.
> 
> What I do is I simply overwrite the properties of the reference in the collection.
> 
> ```js
> httpService.update(item)
>     then(function(updatedItem){
>         //this will keep the same reference so the table will be updated !
>         ng.extend(item, updatedItem);
>     });
> ```
> 
> this work great for me without impacting the performance. The only problem is if your updated item has less properties than the old one...then you will have to delete them
> 
> ```js
> var oldItem={
>     prop1:'val1',
>     prop2:'val2'
> };
> 
> var updatedItem={
>     prop1:'val1Updated',
>     prop3:'val3'
> };
> /*
> if you expect the newItem to be 
> {
>     prop1:'val1Updated',
>     prop3:'val3'
> };
> 
> the above technique won't work as you will get
> {
>     prop1:'val1Updated',
>     prop2:'val2,
>     prop3:'val3'
> };
> */
> ```

You shouldn't say:"//this will keep the same reference so the table will be updated !".It is misleading.$watch listen for object reference change.
