### ISSUE TITLE
Clear all filter inputs

### ISSUE THREAD

**Issue by marcelinhov2** [lorenzofox3/Smart-Table#208]
Hello,

I'm trying to create a button that clear all the st-search that I have inside my table. The problem is, when I set the value of the input to '\nothing\', it didn't refresh the filters inside the table. With this scenario, I tried to "reload" the objects inside my scope to the default value, but for some reason, the filters that I'd cleaned before, make a mess inside my object and I don't have the default values that I want.

Does anyone already did or know some way to generate this button?

Thanks.

**Comment by trajano** [comment]
This is the directive I wrote to handle this

````
app.directive('stClearSearch', function() {
    return {
      restrict: 'A',
      require: '^stTable',
      link: function (scope, element, attr, ctrl) {
        element.on('click', event => {
          event.preventDefault();

          var predicate = attr.stClearSearch;
          var search = ctrl.tableState().search

          ctrl.search('', predicate)
        })
      }
    };
  })
````

In the HTML it is done as follows

````
<div class="input-group input-group-sm col-md-12">
  <input st-search="name" placeholder="name search"
    class="form-control"
    type="search"/>
  <span class="input-group-btn">
    <button st-clear-search="name"
                 class="btn btn-secondary" type="button"><i
                 class="fa fa-eraser"> </i></button></span>
</div>
````

**Comment by jignesh2141** [comment]
I have tried everything but nothing work for me. I want to reset filters and pagination. Anybody can help me how can I do that ?

`<th colspan="3"><input st-search="LASTNAME" class="form-control" placeholder="Last Name" type="text"/></th>
                        <th colspan="3"><input st-search="FIRSTNAME" class="form-control" placeholder="First Name" type="text"/></th>
                        <th colspan="6"><input st-search="" class="form-control" placeholder="global search ..." type="text"/></th>`

above are my filters

`<div st-pagination="" st-items-by-page="itemsByPage" st-displayed-pages="10"></div>`

This is a pagination

I want to clear both things when click on CLEAR button.
