### ISSUE TITLE
Memory leak issue

### ISSUE THREAD

**Issue by anoopov** [lorenzofox3/Smart-Table#215]
Hi,

This is great angularjs table. Nice work!

I am facing huge memmory leak when i used the samrt table in phone gap hyrbrid single page application.RAM usage of application huge when i used smart table. I am using multiple smart tables in single page.RAM usage is increasing after each root change.Please help me to solve this issue.Thanks in advance..

My Smart table directive added blow..

.directive('smartTable', ['templateUrlList', 'DefaultTableConfiguration', function (templateList, defaultConfig) {
            return {
                restrict: 'EA',
                scope: {
                    //columnCollection: '=columns',
                    dataCollection: '=rows',
                    config: '='
                },
                replace: true,
                template: "<table table-scroll class=\"smart-table\">\n" +
    "   <thead ng-class=\"{'head-no-need':!displayedCollection.length}\" >\n"  +
    "    <tr class=\"smart-table-global-search-row\" ng-show=\"isGlobalSearchActivated\">\n" +
    "        <td class=\"smart-table-global-search\" column-span=\"{{columns.length}}\" colspan=\"{{columnSpan}}\">\n" +
    "        </td>\n" +
    "    </tr>\n" +
    "    <tr class=\"smart-table-header-row\">\n" +
    "        <td   >"+
    "        <div bindonce ng-repeat=\"column in columns\" ng-include=\"column.headerTemplateUrl\"\n" +
    "            class=\"smart-table-header-cell {{column.headerClass}}\" scope=\"col\"  tbl-col-map>\n" +
    "           </div>"+
    "        </td>\n" +
    "    </tr>\n" +
    "    </thead>\n" +
    "    <tbody>\n" +
    "    <tr bindonce ng-repeat=\"dataRow in displayedCollection\" bo-class=\"{selected:dataRow.isSelected, }\"\n" +//'new-row-notif':
    "        class=\"smart-table-data-row \" >\n" +
    "        <td >"+
    "<div bindonce ng-repeat=\"column in columns\" class=\"smart-table-data-cell {{column.cellClass}}\" tbl-col-map>&nbsp;</div>    "+
    "       </td>\n" +
    "    </tr>\n" +
    "    <tr ng-hide=\"displayedCollection\">\n" +
    "        <td >"+
    "           <div class=\"no-data\" > No Records Found</div> "+
    "       </td>\n" +
    "    </tr>\n" +
    "    </tbody>\n" +
    "    <tfoot ng-show=\"(isPaginationEnabled && showPagingPane) || $parent.$parent.$parent.policyLevelCommission\" style=\"border:0px\" >\n" +
    "    <tr style=\"border:0px\"  ng-show=\"$parent.$parent.$parent.policyLevelCommission && displayedCollection\"  class=\"smart-table-data-row policy-commission \" >\n" +
    "        <td>\n" +
    "            <div bindonce ng-repeat=\"column in $parent.$parent.$parent.footer\" class=\"smart-table-data-cell {{column.cellClass}}\" tbl-col-map>&nbsp;[[ column ]]</div> "+
    "        </td>\n" +
    "    </tr>\n" +
    "    <tr style=\"border:0px\"  ng-show=\"showPagingPane\"  >\n" +
    "        <td   enable-pane page=\"showPagingPane\" style=\"border:0px;padding-right:15px; padding-left:10px;\" colspan=\"{{columns.length}}\" align=\"left\">\n" +
    "            <div pagination-smart-table=\"\" num-pages=\"numberOfPages\" max-size=\"maxSize\" current-page=\"currentPage\" ></div>\n" +
    "        </td>\n" +
    "    </tr>\n" +
    "    </tfoot>\n" +
    "</table>\n" +
    "\n" +
    "\n",

```
            controller: 'TableCtrl',
            link: function (scope, element, attr, ctrl) {

                var templateObject;
                var obj = scope.$eval(attr.columns);

                scope.columnCollection = obj;

                //var tempConfig = scope.$eval(attr.config);
                //scope.config = tempConfig;
                //  var newConfig = angular.extend({}, defaultConfig, config),
                //  length = scope.columns !== undefined ? scope.columns.length : 0;
                //ctrl.setGlobalConfig(newConfig);

                var watch1=scope.$watch('config', function (config) {
                    var newConfig = angular.extend({}, defaultConfig, config),
                    length = scope.columns !== undefined ? scope.columns.length : 0;

                    ctrl.setGlobalConfig(newConfig);

                    //remove the checkbox column if needed
                   if (newConfig.selectionMode !== 'multiple' || newConfig.displaySelectionCheckbox !== true) {
                        for (var i = length - 1; i >= 0; i--) {
                            if (scope.columns[i].isSelectionColumn === true) {
                                ctrl.removeColumn(i);
                           }
                        }
                   } else {
                  //add selection box column if required
                        ctrl.insertColumn({cellTemplateUrl: templateList.selectionCheckbox, headerTemplateUrl: templateList.selectAllCheckbox, isSelectionColumn: true}, 0);
                   }
                }, true);
                //insert columns from column config
                //scope.$watch('columnCollection', function (oldValue, newValue) {

                    ctrl.clearColumns();

                    if (scope.columnCollection) {
                        for (var i = 0, l = scope.columnCollection.length; i < l; i++) {
                            ctrl.insertColumn(scope.columnCollection[i]);
                        }
                    } else {
                        //or guess data Structure
                        if (scope.dataCollection && scope.dataCollection.length > 0) {
                            templateObject = scope.dataCollection[0];
                            angular.forEach(templateObject, function (value, key) {

                                if (key[0] != '$') {
                                    ctrl.insertColumn({label: key, map: key});
                                }
                            });
                        }
                    }
                //}, true);
                //if item are added or removed into the data model from outside the grid
                var watch2=scope.$watch('dataCollection', function () {
                        ctrl.sortBy();//it will trigger the refresh... some hack ?

                },true);

                //if item are added or removed into the data model from outside the grid
               var watch3=scope.$watch('dataCollection.length', function (oldValue, newValue) {

                    if (oldValue !== newValue) {
                        ctrl.sortBy();//it will trigger the refresh... some hack ?
                    }
                },true);
                scope.$on('$destroy', function() {
                watch1();
                watch2();
                watch3();
                element.remove();
                dataCollection=null;

                });

            }
```

**Comment by olso** [comment]
Also maybe you could try to one-way bind with

```::variable```
