### ISSUE TITLE
How to put the search box out of the table?

### ISSUE THREAD

**Issue by drantunes** [lorenzofox3/Smart-Table#220]
Doing some tests I can not put the search field out of the table. 
For example, I have a search box in the header and I want this field to filter the table.

The following test has filtered the data table, but the pagination remained static (not filtered like the original st-pagination works over the st-search).

```
</table>
<input st-table="myData" st-search ng-model="test" placeholder="global search ..." type="text"/>
```

How to solve this? 

Thanks.

**Comment by nickdevereaux** [comment]
FWIW I've updated the broken link in the plunker example for posterity: 

http://plnkr.co/edit/dpmSdEaL2Xuyb1BWLbVh?p=preview

**Comment by pdarscht** [comment]
this is not working together with st-pipe. Error:
```Error: [$compile:multidir] Multiple directives [searchWatchModel, stPipe] asking for new/isolated scope on: <table search-watch-model="filterprod2" st-pipe="callServer" st-table="displayed" class="table table-striped" style="display: table-row-group;">

**Comment by nickdevereaux** [comment]
@pdarscht you can't use your custom directive that's demanding it's own scope as well as smart-table. In the Plunkr above you'll see the scope has it's own variables, so make sure when you created that directive you set the scope variables up as linked.

**Comment by pdarscht** [comment]
Thank you for your answer. Meanwhile, I´ve tried  @lorenzofox3 ´s comment and put the stpipe and sttable directive "on a element which wrap the table" and it worked fine.

**Comment by ramirescm** [comment]
@pdarscht i have the same problem

  how comunicate table st-pipe with external button and filter?
  
  <input ng-model="timeListCtrl.searchInput" type="text">
  <button ng-click="timeListCtrl.search()" type=button>Search</button>

  <div st-table="teamListCtrl.items"  st-pipe="teamListCtrl.callServer">
    <table class="table" search-watch-model="teamListCtrl.searchInput">
	...
        <tr ng-repeat="i in teamListCtrl.items">
         ...
        </tr>
    ...
    </table>
  </div>
  
   in function search i can call the function callServer? and how the param is pass to callServer?

**Comment by ramirescm** [comment]
<pre>
  how comunicate table st-pipe with external button and filter?
  
  > <input ng-model="timeListCtrl.searchInput" type="text">
  > <button ng-click="timeListCtrl.search()" type=button>Search</button>
  > <button ng-click="timeListCtrl.clear()" type=button>Clear</button>

  > <div st-table="timeListCtrl.items"  st-pipe="timeListCtrl.callServer">
  >   <table class="table" search-watch-model="timeListCtrl.searchInput">
	
        <tr ng-repeat="i in timeListCtrl.items">
     
        </tr>
  
    </table>
  </div>
 </pre>

**Comment by ramirescm** [comment]
@pdarscht  how comunicate table st-pipe with external button and filter?
  
     <input ng-model="myListCtrl.searchInput" type="text">
     <button ng-click="myListCtrl.search()" type=button>Search</button>
     <button ng-click="myListCtrl.clear()" type=button>Clear</button>
      <div st-table="timeListCtrl.items"  st-pipe="timeListCtrl.callServer">
          <table class="table" search-watch-model="timeListCtrl.searchInput">
                 <tr ng-repeat="i in myListCtrl.items">
     
                 </tr>
          </table>
      </div>
I try put the stpipe and sttable directive "on a element which wrap the table"  but when i click in search button don't work.

**Comment by lorenzofox3** [comment]
http://plnkr.co/edit/Kao9707ikzstbvqLFAcc?p=preview

**Comment by ramirescm** [comment]
I get to make the paging on the server side would have to use st-pipe..
I have to filter on the server side and return the list of paged results.
But the problem is executed the query only when you click the search button.

**Comment by ramirescm** [comment]
Now works fine, i found the problem!

Thank you!

**Comment by smiddela** [comment]
I am not able to get the below thing working. I have been working on this from yesterday and was not able to get it working. Not sure what is going wrong. I followed the exact steps from the tutorial and checked and rechecked if I have included all the necessary script files and angular directives. Not sure what is going wrong here.

``
<html>
<head>
<script src="./jslib/smart-table.min.js"></script>
</head>

<body>
          <div id="rp" class="hlb">
                <div id="rp1"  ng-controller="RightTableCtrl">

                    <table st-table="deviceDataDisplay" st-safe-src="deviceData" class="table table-striped">
                        <thead>
                            <tr>
                                <th st-sort="time">time</th>
                                <th st-sort="car_num">car_num</th>
                                <th st-sort="rpm">rpm</th>
                                <th st-sort="speed">speed (km/hr)</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr ng-repeat="(deviceid, car) in deviceDataDisplay">
                                <td>{{car.time | date:'MM-dd-yyyy HH:mm:ss'}}</td>
                                <td>{{car.car_num}}</td>
                                <td align="right">{{car.rpm}}</td>
                                <td align="right">{{car.speed}}</td>
                            </tr>
                        </tbody>
                    </table>
</body>
</html>
``

**Comment by smiddela** [comment]
<pre>
var myroot = angular.module('myroot', ['googlechart', 'ui.bootstrap', 'ngTable', 'smart-table']);

myroot.controller('RightTableCtrl', function($scope, $http,
                                             SelectedCustomer, NgTableParams,
                                             InitDeviceInfo, MyMQTT) {

    $scope.deviceData = MyMQTT.getDeviceInfo();
    $scope.carInfo = [];
    $scope.selectedCustomer = SelectedCustomer.getSelectedCustomer();


    $scope.filterSelectedCustomer = function (deviceData) {
        var result = {};
        angular.forEach(deviceData, function(car, deviceid) {
            //console.log(car);

            if(car.customer_name == SelectedCustomer.getSelectedCustomer().name &&
            car.time != '' && car.time != undefined) {
                //console.log(car.customer_name + ", " + SelectedCustomer.getSelectedCustomer().name)
                result[deviceid] = car;
            }
        })
        return result;
    }

    $scope.updateDeviceData = function() {
        $scope.deviceData = $scope.filterSelectedCustomer(MyMQTT.getDeviceInfo());
        // This prints data
        console.log($scope.deviceData);
    }
});

</pre>
