### ISSUE TITLE
Fix header table with border is not aligned

### ISSUE THREAD

**Issue by suriyanto** [lorenzofox3/Smart-Table#222]
Hi,

I am trying to incorporate smart table into our site and use the Fix Table sample from the site. However when I add table border (table-bordered) style, the border appears but it is not aligned between the fix header and the body.

Please see the forked plunkr at: http://plnkr.co/edit/Q8iLHU

Any suggestion on how to align?

Thanks,
Suriyanto

**Comment by jdwilemo** [comment]
I'm having the same issue, and it's there in the Plunkr for the fixed header example on your site: http://plnkr.co/edit/Q8iLHU?p=preview
with the age/email/balance columns beginning to misalign.
