### ISSUE TITLE
table render on setting custom tableState

### ISSUE THREAD

**Issue by Nesse** [lorenzofox3/Smart-Table#235]
I've created a table and use the pipe/ajax functionality. Everything is working just fine. Now I want to save my tableState on leaving the current view, and reinitialize the saved tableState on the next visit. But when I set the tableState on returning visit ,the table is not rendered according to the tableState. (filters, paging, sorting, ...) Is there a way to re-render the table after setting the tableState?

**Comment by dsludwig** [comment]
It seems like the problem occurs here:

https://github.com/angular/angular.js/blob/master/src/Angular.js#L869

When there is no predicate (i.e. attribute) set, the `predicateObject` defaults to setting the `"$"` property (meaning search all properties), and this is ignored in the `angular.equals` check.

**Comment by jvisser72** [comment]
Hi Lorenzo,

This is still an issue with smart-table 2.0.1. The predicateObject uses the "$" and so the change is not noticed by angular.equals using the stPersist code:
```javascript
.directive('stPersist', function () {
        return {
        require: '^stTable',
        link: function (scope, element, attr, ctrl) {
            var nameSpace = attr.stPersist;

            //save the table state every time it changes
            scope.$watch(function () {
                return ctrl.tableState();
            }, function (newValue, oldValue) {
                if (newValue !== oldValue) {
                    localStorage.setItem(nameSpace, JSON.stringify(newValue));
                }
            }, true);

            //fetch the table state when the directive is loaded
            if (localStorage.getItem(nameSpace)) {
                var savedState = JSON.parse(localStorage.getItem(nameSpace));
                var tableState = ctrl.tableState();
                angular.extend(tableState, savedState);
                ctrl.pipe();
            }
        }
    };
})
```
Any ideas?

Thanx in advance

**Comment by sbervinov** [comment]
Hi, looks like you stPersist directive does not work. It restores search string only (value of st-search), but does not restore sorting and current page. May be it is because I use st-safe-src. Can you help me how can I solve this problem?

Thanks
