### ISSUE TITLE
How to have pagination outside <table>?

### ISSUE THREAD

**Issue by mirko77** [lorenzofox3/Smart-Table#236]
I would need to place the pagination markup outside of the table, so It is possible to scroll horizontally on big tables and the pagination buttons do not scroll with the table.

If I move the markup from the example out of the table, it fails as it does not find the requested controller `Error: [$compile:ctreq] Controller 'stTable', required by directive 'stPagination', can't be found!`

Any suggestion?

**Comment by IvanPrytsko** [comment]
Thanks for @dattanchu

**Comment by Ethergeist** [comment]
Excellent. Thanks @dattanchu
