### ISSUE TITLE
Use Multiple levels sort using st-sort directive

### ISSUE THREAD

**Issue by opeled** [lorenzofox3/Smart-Table#241]
Multiple sort predicates cannot be currently used.

In case the stSort directive will also allow an array of functions (and not only check that 'ng.isFunction(getter(scope)'), then multiple level sort can be used.

**Comment by aidanlister** [comment]
http://ui-grid.info/ supports ordering by multiple columns, so we can learn some lessons from that?

What would the backend code look like to sort by multiple columns? In my use case, I always want inactive columns to appear last regardless of what the user is sorting or filtering by. Is that possible?
