### ISSUE TITLE
st-search not working for select input in Firefox

### ISSUE THREAD

**Issue by bavicj** [lorenzofox3/Smart-Table#254]
Hi,

I am developing table with dropdown filters. I noticed that everything is fine in chrome and safari, but firefox does not work. 
I found the problem in definition of directive stSearch. Problem is that it binds only to event "input", which is not fired in Firefox. When I added binding to "change" event for select tag it works. Can you verify my proposed solution?
```javascript
ng.module('smart-table')
    .directive('stSearch', ['$timeout', function ($timeout) {
        return {
            require: '^stTable',
            scope: {
                predicate: '=?stSearch'
            },
            link: function (scope, element, attr, ctrl) {
                var tableCtrl = ctrl;
                var promise = null;
                var throttle = attr.stDelay || 400;

                scope.$watch('predicate', function (newValue, oldValue) {
                    if (newValue !== oldValue) {
                        ctrl.tableState().search = {};
                        tableCtrl.search(element[0].value || '', newValue);
                    }
                });

                //table state -> view
                scope.$watch(function () {
                    return ctrl.tableState().search;
                }, function (newValue, oldValue) {
                    var predicateExpression = scope.predicate || '$';
                    if (newValue.predicateObject && newValue.predicateObject[predicateExpression] !== element[0].value) {
                        element[0].value = newValue.predicateObject[predicateExpression] || '';
                    }
                }, true);

                if (element.prop('tagName') == 'SELECT') {
                    element.bind('change', function (evt) {
                        evt = evt.originalEvent || evt;
                        if (promise !== null) {
                            $timeout.cancel(promise);
                        }
                        promise = $timeout(function () {
                            tableCtrl.search(evt.target.value, scope.predicate || '');
                            promise = null;
                        }, throttle);
                    });
                } else {
                    // view -> table state
                    element.bind('input', function (evt) {
                        evt = evt.originalEvent || evt;
                        if (promise !== null) {
                            $timeout.cancel(promise);
                        }
                        promise = $timeout(function () {
                            tableCtrl.search(evt.target.value, scope.predicate || '');
                            promise = null;
                        }, throttle);
                    });
                }
            }
        };
    }])
```

**Comment by sjobe** [comment]
I've been experiencing a similar bug on firefox too.

**Comment by mehulcrest** [comment]
Hi I am also facing the same issue in firefox and working in chrome.

input field's search functionality is working fine but
<b>combo box and date picker controls</b> are not working in search functionality.

my code of view file is 
<pre>
&lt;div ng-controller="AppraiserAccountingCtrl"&gt;
  &lt;div class="table-responsive"&gt;
    &lt;table class="table" st-pipe="callServer" st-table="displayed"&gt;
      &lt;thead&gt;
      &lt;tr&gt;
        &lt;th&gt;
          &lt;label&gt;Name&lt;/label&gt;
          &lt;input st-search="'name'" ng-model="name" class="form-control"/&gt;
        &lt;/th&gt;
        &lt;th&gt;
          &lt;label&gt;Month&lt;/label&gt;
          &lt;select st-search="'month'" class="form-control" ng-model="month"&gt;
            &lt;option value="0" selected&gt;-Select Month-&lt;/option&gt;
            &lt;option value="1"&gt;January&lt;/option&gt;
            &lt;option value="2"&gt;February&lt;/option&gt;
            &lt;option value="3"&gt;March&lt;/option&gt;
            &lt;option value="4"&gt;April&lt;/option&gt;
            &lt;option value="5"&gt;May&lt;/option&gt;
            &lt;option value="6"&gt;June&lt;/option&gt;
            &lt;option value="7"&gt;July&lt;/option&gt;
            &lt;option value="8"&gt;August&lt;/option&gt;
            &lt;option value="9"&gt;September&lt;/option&gt;
            &lt;option value="10"&gt;October&lt;/option&gt;
            &lt;option value="11"&gt;November&lt;/option&gt;
            &lt;option value="12"&gt;December&lt;/option&gt;
          &lt;/select&gt;
        &lt;/th&gt;
        &lt;th&gt;
          &lt;label&gt;Year&lt;/label&gt;
          &lt;select st-search="'year'" class="form-control" ng-model="year"&gt;
            &lt;option value="0" selected&gt;-Select Year-&lt;/option&gt;
            &lt;option value="2014"&gt;2013&lt;/option&gt;
            &lt;option value="2014"&gt;2014&lt;/option&gt;
          &lt;/select&gt;
        &lt;/th&gt;
        &lt;th&gt;
          &lt;label&gt;From&lt;/label&gt;
          &lt;!--&lt;input st-search="'fromDate'" class="form-control"/&gt;--&gt;
            &lt;input st-search="'fromDate'"
                   type="text"
                   datetimepicker
                   name="fromDate"
                   id="inputFromDate"
                   class="form-control"
                   validator="date"
                   ng-model="fromDate"/&gt;
        &lt;/th&gt;
        &lt;th&gt;
          &lt;label&gt;To&lt;/label&gt;
          &lt;!--&lt;input st-search="'toDate'" class="form-control"/&gt;--&gt;
            &lt;input st-search="'toDate'"
                   type="text"
                   datetimepicker
                   name="toDate"
                   id="inputToDate"
                   class="form-control"
                   validator="date"
                   ng-model="toDate"/&gt;
        &lt;/th&gt;
        &lt;th&gt;&lt;/th&gt;
        &lt;th ng-show="subSection=='paid'"&gt;&nbsp;&lt;!--KEEP THIS BLANK--&gt;&lt;/th&gt;
      &lt;/tr&gt;
      &lt;tr&gt;
        &lt;th st-sort="file"&gt;File#&lt;/th&gt;
        &lt;th st-sort="borrower_name"&gt;Name&lt;/th&gt;
        &lt;th st-sort="address"&gt;Address&lt;/th&gt;
        &lt;th st-sort="assigned_date"&gt;Assigned Date&lt;/th&gt;
        &lt;th st-sort="completed_date"&gt;Completed Date&lt;/th&gt;
        &lt;th ng-show="subSection=='paid'" st-sort="paid_date"&gt;Paid Date&lt;/th&gt;
        &lt;th st-sort="appraiser_fee"&gt;Appraiser Fee&lt;/th&gt;
      &lt;/tr&gt;
      &lt;/thead&gt;

      &lt;tbody ng-show="!isLoading && displayed.length&gt;0"&gt;
      &lt;tr ng-repeat="row in displayed"&gt;
        &lt;td&gt;{{row.file}}&lt;/td&gt;
        &lt;td&gt;{{row.borrower_name}}&lt;/td&gt;
        &lt;td&gt;{{row.address}}&lt;/td&gt;
        &lt;td&gt;{{row.assigned_date}}&lt;/td&gt;
        &lt;td&gt;{{row.completed_date}}&lt;/td&gt;
        &lt;td ng-show="subSection=='paid'"&gt;{{row.paid_date}}&lt;/td&gt;
        &lt;td&gt;{{row.appraiser_fee}}&lt;/td&gt;
      &lt;/tr&gt;
      &lt;/tbody&gt;
      &lt;tbody ng-show="isLoading"&gt;
      &lt;tr&gt;
        &lt;td colspan="{{cols}}" class="text-center"&gt;{{perPage}} Loading ...&lt;/td&gt;
      &lt;/tr&gt;
      &lt;/tbody&gt;
      &lt;tbody ng-show="!displayed.length && !isLoading"&gt;
        &lt;tr&gt;
            &lt;td class="text-center warning" colspan="{{cols}}"&gt;No record(s) found&lt;/td&gt;
        &lt;/tr&gt;
      &lt;/tbody&gt;
      &lt;tfoot&gt;
      &lt;tr&gt;
        &lt;td class="text-left" st-pagination="" st-items-by-page="perPage" colspan="{{cols-1}}"&gt;
        &lt;/td&gt;
        &lt;td class="text-right " colspan="1"&gt;
            &lt;div class="col-md-12 pull-right"&gt;
                &lt;label&gt;Per Page:&lt;/label&gt;
            &lt;/div&gt;
            &lt;div class="col-md-8 pull-right"&gt;
                &lt;select st-search="'perPage'" ng-model="perPage" class="form-control ng-pristine ng-valid ng-touched"&gt;
                    &lt;option value="5"&gt;5&lt;/option&gt;
                    &lt;option value="10"&gt;10&lt;/option&gt;
                    &lt;option value="15"&gt;15&lt;/option&gt;
                    &lt;option value="20" selected&gt;20&lt;/option&gt;
                &lt;/select&gt;
            &lt;/div&gt;
        &lt;/td&gt;
      &lt;/tr&gt;
      &lt;/tfoot&gt;
    &lt;/table&gt;
  &lt;/div&gt;
&lt;/div&gt;
</pre>

and used above solution for stSearch directive

<pre>
ng.module('smart-table')
    .directive('stSearch', ['$timeout', function ($timeout) {
        return {
            require: '^stTable',
            scope: {
                predicate: '=?stSearch'
            },
            link: function (scope, element, attr, ctrl) {
                var tableCtrl = ctrl;
                var promise = null;
                var throttle = attr.stDelay || 400;

                scope.$watch('predicate', function (newValue, oldValue) {
                    if (newValue !== oldValue) {
                        ctrl.tableState().search = {};
                        tableCtrl.search(element[0].value || '', newValue);
                    }
                });

                //table state -> view
                scope.$watch(function () {
                    return ctrl.tableState().search;
                }, function (newValue, oldValue) {
                    var predicateExpression = scope.predicate || '$';
                    if (newValue.predicateObject && newValue.predicateObject[predicateExpression] !== element[0].value) {
                        element[0].value = newValue.predicateObject[predicateExpression] || '';
                    }
                }, true);

                if (element.prop('tagName') == 'SELECT') {
                    element.bind('change', function (evt) {
                        evt = evt.originalEvent || evt;
                        if (promise !== null) {
                            $timeout.cancel(promise);
                        }
                        promise = $timeout(function () {
                            tableCtrl.search(evt.target.value, scope.predicate || '');
                            promise = null;
                        }, throttle);
                    });
                } else {
                    // view -> table state
                    element.bind('input', function (evt) {
                        evt = evt.originalEvent || evt;
                        if (promise !== null) {
                            $timeout.cancel(promise);
                        }
                        promise = $timeout(function () {
                            tableCtrl.search(evt.target.value, scope.predicate || '');
                            promise = null;
                        }, throttle);
                    });
                }
            }
        };
    }])
</pre>

Still its not working for me.

I can not even check it by console. Am I doing anything wrong?

Can you please advise?

**Comment by alanthai** [comment]
@mehulcrest Your directive looks correct. I could be wrong but it looks like you're doing more complex search that requires a custom filter for date filtering.

**Comment by mehulcrest** [comment]
@alanthai 
Actually it does not work for even drop down control. Dropdown filter works in Chrome but not works in firefox.

**Comment by leijenaarj** [comment]
I had the same issue with IE8 and fixed it like so:

                var e = element[0].tagName.toLowerCase() === "input" ? "keydown" : "change";
                // view -> table state
                element.bind(e, function (evt) {
                    evt = evt.originalEvent || evt || window.event; //ie8 fixes
                    var target = evt.target || evt.srcElement;
                    if (promise !== null) {
                        $timeout.cancel(promise);
                    }
                    promise = $timeout(function () {
                        tableCtrl.search(target.value, scope.predicate || '');
                        promise = null;
                    }, throttle);
                });

**Comment by ivorobioff** [comment]
Will this solution be included to the next release or soon?

**Comment by BobKurtis** [comment]
@leijenaarj where did you replace that code at. Im running into the same issue.

**Comment by ivorobioff** [comment]
make sure you include debug version when doing changes.

**Comment by leijenaarj** [comment]
in st-search were the input event is used

met vriendelijke groet,

Jorgen Leijenaar
jorgen.leijenaar@7till11.com

**Comment by BobKurtis** [comment]
@leijenaarj  I'm sorry to bother you, I'm still rather new at javascript. I've edited the module but it isn't working. do you know what im doing wrong?
```javascript
     t.module("smart-table").directive("stSearch", ["$timeout", function(t) {
        return {
            require: "^stTable",
            scope: {
                predicate: "=?stSearch"
            },
            link: function(e, a, s, n) {
            	 
                var r = n,
                    i = null,
                    c = s.stDelay || 400;
                e.$watch("predicate", function(t, e) {
                    t !== e && (n.tableState().search = {}, r.search(a[0].value || "", t))
                }), e.$watch(function() {
                    return n.tableState().search
                }, function(t) {
                    var s = e.predicate || "$";
                    t.predicateObject && t.predicateObject[s] !== a[0].value && (a[0].value = t.predicateObject[s] || "")
                }, !0)
                var e = element[0].tagName.toLowerCase() === "input" ? "keydown" : "change";
                // view -> table state
                element.bind(e, function (evt) {
                    evt = evt.originalEvent || evt || window.event; //ie8 fixes
                    var target = evt.target || evt.srcElement;
                    if (promise !== null) {
                        $timeout.cancel(promise);
                    }
                    promise = $timeout(function () {
                        tableCtrl.search(target.value, scope.predicate || '');
                        promise = null;
                    }, throttle);
                });
            }
        }
```

**Comment by mehulcrest** [comment]
@BobKurtis 

Please change code in to bower_components -> angular-smart-table -> dist -> smart-table.debug.js
Find directive "stSearch" and change below code in it. you have to replace "change" in place of "input"

<pre>
element.bind('<b>change</b>', function (evt) {
                        evt = evt.originalEvent || evt;
                        if (promise !== null) {
                            $timeout.cancel(promise);
                        }
                        promise = $timeout(function () {
                            tableCtrl.search(evt.target.value, scope.predicate || '');
                            promise = null;
                        }, throttle);
                    });
</pre>

Now include <b>smart-table.debug.js</b> instead of <b>smart-table.min.js</b> in index.html

now please check Is it working?

**Comment by BobKurtis** [comment]
I've got it working with IE 8+ now. I'm doing some trick things with smart-table so I will explain (I'm new at this so if there may be some things I missed. First my situation. I'm using a dataList with search column in order to get a drop down list and text search all at once.
```
<datalist id="formNumbers">
  		<option ng-repeat="num in displayedCollection "
			value="{{num.form_number}}">{{num.form_number}}</option>
	</datalist>
<th><input st-search="'form_number'"class="input-sm form-control" id="formList" type="search"  list="formNumbers" /></th>
```
This works great in ie10+ and Firefox but Chrome doesn't make the list scrollable which causes major page overflow but my target is IE8-11. When implementing what @leijenaarj suggested i was able to get sorting to work(albeit without dropdown list but im not concerned with that) but the dropdown list functionality for ie10+ was killed so after some research i came to the following
``` 		
//slight change from what was suggested
 var e = element[0].tagName.toLowerCase() === "change" ? "input" : "keydown" ;	
//added the following binding to my controller.js
$("#formList").bind('input', function () {
    	var e = $.Event('keydown');
        e.which = 13; // enter key
        $("#formList").trigger(e);
 });	
``` 	
It is now working as desired in IE8+. Thank you for all you help, if i hadn't of stumbled across this page i would still be lost. If you have any suggestions on how to clean this up I'm all ears.

**Comment by btrepp** [comment]
Also just as an fyi, pretty sure this happens with IE11 to, my testing shows IE11 fires change but not input on select boxes.

Not that anyone except me seems to have used IE11 :) haha.

**Comment by emjaksa** [comment]
I change my event handler from **'input'** to **'change'** which fixed the issue with select in Firefox but caused IE9 backspace in input fields to not work. I resolved this issue by changing the bind to handle both change and keydown events. Let me know what you think. 
From my initial tests it works in IE9+, latest Chrome and Firefox.

```javascript
// view -> table state
element.bind('change keydown', function (evt) {
	evt = evt.originalEvent || evt;
	if (promise !== null) {
		$timeout.cancel(promise);
	}

	promise = $timeout(function () {
		tableCtrl.search(evt.target.value, attr.stSearch || '');
		promise = null;
	}, throttle);
});
```

**Comment by gulfaraz** [comment]
@emjaksa may I know what is the behaviour when using **change** instead of **keydown** ? I've been binding **'input change'** and it seems to work in most cases.

**Comment by emjaksa** [comment]
In most cases **'input change'** works expect in IE9. In IE9 I found when you clear or backspace on the input field it does not update the table.

**Comment by danroot** [comment]
I had a similar issue and the 'change keydown' fix worked for me.  Barring any surprises, it seems like this should be changed in stSearch.js.

**Comment by JuanValladares** [comment]
I have a easiest solution:
only change the event in the select element "st-input-event="change""
example: 
```
   <select   st-search="appVersion" class="filter_input pointer"  st-input-event="change">
   <option value=""></option>
   <option ng-repeat="item in usersCollection| unique:'appVersion' | orderBy:'appVersion'">{{item.appVersion}}</option>
```
and that's all.

**Comment by jjmurre** [comment]
@JuanValladares : You just made my day! 
st-seach was still not working in FF (40.0.3) for version 2.1.3 of smart-table, you solution worked like a charm.

**Comment by shilan** [comment]
I have just updated smart table, now it works but not in IE.

**Comment by Korayem** [comment]
Let's update documentation with @JuanValladares answer. It saved my day too :)

**Comment by antajo** [comment]
Set attr st-input-event='change'

**Comment by jarodms6** [comment]
@JuanValladares answer worked great!  IE 11 and FF 44

**Comment by senthilsendhil** [comment]
drop down filter not working in FF , I have tried example given in http://lorenzofox3.github.io/smart-table-website/... this site itself not working in FF ,, I tried adding st-input-event.. no lunck

**Comment by lindmik** [comment]
@senthilsendhil I just last week took AngularJS 1.5.5 and Smart Table 2.1.8 in use and with `st-input-event="change"` the drop down filters do work in Firefox. I had however to remove the single quotes around the property names in `st-search` when updating from earlier version of Smart Table. The examples on the documentation site does not work as they don't have `st-input-event` configured.

**Comment by senthilsendhil** [comment]
@lindmik Thanks for response , Yes I am using old Smart table , I will try to update , if any issue i might ask you again
