### ISSUE TITLE
Using stSort with a name doesn't work

### ISSUE THREAD

**Issue by snicolasPoly** [lorenzofox3/Smart-Table#257]
When I try to use the "Pagination on scroll" example in your website (http://lorenzofox3.github.io/smart-table-website/), it doesn't filter or search properly.

It might be due to the use of "st-pipe" directive with a function argument, which overrides the default pipe function (In the file "smart-table.debug.js" at line 100) but it erases completely the filter and search behaviors.
Is it wanted? 

Maybe I just don't understand the code properly.
Then could you explain to me how to use "st-pipe" directive with a function argument, with filtering and searching working?

**Comment by lorenzofox3** [comment]
I am afraid you'll have to set the sort logic in your pipe function. 
It means:
1) check if the change is the table state is on the sort object
2) if not, (ie pagination or search) call your server 
3) performing the sort on the new dataset by copy/pasting [this line](https://github.com/lorenzofox3/Smart-Table/blob/master/src/stTable.js#L96) where the `filtered variable` would be the currently dataset
