### ISSUE TITLE
Search/filter data using the rendered text and not the value of the attribute

### ISSUE THREAD

**Issue by jmcollin78** [lorenzofox3/Smart-Table#260]
Hi there,

I'm new to Smart-Table and I'm facing a common problem.

I want to filter or search my table's data using the rendered text and not the value of the field itself.
Example: in the Search/filter data of the documentation site (http://lorenzofox3.github.io/smart-table-website/ ), If I type 'May' in the global search field, I would have the line with 'May 21, 1987' displayed.

Does anyone have done this before ?

JM.

**Comment by lorenzofox3** [comment]
I think the best in this case is you format you data collection before you bind it to the table so the rendered text match the actual field value.

in you controller
```Javascript
//assuming the actual collection is var rows ->
$scope.rowCollection = rows.map(function(val){
   return {
    //...
     birthDate:$filter('date')(val.birthDate, format, timezone)
   //...
   }
});
```
