### ISSUE TITLE
Global Search and Search Collection

### ISSUE THREAD

**Issue by acgentry** [lorenzofox3/Smart-Table#261]
Hi there, 

I don't believe this feature exists, pardon if it does, but ideally I would like the ability to set a collection attribute in the st-search directive that gives access to the complete filtered collection of rows.  Currently when using paging and global search, the st-table bound collection only gives access to the current displayed records for that one page.  This new "st-search-results" attribute could be accessed in controllers to build aggregation that respects the results of the filter as a whole.

All the best,
ACG

**Comment by lorenzofox3** [comment]
hello,
this is not supported at the moment and I don't see any valid use case. you could explain what you would need to access the whole filtered collection instead of the displayed one base on the table state ?

Thanks

**Comment by rntorm** [comment]
Whole filtered data is necessary to access when you have a table with pagination. Lets say user filters data by labels and gets 40 results. Since the table is paginated by 20 rows, massactions would not be possible on the filtered result. Instead user would have to mass edit 2 pages separately. @lorenzofox3

**Comment by BobKurtis** [comment]
Is the a workaround for this? Im exporting a table to a csv and being able to access the filtered collection would be ideal.

**Comment by lorenzofox3** [comment]
fix with 1.4.13. To be documented but not you can have access to the filtered collection with the table controller.

``ctrl.getFiletedCollection()``

**Comment by acgentry** [comment]
Thank you @lorenzofox3

**Comment by nirmalgoswami** [comment]
How to use `ctrl.getFiletedCollection()` in view,controler and directive ?

**Comment by OmanFerrer** [comment]
`<table st-table="displayedCollection" st-filtered-collection>`

```
app.directive('stFilteredCollection', function () {
  return {
    require: '^stTable',
    link: function (scope, element, attr, ctrl) {
      scope.$watch(ctrl.getFilteredCollection, function(val) {
        scope.filteredCollection = val;
      })
    }
  }
});
```

Then in your controller, you will have the filteredCollection property on your scope.
