### ISSUE TITLE
Sorting does not work when only one row in certain cases

### ISSUE THREAD

**Issue by oslo10e** [lorenzofox3/Smart-Table#263]
When st-table collection is computed in directive's link function and in case it contains only one row, then, it diseapears after sorting.

See demo : http://jsfiddle.net/opeaucelle/szc4v67L/

**Comment by JanStevens** [comment]
I had some issue running your jsfiddle so updated it (something about mime/types)

Indeed this seems to be an issue:

http://jsfiddle.net/szc4v67L/4/

**Comment by lorenzofox3** [comment]
should be fixed with https://github.com/lorenzofox3/Smart-Table/pull/281
