### ISSUE TITLE
stSafeSrc along with pagination not working if data loaded asynchronously 

### ISSUE THREAD

**Issue by premsh** [lorenzofox3/Smart-Table#264]
Couple days ago smart table page stopped working, pagination isn't working anymore. Paging is displayed at the end of page, but now all the rows are loaded at once instead of 10 which is specified in footer section.  

Anyone has any clue why this might be happening all of the sudden? 

Even this failed in my local machine:

http://plnkr.co/edit/X1pmzB?p=preview

**Comment by JanStevens** [comment]
I've opend your plunker and to me everything works, in your footer you have

```html
<td colspan="5" class="text-center">
   <div  st-items-by-page="20" st-pagination=""></div>
</td>
```

So it loads 20 a page, I've changed it to 10 and it displays 10 a page.
