### ISSUE TITLE
WIP toggle columns

### ISSUE THREAD

**Issue by JanStevens** [lorenzofox3/Smart-Table#266]
Hello,

I've made an attempt to create reusable toggle columns for smart table, the plunkr (click on the wrench icon to open the menu and show hide a column):

http://plnkr.co/edit/6SHVFH5a2xgz3JAqemt6?p=info

I would like to contribute to smart table, I think it extends the smart table plugin without providing to much overhead. ATM I'm not really that happy with the code mainly because I fear there are to many scopes/watches/directives just to toggle columns on or off. (the upside is that if you dont use it there wont be any additional performance penalty).

I did try to use css selectors and hide them with css classes but ran into issues. when using an external pipe function with a timeout the hide classes are removed when the collection is updated. Instead I used seperate small directives that would hide depending on their column state in the `hiddenColumns` array in the table state.

I've created a directive that can be used as a toggle menu (instead of adding a switch/button next to every header, this conflicted with the sort option so I preferred a different menu). Of course this can be styled to create a pop over style or menu.

Any feedback would be welcome, I know there are some issue like the usage of lodash for one `_.find` but with some feedback and help I think we can create a nice addition for smart table.

**Comment by lorenzofox3** [comment]
Looks interesting, I ll try to have look soon. 
But basically, I don't think this menu and its state (which column is hidden or not) have to be related to smart-table. At the end it can simply be bindings with a ng-show directive on each cell. Although if you display a lot of rows in the same time, You might have some perf issues as the number of bindings will increase quickly. 

thanks for sharing !
