### ISSUE TITLE
Jeeez... server-side pagination is SO confusing!

### ISSUE THREAD

**Issue by alvipeo** [lorenzofox3/Smart-Table#268]
I'm trying to sync the pager with the collection of items for current page. I have everything prepared except I can't get pager to work! To actually change the current page. COULD YOU PLEASE CREATE AN EXAMPLE???

Thank you!

**Comment by srph** [comment]
I've created one myself which works for an app I'm working on. You might want to make one that works for you. Here's the simple version: ```https://gist.github.com/srph/1da43c5c6fa6feb9db90```

**Comment by lorenzofox3** [comment]
I don't think you have searched much as this have been discussed in several issues and in the chat.
But the key point is to set in you custom pipe function the `numberOfPages` on the pagination table state as smart-table has no clue about your data set size. Please refer to the Ajax/pipe plugin section of the documentation website where I updated the example to be a more realistic server side implementation
