### ISSUE TITLE
How can I force refresh after delete for example?

### ISSUE THREAD

**Issue by alvipeo** [lorenzofox3/Smart-Table#269]
If I use server-side paging and user deletes a row what is the best way to force refresh the table so user will stay on the same page?

**Comment by srph** [comment]
If you are using ui-router, you can use ```$state.reload()```.

**Comment by dattanchu** [comment]
I think ui-router that allows user to resume the correct pagination and
selection would be a very good example to add to our current website.
+Kier, can you help us out?

**Comment by lorenzofox3** [comment]
Note sure to understand you issue, but as explained in the documentation if you intend to change the content of the collection (remove, add) you'll need to tell smart-table to watch the source using the st-safe-src attribute and it should update by itself. Refer to "stSafeSrc attribute" of the documentation website

**Comment by alvipeo** [comment]
Here's the snippet:

    <table st-table="" st-safe-src="news.newsCollection" st-pipe="news.loadNewsPage" class="table table-striped">

So when a user is on X page out of Y he deletes one item and I need this X page to be reloaded. But it's not. So I do this just deleting the item from current page's array:

    function deleteNews(news) {
			newsService.deleteNewsAsync(news.id).then(
				function (data) {
					// force table refresh - NO WAY
					var index = vm.newsCollection.indexOf(news);
					if (index !== -1) {
						vm.newsCollection.splice(index, 1);
					}
				},
				function(errObj) {
					alert(errObj.data);
				});
		}

Obviously, if I show 10 items per page there's only 9 left. And I want to refresh this collection.
The problem I guess is to determine current page number. Because pipe function has 2 params - tableState and tableController. In my deleteNews method I don't know where to get that data.

Here's my pipe function:

    function loadNewsPage(tableState, tableController) {
			vm.isLoading = true;
			var pageNumber = tableState ? tableState.pagination.start / tableState.pagination.number + 1 : 1;
			var newsPerPage = tableState ? tableState.pagination.number : 20;

			newsService.getPageNewsAsync(pageNumber, newsPerPage).then(
					function (data) {
						// data.totalNews
						// data.pageNum,
						// data.newsPerPage
						vm.totalPages = Math.ceil(data.totalNews / data.newsPerPage);
						if (tableController) {
							tableController.tableState().pagination.numberOfPages = vm.totalPages;
						}

						vm.newsCollection = data.news;
					},
					function(errObj) {
						alert(errObj.data);  // for now
					})
				.finally(function() {
					vm.isLoading = false;
				});
		}

**Comment by roymilder** [comment]
You should create a directive for the buttons that trigger a certain async/ajax method.

example:
```
<button st-custom-action callback='remove($index)'>remove</button>
```

<b>Directive</b>
```
angular.module('smart-table')
    .directive('stCustomAction', function() {
        var directiveConfig = {
            restrict: "AE",
            require: '^stTable',
            link: function(scope, element, attrs, ctrl) {
                var table = ctrl.tableState();
                element.on('click', function(ev) {
                    scope.callback.call().then(function(result) {
                        if (result) {
                            ctrl.pipe();
                        }
                    });
                });
            },
            scope: {
                callback: "&"
            }
        };
        return directiveConfig;
    });
```

<b>Parent controller (where the method is defined)</b>
```
    $scope.remove = function(index) {
        return api.call($entity, $scope.rows[index].id, 'setState', null, null, '2').then(function(result) {
            if (result) {
                $scope.rows.splice(index, 1);
                return true;
            } else {
                return false;
            }
        });
    };
```

Notice that the method returns true or false (in my particular case).
Only when true is returned the pipe() function is called again.

Tried it and it worked.

**Comment by RazvanCosmeanu** [comment]
Implemented roymilder's solution and I think it's the best one so far. You can achieve similar results by using [activation promises](https://github.com/johnpapa/angular-styleguide#controller-activation-promises). $state.reload() seems a bit of an overkill to me, and it flicks the screen. Thanks, Roy, for the solution, and lorenzofox for this great library.
