### ISSUE TITLE
Select All Checkbox and reset row selection when TableState changed

### ISSUE THREAD

**Issue by tam892007** [lorenzofox3/Smart-Table#270]
Hi,
Thanks for your great work. I'm using Smart Table and having some troubles to create a Select All checkbox per page. Also, i want to reset any row selection when table state changed (filter, sorting, pagination). Could you give some helps pls?

**Comment by lorenzofox3** [comment]
Maybe in this case it is easier not to go through smart table api but simply setting the `isSelected` property yourself with a directive.
```Javascript
.directive('stSelectAll', function () {
      return {
        restrict: 'E',
        template: '<input type="checkbox" ng-model="isAllSelected" />',
        scope: {
          all: '='
        },
        link: function (scope, element, attr) {

          scope.$watch('isAllSelected', function () {
            scope.all.forEach(function (val) {
              val.isSelected = scope.isAllSelected;
            })
          });

          scope.$watch('all', function (newVal, oldVal) {
            if (oldVal) {
              oldVal.forEach(function (val) {
                val.isSelected = false;
              });
            }

            scope.isAllSelected = false;
          });
        }
      }
    });
```
so you could set a select all check box 
```Markup
<st-select-all all="yourDisplayedCollection"></st-select-all>
```

to reset, just simply loop over the displayed collection and set the isSelected property of you items to false

**Comment by ggueret** [comment]
Thanks a lot for this directive

**Comment by tam892007** [comment]
It's my bad that i didnt know displayedCollection is exactly the items displayed per page. Many thanks for your help. :)

**Comment by iqbalsublime** [comment]
@lorenzofox3  Can you check this ? 
http://stackoverflow.com/questions/35765915/select-all-row-doesnt-work-properly-with-checkbox

**Comment by nirmalgoswami** [comment]
@iqbalsublime you can change

from
`element.find('input').attr('checked', true);`
to
`element.find('input').prop('checked', true);`

in  your directive code to solve issue just find `element.find('input').attr` and replace `element.find('input').prop('checked', true);` in your directive code

**Comment by nirmalgoswami** [comment]
@lorenzofox3 hi i i try to implement your directive than i got error about length `cannot read property 'forEach' of undefined` on line `  scope.all.forEach(function (val) {` 

look like smart table is not creating an other array by copying the references of the items i.e. `yourDisplayedCollection`

**Comment by joelcdoyle** [comment]
You have to create that array yourself by copying the first array:

```
$scope.yourDisplayedCollection = [].concat($scope.documents);
```

**Comment by samsam321** [comment]
Hello lorenzofox3 , your code working great independently.
But when I integrate with the pagination  ref:  https://plnkr.co/edit/LB2f9P?p=preview
the selection will reset when click any button of pagination. Could you help to give some advice about that . Thanks
