### ISSUE TITLE
Date range filter

### ISSUE THREAD

**Issue by srph** [lorenzofox3/Smart-Table#271]
This isn't a request, but I'd like to ask some assistance to help me create a plugin.

### Date ranger filter

In my case, I'll need two fields (from and to):

```html
<input type="text" datepicker st-search="birthdate" which="from">
<input type="text" datepicker st-search="birthdate" which="to">
```

And I'll need to send to the server the data in this form:

```js
"filters": {
  "birthdate": {
    "from": "...",
    "to": "...",
  }
}
```

Right now, it is only possible to send it as:

```js
"filters": {
  "birthdate.from": "...",
  "birthdate.to": "..."
}
```

Is this feasible?

**Comment by lorenzofox3** [comment]
Hi,
you can pass whatever you want as `input` argument of the the search function and may be able to create a multi level search predicate object. Have a look at https://github.com/lorenzofox3/Smart-Table/pull/221 it has worth reading discussions and links to plunker.

**Comment by srph** [comment]
Thanks a lot, sir.

**Comment by Rmabini** [comment]
Hi Lorenzofx3,

I am currently doing some dateRange, I was just wondering about the used of 
            var inputBefore = ng.element(inputs[0]);
            var inputAfter = ng.element(inputs[1]); 

were does it initialize ?
Thanks

**Comment by mnithya** [comment]
@Rmabini I know this is old and this may not be what you're asking, but I had to replace "ng" with "angular" for those two lines to work in my version of angular.
