### ISSUE TITLE
Issues with running 0.x and 1.x at same time?

### ISSUE THREAD

**Issue by aeharding** [lorenzofox3/Smart-Table#272]
Hello,

I am working on a project that uses the configuration oriented version of Smart-Table. I know I could compare source code, but you could probably tell me much quicker: are there any issues with having both versions of the Smart-Table on the same page -- stuff like naming conflicts (not mixing them on the same table, obviously).

Thanks for letting me bug you in my laziness. :-)

**Comment by lorenzofox3** [comment]
I think, it should be fine

**Comment by aeharding** [comment]
Great, thanks!
