### ISSUE TITLE
how to get current page value in pagination using st-pipe

### ISSUE THREAD

**Issue by avin77** [lorenzofox3/Smart-Table#274]
Hi i am new with angular and smart table so hope i am not too stupid asking this question.Please don't mind my english

I am trying to implement server side code ajax based using Smart Table

Below code is able to render pagination but  when i click on 2nd page its shows me first page as the query parameter passed to server remains always same on any page like this api/v1/makes?page=1&per-page=5,so every time page=1 .

Quick question-
1)Is i am doing in the right way or any other better way to do this?

2)If yes how to pick value of clicked page from paginated pages and passing to api query parameters?

Below is the html and controller code i have shared

//html code/*
   <table st-table="displayedMakes"  st-pipe="callServer" class="table table-striped table-bordered table-hover">
                        <thead>
                        <tr>
                            <th class="numeric" st-sort="id">ID</th>
                            <th st-sort="name">Name</th>
                            
                            
                            
                            
                            <th st-sort="status">Status</th>
                            
                            
                            <th st-sort="created_by">Created By</th>
                            <th class="numeric" st-sort="created_on">Created On</th>
                            <th st-sort="updated_by">Updated By</th>
                            <th class="numeric" st-sort="updated_on">Updated On</th>
                        </tr>
                        <tr>
                            <th colspan="13">
                                <input st-search placeholder="global search" class="input-sm form-control" type="search"/>
                            </th>
                        </tr>
                        </thead>
                        <tbody ng-show="!displayedMakes.isLoading">
                        <tr ng-repeat="make in displayedMakes">
                            <td class="numeric">{{make.id}}</td>
                            <td>{{make.name}}</td>
                            
                            
                            
                            
                            <td>{{make.status | status}}</td>
                            
                            
                            <td>{{make.created_by}}</td>
                            <td class="numeric">{{make.created_on | date}}</td>
                            <td>{{make.updated_by}}</td>
                            <td class="numeric">{{make.updated_on | date}}</td>
                        </tr>
                        </tbody>
                        <tbody ng-show="displayedMakes.isLoading">
                        <tr>
                            <td colspan="4" class="text-center">Loading ... </td>
                        </tr>
                        </tbody>
                        <tfoot>
                        <tr>
                            <td colspan="13" class="text-center">
                                <div st-pagination="" st-items-by-page="itemsByPage" st-displayed-pages="6"></div>
                            </td>
                        </tr>
                        </tfoot>
                    </table>*/

//Controller code

controllers.MakeListController = function ($scope,Make,$state,$timeout) {
    var ctrl=this;
    var perPage = 5;
    var currentPage = 1;
    var totalPages=10;
    var sortOn="name";
    $scope.isLoading = false;
    $scope.displayedMakes=[];

    function getAPage(tableState) {
          //rest api call
        $scope.displayedMakes=Make.query({page:tableState.pagination.start,'per-page':tableState.pagination.number});
        $scope.isLoading = false;
    }

    $scope.callServer = function getData(tableState, tableController,make) {

        //here you could create a query string from tableState
        //fake ajax call
        tableState.pagination = {
            start:1, // start index
            number:5, //number of item on a page
            numberOfPages:5 //total number of pages
        }
        $scope.isLoading = true;

        getAPage(tableState);

    };

};

**Comment by lorenzofox3** [comment]
in the pipe function you can have these information with the tableState.

tableState.start will give you the offset (the number of items skipped)
tablsState.number will give you the number of items by page.

You will have to set the numberOfpages yourself based on what your server says.

So don't assign tableState.pagination.start and tableState.pagination.number just read them and pass them as it is to your server. 
Do assign numberOfpages based on your server response

**Comment by avin77** [comment]
Thanks a ton got it :+1:
