### ISSUE TITLE
In place editing

### ISSUE THREAD

**Issue by GCorbel** [lorenzofox3/Smart-Table#275]
Hello,

I'm looking to do in place editing as in [this demo](http://showcase.sology.eu/smart_listing). I want to click on button then a form should be visible. When we fill the form and click on the save button, an ajax request should be send and the grid should be refreshed.

Is there a way to do this yet? Are you interessed by this feature?

**Comment by lorenzofox3** [comment]
Inline editing is not really related to the table, you can use whatever directive, dialog, etc you want. Just edit the model and the table will be updated

**Comment by GCorbel** [comment]
Ok but if I want to change the row in a form, the table have to be able to be modified. The row can be replaced by a template for example with a form.

I'm new with angular and I may have a lack of knowlodge but I don't see the way to do that with your tool.

**Comment by lorenzofox3** [comment]
The point is that within table template, everything is angular so you can use controllers, directives etc as you would normally. Have you at least tried to create a directive to toggle an edit mode on a normal html table markup (not with smart-table) ... ?
 So [here](http://plnkr.co/edit/avOmz2MOdxZCRgRP6rSe?p=preview ) is a basic example and you'll have to elaborate on it, but please don't ask me to do your job

Thanks

**Comment by GCorbel** [comment]
I think I misunderstood your project's capacity. I don't ask to do my job. I'm suggesting a feature and I 'm ready to do a pull request.
