### ISSUE TITLE
Pagination does not work when passing a string to st-items-by-page

### ISSUE THREAD

**Issue by TomasKli** [lorenzofox3/Smart-Table#276]
If we use a 'select' element  to select the number of rows in a page, it will return a string, so if we have:

`<select ng-model="itemsOnPage" type="number" >`
                      `  <option value="10">10</option>`
                   `     <option value="20">20</option>`
                   `     <option value="30">30</option>`
               `     </select>`

and

`<tr>`
           ` <td class="text-center">`
             `   <div st-items-by-page="itemsOnPage" st-pagination=""></div>`
        `    </td>`
`        </tr>`

pagination would not work from the second page, because the code does not expect a string.

To solve this, line 94 of stTable.js  needs to be changed from -
`filtered = filtered.slice(pagination.start, pagination.start + pagination.number);`
to -
`filtered = filtered.slice(pagination.start, pagination.start + parseInt(pagination.number));`

currently if pagination.start would be set to 10 and pagination.number to '10' (string) filtered.slice would be called with values (10, 1010).

**Comment by lorenzofox3** [comment]
good catch, PR ?
