### ISSUE TITLE
Another initial data loading problem...

### ISSUE THREAD

**Issue by anyong** [lorenzofox3/Smart-Table#279]
I've read through all of the issues on here but I can't seem to figure out how to load initial data after the controller loads for pagination on scroll. I know you recommend using a resolve, but in my case the user needs to select which table to display from a list of available tables. When user presses the button, rowCollection is updated but the st-pipe function is not called, so I'm not sure what to do? Here is the pagination scroll demo plunker that illustrates my problem: http://plnkr.co/edit/JykO5Oqdk8PzJYd1jQDc?p=preview

Very nice table though when I am using it without the infinite scroll!

Another feature that I would really like and would be happy to try to help develop is a virtual scroller that can be used in conjunction with the pagination-scroll, so that the scrollbar height appears to show the entire table, but actually only the current page of the table is on the screen. Angular virtual scroll might be an interesting place to start looking for sample logic. The main problem with virtual scrolling always seems to be calculating the heights of elements, but maybe it's possible anyway. Would you be interested in working together on this feature?

Also, do you plan to include stRatio directive, in the main file? I can add it myself, but just wondering.

**Comment by lorenzofox3** [comment]
Hi, the main issue in your plunker is that the ng-click handler of your checkbox is bound to nothing as you have not exposed the activate function to the scope. 
see the [corrected plunk](http://plnkr.co/edit/HiwPj2SP3FljYbqVXn7Q?p=preview)

Note that st-ratio, st-infinite-scroll and other directives you can see in the examples are more for illustration purpose: to show how to extend smart-table to extend its behaviour using custom directive which call the table controller api. 

Not sure to understand what you mean with your virtual scroll. I don't think it is something which will go in smart-table core features as it is really specific. But if you write a plugin please share it with the community !

thanks,

Laurent R
