### ISSUE TITLE
Dynamic style attribute stay empty with IE (9, 10 or 11)

### ISSUE THREAD

**Issue by oslo10e** [lorenzofox3/Smart-Table#280]
When using dynamic code to generate table structure with a dynamic style attribute,
the style is not applied when using IE 9 IE 10 or IE 11.

Example 
    &lt;th ng-repeat="column in columns" 
        style="{{ column.style }} " 
      >{{ column.label }}&lt;/th> 

See JsFiddle example : http://jsfiddle.net/opeaucelle/5hdabkn8/

**Comment by lorenzofox3** [comment]
Hello,
How is this related to smart-table ?  it is more related to the framework itself for me 
But first you may want to try [ngStyle](https://docs.angularjs.org/api/ng/directive/ngStyle) instead of style ?

**Comment by oslo10e** [comment]
It works well with Chrome, Firefox and Safari but not with IE
Of course it is related to smart-table.

**Comment by lorenzofox3** [comment]
http://jsfiddle.net/d4w8wuf7/

I removed everything related to smart-table, do your problem disappear ? no, so how can you tell "Of course it is related to smart-table"? have you done some investigations to find which part of smart-table could cause you code to fail ?

**Comment by oslo10e** [comment]
You're right ! I am sorry. I wrote before thinking about it.
