### ISSUE TITLE
st-sort-default="reverse" does not work

### ISSUE THREAD

**Issue by mremmik** [lorenzofox3/Smart-Table#283]
Hello,

It appears that setting up a reverse default ordering of a table simply does not work (as of 1.4.8).

* Ordering without reversal, with
```
 <td st-sort="something" st-sort-default>..</td>
```
or
```
 <td st-sort="something" st-sort-default="anything">..</td>
```
works as expected.

* Ordering by
```
 <td st-sort="something" st-sort-default="reverse">..</td>
```
does not work, because stSort.js:16
```
        if (attr.stSortDefault) {
          sortDefault = scope.$eval(attr.stSortDefault) !== undefined ?  scope.$eval(attr.stSortDefault) : attr.stSortDefault;
        }
```
results in sortDefault to be set to false, and later at stSort.js:41
```
        if (sortDefault) {
          index = attr.stSortDefault === 'reverse' ? 1 : 0;
          sort();
        }
```
the attribute will thus never be checked for being 'reverse', and sorting never runs.
* Trying to inject "reverse" from a scope variable such as 
```
$scope.mysortdefault = 'reverse';
...
<td st-sort="something" st-sort-default="mysortdefault">..</td>
```
does not work either, because in the snippet above at stSort.js:42, it checks for **attr.stSortDefault**, i.e. the literal tag attribute, to equal to 'reverse' rather than the sortDefault variable.

Thus it doesn't seem possible to have reverse default ordering at all.

**Comment by lorenzofox3** [comment]
Hello, 
I do not manage to reproduce:
[plunker](http://plnkr.co/edit/jYUh2hOMm2Uq3kU4vMh4?p=preview)
For me it work as expected.

Please follow the guidelines of the "submit an issue" section of the readme: a running example of the problem would be great, 

thanks.

**Comment by mremmik** [comment]
Sorry, Plunkr was acting up at the time. I'll see if I can reproduce the problem tomorrow.

**Comment by mremmik** [comment]
Found the problem: in my controller I had a field named **$scope.reverse** , which was set to false, thus when evaluated at stSort.js:17 it was setting the sortDefault variable to false, too. Renaming the  field made everything work again.

As a small fix it would probably be a good idea to check for the literal "reverse" string in st-sort-default before attempting to evaluate it.
