### ISSUE TITLE
stSort: switching sort between two columns using getter functions

### ISSUE THREAD

**Issue by napple** [lorenzofox3/Smart-Table#285]
1. set up a sortable table where two columns use getter functions (not explicit properties).
2. Click on first column with getter.
3. Click on second column with getter.

The sort direction indicator in the header will not be updated. The table will sort properly, but the column indicator will remain on the previously sorted column.

I believe this is caused by the fact that angular.equals ignores functions when detecting equality. Therefore, the tableState().sort effectively remains equivalent if though the predicate has changed from one function to another. This prevents the watch function from being called (which is where the column classes are updated).

[Plunkr](http://plnkr.co/edit/DTkHIuJH9DCmGvDcyj9b) : Click on First Name col, then on Last Name col. The table sorts properly, but the sort indicator isn't updated properly. Note that if the two columns are in opposite forward/reverse states, then the sort indicator will update properly, since the tableState().sort in-equivalency will be detected by angular.equals...

Thanks!

**Comment by dattanchu** [comment]
Plunker is annoying on android browser but I can reproduce the issue.

**Comment by lorenzofox3** [comment]
thanks and sorry for the late fix.

Note, you'll have to name your getter functions (don't use anonymous function )

**Comment by mdarveau** [comment]
I put this here just in case it can help somebody else. In coffeescript, you can't have named function. You will have to fallback on eval: ```eval( "$scope.sorters[propertyName] = function sortFunction_#{propertyName}(record){return do_your_stuff" );```

**Comment by ejones44** [comment]
Still seeing this exact issue in smart-table 2.1.8 when using sorters like this

`	$scope.getters = {
			//date strings should be converted to Date for sorting
			date: function(row)
			{
				return new Date(row.date).getTime();;
			},
			serviceDate: function(row)
			{
				return new Date(row.serviceDate).getTime();
			}}`

Any ideas?
