### ISSUE TITLE
Remembering and restoring search

### ISSUE THREAD

**Issue by barronj** [lorenzofox3/Smart-Table#286]
Is it possible to store and restore the previous search? For instance, I am using ngRouter to go to another state and then back. I would like the current search to be saved before going away from the table state and then restored when going back. I had naively tried setting the ngModel for the search field to a field in an application-wide settings service. When I go back, the field does go to the old value, but the filtering does not take place unless I start typing in that input.

Thank you.

**Comment by lorenzofox3** [comment]
have you had a look at the example which stores the table state in local storage (cf documentation website) ? might be what you are looking for

**Comment by barronj** [comment]
Thanks for pointing out the example. The last three examples on that page have huge blank rectangles instead of rectangles filled with code and working examples like the others (using Chrome on Windows), so I had assumed they were not yet implemented. But I see the Plunker links go to actual code.
