### ISSUE TITLE
put the content with "!" character  in search box cannot get filtered result

### ISSUE THREAD

**Issue by superkevin5** [lorenzofox3/Smart-Table#287]
![aaaaaaaaaaaaaaaaaaa](https://cloud.githubusercontent.com/assets/8369050/5847234/1b4be9e4-a21f-11e4-8328-9801004d3094.PNG)
![ddddddddddddddddddddddddddddddd](https://cloud.githubusercontent.com/assets/8369050/5847235/1c35e33c-a21f-11e4-8177-a502e5499420.PNG)
I put content with "!" inside the global search box, it seems not working.

**Comment by lorenzofox3** [comment]
hello, please refer to [angularjs filter documentation](https://docs.angularjs.org/api/ng/filter/filter). "!" is a special token used for negation: if your input is "!foo" for example, the output will be all the items which does not match foo.
You can use your own filter if you want to overwrite this default behaviour by adding to your table the attibute `st-set-filter="nameOfYourCustomFilter"`

**Comment by superkevin5** [comment]
Thanks
