### ISSUE TITLE
How to use st-search for child or nested products 

### ISSUE THREAD

**Issue by avin77** [lorenzofox3/Smart-Table#288]
Hi,

I am not sure if this may be stupid question but i have to search some user values and corresponding roles in this format 

{"username":"abcprodigy","email":"abc@gmail.com","role":{"id":1,"name":"admin"},"status":10...}

i am able to search username,email fields but not role i tried st-search="role.name" but didn't worked

**Comment by lorenzofox3** [comment]
smart-table rely on the angular filterFilter by default, so it is not possible to perform nested search. 
Good news though you can use a custom filter instead please refer to https://github.com/lorenzofox3/Smart-Table/pull/221 for more details

**Comment by avin77** [comment]
i tried the example given in #221 & http://plnkr.co/edit/Idbc1JNHKylHuX6mNwZ6?p=preview but custom filter is not working with st-pipe.

Can you let me know if it works with st-pipe ?

**Comment by bademux** [comment]
@lorenzofox3 Bad news custom filters doesn't work with st-pipe.

**Comment by lorenzofox3** [comment]
But why would you use a custom filter with st-pipe, it does not make sense ? the purpose of st-pipe is to overwrite the logic of the table (mostly to link it to a server) so if you want any custom logic you can put it you custom pipe function

**Comment by bademux** [comment]
Sorry, I misunderstood custom filter concept. Still looking for the place that can be used to glue search *inputbox* element and *predicates object*.
For example 
- parse ```html <input type="number" /> ``` as integer 
- create multiple criteria form query string
- put custom object (e.g. extjs-like ```js { property: 'prop', operator:'eq', value='val'} ```)

**Comment by dsm0880** [comment]
Not sure if things changed with recent angular versions but you can do nested filtering natively with $filter. In the expression you pass it an object. For example if you pass {person:{age:29}} then you will get back everyone who is age 29. This is my biggest pain point with Smart-Table, when implementing the custom filter I only get the opportunity to input a single predicate text name and I cannot pass an object or additional options like you can with the angular filter. Does that make any sense? Basically st-search="<textOnly>". I can open an enhancement request, if that is more appropriate. Thanks!
