### ISSUE TITLE
Change of the pagination template

### ISSUE THREAD

**Issue by docseltsam** [lorenzofox3/Smart-Table#289]
It would be useful to show a button to jump to the first and the last page of the table in the pagination template. I recommend to change the template to following:

    
    ng.module('smart-table', []).run(['$templateCache', function ($templateCache) {
        $templateCache.put('template/smart-table/pagination.html',
            '<div class="pagination" ng-if="pages.length >= 2"><ul class="pagination">' +
            '<li ng-if="1!==pages[0]"><a ng-click="selectPage(1)">1...</a></li>' +
            '<li ng-repeat="page in pages" ng-class="{active: page==currentPage}"><a ng-click="selectPage(page)">{{page}}</a></li>' +
            '<li ng-if="numPages!==pages[pages.length - 1]"><a ng-click="selectPage(numPages)">...{{numPages}}</a></li>' +
            '</ul></div>');
    }]);

**Comment by lorenzofox3** [comment]
yep and a button next/previous page, I opted for the minimal but we could set it to the maximal instead :) 

Note you can overwrite the template in the $templateCache or point to another template url by setting the attribute `st-template="your url"` on the pagination directive

**Comment by docseltsam** [comment]
Thanks for your answer. Next suggestion:

ng.module('smart-table', []).run(['$templateCache', function ($templateCache) {
    $templateCache.put('template/smart-table/pagination.html',
        '<div class="pagination" ng-if="pages.length >= 2"><ul class="pagination">' +
        '<li ng-if="currentPage !== 1"><a ng-click="selectPage(currentPage - 1)">&lt;</a></li>'+
        '<li ng-if="1 !== pages[0]"><a ng-click="selectPage(1)">1...</a></li>' +
        '<li ng-repeat="page in pages" ng-class="{active: page==currentPage}"><a ng-click="selectPage(page)">{{page}}</a></li>' +
        '<li ng-if="numPages !== pages[pages.length - 1]"><a ng-click="selectPage(numPages)">...{{numPages}}</a></li>' +
        '<li ng-if="currentPage !== numPages"><a ng-click="selectPage(currentPage + 1)">&gt;</a></li>'+
        '</ul></div>');
}]);

As far as I am new to angular.js and your grid I'm appreciative for your hint with the "st-template" attribute, that's nice.

**Comment by ribcakes** [comment]
recently moved from `ngTable` to using `Smart Table` and I had the same desire for a more sophisticated pagination template.

If you guys would be interested, I managed to get `ngTable`'s template to work with `Smart Table`'s pagination plugin thanks to how modular `ngTable`'s pagination was. I just needed to bring in this function from `ngTable`: https://github.com/esvit/ng-table/blob/master/src/scripts/03-params.js#L276 and use it to generate the pages array. 
Unfortunately, this function hardcodes the number of possible pages to display, thought that could be changed to use `st-items-by-page`.

`ngTable`'s pagination: http://plnkr.co/edit/ISa4xg

**Comment by lorenzofox3** [comment]
You don't have to bring any function or javascript, just use their template and make the plumbing with smart-table API, see [plunker](http://plnkr.co/edit/e82rdx7R4pjbLvayUHXx?p=preview)

**Comment by ribcakes** [comment]
Thank you for the plunker.
You would be correct for just first/back/forward/last buttons, however, I was partial to the way `ngTable` used ellipses.
However, having ellipses isn't really worth modifying the source, so I will use your example.
Thanks
