### ISSUE TITLE
Problem with the persist plugin

### ISSUE THREAD

**Issue by docseltsam** [lorenzofox3/Smart-Table#290]
I tried your solution for persistence with the latest version of smart-table.debug.js. I have the problem that every time I refresh the site the table jumps back to page 1 in the pagination.

I forked your stPersist plunkr:

http://plnkr.co/edit/gUVjELWEMpsQurww7683?p=preview

and just updated the smart-table.debug.js source. 

To reproduce the issue: Jump to a page greater the 1 in the paginator and press the refresh button. The table jumps back to page 1.

My solution would be following:

Change the stItemsByPage watcher at line 384 to

        scope.$watch('stItemsByPage', function (oldValue, newValue) {
          if (oldvalue !== newvalue) {
            scope.selectPage(1);
          }
        });

and comment out line 398

        // ctrl.slice(0, scope.stItemsByPage);

Could you please have a look. Thank you very much.

**Comment by lorenzofox3** [comment]
you are right, the pagination should not kick on the first page if the tableState is provided by the outside world. I ll try to have a look
