### ISSUE TITLE
force safe copy to be updated

### ISSUE THREAD

**Issue by llissssss** [lorenzofox3/Smart-Table#292]
Hey,

I am using the smart table to display a list of elements (array of objects), and when one is selected a form is displayed on the same state.
Everything works fine (source is updated when adding/removing/sorting, etc), but when I update one of the elements, the list is not updated (although the original one it is), so it seems that the updateSafeCopy() method is never called. I know it might be difficult to detect when a change is done to an object, that's why I am looking for an API call (or similar) to force the source to be updated.
I hope I made myself clear :)

Thanks and congrats for the good work.

Albert.

**Comment by lorenzofox3** [comment]
Hi, 

have a look at https://github.com/lorenzofox3/Smart-Table/issues/205 and let me know if that helps,

Laurent

**Comment by llissssss** [comment]
Wow, you are a legend! I was about to come up with a similar idea, as I tried before the angular.copy() method with no success. The angular.extend() method worked for me like a charm!

Thanks and keep up the good work!
