### ISSUE TITLE
pipe/ajax plugin + selection

### ISSUE THREAD

**Issue by xnog** [lorenzofox3/Smart-Table#294]
Hi, I cannot make pipe/ajax plugin + selection work together. Is it work? or it's something I am doing wrong?

I have just got the pipe/ajax plugin code from http://lorenzofox3.github.io/smart-table-website/#section-selection and put the directives st-select-row="row" st-select-mode="multiple" in the <tr>.

Thanks.

**Comment by yilik01** [comment]
Same here...  

I am using the following version.

  "dependencies": {
    "angular": "~1.3.12",
    "angular-route": "~1.3.12",
    "angular-bootstrap": "~0.12.0",
    "angular-smart-table": "~1.4.10",
    "bootstrap": "~3.3.1",
    "jquery": "~2.1.3"
  }
