### ISSUE TITLE
v1.4.10 no longer checks if the pipe is defined

### ISSUE THREAD

**Issue by lyml** [lorenzofox3/Smart-Table#296]
In v1.4.9 the stPipe directive code checked if the pipe was a function before replacing the existing pipe. This allowed you to write a pipe directive even if you didn't need one allowing the control of whether or not to use a pipe to be controlled elsewhere.

v1.4.10 always replaces the pipe function if stPipe is set and thus breaks this behaviour. As a workaround I have set my existing codebase to rely on v1.4.9 however from the commit logs it looks like this behaviour was unintented.

See diff for stPipe.js
https://github.com/lorenzofox3/Smart-Table/commit/bb19a5778c2f451787dbd85533dd6b91976b7d55

**Comment by lorenzofox3** [comment]
Hi, may I ask why you would use the pipe directive without assigning a function ?

**Comment by lyml** [comment]
Previous behaviour of the pipe directive made it so that if you sent in undefined through the directive it was equivalent with not having a pipe directive. This led to the ability to use smart-table as underlying table implementation in a control that could chose if you wanted to override the pipe or not by simply defining the pipe function before constructing it.

I.e. you could do something like this:
```html
<div class="ui-list-viewport">
    <table st-table="dispItems" st-safe-src="items" st-pipe="customPipe"">
        <thead>
            <tr>
                <th ng-repeat="(key, value) in (header)"
                    st-sort="{{key}}">
                    {{value}}
                </th>
            </tr>
        </thead>
        <tbody ng-show="true">
            <tr ng-repeat="row in dispItems">
                <td ng-repeat="(key, value) in row">{{value}}</td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td st-pagination st-items-by-page="pageSize">
                </td>
            </tr>
        </tfoot>
    </table>
<div>
```

**Comment by lorenzofox3** [comment]
ok, I will revert it
