### ISSUE TITLE
scope.$watch in stSelectRow needed?

### ISSUE THREAD

**Issue by tbaeg-eitccorp** [lorenzofox3/Smart-Table#298]
Disclaimer: I'm still new to angular so apologizes for any stupid questions or statements!

Is this $watch needed?

```
        scope.$watch('row.isSelected', function (newValue) {
          if (newValue === true) {
            element.addClass('st-selected');
          } else {
            element.removeClass('st-selected');
          }
        });
```

I was actually troubleshooting to figure out why my selections weren't working. Saw the $watch in my troubleshooting process decided to move everything to the click event. I found no real reason for the separate $watch besides exact sequence of events for .isSelected to be set prior to triggering the addClass; but honestly see no real value. This would eliminate an additional $watch on each row element; which, to me, is a performance improvement. Please correct me if I am wrong!

See below for the change.

```
      link: function (scope, element, attr, ctrl) {
        var mode = attr.stSelectMode || 'single';
        element.bind('click', function () {
          scope.$apply(function () {
            ctrl.select(scope.row, mode);

              if (element.hasClass('st-selected')) {
                  element.removeClass('st-selected');
              } else {
                  element.addClass('st-selected');
              }
          });
        });
```

**Comment by lorenzofox3** [comment]
the problem will happen when you are in single row selection mode. When one row will be selected the table will unselect the last one, and it has to react to it

**Comment by tbaeg-eitccorp** [comment]
Ah! That makes perfect sense. I had a one track mind with multiple selections. Also, I noticed the original object gets modified to have the isSelected property but the watch seems to be monitoring the safe copy. So, I noticed I had to enable the st-safe-src flag for selections to work. Haven't had much time to dive into this but any clarification would be great. Thanks!

**Comment by lorenzofox3** [comment]
the displayed collection is somehow an internal variable for your view to access the current displayed collection (sorted,filtered,paginated) whereas the safe source is the whole dataset loaded. Sometimes they are exactly the same (when you put all the logic (sort, filter,etc) in the client and therefore you have loaded all the data, or when you put all the logic in the server and the response from the server matches exactly the table state -see pipe/ajax plugin section-). Sometimes they are not, like if you want to delete or remove rows from you dataset, you have to tell smart-table to watch the reference collection by using st-safe-src (most of the time if you load  your data after the table has been rendered and initialized)
Yes indeed it adds a property to your model when you select a row and this might be a bit intrusive, but note that the items within both collection (displayed and reference) are the same references, so if you add a property to an item in a collection, this property will be added to the same item in the other. 
However displayedCollection.indexOf(item) may be different than safeSourceCollection.indexOf(item) for the same item and displayedCollection.indexOf(item) may change for the same item whenever the tableState change

**Comment by anatoly314** [comment]
@lorenzofox3 , is it still single approach to implement single selection? I use the following directive:
```
.directive('stSelectRowCustom', function () {
    return {
      restrict: 'A',
      require: '^stTable',
      scope: {
          row: '=stSelectRowCustom',
          callback: '&stSelected' // ADDED THIS
      },
      link: function (scope, element, attr, ctrl) {
        var mode = attr.stSelectMode || 'single';
        element.bind('click', function ($event) {
          scope.$apply(function () {
              ctrl.select(scope.row, mode, $event.shiftKey);
              scope.callback(); // AND THIS
          });
        });

        scope.$watch('row.isSelected', function (newValue) {
            if (newValue === true) {
              element.addClass('st-selected');
            } else {
              element.removeClass('st-selected');
            }
        });
      }
    };
```
And it works very slow with pagination, it takes around 0.5 second to switch between pages. I have 15 rows in total, every page 10 rows. Can `$watch` in this directive be a reason and if yes, can it be replaced? Thank you.
