### ISSUE TITLE
Request for tutorial on how to edit Columns/Rows within Smart Tables

### ISSUE THREAD

**Issue by RC1245** [lorenzofox3/Smart-Table#299]
I think smart table is by far the best table out there, the only thing that I find missing is a simple tutorial on how to edit cells within the table. I understand there is a collection being displayed on the smart table and any changes need to be reflected in the model.

What is the best approach to do this?

**Comment by briantully** [comment]
+1

I read that the ability to edit a cell's data used to be a feature that was recently removed. I'd like to add that functionality back in and would love some tips on how to begin doing that, whether it be a custom plugin or a patch to commit. I'm new to AngularJS so any help would be greatly appreciated :)

**Comment by lorenzofox3** [comment]
As explained in https://github.com/lorenzofox3/Smart-Table/issues/275 this is not really something related to a table. As smart table follows a declarative approach you can use whatever directive you want for inline editing, just google "inline editing angular" and you'll find plenty of examples. There even is one on the angular documentation page for ngModelController ;)

**Comment by spo** [comment]
This could be an option for you: https://vitalets.github.io/angular-xeditable/#editable-row
