### ISSUE TITLE
Table not update when use splice rowCollection as replace function

### ISSUE THREAD

**Issue by vietnh** [lorenzofox3/Smart-Table#300]
Hi,

I'm using Smart-Table to work with my project. Everything is going well with display, select, remove items. But when I do an "edit row" button with will call a request to server and return the updated row, the rowCollection was updated but the table is not. I'm just using the splice function of array, the same with add and remove item but don't know why it's not working. Here's my code:

my table:

        <div class="col-md-12">
            <table st-table="displayedCollection" st-safe-src="rowCollection" class="table table-striped">
                <thead>
                    <tr>
                        <th st-sort="id">Client ID</th>
                        <th st-sort="name">Client Name</th>
                        <th st-sort="active">Active</th>
                        <th st-sort="deleted">Deleted</th>
                    </tr>
                    <tr>
                        <th>
                            <div class="inner-addon left-addon">
                                <i class="glyphicon glyphicon-search"></i>
                                <input st-search="'id'" placeholder="ID" class="input-sm form-control" type="search" />
                            </div>
                        </th>
                        <th colspan="3">
                            <div class="inner-addon left-addon">
                                <i class="glyphicon glyphicon-search"></i>
                                <input st-search="'name'" placeholder="Name" class="input-sm form-control" type="search" />
                            </div>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr ng-repeat="row in displayedCollection">
                        <td> {{ row.id }} </td>
                        <td> {{ row.name }} </td>
                        <td> {{ row.active }} </td>
                        <td> {{ row.deleted }} </td>
                        <td>
                            <button type="button" ng-click="removeClient(row)" class="btn btn-sm btn-primary">
                                <i class="glyphicon glyphicon-edit">
                                </i> Edit
                            </button>
                        </td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="6" class="text-center">
                            <div st-pagination="" st-items-by-page="itemsByPage" st-displayed-pages="displayedPages"></div>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>

and in my script i used this function:

function editData(index, data, $scope, $timeout, $http) {
                $http(
                        {
                            method: "POST",
                            url: clientUrl,
                            data: data,
                        }).success(function (data) {
                            if (index !== -1) {
                                $scope.rowCollection.splice(index, 1, angular.fromJson(data));
                                //$scope.rowCollection.splice(index, 1);
                            }
                        }).
                error(function (data, status, headers, config) {
                    alert('Something went wrong with the server!');
                });
            }

The "$scope.rowCollection.splice(index, 1)" is working fine but when i replace it with "$scope.rowCollection.splice(index, 1, angular.fromJson(data))" the table is not updated anymore. Please help me with this.

**Comment by lorenzofox3** [comment]
have a look at https://github.com/lorenzofox3/Smart-Table/issues/205
 ;)

**Comment by vietnh** [comment]
wow it worked :+1: , thank you very much.
Why don't you add an example of this on web site. I think there are many people confuse about this too :D.
