### ISSUE TITLE
Watching changes to object equality on stSafeSrc

### ISSUE THREAD

**Issue by johnjcorcoran** [lorenzofox3/Smart-Table#302]
Hi,

I'm using [ui-sortable](https://github.com/angular-ui/ui-sortable) to add drag and drop to my tables. I'm aware of other libraries to do the same but this suited our needs best.

The problem of combining this with Smart Table is that when dragging to re-order the table, the effect is that the change to the `rowCollection` (using the same naming in the [docs](http://lorenzofox3.github.io/smart-table-website/) stSafeSrc example) does not change the length of the collection, nor does it change the reference to the collection, so the two watches on `stSafeSrc` (one for length, one on the reference to the object) do not trigger the listeners. Because the listeners do not get triggered, this puts the `rowCollection` and the `displayedCollection` out of sync.

One way of combining the two successfully is make the `$watch` on `stSafeSrc` use `objectEquality == true`, the third parameter to `$scope.$watch`:
```
    if ($attrs.stSafeSrc) {
      ...
      $scope.$watch(function () {
        return safeGetter($scope);
      }, function (newValue, oldValue) {
        if (newValue !== oldValue) {
          updateSafeCopy();
        }
      }, true); 
    }
```

I tried this and it fixed the problem.

Unfortunately, this *might* have performance implications:
> When objectEquality == true, inequality of the watchExpression is determined according to the angular.equals function. To save the value of the object for later comparison, the angular.copy function is used. This therefore means that watching complex objects will have adverse memory and performance implications.

See [$rootScope.Scope](https://docs.angularjs.org/api/ng/type/$rootScope.Scope)

I'm wondering if the performance implications of changing the `$watch` on `stSafeSrc` in this way have been measured or considered?

If it does indeed hurt performance for large tables - which certainly seems likely - would the ability to optionally set watching with `objectEquality == true` ever fit in as a possible addition to the API?

Alternatively, is there a better way of dealing with this issue?

I can provide a plunkr if the issue is unclear from my description. Thanks for your time and for this useful module.

**Comment by lorenzofox3** [comment]
Yep, I have discussed about this https://github.com/lorenzofox3/Smart-Table/issues/205 and I am not fan of adding the true by default. But why not setting it as configuration, seems a good solution.  Not sure how ui-sortable works but note that the collection in the repeater (the one ui-sortable will use I guess) is the displayed collection, so I don't think a reordering of these items would trigger at refresh of the safe source anyway. In your particular case, what is the reason for you to use `stSafeSrc` ? if could get rid of it and use only the displayed collection your problem would be solved

**Comment by daniel-lanciana** [comment]
Hi,

Great module and excellent comprehensive documentation.

I am getting **"Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!"** exceptions unless I set the objectEquality flag to TRUE. 

Using JSON.stringify() the newValue and oldValue arrays are identical. My preference is not to modify this library solely for the purposes of this exception. Any suggestions welcome.

Cheers, Daniel.

**Comment by lorenzofox3** [comment]
@daniel-lanciana 
could you please open a different issue (with a way to reproduce it like plunker, would be great) ? I suspect you use the same collection for safe source and for the displayed one

**Comment by daniel-lanciana** [comment]
**@lorenzofox3**
You're right, I was using the same collection -- I copied and pasted the example from 'Sort data'. Thanks.
