### ISSUE TITLE
Add ability to defer to the default pipe function

### ISSUE THREAD

**Issue by IllyaMoskvin** [lorenzofox3/Smart-Table#304]
It might be nice if it were possible to somehow call the default pipe function (from within the function passed to `st-pipe`) in some cases instead of making a server call. In particular, this would be useful when the page size equals or exceeds the total results as reported by the server. (Doing this check would be up to the programmer from within their `st-pipe` function.) Currently, the `st-pipe` directive overrides the default pipe function entirely. Maybe save `ctrl.pipe()` to `ctrl.defaultPipe()` before overriding?

There's some issues with this though. For example, if `tableState.sort` was defined before the call to the server was made, the primary sort order will default to that. Again, this might depend on the implementation by the programmer, but it's something to watch out for.

Thanks for the great plugin!

**Comment by lorenzofox3** [comment]
yep it seems a good idea to expose the default pipe function. note however that it relies on several closures, so it might involve leaks or side effects. To be double checked

**Comment by sylvainpolletvillard** [comment]
How can I use this ?

```
$ctrl.onTableStateChanged = function(tableState, stController) {
	console.log(tableState, stController)
	//return stController.pipe(); // infinite loop	
};
```

I don't see any default pipe function exposed in your commit.
