### ISSUE TITLE
How do you programmatically make Smart Tables execute a custom pipe filter?

### ISSUE THREAD

**Issue by mediagiant** [lorenzofox3/Smart-Table#305]
Hello,
I have an ajax function that removes a record from the database. I would like to force smart tables to reload upon success, however, I cannot figure out how to get a copy of the current tablestate from smart tables. 

I need the tablestate to be able to force my table to reset, as well as to dynamically change the pagination when "views" switch on the table.

This is my custom pipe:

 $scope.serverFilter = function(tablestate)
    {
        tablestate.start = tablestate.pagination.start || 0;
        tablestate.number = tablestate.pagination.number || 10;
        
        $http.post("/portal/api/loadleads",tablestate).success(function(response){
            console.log(response);
            $scope.leads = response.leads;
            tablestate.pagination.numberOfPages=response.totalPages;
            $scope.leadsCollection = [].concat($scope.leads);
        });
    }

Then I have this other function to remove a lead, which is my first use case for needing to grab the tablestate.

    $scope.removeLead = function()
    {
        if (confirm("Are you sure you wish to remove this lead?"))
        {
            $http.post("/portal/api/removelead",$scope.editor.leaduid).success(function(response){
                if (response.success)
                      $scope.serverFilter(tableState); // where or how do I retrieve the current tablestate?
           });
        }
    }

Finally, is there a way to "set" a tablestate. For example, when switching between views, I may want to revert to what was previously selected in terms of filters and sorts on a particular data set. Can I change this just by resetting the values of the retrieved object?

Thanks in advance for your help.

**Comment by lorenzofox3** [comment]
within the table, you can plug any directive which require ``^stTable`` so the table controller is available as fourth argument of you link function and then you can access the table state by calling ``ctrl.tableState()`` there are few examples across the issues section about restoring a table state stored in local storage or about reseting the table state.
From outside the table, you can access it within a custom pipe function (as the first argument), the pipe function should be called whenever the table state changes

**Comment by yanivkalfa** [comment]
You need to add some sort of render function .. so user can manually make changes to the tabledata / state and invoke render - and the table re renders ..

**Comment by pashamesh** [comment]
There is one dirty hack

```html
<table class="table" st-pipe="pipeFunction" ...>
....
```

In your controller:
```javascript
$scope.pipeFunction = function(tableState, ctrl)
{
    if ( !$scope.stCtrl && ctrl )
    {
        $scope.stCtrl = ctrl;
    }
                
    if( !tableState && $scope.stCtrl ) {
        $scope.stCtrl.pipe();
        return;
    }

    tableState.start = tablestate.pagination.start || 0;
    tableState.number = tablestate.pagination.number || 10;

    // get data
}
```

Then you can call `pipeFunction` in your controller to update entries from server.

**Comment by piterwilson** [comment]
The dirty hack works well, but if i have more than one smart table in my template, i start getting errors. Any way to get the specific tableState of a particular table?

**Comment by sharonx** [comment]
@pashamesh I used your solution and it works. The only problem is that the initial requests are sent twice to the server. Once from  $scope.stCtrl.pipe(); and once from the st-table itself.

**Comment by ajsb85** [comment]
It's works for me:
```js
$scope.pipeFunction = function (tableState, ctrl) {
 $scope.stCtrl = ctrl;
};
```

```js
$scope.stCtrl.pipe($scope.stCtrl.tableState());
```
