### ISSUE TITLE
Sort icons not appearing

### ISSUE THREAD

**Issue by OhioGuy67** [lorenzofox3/Smart-Table#306]
I have a table setup with the st-sort directives included in the <th>.  When I click on the table headers, the table is correctly sorted but the direction icon is not being displayed.  Can you please tell me what I'm missing?  I'm using Angular 1.3.11 and smart-table 1.4.10.

**Comment by lorenzofox3** [comment]
see https://github.com/lorenzofox3/Smart-Table/issues/259

**Comment by OhioGuy67** [comment]
Thank you, that worked!
