### ISSUE TITLE
Can't get sorting to work

### ISSUE THREAD

**Issue by renang** [lorenzofox3/Smart-Table#309]
Hi, I'm sorry if this is not the place for this. But I can't get sorting to work.

- Data is being loaded with AJAX (array contains nested objects)
- I'm using the st-safe-src directive
- Table displays data just fine, but sorting doesn't work

Markup:

![image](https://cloud.githubusercontent.com/assets/11202133/6382802/77748264-bd11-11e4-88bb-d6773632af0e.png)

Controller:

![image](https://cloud.githubusercontent.com/assets/11202133/6382807/86c45438-bd11-11e4-8b4c-b764b361f415.png)

**Comment by lorenzofox3** [comment]
what is "consultant" (object, string, ... ) ?

**Comment by renang** [comment]
String...

**Comment by lorenzofox3** [comment]
why did you close the issue, did you fine a solution ?
