### ISSUE TITLE
Binding to filter inputs

### ISSUE THREAD

**Issue by dandanknight** [lorenzofox3/Smart-Table#311]
Hi, I'm probably going about this the wrong way, but I am trying to create some buttons that allow the user to toggle filter for some common states, for instance, state === 'done', state === 'failed' 

I have set up some filter input boxes (which will be hidden eventually from the user), which have an ng-model, and then I have buttons that set the text of these inputs. When I click the button, the input is set with the correct text to filter by, but the table doesn't filter until I manually change something in the box, like add a character and delete it again.

My question is, is there a way to trigger the filter after I have set the filter text?

Also, is there a better way I could be doing this? For instance, could I use an st-search directly on a button? Or can I set filters programatically from the controller?

I appreciate any help, great module by the way.

Dan

**Comment by dandanknight** [comment]
Sorry, ignore, I've just discovered how to get this done in a directive by requiring the table, thanks to a plunkr you left on StackOverflow. 

Thanks again

**Comment by dandanknight** [comment]
Could I ask another question though, maybe a feature request? Is it possible to search for multiple values on one column? Or would this require a custom filter?

**Comment by leftstick** [comment]
Same question. Could someone help on this?
