### ISSUE TITLE
Was `angular-smart-table.debug.js` removed?

### ISSUE THREAD

**Issue by srph** [lorenzofox3/Smart-Table#312]
My `bower.json` file requires `smart-table`  with the `*` version. I just ran `bower update`, and the latest issues seem to have messed things up.

Was `angular-smart-table.debug.js` removed? I was using it, and it took me a while to realize that `.debug.js` was missing from the latest version.

**Comment by lorenzofox3** [comment]
yes, 

cf https://github.com/lorenzofox3/Smart-Table/pull/308

**Comment by srph** [comment]
Alright, thanks.
