### ISSUE TITLE
Pagination issue -referred issue 169

### ISSUE THREAD

**Issue by bhushanvaidya3** [lorenzofox3/Smart-Table#315]
First of all, thanks for making an awesome grid control. I'm using the smart-table control with AngularJS 1.3x and for some reason, pagination is not working when I populate data from a WCF REST service. If you switch back to Angular 1.2x, the pagination works fine as shown in the plunk below.

I referred issue 169 and forked your plunk to provide you a sample. http://plnkr.co/edit/HP6LET?p=preview

Again, thank you for all help. Much appreciated!!!

**Comment by lorenzofox3** [comment]
you don't use the latest version of ST. with 1.4.12, I don't see any problem http://plnkr.co/edit/fQxRkF?p=preview

**Comment by bhushanvaidya3** [comment]
Thank you!
