### ISSUE TITLE
Design question: Possible to handle stSafeSrc internally?

### ISSUE THREAD

**Issue by stanleyxu2005** [lorenzofox3/Smart-Table#317]
Dear developer,

I'm rendering a table periodically via Ajax. According to the manual, I have to create two arrays `displayArray` and `receivedArray` to get it work. Is it possible to maintain the `displayArray` internally, so that we do not have to maintain two array copies explicitly?

**Comment by lorenzofox3** [comment]
Actually you don't have to maintain the displayed collection, `st-table` is just a way to set how you will call the displayed collection variable in your view http://plnkr.co/edit/LT3LOPmAQc9x59NXs92i?p=preview
We could use a var name by definition (so no need for `st-table` attribute) but then you might bump into name collision, people will complain they can't choose var name, etc

**Comment by stanleyxu2005** [comment]
Nice tip! Thanks and I'd be appreciated if you can put the information to documentation.
