### ISSUE TITLE
Retrive collection of filtered data

### ISSUE THREAD

**Issue by BobKurtis** [lorenzofox3/Smart-Table#318]
Is there a way to retrieve the array of filtered results (regardless of page). i can retrieve the filtered results per page with displayedCollection but is there a filteredCollection or a way to achieve it, I'm exporting smart-table to csv

**Comment by lorenzofox3** [comment]
duplicate of https://github.com/lorenzofox3/Smart-Table/issues/261

**Comment by ProNJ** [comment]
Can you please provide demo or plunker for the same functionality.
