### ISSUE TITLE
Hey How to achieve Custom Columns In Smart Table?

### ISSUE THREAD

**Issue by talasila66** [lorenzofox3/Smart-Table#321]
I am planning to use smart client for my development, I can see a feature missed in Smart Table is Custom Columns.

Suppose a table has 10 columns of data,based on the users preferences few of the columns will be shown it may be 5 or 4 or even 10.

I can see ng-table support this?

Is it supported in SmartTable?, can you please help me how it will be supported?

**Comment by lorenzofox3** [comment]
One of the goal of smart-table is to avoid configuration approach so it remains open and extensible.
But of course you can add a configuration layer on top of it if you find it more convenient
http://plnkr.co/edit/m1gqJr?p=preview

**Comment by talasila66** [comment]
Thank you.It 's really helpful

**Comment by talasila66** [comment]
:+1:
