### ISSUE TITLE
How Column Re-Sizing Is Supported in Smart Table.

### ISSUE THREAD

**Issue by talasila66** [lorenzofox3/Smart-Table#323]
When the user views the application table in viewport,suppose he wants to reduce or increase the column width.

Is this feature supported in Smart Table,if yes can you help me how it is supported?

**Comment by lorenzofox3** [comment]
This is not supported and not related to this module. At the end what you need is more a directive to resize table header, I might provide an example soon

**Comment by talasila66** [comment]
Sure Thank You, will wait for the example from your side :+1:

**Comment by Lokua** [comment]
An example would be awesome!

**Comment by cleversonpuche** [comment]
Waiting for an example too.

**Comment by dlwhiteman** [comment]
@talasila66 , did you close this issue because an example was provided?  I checked the documentation and can't find an example of user resize of columns.

**Comment by stoplion** [comment]
+1

**Comment by stefan-leye** [comment]
+1

**Comment by francoisgergaud** [comment]
+1

**Comment by santhosh-v** [comment]
+1

**Comment by alvachien** [comment]
+1

**Comment by angufix** [comment]
so where is the example?

**Comment by boltex** [comment]
+1

**Comment by vishalkrv** [comment]
+1.. Left with no choice and moving to ui-grid

**Comment by ericpoulinnz** [comment]
+1

**Comment by rameshj28787** [comment]
+1.  

Hello all, 
I found this one while searching for examples.  I hope it will work on smart-table too.  
http://stackoverflow.com/questions/25506512/resizable-columns-with-angularjs
The plugin ("colResizable") looks like a jquery component wrapped in an angular directive .

**Comment by rameshj28787** [comment]
CellCursorColResize directive from AngularCellCursor
https://github.com/team-lab/cell-cursor/blob/develop/cellCursor.js  Line#1142
