### ISSUE TITLE
Can left/right page arrows be displayed?

### ISSUE THREAD

**Issue by OhioGuy67** [lorenzofox3/Smart-Table#325]
For my table, I have the st-displayed-page parameter set.  Is there a way to display the left/right page arrows to scroll through the possible pages?  I'm asking only because I saw a website that was comparing table plugins and the screenshot they had for smart-table had the arrow keys (I didn't see an option in the documentation or briefly looking through the code).

**Comment by OhioGuy67** [comment]
http://angularjs4u.com/tables/top-10-angularjs-table-demos/

**Comment by lorenzofox3** [comment]
https://github.com/lorenzofox3/Smart-Table/issues/289

**Comment by OhioGuy67** [comment]
Thanks.  How do I overwrite the template in the template cache?

**Comment by OhioGuy67** [comment]
Never mind, I figured it out.  :)

**Comment by SydneySmith** [comment]
Can you please share your answer?

**Comment by OhioGuy67** [comment]
Use the st-template directive and specify the .html template that is somewhere in your application.
