### ISSUE TITLE
Getting number of items in table in pagination template

### ISSUE THREAD

**Issue by OhioGuy67** [lorenzofox3/Smart-Table#327]
I'm using a specialized pagination template for my table.  Is there a way to get the number of items currently displayed in the table inside of the template?  I didn't see any scope variables for it.

**Comment by OhioGuy67** [comment]
Actually I meant the total number of items in the table after filtering.

**Comment by lorenzofox3** [comment]
#304

**Comment by OhioGuy67** [comment]
My table is doing everything on the client side (i.e., doesn't make server call) so I apologize but I don't see how issue #304 answers my question.

**Comment by lorenzofox3** [comment]
sorry wrong link https://github.com/lorenzofox3/Smart-Table/issues/261 :)

**Comment by lorenzofox3** [comment]
you can use for example
```Javascript
  .directive('stSummary', function () {
    return {
      restrict: 'E',
      require: '^stTable',
      template: '<div>records:{{size}}</div>',
      scope: {},
      link: function (scope, element, attr, ctrl) {
        scope.$watch(ctrl.getFilteredCollection, function  (val) {
          scope.size = (val || []).length;
        })
      }
    }
  })
```
to display the number of records which match

**Comment by OhioGuy67** [comment]
Sorry for some newbie follow-up questions (just so I'm clear).  Do I add your above example directly into the smart-table.js file and then add a st-summary directive in my html?  Which element do I put the directive on my in my html (the table, the tr that has the ng-repeat)?  Does getFilteredCollection get called even if there is no filter on the table?

Thank you for the assistance.

**Comment by spt131** [comment]
I've been unable to access the filteredCollection, could someone share an example of this working as Lorenzo's directive above?

**Comment by jbonigomes** [comment]
Hi @spt131 does this help? http://plnkr.co/edit/kKzrXKbwoMwDP1JMrvQJ?p=preview

**Comment by spt131** [comment]
Thanks Jose, that does help. I got it working with this plunker.

**Comment by jbonigomes** [comment]
Good stuff
