### ISSUE TITLE
2.0.0 request table stage for every st search directive

### ISSUE THREAD

**Issue by JanStevens** [lorenzofox3/Smart-Table#328]
Before I had multiple st-search directives and my st-pipe function would be called once when the page loads.

With the new version 2.0.0 I see that the st-pipe function is called for every directive I have on the page during loading. On one of my tables this creates 15 request to our server instead of one.

**Comment by JanStevens** [comment]
Ha it seems I had an older version, from version 1.4.12 I see the described issue already

**Comment by JanStevens** [comment]
Haaa forgot to restart my server, everything working, thnx!

**Comment by lorenzofox3** [comment]
I fix it for 2.0.0 as well

let me know if there is anything wrong
