### ISSUE TITLE
Access to filtered entries

### ISSUE THREAD

**Issue by totycro** [lorenzofox3/Smart-Table#330]
I would like to show the number of entries filtered by st-search along the lines of this:

```html
<table st-table="entries_displayed" st-safe-src="entries">
    ...  <input st-search=""/> ...
    ...  <th> Showing {{ entries_filtered.length }} entries </th> ...
</table>
```

According to a stackoverflow post, this is currently not possible: http://stackoverflow.com/questions/28985412/show-number-of-filtered-entries-in-smarttable#comment46219934_28985412

In the code, `filtered` in `pipe()` would contain the right data. Would it be possible to make it accessible somehow? It would make st-table a lot more flexible.

**Comment by lorenzofox3** [comment]
https://github.com/lorenzofox3/Smart-Table/issues/327
