### ISSUE TITLE
Search broken

### ISSUE THREAD

**Issue by croivzeba** [lorenzofox3/Smart-Table#332]
Updating from 1.4.11 to 2.0.1 seems to break search functionality, the issue appears to be with the way the predicateObject is generated. If st-search is set to 'id' for the column and the number 1 is typed in, the following arrays are generated

1.4.11:
{id: "1"}

2.0.1:
{'id': "1"}

Because of the quotes it does not seem to be possible to access the field through Object.id

**Comment by lorenzofox3** [comment]
yes there is a breaking change, Have you had a look at the changeLog.md

**Comment by croivzeba** [comment]
It seems my eyes were tired last night and I overlooked it.

As per change log for any one in the future that is looking at this:

<code>
This is a breaking change as now, you will have to remove the single quote around the predicate property name, and if you were using a binding, you'll have to interpolate it with the curly brace notation
</code>

Love the tool, keep up the great work!
