### ISSUE TITLE
How to set initial page number and initial sort order?

### ISSUE THREAD

**Issue by oliverzy** [lorenzofox3/Smart-Table#333]
Hi,

I'm trying to use AJAX/PIPE plugin to do pagniation/sort/order. It works great.
But I don't find a way to set initial page number/sort oder.

The initial page number/sort order is retrieved from $location.search()

**Comment by lorenzofox3** [comment]
you can have a look at the "persist example"  on the documentation, where the tableState is basically recreated from local storage (so it could be from $location). Note however, any change in the tableState is likely to trigger another call to pipe function (so now, you don't have to manually call the pipe function). I think there is a bug with the pagination directive with triggers an unwanted second call (https://github.com/lorenzofox3/Smart-Table/issues/329)

**Comment by lorenzofox3** [comment]
:+1:

**Comment by oliverzy** [comment]
Thanks a lot!
