### ISSUE TITLE
Searching within a set of fields

### ISSUE THREAD

**Issue by jeffhoang** [lorenzofox3/Smart-Table#338]
Is it possible to search within a set of fields, instead of globally?

Example: 

st-search="'name','description'"

**Comment by lorenzofox3** [comment]
http://stackoverflow.com/questions/28791998/angularjs-smart-table-search-within-multiple-columns

**Comment by jbonigomes** [comment]
I tried this out, but couldn't get it to work, is there an official way of doing it now?

**Comment by jeffhoang** [comment]
I tried a different approach to this and created a model watcher outside the scope of this module.  

Example (coffeescript) : 

      query = @$scope.query

      # collection used by smart-table
      collection = @$rootScope.original_data

      if query?
        query = query.toLowerCase()
        newCollection = []
        for item in collection
          name = item.name.toLowerCase()
          description = if item.description? then item.description.toLowerCase() else ""
          if name.indexOf(query) != -1 or description.indexOf(query) != -1
            newCollection.push(item)

        @$scope.data = newCollection
      else if !query? or query.length == 0 or query == ''
        @$scope.data = collection
