### ISSUE TITLE
Does the Smart-Table keep track of the selected items?

### ISSUE THREAD

**Issue by DrAlexMV** [lorenzofox3/Smart-Table#34]
Is there a way to keep track of the selected items easily instead of watching and checking my data models?

**Comment by jcford73** [comment]
Was this event removed at some point? Is there some other way of attaching to a selection change event now?

**Comment by lildukedana** [comment]
I've tried a lot of work a rounds, but still can't trigger and event or get a watch over the collection.

**Comment by lorenzofox3** [comment]
please note that this issue is 2years old and related to a deprecated version of smart-table...

**Comment by lildukedana** [comment]
I just pulled your module not even two weeks ago. Is there any updated documentation on handling a row event or keeping track of the bound collection with an example??

**Comment by lorenzofox3** [comment]
Smart table simply add a isSelected = true to selected items following a given set of rules depending on the selection mode (and add a class on selected rows for styling purpose). Then you can do whatever  you want depending on your use case:
1.  creating watch on item basis
```Javascript
app.directive('selectNotifier', function(){
   return {
     scope:{
        row:'=',
        link:function(scope){
             scope.$watch('row.isSelected', function(value){
                // do what you want 
             })
        }
     }
   }
})
```

2. add your own event handler on the row
```Makrup
<tr st-select-row="row" ng-click="doSomething(row)></tr>
```

3. if it a bulk operation you want to do you can simply filter selected items when performing the action
```Javascript
$scope.doSomeStuffToSelected=function(){
   var selected = $scope.rowCollection.filter(function(item){
     return item.isSelected === true;
   })
   //do something with selected
}
``` 

4. globally enhance smart table controller
from a directive which require smart-table controller
```Javascript
var originalSelect = ctrl.select.bind(ctrl)
ctrl.select = function (row, mode) {
      originalSelect(row, mode)
       // do something else
}
```

actually this one could be easier if the controller.select returned the list of currently selected items

Anyway there is plenty of choices, you can even run you own selection code if you find it more convenient

**Comment by lildukedana** [comment]
Awesome, problem solved. Thanks for taking the time to comment on this dinosaur of an issue!!!!!
