### ISSUE TITLE
table not refreshing on data update

### ISSUE THREAD

**Issue by jmls** [lorenzofox3/Smart-Table#340]
I have a process that completely updates  (ie replaces)  an array every x seconds. This array is used as the data source for smart table.

no matter what I do , the table is drawn with the initial set of data, but never gets updated after that.

I've tried st-safe-src etc to no avail

is this a bug, or am I doing something really stupid ...

**Comment by lorenzofox3** [comment]
plunkr?

**Comment by jmls** [comment]
no need, looks like a freaking typo in my code () != [] 

apologies for the waste of space and time
