### ISSUE TITLE
Cell flickering on background data refresh maybe reduce cell update

### ISSUE THREAD

**Issue by stanleyxu2005** [lorenzofox3/Smart-Table#341]
I have two tables, one is normal bootstrap table and the other one is with smart-table directive. Both tables will be updated by an ajax periodically. If I select a cell, the bootstrap table will NOT clear my selection, unless the cell content is changed. But the smart-table will change periodically, regardless the content is not changed.

```
<table st-table="ng" st-safe-src="apps" class="table">
  <thead>
  <tr>
    <th st-sort="id" st-sort-default="reverse">ID</th>
    <th st-sort="name">Name</th>
  </tr>
  </thead>
  <tbody>
  <tr ng-repeat="app in ng">
    <td><span ng-bind="app.id"></span></td>
    <td><span ng-bind="app.name"></span></td>
  </tr>
  </tbody>
</table>
```

Do you think the problem can be fixed?

**Comment by lorenzofox3** [comment]
what do you mean by selection ? I don't see any code related to selection in your sample ?

**Comment by stanleyxu2005** [comment]
@lorenzofox3 I use a periodically ajax call to update `$scope.apps`. And then you will see data in table and they will be changed periodically. If I select cell text (with mouse), the selection will be cleared, when new ajax result is received, regardless the text of selection is changed or not.

**Comment by lorenzofox3** [comment]
I still don't get what you mean by selection. Smart-table allows selection on row not cell, so I have no idea what you are talking about

**Comment by stanleyxu2005** [comment]
I've created a live demo https://jsfiddle.net/stanleyxu2005/os7L19hp/
Here are the steps:
1. Use mouse to select a row, Wait for data update, The selection will not disappear.
2. Use mouse to select a cell, Wait for data update, The selection will gone.

Unfortunately it also happens on a normal table...
