### ISSUE TITLE
Inline editing

### ISSUE THREAD

**Issue by VPatrick** [lorenzofox3/Smart-Table#343]
How can I edit cells inline?
Is there any directive or something else?

Cheers,
Patrick

**Comment by Toilal** [comment]
You can use [xeditable](http://vitalets.github.io/angular-xeditable/). It's not really maintained at the moment, but it works.

**Comment by lorenzofox3** [comment]
#275 and #230 have examples. If you search the issues section with "inline editing" you may find a couple more

**Comment by VPatrick** [comment]
Thanks a lot.
