### ISSUE TITLE
fixed headers with flex box?

### ISSUE THREAD

**Issue by mikeupton** [lorenzofox3/Smart-Table#345]
I'm trying to use smart table with fixed headers, in a page laid out with flex box.  The table seems to grow beyond the bounds of the container that is being sized for it by flex box.

If I give the table a fixed height - the fixed headers work fine.

Is it expected that i can use the fixed header example - with a table inside of a div sized by flexbox?

Thanks.

**Comment by lorenzofox3** [comment]
I have no idea !  This is more about css than smart table.
