### ISSUE TITLE
The default pagination template uses incorrect Bootstrap markup

### ISSUE THREAD

**Issue by blaise-io** [lorenzofox3/Smart-Table#348]
The default pagination template is currently this:

```
<div class="pagination" ng-if="pages.length >= 2"><ul class="pagination">...</ul></div>
```

Due to `ul.pagination` being nested in `div.pagination`, there are double margins, which looks bad.

The [default Bootstrap example](http://getbootstrap.com/components/#pagination) uses this markup:

```
<nav ng-if="pages.length >= 2"><ul class="pagination">...</ul></nav>
```

I have overwritten the template in my own app, but I think it's good to fix the default in this library as well.

**Comment by lorenzofox3** [comment]
I think it is fine in the latest version https://github.com/lorenzofox3/Smart-Table/blob/master/src/smart-table.module.js

**Comment by blaise-io** [comment]
It is, thanks!
