### ISSUE TITLE
keyboard accessible for all features currently activated by mouse only?  

### ISSUE THREAD

**Issue by getterdone** [lorenzofox3/Smart-Table#351]
for example being able to keyboard tab to (sort ^) and press enter to display sorting

**Comment by lorenzofox3** [comment]
You can write an external plugin to handle the keyboard event and call the controller api, I'll be happy to show your example on the documentation website

**Comment by getterdone** [comment]
yes that sounds like a good idea. Please link me to an example so I can give give it a shot at keyboard accessibility.
