### ISSUE TITLE
HowTo: Load data via router resolve, pipe just persists state into url

### ISSUE THREAD

**Issue by smajl** [lorenzofox3/Smart-Table#352]
Hi, I just can't figure out, if I can easily achieve this here.

Basically, my grid data is resolved before app state change via the `ui-router resolve` and injected into view controller - the `smart-table` gets populated. When user sorts/filters/paginates, I just wan't to call new app state (`$state.go(...)`), so the view will refresh and new data collection is resolved and injected. But if I override directly the `pipe` function, I'll get into infinite loop (**it is unfortunately auto-called after table initialization if specified**).

Use-case: State persistence, history, state sharing, bookmarks, etc.

I got this working e.g. with `ng-table`, but I wan't to give a `smart-table` a try. :) Thanks for suggestions (mainly @lorenzofox3). :)

**Comment by smajl** [comment]
Or at least.. put params in URL after/before pipe call. ng-table's getData function gets params object, which has url() serialization method which result you can just put into $location.search. Is there something similar in smart-table?

**Comment by lorenzofox3** [comment]
your infinite loop is strange, can you provide a plunker ?  
If you don't use custom pipe function, you'll need to serealize tableState into your new url/state, which you can get from any sub directive requiring the table controller, have a look at the stPersist example on the documentation website for instance

**Comment by smajl** [comment]
If I want to have $state.go(...) in custom pipe, I need to check that params really changed, or I will get the loop.. Anyway I sorted this out in a completely different way, sorry to bother, closing. :)

**Comment by Deminem** [comment]
@smajl - Hi Sam, I am also facing the same issue for ui.router and want all these use cases (State persistence, history, state sharing, bookmarks) working with smartTable. Can you please share that how do you solve this problem? Thanks.

**Comment by smajl** [comment]
@Deminem: Well, to be honest, I switched to ngTable - it works almost instantly there. I am not saying it doesn't work in Smart-Table, but I struggled to get it working.. :/
