### ISSUE TITLE
"st-sort" not working with api fetched data

### ISSUE THREAD

**Issue by NikhilNanjappa** [lorenzofox3/Smart-Table#353]
I'm fetching data by hitting an api and passing it through the scope to the smart table like so

![screen shot 2015-03-30 at 3 13 30 pm](https://cloud.githubusercontent.com/assets/5576981/6894009/63d7f7de-d6ef-11e4-80f5-3642849f3c8e.png)

Here is the data format of the 'scope.rowCollection' as seen on the console

![screen shot 2015-03-30 at 3 15 10 pm](https://cloud.githubusercontent.com/assets/5576981/6894033/990a68ba-d6ef-11e4-8e24-3bfbde0e9aeb.png)

When i'm trying to show the same data and sort it using st-sort method, the table values go blank clearly not sorting the column. Here is a view of my html snippet

![screen shot 2015-03-30 at 3 18 50 pm](https://cloud.githubusercontent.com/assets/5576981/6894091/21882056-d6f0-11e4-8e8f-acd0ea4222dd.png)

Can you please tell me what exactly am i doing wrong. The moment i use my own data collection set(NOT hard coded) the whole table values go haywire.
I have a feeling its something to do with the variable names that i'm using on the angular end. 
Any help is much appreciated....Thanks

**Comment by lorenzofox3** [comment]
because as your data is loading asynchronously, you should use st-safe-src attribute, search the issue section with "ajax" key word you'll find more explanations

**Comment by NikhilNanjappa** [comment]
Alright now i have added an attribute ' st-safe-src="rowCollection" ', the sorting works fine but it shows a huge error from angualrjs. I guess it ended up in an infinite loop

**Comment by lorenzofox3** [comment]
because in the repeater you use the same collection than your st-safe-src.
It should be as the example in the documentation website
```Markup
<table st-table="whateverNameYouWantToGiveInTheView" st-safe-src="rowCollection">
     <!-- -->
    <tr ng-repeat="row in whateverNameYouWantToGiveInTheView"></tr>
     <!-- -->
</table>
```

**Comment by NikhilNanjappa** [comment]
Ok got it. and for your above provided example, the scope variable's name passed from the controller should be ```$scope.rowCollection``` right?
