### ISSUE TITLE
stPipe directive: scope.stPipe is undefined during linking of the directive

### ISSUE THREAD

**Issue by Sayrus** [lorenzofox3/Smart-Table#355]
I'm using  Angular 1.4.0-beta.6 with angular-new-router (from master branch). The smart-table defined in Angular component (http://angular.github.io/router/getting-started#components) named employeesList. It looks like this:

```html
<table class="table"
       st-table="employeesList.users"
       st-pipe="employeesList.updateUsers">
...
</table>	
```

Inside EmployeesList component I implemented this fake function:
```javascript
this.updateUsers = function (a, b) {
    console.log(a, b); 
};
```

But scope.stPipe of stPipe directive during preLink is undefined - https://github.com/lorenzofox3/Smart-Table/blob/master/src/stPipe.js#L10

I'm not sure, that the issue is problem of Smart-Table, but I believe that $watch on scope.stPipe in this point won't be superfluous.

**Comment by lorenzofox3** [comment]
let's wait a bit for the proper 1.4 release

**Comment by lorenzofox3** [comment]
Do you still have the issue ?

**Comment by JamesHenry** [comment]
I believe I encountered the same root issue when creating a directive which wraps smart table in order to allow it to be dynamically constructed.

The custom pipe method in my directive is undefined at the time smart table evaluates it. Using the code in @Sayrus PR solved the problem.

Hope that helps, and thanks for ST!

**Comment by ibbatta** [comment]
@JamesHenry what method ? You have tagged someone without proving examples...

**Comment by JamesHenry** [comment]
It is the PR linked to this issue above (#356). It is over 13 months ago since I wrote that, but I can only assume that Sergey changed his username...
