### ISSUE TITLE
smart-table css doesn't work

### ISSUE THREAD

**Issue by fish3** [lorenzofox3/Smart-Table#358]
why my table css doesn't work？
![image](https://cloud.githubusercontent.com/assets/11770165/6962820/065ed4dc-d96b-11e4-8935-d33a004e4b4e.png)

**Comment by lorenzofox3** [comment]
did you include your stylesheet ? anyway, I am sorry but it is really out of topic

**Comment by fish3** [comment]
I thought smart-table provide the css ？
