### ISSUE TITLE
st-table directive is not needed

### ISSUE THREAD

**Issue by bastienJS** [lorenzofox3/Smart-Table#361]
This is your sample: http://plnkr.co/edit/fcdXKE?p=preview

When I remove the => st-table="displayed" from the table-tag the sample still works.

Why? When do I really need this directive?

**Comment by lorenzofox3** [comment]
no it won't work, your data will still be displayed as smart-table is declarative and the ng-repeat will display your data, but you will not have pagination, sort, filter etc

**Comment by bastienJS** [comment]
ok the sample works... just not when plugins are included.
