### ISSUE TITLE
AutoResize plugin for smart table just like ui-grid has

### ISSUE THREAD

**Issue by bastienJS** [lorenzofox3/Smart-Table#362]
I need a lightweight "table" thus I choose yours over the fat ui grid.

But what I miss in your smart table is a little feature called auto resize of the table when the window resizes.

Could you implement that please? 

Just like ui grid has: http://ui-grid.info/docs/#/tutorial/213_auto_resizing

source: https://github.com/angular-ui/ng-grid/blob/acda59a7aceb44af9de9e041c2d712b0b81fe183/src/features/auto-resize-grid/js/auto-resize.js

I think many would love that 100% table height feature offering a responsive UI on any device...

**Comment by lorenzofox3** [comment]
No, I will definitely not write any single line of javascript for something which should be handle by css. 
Just fix the size of its container and make the table occupy the whole space available. You have an example for the width [here](http://plnkr.co/edit/fcdXKE?p=preview)
