### ISSUE TITLE
need a function to trigger SmartTable pipe reload by external event

### ISSUE THREAD

**Issue by lhwparis** [lorenzofox3/Smart-Table#363]
Hi i am using SmartTable with a custom ajax pipe like in your example. 
Now i need an option to trigger reloading of the ajax data by an external event so that function which is named in st-pipe="" is triggered again. is there any way to do that?

another way is that i call these function manually but then i have the problem that i dont get tableState as a parameter.

**Comment by lorenzofox3** [comment]
well if you want to call it even when the tableState has not changed you can as you mentioned call it manually. Just keep the table state in an external variable

**Comment by timomayer** [comment]
thanks for your answer. yes i have to call it when tableState has no changed cause i send some external paramters with it which have an impact on the result list. so i have to reload the results when this parameters change. but i need tableState within as parameter which is not set when i call the function from my controller, can you give me a hint how to trigger this from my controller and to get the tableState with it? thanks for your help!

**Comment by lhwparis** [comment]
thanks for your answer. yes i have to call it when tableState has no changed cause i send some external paramters with it which have an impact on the result list. so i have to reload the results when this parameters change. but i need tableState within as parameter which is not set when i call the function from my controller, can you give me a hint how to trigger this from my controller and to get the tableState with it? thanks for your help!

**Comment by lhwparis** [comment]
solved it sorry i was on the wrong way yesterday. you can close this. thanks.

**Comment by RodolpheNivelet** [comment]
Hello,

Sorry can you tell me how did you resolved this ? Did you do a custom tableState ?
Because I need to set the numberOfPages on the variable.

Thank you

**Comment by andykais** [comment]
I would also like to hear how to trigger a pipe reload without a change in the variable it is watching

**Comment by vpratti** [comment]
+1

**Comment by Marcrazyness** [comment]
Used this post for a solution: https://github.com/lorenzofox3/Smart-Table/issues/305

**Comment by gtaylor44** [comment]
I solved this problem by creating a directive local to stTable and broadcasting the event. 

**View**
```
<table st-pipe="productsTableCtrl.getTableData" 
st-table="productsTableCtrl.tableData" refresh-table>
```

**Controller**
`$scope.$broadcast('refreshProducts');`

**Directive**
```
app.directive("refreshTable", function(){
    return {
        require:'stTable',
        restrict: "A",
        link:function(scope,elem,attr,table){
            scope.$on("refreshProducts", function() {
                table.pipe(table.tableState());
            });
    }
}});
```

**Comment by sharayuj** [comment]
I would like to know how to trigger the st-pipe function on external element event

**Comment by anibalardid** [comment]
amazing @gtaylor44 solution !!!

THANKS

**Comment by dice-pickle** [comment]
Hello everybody, I'm angularjs noobie and having some trouble applying the  solution  suggested by  gtaylor44. I get the following:

`Error: [$compile:ctreq] Controller 'stTable', required by directive 'refreshTable', can't be found!` 

tried to change `require:'stTable',` to `require:'^?stTable',` and got no error but `console.log(table)` gives null.

I ended up adding this directive to the original smart-table module  but I know it is not right, any other ideas!?

**Comment by molerat619** [comment]
@gtaylor44 great solution. does this also work with functions like `st-pipe="callServer"`?

**Comment by antondperera** [comment]
I was struggling on this and this saved my day. Thanks. 

> well if you want to call it even when the tableState has not changed you can as you mentioned call it manually. Just keep the table state in an external variable
