### ISSUE TITLE
Error: Controller 'stTable', required by directive 'stSearch', can't be found!

### ISSUE THREAD

**Issue by mishelka** [lorenzofox3/Smart-Table#365]
When I try to put the search input into another directive, such as lumx text field, I get this error:
```bash
Error: [$compile:ctreq] Controller 'stTable', required by directive 'stSearch', can't be found!
```
(full error stack here: http://prntscr.com/6r4n7b).

Here's an example of what I'm trying to do:

```html
 <tr>
     <th colspan="9">
        <lx-text-field class="global-search-margin" label="search in table ..." fixed-label="true">
           <input st-search type="search" ng-model="globalSearchText">
        </lx-text-field>
     </th>
 </tr>
```

Both the table and the search are working properly, but the error is constantly filling my console log, please is there any way to avoid it?

**Comment by lorenzofox3** [comment]
As the message suggests, you are missing the st-table directive. Have you set 
```Markup
<table st-table="yourCollection">
<!--... -->
</table>
```
?

**Comment by mishelka** [comment]
Yes, I've set it:

```html
<table st-table="displayedDataList"  st-safe-src="dataList" class="table table-striped table-bordered table-hover">
...
</table>
```

When I remove the lx-text-field wrap so that only input remains, the error dissapears. It seems as if the st-search, since it is wrapped in a lumx field, is not able to find the st-table anymore.

**Comment by lorenzofox3** [comment]
Then I am sorry but I don't know. Maybe it is related to the lx-text-field directive ?

**Comment by mishelka** [comment]
Ok then I will try to figure something out, thank you for your effort.

**Comment by Jareechang** [comment]
s

**Comment by Oleh-Pashchenko** [comment]
I had the same problem, but I found solution [here](http://stackoverflow.com/questions/33248577/trying-to-setup-sort-on-a-table-using-smart-table-in-angularjs)

**Comment by Xsmael** [comment]
I also have the same problem. but am not using any other directive, does the st-search element be enclosed in a <tr><th> .... </th></tr>  to work ?

**Comment by Xsmael** [comment]
> I also have the same problem. but am not using any other directive, does the st-search element be enclosed in a .... to work ?

Dammit! am having the same issue again 2years later and completely forgot how i managed earlier!
