### ISSUE TITLE
Suppress initial call to st-pipe function / best way to handle url param for filter

### ISSUE THREAD

**Issue by jugglingcats** [lorenzofox3/Smart-Table#366]
Our goal is to be able to pass in a filter criteria in the URL. This is to support proper back button behaviour. We are using UI Router but I think this requirement is fairly generic.

To get this working we've created an alternative st-search directive that just does a one way transfer from model to the table state, and it is working fine for us. However, we get multiple calls to the st-pipe function on page load. Once with empty filter and then another when the model is modified.

We're open to using a different approach, but we like using ng-model to hold the filter, because we can then watch for changes in the controller, etc. I think the model <--> table state sync was mentioned in another issue.

Our directive looks like this:
```
angular.module('smart-table')
.directive("stSearch2", ['stConfig', '$timeout', '$log', function(stConfig, $timeout, $log) {
        return {
            require: '^stTable',
            scope: {
                predicate: '=?stSearch2',
                ngModel: '='
            },
            link: function(scope, element, attr, ctrl) {
                var tableCtrl=ctrl;
                var throttle = attr.stDelay || stConfig.search.delay;

                // model -> table state
                scope.$watch('ngModel', function(newVal) {
                    if ( newVal ) {
                        $log.info("Model changed for search!!", scope.predicate, newVal);
                        tableCtrl.search(newVal, scope.predicate || '');
                    }
                });
            }
        }
    }]);
```

You can see example Plunkr here: http://plnkr.co/edit/FErRR0cgvdBduo94fYca?p=info. In the console you will see "func called" twice on page load.

Any help much appreciated.

**Comment by lorenzofox3** [comment]
yes there is a known bug https://github.com/lorenzofox3/Smart-Table/issues/329, st-pipe is called whenever the table state change and the pagination directive tends to change it when the table loads (st-sort as well with the st-sort-default attribute) I need to fix it. Your one direction flow is nice but you will likely face problems when you will need to rebuild the tablestate from an exetrnal source (like if you want to persist the state in local storage or sessions and rebuild the table from it)
