### ISSUE TITLE
unit testing with smart-table

### ISSUE THREAD

**Issue by jeffhoang** [lorenzofox3/Smart-Table#367]
I have a jasmine unit test for my own directive that uses smart-table inside its template.   When I ran the test, it doesn't seem to render the smart table even though I've set the data collection accordingly.

Sample code:

element = $compile("\<some-element\>\</some-element\>")($scope);
$scope.$digest();

"some-element" is my custom directive that uses a templateUrl which contains the smart-table related mark ups.

What am I missing here?

**Comment by lorenzofox3** [comment]
Not sure in you particular case, but you can check the specs for the built in smart-table directives like stSearch.spec.js, stSort.spec.js etc in the [spec folder](https://github.com/lorenzofox3/Smart-Table/tree/master/test/spec)
