### ISSUE TITLE
Issue in filter

### ISSUE THREAD

**Issue by sameer22** [lorenzofox3/Smart-Table#370]
I am using Angular 1.3.15 and Smart-Table 2.0.2.

I am not getting the desired results either on column specific filter or global filter. However I have sorted the column specific issue with custom filter.

Can you please let me know the correct combo of versions?

Thanks.

**Comment by lorenzofox3** [comment]
There is no particular requirement in versions. The problems may come quite few different places. Please set up a plunker with your table and a similar dataset

**Comment by sameer22** [comment]
As you mentioned for versions, I have given a try again and found global search functionality is working properly. May be browser (cache/other) issue.

Column specific searches are also working except nested one (which is know angular functionality). I have solved the nested filter by using st-set-filter (custom filter).

Thanks for your response.
