### ISSUE TITLE
"st-select-row" attribute run without class changes 

### ISSUE THREAD

**Issue by sergey-wagner** [lorenzofox3/Smart-Table#371]
If you set a st-select-row and st-select-mode attribute on 'tr', than run it without change on row class to  'st-selected'.

**Comment by lorenzofox3** [comment]
I am sorry, I don't understand

**Comment by sergey-wagner** [comment]
I use server side data loading for table and want use select row, but it happens without a changes of css class name of row :
http://plnkr.co/edit/DioRWFOLBHxVzTlWLe6g?p=preview
