### ISSUE TITLE
st-select-row does not work properly with HTML select control inside the row.

### ISSUE THREAD

**Issue by Deminem** [lorenzofox3/Smart-Table#372]
I have a html `select` control inside the table column and whenever I try to select any item from the `select` control list. st-select-row also perform the table row selection. 

Please see the issue in plunker - http://plnkr.co/edit/0PpiRlC5oDKVsdPes0IT?p=preview

How can I avoid the table row selection while selecting the item from combo/select list. Because I have detail panel which basically expand/collapse on table row selection. And ideas or help would be appreciated - thanks!

**Comment by lorenzofox3** [comment]
You need to stop the event propagation from the cell to the row element. Have a look [here](http://stackoverflow.com/questions/14544741/how-can-i-make-an-angularjs-directive-to-stoppropagation)
