### ISSUE TITLE
Draggable headers bug

### ISSUE THREAD

**Issue by iyel** [lorenzofox3/Smart-Table#373]
If you drag the very left header to left it will disappear
Steps to reproduce:
 1. Click on very left header and hold it
 2. Make orange pipe appear on right
 3. Make orange pipe appear left  
 4. Release mouse button

http://plnkr.co/edit/DRagFo?p=preview

**Comment by lorenzofox3** [comment]
You are right, but I think it is more related to lrDragNDrop. These were more examples to inspire people rather than "officially supported plugin"
