### ISSUE TITLE
select populated by ng-options as st-search have index instead value

### ISSUE THREAD

**Issue by ilbarzo** [lorenzofox3/Smart-Table#375]
I need a ```<select>``` filter for my table, populated dinamically by ```ng-options``` from an object array, and pass it selected value to the ```st-pipe``` function.
As angular know constructor, the options of the select populated in this way, have an index instead of the value of the objet. The value is binded to the related ```ng-model``` scope variable.
But the st-search related filter, doese not have this value, but the index of the current option selected.
Here my html:
```html
<table class="table table-striped table-bordered table-hover tableData" st-pipe="ctrl.callServer" st-table="ctrl.displayed"><tr  class="filter"><td>
<select ng-model="currentValue" st-search="slsi_reg" ng-options="obj.val as obj.name for obj in list" ></select></td></tr>....</table>
```
So, ```$scope.currentValue``` has the right value, but slsi_reg param of the ```tableState.search.predicateObject.slsi_reg``` has the index value.
How can I handle this before the ```st-pipe``` function is called?
Best regards

**Comment by ilbarzo** [comment]
I have fond a workaround to edit `tableState.search.predicateObject`, doing an `angular.copy` of `tableState`, edit predicateObject properties reading related `scope` values, and then call my service in the `callServer` pipe, passing the duplicated var instead of `tableState`.
Hope this help someone.
```javascript
    this.callServer = function callServer(tableState) {
        if (ctrl.isLoading) return;
        ctrl.isLoading = true;
        var pagination = tableState.pagination;

        var start = pagination.start || 0;
        var number = pagination.number || ctrl.itemsByPage;

        var ts = angular.copy(tableState);

        if (ts.search.predicateObject.slsi_reg)
            ts.search.predicateObject.slsi_reg = $scope.currentRegione;
        if (ts.search.predicateObject.slsi_prov)
            ts.search.predicateObject.slsi_prov = $scope.currentProv;
        if (ts.search.predicateObject.slsi_comu)
            ts.search.predicateObject.slsi_comu = $scope.currentComune;
        ts.search.predicateObject.bycomu = ($scope.bycomu ? '1' : '0');
        ts.search.predicateObject.s = ($scope.s1 ? '1' : '0');
        service.getPage(start, number, ts).then(function (result) {
            ctrl.displayed = result.data.data;
            tableState.pagination.numberOfPages = result.data.numberOfPages;
            $scope.totalRecords = result.data.totalRecords;
            $scope.wannaImpianti = result.data.wannaImpianti;
            ctrl.isLoading = false;
            ctrl.tableStateRef = tableState;
        });
    };
```

**Comment by lorenzofox3** [comment]
thanks for sharing

I think in ng-options directive you can specifiy what porperty of the model will be bound to the ng-model var, perhaps it is easier

**Comment by rahulkadam-2015** [comment]
Hi, 
I am facing same issue if I pass dynamically created ng-options to st-search it will pass index instead of value. Please help me to resolve issue.

**Comment by gulfaraz** [comment]
@rahulkadam-2015 using the following syntax on **ng-options** helped me set the *value* for the *option* tag `item `**`for`**` item `**`in`**` array `**`track by`**` item`

Spent a few days looking for this, I hope it solves your issue.

**Comment by rahulkadam-2015** [comment]
Thanks for your help!!!
I have resolved using same.
