### ISSUE TITLE
Unit Tests for website examples

### ISSUE THREAD

**Issue by chavz** [lorenzofox3/Smart-Table#376]
I have controller which is bound to a view that uses smart-table, and I'm trying to test the callback that I use for `st-pipe`, how will I be able to replicate a `tableState` object which is a required parameter for `st-pipe's callback function` without literally creating a mock `tableState` object. I'm fairly new to unit testing so I'm probably approaching this the wrong way. Perhaps some sample unit tests in the example  used in the  [website](http://lorenzofox3.github.io/smart-table-website/) could help ? so we could see how one might test a controller/directive/etc that utilizes `smart-table`.

here's my  code in the controller

    var vm = this;

    vm.stCompaniesTable = [];
    vm.stGetTableData =  stGetTableData;
    //////////////////////////////////////////
    function stGetTableData (tableState) {
      var params = $filter('stUrlParams')(tableState);  // parse tableState to an object that the api could understand
      var tablePromise = companyResource.getCompanies(params);

      tablePromise.then(function (response) {
        vm.stCompaniesTable = response.data.companies;
        tableState.pagination.numberOfPages = response.data.pages;
      });
      tablePromise.catch(function (error) {
        logger.error('unable to fetch data', error);
      });
    }

and I want to be able to say, that `stGetTableData` did indeed call `companyResource.getCompanies` for its data, and on how it should react on successful or error response.

so far I'm just testing this by using a `spyOn` on `companyResource.getCompanies` which keeps on giving an error since i have to call `stGetTableData` with a `tableState` which i dont know how to create an instance of without literally recreating one.

**Comment by lorenzofox3** [comment]
actually I would completely forget about smart-table for your test. You want to test that your function stGetTableData behaves in such way for such input, that way for that input, etc
The idea of unit tests is to abstract dependant components. 

A pseudo example:

```Javascript
describe('myController', function () {
 var ctrl;
 var http;

 beforeEach(inject(function ($controller, $httpBackend) {
	//here we will assert on http request it could/should be done by mocking companyResource to better isolate the code to test.
	//So in our test we will somehow test CompanyResource service and stUrlParams filter which can be considered as bad for unit tests
	http = $httpBackend;
	//pass mocks in place of the dependencies you want to abstract
	ctrl = $controller('myController', {dependency1: MockDependency1});
 }));

 afterEach(function () {
	//assertion on http request
	http.verifyNoOutstandingRequest();
	http.verifyNoOutstandingExpectation();
 });


 it('should set the new data set for that table state', function () {
	//input
	var tableState = {
	 sort: {predicate: 'prop1'},
	 search: {},
	 pagination: {}
	};
	//expected result
	var dataSet = {
	 companies: [{id: 1}, {id: 2}],
	 pages: 3
	};

	//expect http call (cf afterEach)
	http.expectGET('www.example.com/companies?sort=prop1').respond(200, dataSet);

	//code to test
	ctrl.stGetTableData(tableState);

	//initial state
	expect(ctrl.stCompaniesTable).toEqual(whatever);

	http.flush();

	//after our code to test has run
	expect(ctrl.stCompaniesTable).toEqual(dataSet.companies);
	expect(tableState.pagination.numberOfPages).toEqual(3);

 });

 it('should set the new data set for that other table state ', function () {
	// ... etc 
 });

});
```



Then to test directives, I suggest you look at the examples of this repository

**Comment by chavz** [comment]
I see .. thanks for the clarifications. really helps =)
