### ISSUE TITLE
How to programmatically unselected items in the controller?

### ISSUE THREAD

**Issue by wpoosanguansit** [lorenzofox3/Smart-Table#38]
Is there a public api to unselect all rows and the check box in the header?  At the moment, I iterate through the row data and set isSelected to false.  That unchecks the items but the checkbox in the header is still checked even $scope.isChecked is set to false.  

Also related to this, I also did not know how to make the cell clickable for popup modal.  Is there a way to accomplish that?

Thanks for your help.

**Comment by nmeeda** [comment]
its not mention how to unselect(or deselect) a row
