### ISSUE TITLE
stSafeSrc element order changes do not cause rerender

### ISSUE THREAD

**Issue by pheuter** [lorenzofox3/Smart-Table#382]
**Template:**

```html
<table st-table="displayedCollection" st-safe-src="collection">
  ...
</table>
```

**Controller:**

```js
temp = $scope.collection[index]
$scope.collection[index] = $scope.collection[newIndex]
$scope.collection[newIndex] = temp
```

---

What I'm trying to do above is to swap positions of rows. What I'm noticing is that `displayedCollection` is not getting updated, cause the table doesn't rerender, even though the underlying `collection` source does change.

It may have something to do with the [watch](https://github.com/lorenzofox3/Smart-Table/blob/7d18cd8bcfed1bd4c6f4c3eab8d3d5c0a4ba3f31/src/stTable.js#L44) not picking up changes that don't change the amount of elements in the array.

**Comment by yashikagarg13** [comment]
I think you should use angular.copy. Because in this way, $scope.collection[newIndex] and $scope.collection[index] will always point to same reference

**Comment by lorenzofox3** [comment]
Yes the watchers trigger if either the reference to the data source changes, or its size. We don't watch for changes within item for performance reason. You can be more strict in your watcher by changing the line [here](https://github.com/lorenzofox3/Smart-Table/blob/master/src/stTable.js#L44) and use a collection watcher instead. 

Or as @yashikagarg13  suggested, overwrite the properties of a row while not changing the reference to it.

Lastly you can splice the source collection but this will likely trigger the watchers twice (as the size of the collection changes twice)

```Javascript
var temp = $scope.rowCollection.splice(index, 1); //change in size
$scope.rowCollection.splice(newIndex,0,temp); // another change in size
```

**Comment by pheuter** [comment]
That makes sense, but for some reason, it still doesn't rerender, neither when using `angular.copy` nor `splice`.

**Comment by pheuter** [comment]
What does work is when I copy the whole array, not the individual element, like so:

```js
temp = $scope.collection[index]
$scope.collection[index] = $scope.collection[newIndex]
$scope.collection[newIndex] = temp
$scope.collection = angular.copy($scope.collection)
```

**Comment by lorenzofox3** [comment]
yes because you change the reference bound through st-safe-src, so it triggers the first watch. I am a bit surprised the splice method does not trigger a refresh though

**Comment by pheuter** [comment]
Yeah, might it have something to do with not enough time passing for the watcher to register the different length between the two calls?
