### ISSUE TITLE
question about "pipe/ajax plugin" example in "http://lorenzofox3.github.io/smart-table-website/"

### ISSUE THREAD

**Issue by davidolen** [lorenzofox3/Smart-Table#383]
First of all, I have to say RENARD has done a great job in designing and maintaining smart-table.
The documentation is pretty good. The design is pretty smart :-). Critical thinking has been applied very well in many places of the smart-table design.

After reading the examples on the home page, I think I've understood most parts.
However, I still have the following points not so clear to me. 

1) If stSafeSrc attribute is NOT used, smart-table will create a safe collection from the displayed collection. And the displayed collection will be modified based on sorting and filtering while the safe collection remains unchanged.
So, if stSafeSrc attribute IS used,and stSafeSrc and st-table refer to the base collection and displayed collection respectively, Will smart-table still create a safe collection anyhow?

2)  the "pipe/ajax plugin" example does not use the stSafeSrc attribute, does this imply stSafeSrc cannot be used with st-pipe at the same time? If they can be used together, why stSafeSrc was not used (forgive my circular question :-) )

3) When AnguarJS 2.0 comes out next year, are you planning to upgrade smart-table for angular-js 2.0? (trust me, the community needs it)

I know these questions may not make much sense. Considering I'm still new to the angular-js world, please help me to figure them out.

Thank you!

David

**Comment by lorenzofox3** [comment]
Thanks for the kind words, I truly appreciate :)

First of all, note that ``st-table`` is simply a way to name and expose a variable (which represents the displayed data set ie sorted,filtered,sliced) to the template and to the parent controller, if required. But the var does not have to exists in your parent controller if you don't need it (it will simply be created on the current scope by smart-table).

1) however if you base your data set to an existing collection in you parent controller, when smart-table creates its own controller a copy of this data set is created and any further table logical operation (slice, sort, search) will be based on this initial data set. Any change in the table state will trigger a set of operations to perform on this initial data set and will create a new version of the displayed collection which the view is bound to.
If you use st-safe-src attribute you simply tells smart-table that you expect external changes to the initial data set and to watch for these changes. So smart-table will simply update its reference copy whenever an external change happen

so to sum up : 
always: smart-table creates a safe reference copy based on data passed at initial time
with st-safe-src: this copy is updated whenever an external change happens to it

2) this is a bit different use case. The role of smart table here is more to sync the different directives based on table state and forward to a server any change in table state, but it won't perform any logical operation as everything will happen on the server. In this particular case you expect that the data set sent by the server to EXACTLY match the table state, and therefore to be displayed as it is. That is why there is no need to hold a safe reference copy.

3) Yes I have actually a small prototype, I might share when I am back from holiday (mid-may). Obviously I have not yet a great knowledge of angular 2 internal and as the documentation is lacking at the moment, there will obviously have some changes to do. But the idea is to abstract data source, data flow through the chain of operations and this can actually be framework agnostic. The rest is component plumbing, component state sync, etc

**Comment by davidolen** [comment]
Got it. Thank you!

**Comment by renehamburger** [comment]
@lorenzofox3, have you continued working on the Angular 2 prototype you've mentioned above? Anything worth sharing that we could possibly contribute to?
