### ISSUE TITLE
hide table header but need st-ratio

### ISSUE THREAD

**Issue by ericq** [lorenzofox3/Smart-Table#384]
I'm new to this tool.

I'm embedding the table within other components and I need to hide the table header. There was a closed issue about the similar question  but answer was not documented clearly in that thread.  In addition, I still need a way to control the ratio between the two columns (80, 20). Please advise how to do it.

**Comment by lorenzofox3** [comment]
what issue are you talking about ? st-ratio was just an example and is not really related to smart-table. I think you can do what you want with plain old css, can't you ?

**Comment by mgonzalez10** [comment]
st-ratio is a directive so you can use in any control.

**Comment by ericq** [comment]
Thanks. I fixed it with some css trick.
