### ISSUE TITLE
the table header does not align with columns

### ISSUE THREAD

**Issue by ericq** [lorenzofox3/Smart-Table#385]
When I have 5 columns, the header and content aligns very well. But if I reduced them to 4 columns or less, the header portion looks longer (to the right), while all the columns shrinks to the left. 

Looks like the header behavior is right because it tries to take the full available space, while the body part did not try to use the "full space" but used some kind of default width instead. 

I'm using the table within bootstrap grid.

**Comment by lorenzofox3** [comment]
I guess it is also related to your css. If you don't change the display mode of your table, the browser will handle it by itself, if you change it to "block", "inline-bock", "flex" etc, you'll have to adjust the tbody yourself

**Comment by ericq** [comment]
Thanks. I fixed it with some css trick.

**Comment by Balachandar1996** [comment]
Try this one,
valuePrepareFunction: (data) => {
  return '<p class="cell_right">' + data + '</p>';
 },
:host /deep/ .cell_right {
  width:100%;
  height: 100%;
  text-align: right;
}

**Comment by Balachandar1996** [comment]
valuePrepareFunction: (data) => {
        return '\<p class="cell_right">' + data + '\</p>';
          },

**Comment by Balachandar1996** [comment]
try this one, 
valuePrepareFunction: (data) => { return '\<p class="cell_right">' + data + '\</p>'; },

**CSS**
:host /deep/ .cell_right {
  width:100%;
  height: 100%;
  text-align: right;
}
thanks ;)
