### ISSUE TITLE
st-sort not sorting with st-safe-src

### ISSUE THREAD

**Issue by lucaalex87** [lorenzofox3/Smart-Table#386]
Hi,

First of all, thanks for this really nice table.

Second, I'm loading data async, I used st-safe-src, and copied rowCollection to displayCollection. I have draggable headers also.

(below a Plunker with the code)
http://plnkr.co/edit/s407ao

I'm not sure if it's really a defect, or I'm doing something wrong?

Tried many options, the last one was to come here and open an issue.

Thanks :)

**Comment by lorenzofox3** [comment]
you have to use the displayed collection in  the repeater ;) 
[plunk](http://plnkr.co/edit/fhU8rX?p=preview)

**Comment by lucaalex87** [comment]
Thanks for the quick reply.

I used the draggable headers example, and when I updated it to make it use st-safe-src, I forgot to check the body of the table also.

Sorry for the un-needed issue (in case you're tracking their number or something).That was easy :)

Thanks again :) And congrats for the work you are doing
