### ISSUE TITLE
Custom  sorting function

### ISSUE THREAD

**Issue by nitulk** [lorenzofox3/Smart-Table#392]
Can I specify the sorting functionality through comparison function.
E.g. : Comparison function.
Two arguments : object1, object2
Returns : 
1 : if object1 > object2
0 : if object1 equals to  object2
-1 : if object1 <  object2

**Comment by lorenzofox3** [comment]
Smart-table use the default [orderBy angular filter](https://docs.angularjs.org/api/ng/filter/orderBy)
you can pass as predicate either a string (property name) or a *getter function*. see [the documentation](http://lorenzofox3.github.io/smart-table-website/#section-sort) where the first column is sorted by the number of characters in the firstname of each row.

If this does not allow you do do what you want you can still replace the default order filter by you own filter

**Comment by Mbarki92** [comment]
I am new in angular. I need to change the default comparator to use my own filter.

**Comment by mihaelavelimiroviciu** [comment]
> 
> 
> I am new in angularJS, I used smart table sort but i face problem with special character ( àáâã ...)
> so I need to change the default comparator to use my own filter.
> or just try to get the displaySetter to my own directive that i can display result.
> any idea ?? @lorenzofox3

Hi @Mbarki92 !  I have the same problem with local characters. Did you find any solution? Thank you!

**Comment by julienrott** [comment]
Hi  @mihaelavelimiroviciu @Mbarki92 @nitulk ,

I'm looking for the same solution, how to replace the default order filter as mentioned by @lorenzofox3  ?
