### ISSUE TITLE
StPipe and table reload from outside

### ISSUE THREAD

**Issue by matgardon** [lorenzofox3/Smart-Table#393]
First of all, thanks for the hard work, the simplicity & efficiency of your smart-table, I very much like most of the paradigms.

I've searched for past issues for my problem, but couldn't find my exact scenario, nor any sense of something that I might not have "gotten" from your philosophy with smart-table, so here is my issue.

I'm using your basic pipe/ajax example (with pagination), and things are working fine. I have no specific code to provide, as my code is exactly like your example of a custom pipe function loading data from a server.

In the case of your example, you handle the "initial/first load of data" case using the linking function of your stPipe directive (on post link, call ctrl.pipe()). 

But this way of handling things works fine only for the initial creation of the directive : afterwards, I need to reload the table based on external changes (a user profile change in my application causes the data to be outdated so I want to reload the table / call the pipe function again). 

I have the option to reload my entire state upon this user profile change, but that's far from perfect (other elements in my view do not need to be reloaded, only the table).

I've tried to call my custom pipe function from outside the directive, but this way the tableState.pagination.numberOfPages is not provided, thus not updated, causing a UI bug.

I could also re-set the pipe function to force the intial post link function to execute again, but that's not ideal either.

I'm considering 2 options : 

- modifying your stPagination directive to be able to do 2 way data-binding onto the numberOfPages attribute, so that I can update it from the outside when calling the pipe function without needing to pass-in the tableState Parameter. 

- providing a reload() method from the directive to the outside world, method that would then have access internally to the tableState, and call the custom pipe function with this tableState. This pretty much sums up to the ng-table table.reload() feature.

What are you thoughts on the problem ? I I do a pull request, would you consider my proposition ?

**Comment by lorenzofox3** [comment]
Note sure about the reload of ng-table, but that seems a good idea. 
Or without changing the code of smart-table, you can create a smart-table plugin which watches your changing external state, and every time a change occurs call the table controller api, like 
```Javascript
ctrl.slice(0, itemsByPage)
```

**Comment by matgardon** [comment]
The plugin may be a good solution, but I currently tend to think that this feature should be in the core smart-table codebase.

I've pursued the discussion about this feature in the [pull-request](https://github.com/lorenzofox3/Smart-Table/pull/394) I've made, but I'l also look into the plugin creation approach.

**Comment by matgardon** [comment]
The plugin approach works for my use case : a simple directive to use on the same element stTable is defined upon, that reloads (using ctrl.slice) the table.

The directive/plugin code can be found [here](https://github.com/matgardon/SmartTable-external-data-context/blob/master/README.md) for anyone to use (I don't have time to write unit tests, but could this be interesting to commit to the main repo as a complement to stPipe ?).

Main problems left with this approach :
* The plugin/directive can be used weather the data is externally loaded or not : that is not good as in case of internally managed data, the expected behavior is to reload the data-soure, which will not be the case.
* Due to the above problem, the behavior of smart-table is quite difficult to apprehend between externally and internally managed data : in the first case, one has to provide a way to load data to smart-table & manage every external event accordingly with plugins, in the other, one can manage the collection smart-table is bound to, and updates to this collection will be reflected in smart-table as expected. The 2 behaviors are quite different for developers and not that well explained in the docs.
