### ISSUE TITLE
Matching only first part of value when filtering on a field

### ISSUE THREAD

**Issue by OhioGuy67** [lorenzofox3/Smart-Table#396]
I have a search box for a particular field in my table.  Currently it will search for rows containing the search string anywhere in the field's value.  How do I have it only search for the first part of the value?  For example, if there are rows with the values of "12345" and "991288" and search for "12", how do I only get the row with the "12345" value?

Thanks.

**Comment by lorenzofox3** [comment]
smart-table uses by default the [angular filter filter](https://docs.angularjs.org/api/ng/filter/filter) which does not support regex, so you'll have to create your own filter and tell smart table to use that one instead of the default one (using the st-set-filter attribute)

**Comment by OhioGuy67** [comment]
Thanks.  I was able to get this working for the most part with one minor hiccup.  Everything works great for the fields with a text input search box.  However, I setup one of the search fields as a dropdown (<select class="..." st-search="status" type="search" ng-model="list.status" ng-options="...").  When I select an option from the pulldown, the custom filter function I specified using st-set-filter is not being called.  Any suggestions?

**Comment by OhioGuy67** [comment]
Here is how my filter looks (I found this example online):

app.filter('tableFilter', [function() {
   return function(items,filters) {
         // Build a new_items array with rows to be displayed
         return new_items;
   }
}]

This works well.  My problem is that I want to be able to call this function on demand in much the same way its called when a search input is made (so that it items and filters will be initialized).  Do you have any idea?
