### ISSUE TITLE
Smart Table Ajax Call not working properly 

### ISSUE THREAD

**Issue by reviliant** [lorenzofox3/Smart-Table#399]
I am using the following line 

table st-safe-src="displayed" st-pipe="callServer" st-table ="rowCollection" class="table table-bordered table-striped"

displayed has the structure as follows : displayed= [{name: "asaS", age: 78}, {name : "rrfdsf", age:56 }]

"displayed" fetches the entire json properly. (I am able to print)

But when I do 

ng-repeat="row in displayed"
					        {{row}}
</tr>

it does not work

**Comment by reviliant** [comment]
<table st-safe-src="displayed" st-pipe="callServer" st-table ="rowCollection" class="table table-bordered table-striped">

**Comment by reviliant** [comment]
table st-safe-src="displayed" st-pipe="callServer" st-table
			class="table table-bordered table-striped"

**Comment by lorenzofox3** [comment]
Hi, I have not idea what you are talking about, you'll have to provide a running example
but I am quite surprised you are using st-safe-src and st-pipe in the same table

**Comment by lorenzofox3** [comment]
(and read the submit an issue secion on the readme ;) )

**Comment by reviliant** [comment]
Sorry my bad...for the time being let us close the issue.....
