### ISSUE TITLE
Custom Filter arguments

### ISSUE THREAD

**Issue by tbugge** [lorenzofox3/Smart-Table#401]
I am trying to add a custom filter to smart-table.  It doesn't seem to be able to handle any additional arguments at all as the setFilter function just calls $filter(filterName).  Is there any way to pass an additional argument through to the filter function from smart-table?  Thanks!

**Comment by lorenzofox3** [comment]
Hi, I don't really understand your point as the [angular $filter](https://docs.angularjs.org/api/ng/service/$filter) function takes only one arg: the filter name

**Comment by tbugge** [comment]
I figured this out.  To clarify my question it wasn't at the level of calling $filter, it was at $filter("filter") in the code.  The answer to what I was asking is that if you write a plug in to filter differently than smart table does by default and you need custom info, you pass in your own predicateObject via tableState.search.predicateObject.  Does that make sense?

**Comment by lorenzofox3** [comment]
Ok, it makes sense. Yes your filter signature has to be filter(array, predicateObject)
https://github.com/lorenzofox3/Smart-Table/blob/master/src/stTable.js#L98
where predicate object can be accessed on the tableState.search.predicateObject if you need to pass more complex data
