### ISSUE TITLE
Filtering issue

### ISSUE THREAD

**Issue by tudorgeorge** [lorenzofox3/Smart-Table#402]
I use smart table to display the data in an array where each item has properties to be rendered under a 'data' property. Like in your filtering/sorting example, instead of having plain items like 
{ firstName: 'Laurent', lastName: 'Renard'} I have items like 
{ data: { firstName: 'Laurent', lastName: 'Renard'} }. The problem is that if I use multiple search criteria like st-search="data.lastName" and st-search="data.firstName", all inputs are populated when you input text in one of them. Any idea what I should do?

I was able to reproduce the behavior with the example for filtering on smart-table-website.

#Html
&lt;table st-table="rowCollection" class="table table-striped">
    &lt;thead>
        &lt;tr>
            &lt;th st-sort="data.getters.firstName">first name</th>
            &lt;th st-sort="data.lastName">last name</th>
            &lt;th st-sort="data.birthDate">birth date</th>
            &lt;th st-sort="data.balance" st-skip-natural="true">balance</th>
            &lt;th>email</th>
        &lt;/tr>
        &lt;tr>
            &lt;th>
                &lt;input st-search="data.getters.firstName" placeholder="search for firstname" class="input-sm form-control" type="search" />
            &lt;/th>
            &lt;th colspan="3">
                &lt;input st-search placeholder="global search" class="input-sm form-control" type="search" />
            &lt;/th>
            &lt;th>
                &lt;input st-search="data.lastName" placeholder="last predicate" class="input-sm form-control" type="search" />
            &lt;/th>
        &lt;/tr>
    &lt;/thead>
    &lt;tbody>
        &lt;tr ng-repeat="row in rowCollection">
            &lt;td>{{row.data.firstName | uppercase}}</td>
            &lt;td>{{row.data.lastName}}</td>
            &lt;td>{{row.data.birthDate | date}}</td>
            &lt;td>{{row.data.balance | currency}}</td>
            &lt;td><a ng-href="mailto:{{row.data.email}}">email</a></td>
        &lt;/tr>
    &lt;/tbody>
&lt;/table>

#JavaScript
scope.rowCollection = [
{data: { firstName: 'Laurent', lastName: 'Renard', birthDate: new Date('1987-05-21'), balance: 102, email: 'whatever@gmail.com' }},
{data: { firstName: 'Blandine', lastName: 'Faivre', birthDate: new Date('1987-04-25'), balance: -2323.22, email: 'oufblandou@gmail.com' }},
{data: { firstName: 'Francoise', lastName: 'Frere', birthDate: new Date('1955-08-27'), balance: 42343, email: 'raymondef@gmail.com' }}
];

scope.getters = {
    firstName: function (value) {
        //this will sort by the length of the first name string
        return value.data.firstName.length;
    }
}

**Comment by lorenzofox3** [comment]
Hi, 
Sorry I don't understand and I can't read your unformatted snippet, can you provide a plunker. 

But it seems your issue might be related to https://github.com/lorenzofox3/Smart-Table/issues/400 or https://github.com/lorenzofox3/Smart-Table/issues/288 or https://github.com/lorenzofox3/Smart-Table/issues/184 or ...
