### ISSUE TITLE
Error in your example

### ISSUE THREAD

**Issue by mydiscogr** [lorenzofox3/Smart-Table#403]
Hi, thanks for this great piece of software but after 2 hour of try I find a bug into your example where you describe how to use st-safescr here's the example that works

look at displayed collection, and please specify the include file... thanks

.controller('safeCtrl', ['$scope', function ($scope) {

    var firstnames = ['Laurent', 'Blandine', 'Olivier', 'Max'];
    var lastnames = ['Renard', 'Faivre', 'Frere', 'Eponge'];
    var dates = ['1987-05-21', '1987-04-25', '1955-08-27', '1966-06-06'];
    var id = 1;

    function generateRandomItem(id) {

        var firstname = firstnames[Math.floor(Math.random() * 3)];
        var lastname = lastnames[Math.floor(Math.random() * 3)];
        var birthdate = dates[Math.floor(Math.random() * 3)];
        var balance = Math.floor(Math.random() * 2000);

        return {
            id: id,
            firstName: firstname,
            lastName: lastname,
            birthDate: new Date(birthdate),
            balance: balance
        }
    }

    $scope.rowCollection = [];

    for (id; id < 5; id++) {
        $scope.rowCollection.push(generateRandomItem(id));
    }

    //copy the references (you could clone ie angular.copy but then have to go through a dirty checking for the matches)
    $scope.displayedCollection = [].concat($scope.rowCollection);

    //add to the real data holder
    $scope.addRandomItem = function addRandomItem() {
        $scope.displayedCollection.push(generateRandomItem(id));  //push in displayedCollection no in row
        id++;
    };

    //remove to the real data holder
    $scope.removeItem = function removeItem(row) {
        var index = $scope.rowCollection.indexOf(row);
        if (index !== -1) {
            $scope.rowCollection.splice(index, 1);
        }
    }
}]);

**Comment by lorenzofox3** [comment]
Hi,
The actual code running on the demo website can be found on the gh-pages of the smart-table-website repository. For your particular example, it is [there](https://github.com/lorenzofox3/smart-table-website/blob/gh-pages/sections/basics/code.js)

Of course you have to bootstrap the app first as any regular angular app
``var app = angular.module('app', ['smart-table']);``

**Comment by mydiscogr** [comment]
maybe there's is a difference, I dunno but what I now that your code example simply do not work on my pc with latest chrome... I would like only say only this bye :)

**Comment by lorenzofox3** [comment]
but you mean the code you have downloaded and run locally or when you reach http://lorenzofox3.github.io/smart-table-website/ ?

**Comment by mydiscogr** [comment]
yes at the "stSafeSrc attribute" read my code where is the comment I fix code there and it works

**Comment by lorenzofox3** [comment]
great thanks :+1:
