### ISSUE TITLE
Ordering with more than one ordering function doesn't display change active row

### ISSUE THREAD

**Issue by hrycko-struzhynskyi** [lorenzofox3/Smart-Table#405]
http://plnkr.co/edit/oIhw5Nsv806wYkXCOfpE?p=preview
In example please click on "last name" header. As expected table is sorted but visual active sort column is "first name". And if i click on "first name" table is sorted by "first name" but in Desc order.

**Comment by lorenzofox3** [comment]
Hi, 

have a look at https://github.com/lorenzofox3/Smart-Table/issues/285

The idea is to name your getter functions instead of using anonymous functions. And make sure you use latest smart-table version.

[working plunk](http://plnkr.co/edit/wEibiv?p=preview)

**Comment by hrycko-struzhynskyi** [comment]
Thanks, problem is in anonymous functions. Would be great add it issue  in documentation

**Comment by bkardell** [comment]
Is it just me or is the plunk above working in only non-IE browsers?  IE11 is demonstrating the same behavior originally defined in @lorenzofox3's working plunk above for me...
