### ISSUE TITLE
When ajax promise takes long time to resolve, pagination bar is visible.

### ISSUE THREAD

**Issue by vejandla** [lorenzofox3/Smart-Table#406]
In addition to just checking ```page.length <nav ng-if="pages.length >= 2">```, you should also check for  ``` numPages, <nav ng-if="numPages && pages.length >= 2">```. 

When ajax promise takes long time to resolve, currently pagination bar is visible.

**Comment by lorenzofox3** [comment]
sounds like a good idea, I do have that flickering too when using a custom pipe function
I'll give a try
