### ISSUE TITLE
How to Add Loading Animation?

### ISSUE THREAD

**Issue by srsgores** [lorenzofox3/Smart-Table#407]
When loading data into the smart table, I want to display a loading animation, as the query performs in the back-end.  How can this be done?

I am using the ``st-safe-src`` directive:

```
<article class="grid-container" st-table="relGrid.contactsProxy" st-safe-src="relGrid.contacts">
```

**Comment by lorenzofox3** [comment]
do it in your controller

```Javascript
function controller($scope){

$scope.loadData = function(){
    $scope.isLoading = true
    $http.get('data.json).then(function(data){
        $scope.rowCollection = data
        $scope.isLoading = false
   })
}

}
```

So you'll have a property to watch in your template to know the current loading state

You can have a look at the [pipe/ajax](example) for an example of template

**Comment by srsgores** [comment]
@lorenzofox3, URL is invalid, but I figured as much.  Thanks for explaining.
