### ISSUE TITLE
Backspacing in search text box doesn't work in IE

### ISSUE THREAD

**Issue by OhioGuy67** [lorenzofox3/Smart-Table#410]
In my application, I have a global search box associated with a table.  As I start to type characters, the table is being filtered correctly.  However, if I backspace over a character, the table results are not changing.  For example, if I have 10 rows in my table, type "A" into the search box that reduces the rows to 7, type "B" that reduces the rows to 5, when I remove "B" (so the search string is only "A"), the number of rows doesn't change (i.e., it is still 5).  This does not occur in FF and is only occurring in IE (IE9 to be specific).  The only way to get around this is to refresh the page but that is not desirable.  Do you have any suggestions?

**Comment by lorenzofox3** [comment]
Maybe you'll have to enhance the [stSearch directive](https://github.com/lorenzofox3/Smart-Table/blob/master/src/stSearch.js#L30) by manually handling the key related to backspace and call the table controller search function with the proper value. Or maybe you should listen to another event than "input" (change maybe)

**Comment by lorenzofox3** [comment]
https://github.com/lorenzofox3/Smart-Table/issues/254 might be useful

**Comment by OhioGuy67** [comment]
It turns out that simply adding "keydown" to the existing "input" listener took care of the problem.  Yes there may be unnecessary searches occurring but at least for me, it solved this problem (and performance is not a huge concern in my application).

Thanks for the help.

**Comment by lorenzofox3** [comment]
:+1:
