### ISSUE TITLE
How to proper handle the back button

### ISSUE THREAD

**Issue by forcewill** [lorenzofox3/Smart-Table#412]
How can one handle the back button with pagination on the smart table,
i am using server side pagination sorting and filtering,
also ui-router 

I am displaying a list of items from the server paginating them with the smart-table going onto the details of one item and upon pressing back i would like to show the page containing the item that lead to the details.

**Comment by vejandla** [comment]
This might be helpful !!

<nav ng-if="numPages && pages.length >= 2">
	<ul class="pagination">
		<li ng-class="{ disabled : currentPage == 1 }">
			<a href="" ng-click="selectPage(1)">&laquo;</a>
		</li>		
		<li ng-class="{ disabled : currentPage == 1 }">
			<a href="" ng-click="selectPage(currentPage - 1)">&lsaquo;</a>
		</li>
		<li ng-repeat="page in pages" ng-class="{active: page==currentPage}">
			<a ng-click="selectPage(page)">{{page}}</a>
		</li>				
		<li ng-class="{ disabled : currentPage == numPages }">
			<a href="" ng-click="selectPage(currentPage + 1)">&rsaquo;</a>
		</li>
		<li ng-class="{disabled : currentPage == numPages}">
			<a href="" ng-click="selectPage(numPages)">&raquo;</a>
		</li>
	</ul>
</nav>

**Comment by lorenzofox3** [comment]
Normally smart-table is able to sync with external table state. 

I think you can write a plugin which track changes on $location (or from history API) to build a table state and cache the latest. Around a similar concept, you can find the example of [stPersit](http://plnkr.co/edit/ekwiNt?p=preview) relevant, it is a bit old but the idea is to store in local storage the table state every time it changes, and set manually the table state from it when the page load.
