### ISSUE TITLE
Smart-Table controller does not know which rows are selected

### ISSUE THREAD

**Issue by beeman** [lorenzofox3/Smart-Table#413]
I need a way to select multiple rows with a checkbox and apply a batch operation on that selection. 

I have used the example direct called `csSelect` and extended it to have one checkbox that does a select all like this:

```js
app.directive('csSelectAll', function () {
  return {
    require: '^stTable',
    template: '<input type="checkbox"/>',
    scope: {
      rows: '=csSelectAll'
    },
    link: function (scope, element, attr, ctrl) {
      element.bind('change', function (evt) {
        scope.rows.forEach(function(row){
          scope.$apply(function () {
            ctrl.select(row, 'multiple');
          });
        });
      });
    }
  };
});
```

Used like this:
```html
<th cs-select-all="rows"></th>
```

It would be great if the Smart-Table controller was aware of which rows are selected, and also if that selection is a partial or full list of rows. That way it would be easier to toggle the 'select all' checkbox, and it will also make it easier which rows to include in the batch operations.

Are there any plans of implementing this, or suggestions on how to do this or what to think about when implementing this?

**Comment by lorenzofox3** [comment]
Hey, 

Actually I do use a similar directive

```Javascript
.directive('crmSelectAll', function () {
      return {
        restrict: 'E',
        template: '<input type="checkbox" ng-model="isAllSelected" />',
        scope: {
          all: '='
        },
        link: function (scope, element, attr) {

          scope.$watch('isAllSelected', function () {
            if (scope.all) {
              scope.all.forEach(function (val) {
                val.isSelected = scope.isAllSelected;
              })
            }
          });

          scope.$watch('all', function (newVal, oldVal) {
            if (oldVal) {
              oldVal.forEach(function (val) {
                val.isSelected = false;
              });
            }

            scope.isAllSelected = false;
          });
        }
      }
    });
```

There is no particular plan to add such thing into core module. I am not sure you would need smart table for that as anyway smart table already "pollute" the model by adding the isSelected property. I believe it is relevant however when we are in single mode selection as there is a bit of logic to check and a state to keep

**Comment by beeman** [comment]
Hi @lorenzofox3,

Thanks for your comment, it gave me in insight in how to fix this neatly. I didn't manage to get your example working but it did inspire me to refactor my own.

This is what works for me now. It can probably be optimised but it's enough for my use case now. 

Thanks a lot for this project!

```js
app.directive('csSelectAll', function () {
  return {
    require: '^stTable',
    template: '<input type="checkbox" ng-model="isAllSelected"/>',
    scope: {
      rows: '=csSelectAll'
    },
    link: function (scope) {

      function getAllSelected() {
        return (getTotalRows() === getSelectedRows());
      }

      function getTotalRows() {
        return scope.rows.length;
      }

      function getSelectedRows() {
        var selectedRows = 0;
        scope.rows.forEach(function (row) {
          if (row.isSelected) {
            selectedRows++;
          }
        });
        return selectedRows;
      }

      function setAllRows(bool) {
        scope.rows.forEach(function (row) {
          if (!row.isSelected == bool) {
            row.isSelected = bool;
          }
        });
      }

      scope.$watch('rows', function () {
        scope.isAllSelected = getAllSelected();
      }, true);

      scope.$watch('isAllSelected', function () {
        if (scope.isAllSelected) {
          setAllRows(true);
        } else {
          if (getAllSelected()) {
            setAllRows(false);
          }
        }
      });

    }
  };
});
```

**Comment by e-cloud** [comment]
@lorenzofox3 , as you have polluted the model, you should maintain the property `isSelected`.
IMHO, it should be checked when the data collection is being initializing, cache the pre-selected row
with the select mode(can throw some error if not match the mode)
