### ISSUE TITLE
Strange behaviour when rowCollection is bound to service object

### ISSUE THREAD

**Issue by AndrewIsh** [lorenzofox3/Smart-Table#415]
I think I must be doing this incorrectly so I'm hoping for some enlightenment :) I'm hoping this isn't *too* much of a stupid question.

I have a service TagService that makes an API call and populates a service object called TagService.allTags. I need to bind to this in my controller in order to be able to display the results in my Smart Table. This is what I have in my controller:
```
tagController.rowCollection = TagService.allTags;
tagController.displayedCollection = [].concat(tagController.rowCollection);

TagService.getAllTags();
```
In my view I have:
```
<table st-table="adminTags.displayedCollection" st-safe-src="adminTags.rowCollection">
```
TagService.getAllTags() populates TagService.allTags.

As I understand it, Smart Table is watching tagController.rowCollection for changes and should update adminTags.displayedCollection upon change, but it doesn't appear to be. When I first load the page, I am getting an empty table. Upon switching view, then back again, the table is populated.

I assumed that, since Smart Table is watching tagController.rowCollection and tagController.rowCollection is a reference of TagService.allTags, every time I change (or populate) 
TagService.allTags the table should update, but this doesn't appear to be the case.

Any thoughts?

Many thanks :)

**Comment by hugsbrugs** [comment]
Try this : 

$scope.rowCollection = TagService.allTags;
$scope.displayedCollection = [].concat(tagController.rowCollection);

TagService.getAllTags();

<table st-table="displayedCollection" st-safe-src="rowCollection">

**Comment by lorenzofox3** [comment]
Not sure, but if you need to watch the array for only the first time maybe you can try 

```Javascript
$scope.rowCollection = [];
TagService.getAllTags().then(function(result){
    $scope.rowCollection=result;
});
```

**Comment by AndrewIsh** [comment]
Thanks for the suggestions.

@hugsbrugs Sadly that didn't make any difference
@lorenzofox3 Unfortunately, TagService.getAllTags() populates an allTags object in TagService, which is what I'm binding too with:
```
tagController.rowCollection = TagService.allTags;
```
TagService.getAllTags() doesn't return a promise sadly.

Can you think of any reason why my proposed solution is not working? As I understand it, it should, unless I'm missing something, which is quite possible! :)

**Comment by lorenzofox3** [comment]
difficult to say without the code of your service (could you share it or set up a plunker) but I would expect that if TagService.allTags is an array smart table should see the changes whenever either the reference changes or the size of the array

**Comment by hugsbrugs** [comment]
To be sure data will be available in a controller, I'm using ui-router resolve function to populate my service (which is further requested by controller).

**Comment by AndrewIsh** [comment]
OK, here's some code extracts, hopefully they might help:

TagService:
```
var tagService = this;                                                                                                                                                                                                                         
                                                                                                                                                                                                                                               
// Get all tags                                                                                                                                                                                                                                
tagService.getAllTags = function() {                                                                                                                                                                                                           
    TagFactory.apiGetAllTags().then(function(response) {                                                                                                                                                                                       
        if (response.data.results && response.data.results.length) {                                                                                                                                                                           
            tagService.allTags = response.data.results;                                                                                                                                                                                        
        } else {                                                                                                                                                                                                                               
            tagService.allTags = [];                                                                                                                                                                                                           
        }                                                                                                                                                                                                                                      
    });                                                                                                                                                                                                                                        
}
```

tagController:
```
var tagController = this;

// Get a handle on TagService                                                                                                                                                                                                                  
tagController.TagService = TagService; 

// Object required for Smart Table                                                                                                                                                                                                             
tagController.displayedCollection = [].concat(tagController.TagService.allTags);
```

view ("tagController as adminTags"):
```
<table st-table="adminTags.displayedCollection" st-safe-src="adminTags.TagService.allTags">
...
<tr ng-repeat="row in adminTags.displayedCollection">
```

**Comment by lorenzofox3** [comment]
Maybe at some point allTags is undefined

I suggest you should return the promise from your service

service.js
```Javascript
...
this.getAllTags = function() {                                                                                                                                                                                                           
    return TagFactory.apiGetAllTags()
        .then(function(response) {       
            return response.data.results || [];                                                                                                                                                                                                                                                                                                                                                                          
        })
        .then(function(tags){
            // if you need to persist it but I don't think is a good practice
           this.allTags=tags;
           return tags
        }.bind(this))                                                                                                                                                                                                                                   
}
...
```

controller bound to smart-table
```Javascript
function controller( $scope, tagService) {
     $scope.rowCollection = [];
     tagService.getAllTags().then(function(tags){
         $scope.rowCollection=tags;
     });
}
```

html
```Markup
<table st-table="displayedCollection" st-safe-src="rowCollection">
    <tbody>
        <tr ng-repeat="tag in displayedCollection">{{tab | json}}</tr>
    <tbody>
</table>
```

**Comment by AndrewIsh** [comment]
Thanks for the suggestion @lorenzofox3. I think I will have to resort to returning a promise. It feels like it shouldn't be necessary, binding to the TagService.allTags object should be sufficient, I've certainly never had any problems with controllers not seeing changes in service objects before.

I'm interested as to why you feel persisting the service object isn't good practice. One of the main uses of services is to share state across multiple controllers, which is exactly what I'm using it for here, once TagService.allTags is populated, it is available to any controllers injecting TagService elsewhere in the app.

I'm going to spend some more time trying to discover the root of the problem before resorting to returning a promise, as it feels that others are likely to run into the same problem at some point and it would be good to know what's happening.

**Comment by AndrewIsh** [comment]
I've not been able to figure out why this is happening, so am now returning a promise from my TagsService.getAllTags method.

I'm 99% sure the problem is due to the assignment of displayedCollection happening before the service object is populated but, as I understand it, that shouldn't matter as Smart Table should be watching for changes and update when the service object is populated.

**Comment by lorenzofox3** [comment]
I consider having a stateful service as a bad practice because you make your data flow in different directions and expect the result to be propagated through the watches (and obviously it does not always work :) )

I would rather see my application

1) load a view
2) get the latest data from service
3) ask service to update
4) update local view 

1) load another view
2) get the latest data from service (should have the update perform by the first service)

etc

If you keep a stateful service you rely more on an publish/subscribe pattern
1) load a view 
2) give me the reference of data => tells me when data is updated (based on bindings and watches)
4) ask service to update the view
5) I should be notified the data as changed

It is a bit Flux architecture vs binding.

I think the second pattern is only relevant when you have different components(controllers) in the SAME view sharing the same data. 
Otherwise I find it much easier to rely on injection and resolve mechanism

**Comment by AndrewIsh** [comment]
@lorenzofox3 Thanks for that, some interesting thoughts. I can definitely see the appeal of your preferred approach, keeping the service in sync with the the 'definitive' data on the server is definitely a concern and something I am mindful of.

A single service being shared by multiple views undoubtedly has many benefits and I struggle to think how I'd do some of the things I'm doing without making use of services in this way.

Anyway, each to their own, many thanks for your time on this.
