### ISSUE TITLE
Pagination Not Updating On Collection Update

### ISSUE THREAD

**Issue by FrankSalad** [lorenzofox3/Smart-Table#417]
I have an external event that updates the st-table by changing the bound collection to one with a different number of pages. Here's an example plunkr:

http://plnkr.co/edit/wbjCoBAXtXuN3NDQBUvQ

When the `Change Datasource` button is clicked , I expect the `st-pipe` function to be called so that the `numberOfPages` pagination attribute gets updated. I tried using `st-safe-src` instead, but the behavior of `st-safe-src` changes when I have an `st-pipe` function defined, and it doesn't fix my problem unless I comment out `pipeAfterSafeCopy = false;` in the `preventPipeOnWatch` function. 

I believe this issue is related to #394, #244, and #167.

**Comment by lorenzofox3** [comment]
Hi, I don't see why you should use st-pipe here as you don't want to overwrite table logic. 
Just use st-safe-src and it should be fine
[plunkr](http://plnkr.co/edit/uyKbfp?p=preview)

**Comment by FrankSalad** [comment]
I am using st-pipe because I need to fetch the datasource from the server when the page changes and when the sort changes. I looked at the source and it appears there is a `stPageChange` callback, but as far as I can tell `stPipe` is the only way I can listen in on sort order changes.

**Comment by lorenzofox3** [comment]
I don't understand is it smart table which triggers the change in the data source (when changing the page or clicking on sort header) or is it an external event (like logged in user changed). If it is the first case you should not have any problem, have you had a look at the [pipe example](http://lorenzofox3.github.io/smart-table-website/#section-pipe) on the documentation website ?
