### ISSUE TITLE
rowCollection as an object not an array ! ?

### ISSUE THREAD

**Issue by hugsbrugs** [lorenzofox3/Smart-Table#418]
Hi everybody, thank @lorenzofox3  for your great plugin !

I have a data source made of objects : 
```javascript
{
    "1":{"prop_1":value_1, "prop_2":value_2},
    "2":{"prop_1":value_1, "prop_2":value_2},
    ...
}
```

I've desperately tried to make smart table works with objects data source instead of arrays and it almost works because it displays data but won't sort them or filter them.

You can have a look at this plunk http://codepen.io/hugsbrugs/pen/NqjZJP which is a modification of docs second example (look for CHANGED in html (1 line) and js (4 lines) )

Does anybody managed to make smart table works with object data source ? or do you have any suggestions ? thanks

Hugo

**Comment by lorenzofox3** [comment]
I think, the easies remain to transform you object in an array, smart-table is not meant to work with object data source. There is this [stackoverflow question](http://stackoverflow.com/questions/30448491/sorting-angularjs-smart-table-bound-to-list-of-ids/30472057#30472057) which deals with the same kind of dataset

**Comment by hugsbrugs** [comment]
YES this is what I am doing at the moment : 
```javascript
           // Original data collection
            $scope.displayedCollection = [];
            // Retrieve webpages from service
            $scope.webpages = UserDuplicateService.get_pages($stateParams.websiteId);
            // Transform object to array because smart table does not handle objects ...
            $scope.webpages_array = utilities.obj_to_array($scope.webpages);
            // Assign dynamic data
            $scope.displayedCollection = $scope.webpages_array;
           // Watch for changes
            $scope.$watch("webpages", function(value) {
                //console.log('watch webpages : ');
                $scope.webpages_array = utilities.obj_to_array($scope.webpages);
            }, true);

           ...

            obj_to_array: function(obj)
            {
                var array = [];
                angular.forEach(obj, function(value){
                    array.push(value);
                });
                return array;
            }
```
But I'm experiencing performances issues since I deal with large data sets. I think this is the wrong way to have : 
- my object of objects
- an array which is a copy of previous object
- smart table which makes its own safe copy
So memory management is far from being optimal with all those copies and watchers ....

I feel like I have 2 choices : 
- change my server data source from object to array but I don't like the idea since my services are made for objects and I like its simplicity  
- change smart-table to another table which handles objects (if I can found any) but I don't like this idea neither since I like smart-table and I was able to manage almost everything I need ... every choice is a bad choice in my case ;)

Thanks for your concern !

**Comment by lorenzofox3** [comment]
But what is the cause of your performance issue (rendering too many html nodes, memory, ... )? (you can use batarang and other tools to have an idea) because smart-table copy references to objects (ie the pointer in memory) rather than deep copies (ie it does not copy object properties etc), so the memory footprint should be light (just a pointer to a new array). However when I see
```Javascript
   $scope.$watch("webpages", function(value) {
                //console.log('watch webpages : ');
                $scope.webpages_array = utilities.obj_to_array($scope.webpages);
            }, true);
```
I see a bottleneck: by setting the flag to "true" you are basically asking angular to keep a **deep** copy of each object in webPages and to perform a dirty check on every single property of every single object at each digest cycle which is far from being optimal :)

**Comment by hugsbrugs** [comment]
I cannot use batarang for debugging since it's so slow it's unusable (I have 16GB of ram ...) but thanks for the tip, I'll try to use it in others worflows.

You're absolutely right about deep watching but surprisingly that's not what slows down rendering (I will certainly replace it by manual updating but as my data can be updated by sockets, that quick solution was working ...)

What put me on the way is the fact you mention "rendering too many html nodes" hum hum I must confess I display sub-tables inside each row : 
![zen](https://cloud.githubusercontent.com/assets/4385090/8079746/fdeb654a-0f66-11e5-9b09-f13b36a29ed7.png)

And as I only display one sub-table at a time, replacing my ng-show (which adds elements to DOM even when they are hidden) by a ng-if (which adds elements to DOM ONLY when they are visible) did the trick, my smart table is now fast enough to not bore users !! COOL & THANKS for pointing me out on solutions !

**Comment by lorenzofox3** [comment]
:+1:
