### ISSUE TITLE
Search on multiple columns

### ISSUE THREAD

**Issue by Jojo2323** [lorenzofox3/Smart-Table#419]
Hello ! 

I am trying to make a search on multiple columns. I use this directive:
```
app.directive('customSearch',function(){
	return {
		restrict:'A',
		require:'^stTable',
		scope:true,
		link:function(scope, element, attr, ctrl){
			var tableState=ctrl.tableState();
			scope.$watch('filterValue',function(value){
				tableState.search = {};
				if(value){
					ctrl.search(value, 'title');
					ctrl.search(value, 'counter');
				} else {
					ctrl.search();
				}
			})
		}
	};
});
```
The problem is that the ctrl.search are cumulative. Is there a way to get smart-table to search on title OR counter ? 

Thanks !

**Comment by lorenzofox3** [comment]
If you want a OR filter you'll need to use a custom filter with this specific logic as it is not supported by the default angular filter used by smart table. This will change the filter globally to your table

```Markup
<table st-set-filter="myFilterName"> </table> 
```
