### ISSUE TITLE
Bower.json angular version is set as latest

### ISSUE THREAD

**Issue by stanleyxu2005** [lorenzofox3/Smart-Table#420]
I noticed that the angular version is set to latest in bower.json, it is really promising? The magic version identifier does not compatible with other artifact provider, e.g. webjar (https://github.com/webjars/webjars/issues/1073) Could you please set an angular version instead of using latest?

**Comment by jamesward** [comment]
The problem with setting a dependency version as `latest` is that it is a totally indeterminate promise of compatibility essentially saying that `Smart-Table` is compatible with any and every version of `angular`.  That is very unlikely to be true.

**Comment by stanleyxu2005** [comment]
`latest` means the project has been at least tested with the current version of foo library in the world. I dont see many problems of it.

**Comment by jamesward** [comment]
What does `current version` actually mean?  Current to what point in time?

**Comment by stanleyxu2005** [comment]
@lorenzofox3 Is smart-table compatible with Angular 2.0? If not, define a clear version boundary is necessary.

**Comment by jamesward** [comment]
The point is more that without a clear version boundary being defined, smart-table is essentially saying that it is compatible with all versions of angular, in the past and into infinity.

**Comment by lorenzofox3** [comment]
done. 

Note you can use npm or the package.json too.

**Comment by stanleyxu2005** [comment]
@lorenzofox3 Thanks for the change. And smart-table is the best!
