### ISSUE TITLE
nothing is working for me.

### ISSUE THREAD

**Issue by ErBahuguna** [lorenzofox3/Smart-Table#421]
nothing is working for me.
grid is display.
if i click on header data go blank.
if i search again blank
even paging is not display for me .

![image](https://cloud.githubusercontent.com/assets/9461432/8147564/92d568f2-128e-11e5-95f8-be4977b71725.png)

![image](https://cloud.githubusercontent.com/assets/9461432/8147567/9ec9b122-128e-11e5-8f60-5f6c9b954e0a.png)

**Comment by lorenzofox3** [comment]
And what can I possibly do... ?

**Comment by devmark** [comment]
http://plnkr.co/edit/4TLESb1hvcfiXy3M644B?p=preview
lorenzofox3 make lots of demo, maybe it can help for you

**Comment by ErBahuguna** [comment]
okay thanks you.

On Tue, Jun 16, 2015 at 9:11 AM, Mark <notifications@github.com> wrote:

> http://plnkr.co/edit/4TLESb1hvcfiXy3M644B?p=preview
> lorenzofox3 make lots of demo, maybe it can help for you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lorenzofox3/Smart-Table/issues/421#issuecomment-112272801>
> .
>



-- 
@Bahuguna Goyal
