### ISSUE TITLE
Number of pages in pagination does not change with search reasult

### ISSUE THREAD

**Issue by AnandGhaywankarCybage** [lorenzofox3/Smart-Table#422]
Hi, 
During an implementation of smart table in my project I found that pagination numbers does not change with number of rows found in search. My search, result returns me 1 row where as number of pages still remain same as when all rows. 
After debugging I found that pagination.number in function pipe() comes undefined somehow while search and hence pagination.numberOfPages does not get bind with filtered.length. 

Please see attached. 
![smart-table_error](https://cloud.githubusercontent.com/assets/12638200/8159901/bd155ca8-1388-11e5-9d52-c7c08f7330e3.png)
 
Please suggest me  How I can resolve this issue. Thanks in advance!

**Comment by lorenzofox3** [comment]
please provide a plunker
