### ISSUE TITLE
Fixed Header doesn't work on iPad

### ISSUE THREAD

**Issue by dweremeichik** [lorenzofox3/Smart-Table#423]
On the iPad in safari, fixed header renders similar to a normal table, with the headers taking up the entire width of the page, and the body only taking up a small portion of the page. The headers do not stick to the top of the view port. 

@lorenzofox3 This is visible in your demo  on: http://lorenzofox3.github.io/smart-table-website/

**Edit**
It appears that this may be due to Safari needing -webkit- prefixes, this will need testing though.

**Comment by lorenzofox3** [comment]
yes maybe, again the fixed header plunker is more an example to give inspiration, you might need to adapt to your use case

**Comment by dweremeichik** [comment]
Fixed in this plunker:
http://plnkr.co/edit/qC3AdM?p=info

Perhaps you might want to consider updating the plunker on your page to reflect the one above, I know you said it was for inspirational purposes, however it will save someone else time and headache later on.

**Comment by lorenzofox3** [comment]
thanks, I will :+1:
