### ISSUE TITLE
st-select has strange when table has class 'table-striped' (in combination with st-safe-src?)

### ISSUE THREAD

**Issue by pieterdegraeuwe** [lorenzofox3/Smart-Table#427]
Don't know what is causing this, but it seems that only the even rows are selectable.
The odd rows cannot be selected.

see this plunk: http://plnkr.co/edit/SktdSv?p=preview

It seems to be related to the class bootstrap class 'table-striped'. Removing that class fixes the issue.
Anyhow, I think css classes should not break this functionallity, no?

**Comment by lorenzofox3** [comment]
For the selection smart-table add a property isSelected to your row model, this should always work
Then it add its own class to the row so you can style it as you wish but it is your responsibility to integrate with your css library etc

**Comment by pieterdegraeuwe** [comment]
aarrgh. you're right. 
Css was wrong + I did use the wrong selection property ('selected' instead of 'isSelected')
(I've updated the css in the plunk for reference)

Thanks

**Comment by tonipiano** [comment]
Hi Lorenzo!
Can you show me an example about using isSelected property?
Thanks

**Comment by hverlin** [comment]
If you want to use it with the bootstrap table
````css
.st-selected {
 background-color: blue !important;
  color: white !important;
}
````

**Comment by lonerzzz** [comment]
I did this to make it work:

`
tr.st-selected
{
	background-color: blue;
}
.table-striped>tbody>tr.st-selected
{
	background-color: blue;
}
`
`

**Comment by rameshj28787** [comment]
Below CSS worked well for me!

.table-striped>tbody>tr.st-selected:nth-child(odd)>td,
.table-striped>tbody>tr.st-selected:nth-child(even)>td {
background-color: #C1FFC5 !important;
color: red!important;
