### ISSUE TITLE
About stSafeSrc attribute

### ISSUE THREAD

**Issue by frorerain** [lorenzofox3/Smart-Table#432]
Hi there,
I have following code in controller:
<pre>
$scope.rowCollection = Restangular.all('order').getList().$object
$scope.itemsByPage = 30
$scope.displayedCollection = [].concat($scope.rowCollection)
</pre>

And in view:
<pre>
&lt;table class="table table-bordered table-hover" st-table="displayedCollection" st-safe-src="rowCollection"&gt;
</pre>

Is this a normal behavior that $scope.displayedCollection did NOT be changed when I did an operation like following:
<pre>
$scope.rowCollection[index] = data 
</pre>

I find the stSafeSrc attribute which in smart-table.js is using $scope.$watch() method, so I tried to use following code in my controller:
<pre>
//This one is not work.
$scope.$watch 'rowCollection', (newVal, oldVal) =>
   $scope.displayedCollection = [].concat($scope.rowCollection)

//This one works for me.
$scope.$watchCollection 'rowCollection', (newVal, oldVal) =>
   $scope.displayedCollection = [].concat($scope.rowCollection)
</pre>

Is there anything i did wrong? Otherwise I was expected that $scope.displayedCollection will be changed when $scope.rowCollection changed.

Any helper will be appreciated, and sorry for my poor english.

**Comment by lorenzofox3** [comment]
Hi,
There is not check on the content of the item itself (for performance reason), so you'll need to keep same references to see the updates.

```Javascript
angular.extend($scope.rowCollection[index], data)
```

you'll find more details here https://github.com/lorenzofox3/Smart-Table/issues/205

**Comment by frorerain** [comment]
That's nice, thanks for the help. I will close this issue, and very appreciated.
