### ISSUE TITLE
Sorting a column that uses a function always results in functionName: "" in tableState

### ISSUE THREAD

**Issue by dbkaplun** [lorenzofox3/Smart-Table#434]
``` json
>> JSON.stringify(ctrl.tableState());
{"sort":{"reverse":true,"functionName":""},"search":{"predicateObject":{"$":"sails"}},"pagination":{"start":0}}
```

This means that the `stPersist` directive under "Persist table state in local storage" on [smart-table-website](http://lorenzofox3.github.io/smart-table-website/#examples-section) ([direct link](http://plnkr.co/edit/ekwiNt?p=preview)) doesn't work with function sorting.

**Comment by lorenzofox3** [comment]
Maybe because your sort function is anonymous ?

**Comment by dbkaplun** [comment]
I've added names to the functions (so they look like `function name () {}` now), and I see the names in `tableState`, however smart-table is not associating the name from `tableState` to the functions in `st-sort` directives. I am storing the sort functions like `$scope.sortFns.id`, `$scope.sortFns.user` and passing them like `st-sort="sortFns.id"`.
