### ISSUE TITLE
How to bind external search box with smart-table

### ISSUE THREAD

**Issue by stanleyxu2005** [lorenzofox3/Smart-Table#436]
The current `st-search` works only within a table scope. I want to create a nice search box on the top of a page. When user search sometime, it will search in smart-table. I found this answer
http://stackoverflow.com/questions/26983664/how-to-implement-custom-search-with-smart-table-and-angularjs but it does not work. 

I found a workaround, but looks ugly. 
```
<input type="text" ng-model="search"/>

<table st-table="data" ng-controller="MyCtrl">
<thead>
<th>
  <td st-sort='id'>id</td>
  <td st-sort='name'>name</td>
</th>
<th ng-show="false">
  <td colspan="2">
    <input type="text" st-search/>
  </td>
</th>
</thead>
<tbody>...</tbody>
</table>

<script>
var MyCtrl = function($scope, $element) {
    var elem = $element.find('input')[0];
    $scope.$watch('search', function(val) {
      elem.value = val || ''; // empty string means to show all records
      angular.element(elem).triggerHandler('input');
    });
};
</script>
```

**Comment by henrahmagix** [comment]
You can place the `st-table` directive wherever you like, it doesn't have to be on the `<table>` element. Is it possible for you to move it to a common parent element of `<input>` and `<table>`? That is exactly what I have done to have a search filter outside of a `<table>` element.

**Comment by stanleyxu2005** [comment]
@henrahmagix I get your point. Thanks for the tip!

**Comment by stanleyxu2005** [comment]
@henrahmagix I get your point. Thanks for the tip!
