### ISSUE TITLE
Or operator for column filter

### ISSUE THREAD

**Issue by bbuie** [lorenzofox3/Smart-Table#437]
Is it possible to make a filter that shows all rows with Value1 OR Value2? I totally understand making a [custom filter](http://stackoverflow.com/questions/25923376/filter-by-multiple-boolean-properties-in-angular-js-smart-table) but can't find anything on filtering with an or operator.

**Comment by lorenzofox3** [comment]
http://stackoverflow.com/questions/15868248/how-to-filter-multiple-values-or-operation-in-angularjs

**Comment by bbuie** [comment]
Thanks!

That is what I ended up doing but it was difficult because the filter totally replaces the built in filter so I had to recreate the built in filter with the addition of my custom requirements.
