### ISSUE TITLE
Event on pagination

### ISSUE THREAD

**Issue by xOrionRTM** [lorenzofox3/Smart-Table#438]
I have a smart-table with pagination. When I choose a row, the data is displayed on a form, but i want to reset to null that data when i move to a new page (so the selection also) on the pagination.

    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.23/angular.min.js"></script>
    <div ng-app="myApp" ng-controller="TestCtrl">
    <div class="smart-table-container">
                <table id="mytable" st-safe-src="dataSet" st-table="displayed" class="smart-table table">
                    <thead>
                    <tr >
                        <th >A COLUMN</th>
                        <th >A COLUMN</th>
                        <th >A COLUMN</th>
                        <th >A COLUMN</th>
                        <th >A COLUMN</th>
                    </tr>
                </thead>

                <tbody data-ng-dblclick="scrollTo()">

                    <tr data-ng-repeat="row in displayed" st-select-row="row" st-select-mode="single" data-ng-click="$parent.setClickedRow($index)" and data-ng-class="{'selected':$index == $parent.selectedRow}">
                        <td data-ng-click="$parent.selData(row);">{{$index}}</td>
                        <td data-ng-click="$parent.selData(row);">{{row.asd}}</td>
                        <td data-ng-click="$parent.selData(row);">{{row.dsa}}</td>
                        <td data-ng-click="$parent.selData(row);">{{row.qwe}}</td>
                        <td data-ng-click="$parent.selData(row);">{{row.ewq}}</td>
                    </tr>
                </tbody>
                    <tfoot>
                        <tr>
                                <td class="text-center" st-pagination="" st-items-by-page="5" colspan="8">
                                </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
       </div>

And the Controller:

    angular.module('myApp', []);

     function TestCtrl($scope) {
        $scope.selectedRow = null;
        $scope.displayed = [{asd:3},{asd:3},{asd:3},{asd:3},{asd:3},{asd:3}]
        $scope.setClickedRow = function(index){
             $scope.selectedRow = index;
        }
    }

**Comment by lorenzofox3** [comment]
hi, 
it is not documented but you can register a callback on the pagination directive whenever the page changes ``<div st-pagination st-page-change="myFunc"></div>``

see https://github.com/lorenzofox3/Smart-Table/blob/master/src/stPagination.js#L49

**Comment by stanleyxu2005** [comment]
I registered a `myFunc` and it always return undefined
```
$scope.myFunc = function(data) {
  console.log(data);
}
```

**Comment by stanleyxu2005** [comment]
@lorenzofox3 Correct you that `st-page-change="myFunc"` should be `st-page-change="myFunc(newPage)"`, otherwise it will not be called expectedly.

I have a question (or maybe a feature request) here: I'd like to know more than the current page number, but the indices of these showing records from `st-table` or `st-safe-src`. Is it possible?

**Comment by bangph** [comment]
I found a working example here for one who wants to bind a function when page is clicked

https://stackoverflow.com/a/39839821/2028440

Really cool stuff.
