### ISSUE TITLE
Expose more numbers in pagination

### ISSUE THREAD

**Issue by stanleyxu2005** [lorenzofox3/Smart-Table#440]
Is it a way to show the number of total records and the number of records in current page. 

I'd like to add such text in pagination:
```
Total: 550 records (showing 100-120)
```

**Comment by dmackerman** [comment]
You'd have to have your server return a `total` or `count` for the total number. You can calculate those other 2 numbers based on the current offset, and the number of records you're actively showing, right?

**Comment by stanleyxu2005** [comment]
@dmackerman In `st-table` scope, there is no problem to know the number of records. If you use `st-pagination st-pagination-template="footer.html"`, in footer.html it is not possible to know the total number of records. I'd like to find a simple way to show the number there.

**Comment by aleross** [comment]
+1

**Comment by stanleyxu2005** [comment]
Good solution. FYI, the 2.1.1 supports `totalItemCount` now.

**Comment by emersy** [comment]
@aleross unfortunately that doesn't works in case if we use pipe/ajax plugin ( size is always = 0 ).

**Comment by stanleyxu2005** [comment]
@emersy could you test with my version, which need the help of smart-table 2.1.1?
```
.directive('stSummary', function() {
    'use strict';
    return {
      require: '^stTable',
      template: 'Showing {{ stRange.from }}-{{ stRange.to }} of {{ totalItemCount }} records',
      link: function(scope, element, attrs, stTable) {
        scope.stRange = {
          from: null,
          to: null
        };
        scope.$watch('currentPage', function() {
          var pagination = stTable.tableState().pagination;
          scope.stRange.from = pagination.start + 1;
          scope.stRange.to = scope.currentPage === pagination.numberOfPages ?
            pagination.totalItemCount : (scope.stRange.from + scope.stItemsByPage - 1);
        });
      }
    };
  })
```

**Comment by emersy** [comment]
@stanleyxu2005 great! It works if we set values of totalItemCount & numberOfPages when we got a response from server.

**Comment by lorenzofox3** [comment]
you can now have access to this information on the pagination scope https://github.com/lorenzofox3/Smart-Table/blob/master/src/stPagination.js#L31-L32
(plus the bindable property stItemsByPage

**Comment by starlightyear** [comment]
Can you please add a working example with stSummary ?
