### ISSUE TITLE
Do the custom tags st-sort, st-search work when I am rendering columns dynamically?

### ISSUE THREAD

**Issue by AdityaKumarRavikanti** [lorenzofox3/Smart-Table#441]
Hi there,
I am new to Angularjs and I am trying to implement dynamic tables using the smart-table library.

I am doing something like this 
```<th ng-repeat="col in columns"  st-sort="{{col}}" >{{col}}</th>```
But the sort doesn't work.

Am I doing something wrong? Can you help me?

Thanks and Regards,
Aditya.

**Comment by lorenzofox3** [comment]
I think it should work, have you tried without doing the interpolation for st-sort attribute ?
```st-sort="col"```

**Comment by AdityaKumarRavikanti** [comment]
I figured out the problem, I forgot to use stSafeSrc attribute. Sorry to bother you. 
After configuring this it worked like a charm.
Thanks for the help.

**Comment by Chalkin** [comment]
Ho did you render the columns dynamically? Trying to do exactly that, but haven't figured out yet.
