### ISSUE TITLE
Object that gets updated in safeSrc array is not updated in displayed array

### ISSUE THREAD

**Issue by wolfgangmeyers** [lorenzofox3/Smart-Table#446]
I know it would be inefficient to scan *every single object* in the safeSrc array for changes each digest cycle in order to detect an updated object, so I found a reasonable work around. Update the value (safeSrc[index] = value), push a dummy value to the end, schedule a $timeout callback to remove from the end.

So I'd say this isn't a high priority to fix given that there is a workaround, but it would be nice to have a more elegant way of notifying the table that a value had been updated so that a hack like this isn't necessary. If you have any suggestions I might find time to submit a pull request with the changes.

**Comment by lorenzofox3** [comment]
https://github.com/lorenzofox3/Smart-Table/issues/205
