### ISSUE TITLE
How to set the size of a table and make scrollable?

### ISSUE THREAD

**Issue by mrLoloCoco** [lorenzofox3/Smart-Table#448]
Hi, 

I started using smart-table and I'm liking it so far. However, how do I set the size of my table, for example, max number of rows, and how do I make my table scrollable once I set the max number of rows? Sorry, I'm a beginner at this.

**Comment by lorenzofox3** [comment]
Hi, 
This is more related to css not really to smart-table, you'll find a lot of documentation online.
For the maximum number of rows you can set up a pagination on scroll. You can look at [this example](http://plnkr.co/edit/Qq2yfC?p=info) for inspiration.
