### ISSUE TITLE
Complex property names doesn't work with st-pipe

### ISSUE THREAD

**Issue by bademux** [lorenzofox3/Smart-Table#449]
It im using ST with a pipe (table backed with serverside data).
the complex object names like 'article.title'.
In my case I don't want to get nensted object in the predicateObject, but plain  string 'article.title'.
Is there any way to control  parsing st-search value?

**Comment by lorenzofox3** [comment]
again, you can pass whatever you want to the table.search api. 
```Javascript
ctrl.search('value','myInput.Like.A.String')
```

and use it as you want in your pipe function

```Javascript
function customPipe(tablestate){
  var search = tablestate.search.predicateObject;
  if(search['myInput.Like.A.String']){
    //do something
  }
}
```

**Comment by bademux** [comment]
cool, so it is possible to extend search behavior by directive that will use ctrl.search() API.
thanks.

**Comment by bademux** [comment]
@lorenzofox3 Unfortunately it is unpossible to use ``` search['myInput.Like.A.String']``` in my pipe method.
Dots are treated as special chars for nested, the same, please check stTable.search() impl.

**Comment by lorenzofox3** [comment]
you are right, it is due to https://github.com/lorenzofox3/Smart-Table/pull/411. 
however you can still use a different token and parse it the way you like in the pipe function: 

http://plnkr.co/edit/F0WKGS?p=preview
