### ISSUE TITLE
[Q] How to pass additional information for st-search in PipeMode

### ISSUE THREAD

**Issue by bademux** [lorenzofox3/Smart-Table#450]
What is the best way to provide  property name, sort type (like, eq, gt, lt) for st-search in PipeMode in declarative way  (in template).
Thanks.

upd, looks like it is generalisation of #437

**Comment by lorenzofox3** [comment]
You'll have to write a custom directive that translate your DSL into a call to the table api 

```Javascript
//ctrl is st table controller
ctrl.search({whatever:{complicated:'input coming from your custom directive'}}, 'myProp')
```
