### ISSUE TITLE
Uncaught Error: [$injector:modulerr]

### ISSUE THREAD

**Issue by Leo-g** [lorenzofox3/Smart-Table#453]
I insatlled via bower and added the below to html file but I get error Uncaught exception
   
     <script src="/static/js/bower_components/angular/angular.min.js"></script>

Complete stack trace
https://gist.github.com/Leo-g/ca28cd10197acd140a9d

**Comment by jss3426** [comment]
How did you resolve this?

**Comment by Leo-g** [comment]
I rewrote the whole code line by line, I also installed via npm
