### ISSUE TITLE
stSort and stPersist not working if stSort contains expression + Solution

### ISSUE THREAD

**Issue by ChrisWiGit** [lorenzofox3/Smart-Table#454]
Hi,
sorry if this was already posted here. There are so many posts similar to my problem that I didn't know what to do. However, I also give a solution.

I found out that stSort does not correctly read the table state if the sort attribute is a method instead of property. I'm using stPersist to jsonfy the tablestate.

e.g.

``` javascript
<th st-sort="sort.aMethod"..>
```

where sort is a scope object with methods for sorting.

https://github.com/lorenzofox3/Smart-Table/blob/master/dist/smart-table.js
In Line 373 (in stSort) there is 

``` javascript
if (newValue.predicate !== predicate) {
```

where

``` javascript
var predicate = attr.stSort; 
```

in our example it is "sort.amethod".

However, if methods are used for sorting, the ctrl.tablestate().sort.predicate contains a function binding and not a string. So the if decision in L373 cannot work since nowhere in code the function tableState.sort.predicate is created and JSON.parse does not work with functions, of course. 
(As a side note: the functionName attribute, if a binding is a function, will be empty if the sorter object looks like this:

``` javascript
$scope.sorter = {
   aMethod : function () { return ... };
}
```

functionName uses prototype Function.name which will use the name between "function" and "()". However it is empty in most examples I've seen. On the other hand "name" of Function prototype doesn't seem to be readily available everywhere since it is a ES6 standard. See:
https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Function/name
)

**SOLUTION**
I have created a plunk to show the problems
http://plnkr.co/edit/kqyv4I?p=preview

In the header you can find stSort with direct property name (PropertyPersistSinceName) of a row and also a method name of a sorter object in scope (EvalNotPersist). 
Click on EvalNotPersist to sort and stop then run the plunk again to see that persistance is not given.

It works, however, for the suggested solution. I created a stSortx directive (mostly copying stSortx) and added a //NEW comment to highlight the changes. In short, I also save the plain attribute content as a string, save it to a new property of the tablestate and compare it later to check whether the directive is currently responsible for sorting.
It does not need a function name and is simple imho.

I hope it helps.

Otherwise good work! :+1:

**Comment by lorenzofox3** [comment]
thanks it looks great !

**Comment by chriswong929** [comment]
I think Smart table should implement their st-sort attribute similarly. I encountered a similar problem where I had: 

```
<th st-sort="::column.sorter"
...
ng-repeat="column in ctrl.vm.columns">
```

and each column would have a custom sorting functionality:
```
column.sorter = function sorter(data) {
   return customSortingFunction(data);
}
```

However, this will not trigger the `$scope.$watch` on `tableState` because we are only updating the sorting function's name in table state (L119):
```
if (ng.isFunction(predicate)) {
        tableState.sort.functionName = predicate.name; // predicate.name is always 'sorter'
```
In the way it is currently implemented, it does not allow for dynamic sorting functionality. We would have to specify a different function name for each column's sorting functionality. If the sorting function name is not unique, then `tableState.sort.funtionName` will not change and we run into problems because the `$scope.$watch` on `tableState` will not trigger.

**Comment by nickiewooster** [comment]
This does not fix the problem restoring the sort state but merely change the sort icons.
The pipe function line 164

if (tableState.sort.predicate) {
        filtered = orderBy(filtered, tableState.sort.predicate, tableState.sort.reverse);
   }

will only executed based on the predicate and not the functionName where the expression is saved
