### ISSUE TITLE
st-search not working with <select> in IE

### ISSUE THREAD

**Issue by xyuanX** [lorenzofox3/Smart-Table#456]
I have been following #254 when I first found the problem. after few weeks, good to see the issue was solved and closed, but my code doesn't work after update. could somebody throw any light on me, what should be done? thx

pls open example with IE  http://plnkr.co/edit/vkmLPRhhAwbIw0XYStg3.

**Comment by lorenzofox3** [comment]
does it help https://github.com/lorenzofox3/Smart-Table/issues/254 ?

**Comment by lorenzofox3** [comment]
does it help http://plnkr.co/edit/4oV3SZ?p=preview (I don't have IE) ?

**Comment by xyuanX** [comment]
yes, it does!  you are a life saver, really appreciated man

**Comment by mderaeve** [comment]
Using the **st-input-event="change"** worked for me to, thanks.
