### ISSUE TITLE
When using st-safe-src, st-table cannot have a '-' in it's name

### ISSUE THREAD

**Issue by StuAtGit** [lorenzofox3/Smart-Table#459]
I'm retrieving data via an async callback in my controller. So I used the st-safe-src attribute.

If I set the values like so:
```
st-table="brandsClientside" st-safe-src="brands"
...
<tr ng-repeat="brand in brandsClientside">
```
It works fine. But if I set the values like so:
```
st-table="brands-clientside" st-safe-src="brands"
...
<tr ng-repeat="brand in brands-clientside">
```
It does not work. The only difference is the '-'.

**Comment by lorenzofox3** [comment]
It is becaue $parse service can not parse properties with '-', I don't think it is an issue as you can simply rename your variable

**Comment by StuAtGit** [comment]
If it was a clearly documented limitation or, even better, a clear error message. And I didn't have to spend time debugging, then, no, it would not be an issue. I do appreciate the work, but, as it stands, it's an issue for someone trying to get the component to work correctly.

**Comment by lorenzofox3** [comment]
:+1: got your point
Note: you can always improve the documentation by clicking on the "improve this documentation" on the documentation website
Note bis:
any angular directive which uses the $parse service will have the same issue: try ``ng-if="{{my-string}}"``
it will break as well. Although I admit in this particular case, it is not straightforward that the binding uses the $parse service behind the scene
