### ISSUE TITLE
How to call server in controller by accessing tablestate

### ISSUE THREAD

**Issue by amanprodigy** [lorenzofox3/Smart-Table#460]
I have a list of products which have created_on property. I have to filter them according to date range. So I decided to use the daterange picker directive https://github.com/fragaria/angular-daterangepicker. Now how do I link it up with st-search? I can't set two directives (st-search and daterangepicker) on one input element. 

Now the daterangedirective has an option of firing a function on change of dates. Can I link it with callServer() of smarttable. To do that, I would need to access tablestate. Please let me know how to access it in controller.

If it is not possible this way, please suggest how to filter a daterange in smart-table.

**Comment by lorenzofox3** [comment]
I dont't think it would work as the tablestate provided with the callServer() will not be the internal state of the table. 
You should rather create a directive which directly calls the table api. Have a look at this [example](http://plnkr.co/edit/Idbc1JNHKylHuX6mNwZ6?p=preview) and particularly the directive stDateRange.
Of course the example is for client side implementation with custom filter but the stDateRange should work for server side impl too: in your callServer you will have something like
```Javascript
function callServer(tableState){
    //parse search object, you should have something like -> tableState.search.predicateObject.myDateProperty.before (or after)
    var query = { ... }

   //send request to server with params
  http.get(url, query).then(function(result){
    //process result
  })

}
```
