### ISSUE TITLE
Notify on pipe completed

### ISSUE THREAD

**Issue by eirikbell** [lorenzofox3/Smart-Table#463]
I have a requirement where one of my filtering directives needs to know when the result of getFilteredCollection method on stTableController changes, this so I'm able to hide some rows in an advanced dropdown multi select filter when no entries with the value exists in the filtered collection (customer requirements). 

When looking at the code I see there is no way of knowing when the property content changes or for that sake know when the pipe method is done without watching the results, which would downgrade performance significantly. Knowing when the pipe method is done would be valuable, I have several times used quirky workarounds to cope with the lack of any such "notification".

I have created 2 different implementations offering notification when pipe function is done, one where consumer may register a callback, and one where an event is broadcasted. I prefer the broadcasting, but included both so you may evaluate which direction we want to go.

Let me know what you think, and I'll put up a pull request with linted and commented code if you like one of the solutions.

Callback:
https://github.com/eirikbell/Smart-Table/commit/30691f79a66bfae9bbac60ed430fce9b75ef8571

Broadcast event:
https://github.com/eirikbell/Smart-Table/commit/9b03940842d74a52275bbf52586921ad609d548d

Broadcast event with only 1 event broadcasted per stConfig.pipe.delay:
https://github.com/eirikbell/Smart-Table/commit/5c97df4c8623418859225b109fa9af0eec36fbe1

Note: I updated Jasmine to 2.3 and fixed spies for better async testing

**Comment by lorenzofox3** [comment]
I don't think putting a watch on getFilteredCollection would have an impact on perfs (as long as you don't set the last flag to true) as you ask to watch for reference (a simple pointer in memory). Have you already tried ?

**Comment by eirikbell** [comment]
Got it working ok when putting the throttle on timeout inside the watch listener. We have selections in filters saved in browser, causing the filtered collection to change many times on load. Thanks for the tip.

**Comment by lorenzofox3** [comment]
:+1:
