### ISSUE TITLE
Filtering on displayed values and not actual values

### ISSUE THREAD

**Issue by danscrima** [lorenzofox3/Smart-Table#464]
If I have a formatted date, like Aug 4, 2015, I cannot filter on the term "Aug" because the actual date as the real value is 08042015. Is there a way of doing this or overriding the filter function similar to how you can override the sorting function? 

Thanks!

**Comment by lorenzofox3** [comment]
you can override the filter used by using the attribute st-set-filter="myFilterName" on the same element where you have the st-table directive. 
Or you can format you data programmatically before you bind them:
```Javascript
$scope.rowCollection = data.map(function(row){
  row.birthDate = (new Date(row.birthDate)).toString()
  return row
})
```
