### ISSUE TITLE
Draggable rows support

### ISSUE THREAD

**Issue by softengi** [lorenzofox3/Smart-Table#467]
Does smart-table support draggable rows for letting user rearranging row order?

**Comment by jvisser72** [comment]
Hi Softengi,

I don't think that smart-table supports dragging of rows at the moment.
Single and multiple selections of rows are possible though, but not what you are looking for.

Regards,

JVisser

**Comment by lorenzofox3** [comment]
you can use [lrInfiniteScroll](https://github.com/lorenzofox3/lrInfiniteScroll), however it won't work if you use a safe source st-safe-src as you will re order the displayed values instead of the original source. Depends on your use case
