### ISSUE TITLE
Sort on click: descending first, then ascending

### ISSUE THREAD

**Issue by alberto** [lorenzofox3/Smart-Table#468]
By default, Smart-Table sort states are ascending, descending, default, in that order.

Is there a way to make the order: descending, ascending, default?

Please notice I am talking about the behaviour of any column when its header is clicked, not the ordering of the  default column (st-sort-default).

**Comment by lorenzofox3** [comment]
No there is no way at the moment to change the order of the different states, I am sorry

**Comment by alberto** [comment]
I think it should be doable if you had a new attribute st-sort-descending="true" or something like that, which you could apply to any sortable column. Would you be open for a pull request to include that? I can give it a try. :)

In that case, I would also remove st-sort-default="reverse", separating the notion of ordering direction from that of the default sorting column.

**Comment by stanleyxu2005** [comment]
@alberto better change the order in config.

**Comment by alberto** [comment]
Thanks @stanleyxu2005 I didn't know you can change the order in the config. Anyway, I want to be able to make some columns descending first (e.g date) and others ascending first (category) so a global change doesn't fix my problem.

**Comment by angoras** [comment]
I'm also very interested in this feature. Any suggestions on how to implement it? I'm an absolute beginner in Angular...

**Comment by JeffreyRoosendaal** [comment]
Please add support for this! It's the only reason I simply can't use it for my project, while I think it's the best and cleanest Angular table module. After trying most of them, Smart Table is by far the best/easiest solution, but I had to switch (back) to ng-table because of this :(

I suggest naming the attribute st-sort-initial, which accepts 'asc' and 'desc', and defaults to 'asc'.

**Comment by rkpatel0** [comment]
Would love this feature too!!!

**Comment by stanleyxu2005** [comment]
+1 I have a large table with 1k metrics records. Usually I want to see the largest throughput, but now I have to click column twice..

**Comment by timonwong** [comment]
FYI: `hz-table` directive (from OpenStack horizon project) have implemented `default-sort` and `default-sort-reverse` attribute
https://github.com/openstack/horizon/blob/master/horizon/static/framework/widgets/table/hz-table.directive.js#L78

**Comment by douglas-treadwell** [comment]
timonwong, I looked at the code there and it seems to only reverse the initial sort.  It doesn't seem like it would enable column-by-column default sort order reversal upon clicking each column.

**Comment by douglas-treadwell** [comment]
Here's an implementation.

https://github.com/lorenzofox3/Smart-Table/pull/608

**Comment by andy-dumbell** [comment]
+1 please

**Comment by lorenzofox3** [comment]
@andy-dumbell do you realize, it has been merged and it is already available ?

**Comment by andy-dumbell** [comment]
Thanks @lorenzofox3 I hadn't realised. Will try now. Cheers Andy

**Comment by lorenzofox3** [comment]
👍
