### ISSUE TITLE
How locally sorting and searching with server side pagination ?

### ISSUE THREAD

**Issue by maustand** [lorenzofox3/Smart-Table#469]
Hi Guys
Just i wanna know if there is available way to enable partial server side processing ?

I wanna keep the sorting, searching functions in the client side but server side manage the pagination system with my pipe/ajax function.

I know that if i set a pipe function, maybe i should manage this by server side, but i prefer to do it locally. 

Maybe its a trivial question and already it has been replied, but i tried to find something in the bugs tracker and just i got this :  
https://github.com/lorenzofox3/Smart-Table/issues/9
https://github.com/lorenzofox3/Smart-Table/tree/server-partial

So those examples are very old and i noticed that it is not working anymore..

This is my code : 

```html
			<table  config="globalConfig"
				st-pipe="leadsServPage" 
				st-table="leadsDisplayedCollection" 
				class="table table-striped" >
				<thead>
					<tr>
						<th st-sort="phoneNumber">Phone Number</th>
						<th st-sort="userName">Username</th>
						<th st-sort="kharonStatus">Status</th>
						<th>Comment</th>
					</tr>
					<tr>
						<th>
							<input class="input-sm form-control" placeholder="search Phone Number" st-search="phoneNumber" />
						</th>
						<th>
							<input class="input-sm form-control" placeholder="search Username" st-search="userName" />
						</th>
						<th>
							<st-select-distinct collection="leadsDisplayedCollection" predicate="kharonStatus"></st-select-distinct>
						</th>
					</tr>
				</thead>
				<tbody>
					<tr ng-repeat="row in leadsDisplayedCollection">
						<td>{{row.phoneNumber}}</td>
						<td>{{row.userName}}</td>
						<td>{{row.kharonStatus}}</td>
						<td>{{row.comment}}</td>
					</tr>
				</tbody>
				<tfoot>
					<tr>
						<td colspan="5" class="text-center">
							<div st-pagination="" st-items-by-page="defaultItemsByPage"></div>
						</td>
					</tr>
				</tfoot>
			</table>
}
```

```javascript

    $scope.leadsServPage = function leadsServPage(tableState) {

      LeadsSvc.orgLeadsList($stateParams.idOrganization, { 
        index: tableState.pagination.start  || 0,
        count: tableState.pagination.number || DEFAULT_ITEMS_BYPAGE,
        withTotal: true
      }).then(function (serverData) {
        $scope.leadsDisplayedCollection = serverData.data.response.leads;
        tableState.pagination.numberOfPages = Math.ceil(( serverData.data.response.total / DEFAULT_ITEMS_BYPAGE ));
      });
    };
		
```

Thank you in advance.

Mauricio Stand.

**Comment by lorenzofox3** [comment]
In this case I think the best is not to handle the pagination (and how you load data) with smart-table but to do it on your own:
1. Don't use st-pagination
2. Don't use st-pipe so the default client side logic (filter,sort) will be handled by smart-table
3. Use st-safe-src attribute so smart-table will know when you have loaded new batch of data

**Comment by augustbend** [comment]
Hi all,

I'm looking for quite the same functionality. Use the server-side pagination but sort locally. According to Lorenzofox3 (by the way, great tool), we should not use st-pagination. If so, I suppose bootstrap UI can be used instead, but what about the logic (going prev, next, changing number of records perpage), would it be retained?
