### ISSUE TITLE
Basic filter works with REST but ...

### ISSUE THREAD

**Issue by Kris-I** [lorenzofox3/Smart-Table#470]
Hello,

Beginner with Smart-Table, I try to get data from REST service. That's work but I read/see some samples around the web and I'm not sure the simple should work. Is it correctly implemented ?

    $scope.getCustomers = function () {
        var url = 'api/customer/getCustomers?';

        $http({ method: 'GET', url: url })
        .success(function (data, status, headers, config) {
            $scope.rowCollection = data.Customers;
        })
        .error(function (data, status, headers, config) {
        });

    };

    $scope.getCustomers();

Markup
st-table="customers" st-safe-src="rowCollection" 

<table st-table="customers" st-safe-src="rowCollection" class="table table-striped">
    <thead>
        <tr>
            <th st-sort="FirstName">FirstName</th>
            <th st-sort="LastName">LastName</th>
            <th st-sort="Code">Code</th>
            <th st-sort="Email">Email</th>
        </tr>
        <tr>
            <th colspan="6"><input st-search="" class="form-control" placeholder="global search ..." type="text" /></th>
        </tr>
    </thead>
    <tbody>
        <tr ng-repeat="row in customers">
            <td>{{row.FirstName}}</td>
            <td>{{row.LastName}}</td>
            <td>{{row.Code}}</td>
            <td>{{row.Email}}</td>
        </tr>
    </tbody>
</table>

**Comment by lorenzofox3** [comment]
I have no idea, the code you provide lack of context. Try to make a runnable example and you'll find out quickly ! ;)
