### ISSUE TITLE
Dynamic st-sort-default setting

### ISSUE THREAD

**Issue by mzealey** [lorenzofox3/Smart-Table#471]
I'm writing some code to dynamically construct a table, it would be really useful if you could set a watch on the st-default-sort attribute to monitor it for changes and apply to the table

**Comment by lorenzofox3** [comment]
I don't think that is a good idea, st-default-sort is supposed to be ... a default, so a one shot. For you very specific use case, I think you can use a directive with high priority which add the st-default-sort attribute if a condition matches
