### ISSUE TITLE
st-sort does not seam to work

### ISSUE THREAD

**Issue by firecentaur** [lorenzofox3/Smart-Table#472]
Hi there, I have duplicated your sort example, however it does not seam to work.
I have included "bower_components/angular-smart-table/dist/smart-table.min.js"  is there anything I need to do to get sorting to work?  My html is here: https://gist.github.com/anonymous/57b375ebec5edd73f821
and my actors json is here: https://gist.github.com/anonymous/d7bfe649e60ba9632c6b

**Comment by lorenzofox3** [comment]
see comments on the gist ;)

**Comment by firecentaur** [comment]
I have fixed it as you said but it is still not sorting

html is here: https://gist.github.com/anonymous/8111a1b61b07b433cfc0
Js here: https://gist.github.com/anonymous/5781c3115949e75b2aa9

**Comment by lorenzofox3** [comment]
then set up a running example please, much easier to troubleshoot

**Comment by firecentaur** [comment]
Hi, thanks for your help.  I created a basic app using your example - 
you can see it here; https://bitbucket.org/firecentaur/smart-table
please check out the repo, type bower install
then type http-server (if you have that installed) to see it in operation

**Comment by lorenzofox3** [comment]
are you sure it is the good repository, it looks like a boilerplate ( I don't see any file related to smart-table for example)

**Comment by lorenzofox3** [comment]
I don't get it, you provide a whole application with a ton of things to simply copy/pasting the documentation example (without actually including smart-table). how is it supposed to help me reproducing your issue ?
I obviously know the documentation example works, thanks :D

**Comment by firecentaur** [comment]
Hi Renard,

I was trying to make it easy to reproduce the issue.  I'll try again...
The problem is, I can't get your example working, that is why i pasted your
example.
The application was generated with yeoman.

[image: circleImagePaulPreibisch.png]

*  Paul Preibisch*
  CTO: Movie English Project
  email: fire@b3dmultitech.com
  LinkedIn <http://linkedIn.com/pub/paul-preibisch/4/130/a64/>

  Public PGP Key: Click Here
<https://pgp.mit.edu/pks/lookup?op=get&search=0x51DE8A676AB03950>
<http://linkedIn.com/pub/paul-preibisch/4/130/a64/>
<http://linkedIn.com/pub/paul-preibisch/4/130/a64/>

**Comment by lorenzofox3** [comment]
for the documentation you are at least missing:
1) smart-table files (there are not loaded)
2) register smart-table module in your app
```app.module('myapp',['smart-table'])

I was able to do it by running 
```bower install --save angular-smart-table```
and modifiying /app/scripts/app.js
```Javascript
'use strict';

/**
 * @ngdoc overview
 * @name smApp
 * @description
 * # smApp
 *
 * Main module of the application.
 */
angular
  .module('smApp', [
    'ngRoute',
    'smart-table'
  ])
  .config(function ($routeProvider) {
    $routeProvider
      .when('/', {
        templateUrl: 'views/main.html',
        controller: 'MainCtrl'
      })
      .when('/about', {
        templateUrl: 'views/about.html',
        controller: 'AboutCtrl'
      })
      .otherwise({
        redirectTo: '/'
      });
  });
```

**Comment by firecentaur** [comment]
aha!  Thanks! I think the issue is that smart-table was not registered as a
module with my app! I think this is no in your documentation by the way.
Thanks for your diligence and getting back to me! Muchly appreciated!

[image: circleImagePaulPreibisch.png]

*  Paul Preibisch*
  CTO: Movie English Project
  email: fire@b3dmultitech.com
  LinkedIn <http://linkedIn.com/pub/paul-preibisch/4/130/a64/>

  Public PGP Key: Click Here
<https://pgp.mit.edu/pks/lookup?op=get&search=0x51DE8A676AB03950>
<http://linkedIn.com/pub/paul-preibisch/4/130/a64/>
<http://linkedIn.com/pub/paul-preibisch/4/130/a64/>
