### ISSUE TITLE
Sorting and Filtering Duplicate values

### ISSUE THREAD

**Issue by JuanMagalhaesDev** [lorenzofox3/Smart-Table#474]
Greetings!

I would like to know if there is a standard way of filtering and sorting data allowing my rows to have duplicate values. 
Right now it seems that I can only filter and sort unique values, is that right?

Thank you,
Juan

**Comment by lorenzofox3** [comment]
filter and sorting work as standard angular filter Filter and orderBy filter do. If you want another behaviour you can replace the filter by yours:  see the "Strict mode filtering" section on the documentation website

**Comment by nillis** [comment]
+1
