### ISSUE TITLE
Missing resizable columns

### ISSUE THREAD

**Issue by ShahzadAnjum** [lorenzofox3/Smart-Table#475]
Can we re-size columns width (LeftnRight) by mouse. I need it ASAP please to use in my project.

**Comment by lorenzofox3** [comment]
then do it ! :)

**Comment by sushanzh** [comment]
Hi, was this enhancement ever added to SmartTable? Or does SmartTable auto adjust the width of each column based on the number of value? Thank you!

**Comment by lorenzofox3** [comment]
No, it is actually not really relevant for this project. It is more viewport related and should come as a different module.
