### ISSUE TITLE
pagination does not work on ajax data?

### ISSUE THREAD

**Issue by fewiki** [lorenzofox3/Smart-Table#476]
Hi, excuse me.  when I use ajax($http) to get data, the pagination does not work.
my code is here:  http://plnkr.co/edit/VEHXhIJketqcryvoia0V?p=preview
Will you give me a hand? I've try 'st-safe-src', but it is still the same.  thanks a lot.
best wishes.

**Comment by fewiki** [comment]
I have found just now it is work on angular.js 1.2.x.  But it does not work on angular.js 1.2.x above. 
http://plnkr.co/edit/k7HG42jUsPpF7X9XB9YX?p=preview
what's the problem,thanks.

**Comment by lorenzofox3** [comment]
I think, the problem is that in your repeater you are using the reference collection rather than the displayed one:
http://plnkr.co/edit/UPCSj9?p=preview

**Comment by fewiki** [comment]
Thanks a lot, it's my fault. It's very kind of you.
