### ISSUE TITLE
Injecting collection programmatically

### ISSUE THREAD

**Issue by djechelon** [lorenzofox3/Smart-Table#479]
Hello, (@symrad fyi)

I have a trouble extending Smart Table with a new directive. I am currently working on a Plunk to share with you in order to reproduce the issue. Code is at http://plnkr.co/edit/F3ILh8?p=info

At our company we wanted to extend Smart Table with a `st-url` directive in order to simplify AJAX loading of the collection in one attribute that handles filtering, sorting and pagination automagically

### The st-url directive
We designed such directive in order to be simplemost for every developer. Since in our company's projects we handle 90% the times paginated data tables with simple sorting, searching and inline-creation features, we preferred to wrap them into a single directive

    <table st-url="/path/to/controller" st-table="rowCollection">

The `st-url` directive, containing **only** the URL of the HTTP POST resource that returns the data, replaces the Smart Table's pipe function (the one you can override with st-pipe) in order to POST search, order and pagination data at once, and in order to retrieve the data collection from the server in order to be stored into the collection variable.

The client-server interface is fixed in the code, because this directive is born only to be used internally

Here is the code we wrote so far

	angular.module('smart-table').directive('stUrl', [ 'stConfig', '$timeout', '$log', '$http', function(config, $timeout, $log, $http) {
		return {
			require : 'stTable',
			controller : 'stTableController',
			scope : {
				stUrl : '@'
			},
			link : {

				pre : function(scope, element, attrs, ctrl) {
					var oriPipe = ctrl.pipe;
					var pipePromise = null;

					ctrl.preventPipeOnWatch();
					ctrl.pipe = function() {

						if (pipePromise !== null)
							$timeout.cancel(pipePromise)

						pipePromise = $timeout(function() {

							var tableState = ctrl.tableState();
							var pagination = tableState.pagination;
							var perPage = pagination.number || 10;
							var start = pagination.start || 0;
							// currentPage, perPage

							var order = tableState.sort;
							var filter = tableState.search.predicateObject;

							$http.post(scope.stUrl, {
								offset : start,
								perPage : perPage,
								sort : order,
								filter : filter
							}).then(function(result) {
								var response = result.data;
								// ctrl.displayedCollection = response.data;
								// scope.$parent.displaySetter(scope, response.data
								// || {});
								scope.rowCollection = response.data; //Don't know how to do

								tableState.pagination.numberOfPages = response.totalPages;
								oriPipe();

							});

						}, config.pipe.delay);

						return pipePromise;
					}

				},

				post : function(scope, element, attrs, ctrl) {
					ctrl.pipe();
				}
			}
		};
	} ]);

### The problem
After returning from the server, we must store the collection somewhere. Please ignore that we wrote `scope.rowCollection`, it was an attempt.

From the scope of the new pipe function we don't have means to store the result set to the object Smart Table uses as collection (the one declared in st-table).

- `scope.rowCollection` has two issues: it hardcodes member name and scope is **not** the controller scope (see Plunk)
- `displaySetter` is not accessible because it is not "publicly" declared in the Smart Table controller

## Wrapping it up
I would kindly ask if there is a way to programmatically set the Smart Table collection, **or** if this feature requires a slight edit in the code in order for Smart Table to expose the displaySetter function.

We have tried (and next message will contain a practical example) to edit Smart Table code by exposing a `setCollection` method in the `this` scope and succeeded in displaying the collection.

Thank you

**Comment by djechelon** [comment]
Hello, the following Plunk proposes and uses a [modification](https://github.com/lorenzofox3/Smart-Table/compare/master...OpenCST:cst-stUrl#diff-ba01d1c7484a8ba86617307724ff2052L48) to Smart Table API

http://plnkr.co/HYIFtx

**Comment by lorenzofox3** [comment]
can you set up the first plunk public ? I have managed to modify it to make it work but I am not able to save it

**Comment by lorenzofox3** [comment]
see [here](http://plnkr.co/edit/05jQwv?p=preview)

I think in your case, as you have your logic in the server the easier is to use st-pipe. And to avoid repetition you can wrap the custom pipe function in a directive. (which configure the custom pipe based on the url)

Note, the stUrl can not define an isolate scope otherwise there is a scoping issue which I don't know the reason, so if you need to watch the value or to interpolate it you'll have to do it manually in the link function of your stUrl directive
