### ISSUE TITLE
Grouping is done only page wise data not whole data

### ISSUE THREAD

**Issue by vipintme** [lorenzofox3/Smart-Table#481]
We have implemented grid using smart table and groping is done by custom filter. When grouping is done, the page wise data is grouped. For example , the list contain 15 users, 5 users having its  name is Robin .When grouping is done for last name field, it groups only page wise data. That mean first page having 2 rows for  Robin and in next page having also 2 rows for Robin and last page having one row.

http://plnkr.co/edit/Nim9qBi3U9yCzt31QyjX?p=preview

**Comment by Ram-Kale** [comment]
1+.Same issue.Need whole data grouping.
