### ISSUE TITLE
how to make cells editable (and update the json?)

### ISSUE THREAD

**Issue by JacopoMoscioni** [lorenzofox3/Smart-Table#483]
Hello, I'm a newbie in Angular and was trying to use your smart table project to show some content into a web page.. all was going good, but now I have the need to edit the values of the cells and I want that the changes will update the json too.... 
In the smart table documentation I didn't find anything of useful about cell editing.
Can you provide a little example (to put in the doc too)? thank you!!

**Comment by lorenzofox3** [comment]
Duplicate: https://github.com/lorenzofox3/Smart-Table/issues?utf8=%E2%9C%93&q=inline+editing
