### ISSUE TITLE
Best approach for fixed header

### ISSUE THREAD

**Issue by jss3426** [lorenzofox3/Smart-Table#485]
I am using the plugin and have only 3 columns to display. How can i place then evenly? i tried using st-ratio 33, but the 1st column was much > than 33 and the rest were smaller.

**Comment by e-cloud** [comment]
st-ratio is a directive defined in one of the website's example(the st-ratio one), it's no in the src code. So, if you don't define one in your src code, using directive means nothing.

by the way
![image](https://cloud.githubusercontent.com/assets/5255354/9787860/c95dcaea-57f8-11e5-9bb4-004972d27a67.png)
you can use this way, but it is a bit old-fashion and non-flexible
