### ISSUE TITLE
pagination with pipe/ajax plugin 

### ISSUE THREAD

**Issue by parvanova** [lorenzofox3/Smart-Table#487]
Hi,
I am looking for a simple and fast table/grid solution for my app. I really like Smart-table. Great work!
I would like to use it with pipe/ajax plugin. But from what I see on http://lorenzofox3.github.io/smart-table-website/#section-pipe the pagination does not work correctly. tableState.pagination.numberOfPages does not take effect. Is there something i miss?

Thanks

**Comment by lneves12** [comment]
I think you have to call the method pipe() so it take effect, something like this:

````
            ctrl.tableState().pagination.start = 0;
            ctrl.tableState().pagination.number = undefined;
            ctrl.tableState().pagination.numberOfPages = undefined;
            ctrl.pipe();
````

**Comment by parvanova** [comment]
I think in the example in  the getPage the code should be
                numberOfPages: Math.ceil(filtered.length / number)
instead of
                numberOfPages: Math.ceil(1000 / number)

this why pagination will show number of pages AFTER filtering.

Hope this helps someone to not go away from Smart-Table

**Comment by lorenzofox3** [comment]
you are correct. 
Note this code is just to mimic a server behaviour and the logic would happen normally in the server. It is not really related to smart-table

**Comment by lorenzofox3** [comment]
fixed thanks :+1:
