### ISSUE TITLE
Problem with st-safe-src attribute

### ISSUE THREAD

**Issue by T4ddy** [lorenzofox3/Smart-Table#488]
Hi,

I'm trying to implement drag and drop between two tables and I had problems with the attribute st-safe-src. The problem is that when adding a new element to the collection, table is not updated. I tried push, splice, angular.copy, [].concat, inside Smart Table source setting third parameter of $scope.$watch to true, but nothing worked. Table is updated only after sorting. Is it possible to force the table update?

Thanks.

**Comment by lorenzofox3** [comment]
Hello,
difficult to say, can you please try to set up as small plugin to reproduce your issue, thanks

**Comment by T4ddy** [comment]
My apologize for the delay,

I fill an array like this

```javascript
scope.deliveryCollectionSafe = [];
for(...){
   ...
   scope.deliveryCollectionSafe = scope.deliveryCollectionSafe.concat(jsonRoutes.routes[i].deliveries);
}
scope.deliveryCollection = [].concat(scope.deliveryCollectionSafe);
```

and when later i do

```javascript
scope.deliveryCollectionSafe.splice(insertPos , 0, tmpDelivery);
```

nothing is updated.

**Comment by lorenzofox3** [comment]
and, can you provide a running example ? ...

**Comment by T4ddy** [comment]
Unfortunately no. On Plunker it works well and i don't now why :(  I just wanted to know, is it possible to manually update the table? Thanks.

**Comment by lorenzofox3** [comment]
if you use st-safe-src attribute, changing the reference of the bound collection should trigger an update.

I am going to close the issue then.
