### ISSUE TITLE
Sort column that contains a dot in its name

### ISSUE THREAD

**Issue by oslo10e** [lorenzofox3/Smart-Table#491]
I want to display st-table with a column that contains a dot :
data = [{'product.price': 1}, {'product.price': 2}]
When I declare st-sort="product.price" it does not work.

See jsfiddle : http://jsfiddle.net/opeaucelle/w5fpr9we/

**Comment by lorenzofox3** [comment]
You can use a getter function for your st-sort (have a look a the documentation website for more details)
```
function priceSorter(item){
    return item['product.price'];
}
```

**Comment by lorenzofox3** [comment]
You can use a getter function for your st-sort (have a look a the documentation website for more details)
```
function priceSorter(item){
    return item['product.price'];
}
```

http://jsfiddle.net/fwgsh866/
