### ISSUE TITLE
default value of a select element for itemsByPage 

### ISSUE THREAD

**Issue by parvanova** [lorenzofox3/Smart-Table#493]
Hi,

I want to give the user an opportunity to change the number of items per page by selecting from a select list. Everything works OK except that I can't set the default value of the select element. If I change the `<select>` to` <input type=text>` - no problem.
Here is my code:
in the html
```
<div ng-controller="AppController as mc" >
    <table st-pipe="mc.callServer" st-table="mc.displayed">
.....
    <td class="text-center">
        <select name="itemsByPage" ng-model="mc.itemsByPage" >
            <option value="5">5</option>
            <option value="10">10</option>
            <option value="25">25</option>
            <option value="50">50</option>
        </select>
        </td>
     <td class="text-center" st-pagination=""  st-items-by-page="mc.itemsByPage"> </td>
```
in the AppController:

    $scope.itemsByPage = '5';

Can you please help me!

**Comment by nickatedge** [comment]
I encountered a similar issue before. It turns out that you need to ensure that itemsByPage is a number not a string type. You can use parseInt() to convert it to number type.

**Comment by parvanova** [comment]
well, I set `$scope.itemsByPage = '5';` because of what I read here https://github.com/angular/angular.js/blob/master/CHANGELOG.md#140-beta0-photonic-umbrakinesis-2015-01-13 - "the select directive will now use strict comparison of the ngModel scope value against option values to determine which option is selected. This means Number scope values will not be matched against numeric option strings."

Note that if I remove the `<td class="text-center" st-pagination=""  st-items-by-page="mc.itemsByPage"> </td>` from the html the `<select>` gets the default option as expected. So I think the issue is something specific to Smart-table... Оf course I could be wrong...

**Comment by lorenzofox3** [comment]
I can not reproduce, please follow the "submit an issue" guidelines and provide a running example

**Comment by parvanova** [comment]
I am sorry! I had to provide a running example at the beggining.
Here it is - http://plnkr.co/edit/gv50StC62X3p8Kuvt06F?p=preview

Note that the default option is set correctly if you use angular 1.3 but is not set if you use angular 1.4

Thanks for your time!

**Comment by lorenzofox3** [comment]
I think it is more related to how ngOptions parses values, if you set the default value as member of ngOptions there is no problem: 

http://plnkr.co/edit/rOlHMr?p=preview

**Comment by parvanova** [comment]
Thank you very much!
