### ISSUE TITLE
How to animate the sort arrow toggling

### ISSUE THREAD

**Issue by stanleyxu2005** [lorenzofox3/Smart-Table#494]
I have defined two arrow images (as background image) for column sort state. Now I want to make it more fancy. I want to have an arrow rotation animation, when I click on column. Is it possible?

**Comment by lorenzofox3** [comment]
yes but it is not really related to smart-table, add [transition](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transitions/Using_CSS_transitions) or animation on st-sort-ascent/descent for example
