### ISSUE TITLE
Trouble with Paging 

### ISSUE THREAD

**Issue by praveenrulz** [lorenzofox3/Smart-Table#498]
I am having trouble with paging. I tried the inbuilt as well as custom. But there is no li inside the ul. I am not able to figure out what the issue is. I am doing client side page after getting the data from a AJAX call. Here is the markup i am using. 

<div class="pagination ng-scope" ng-if="pages.length >= 2" st-items-by-page="10" st-pagination="" st-template="/App/infra/templates/pagination.custom.html">
<ul class="pagination">

</ul>
</div>
![image](https://cloud.githubusercontent.com/assets/6440219/9884376/9c84948e-5b9c-11e5-80d1-cc1ef2abe398.png)

And here is the generated html markup after I run the page. There are no li inside the ul tag.

![image](https://cloud.githubusercontent.com/assets/6440219/9884543/83f5926e-5b9d-11e5-9ed8-35f3ad22ac6d.png)

**Comment by wsbrunson** [comment]
What does your `pagination.custom.html` file look like?

**Comment by praveenrulz** [comment]
I am not able to post the html mark up directly. SO i posting images. Here is what i have in pagination.custom.html
 
![image](https://cloud.githubusercontent.com/assets/6440219/9905938/0d91772a-5c45-11e5-87cd-801399ae4080.png)

**Comment by wsbrunson** [comment]
Why don't you have the ul and ng-repeat in the custom template? If won't be able to access pages outside of the st-pagination directive.

**Comment by praveenrulz** [comment]
I didn't describe the issue properly. I updated it to make it clear. The screenshot is the markup. The second screenshot is the markup generated after I run the application. Angular generates the UL but there is no LI inside the list.

**Comment by wsbrunson** [comment]
Is there any way you could put this into a plunkr?

**Comment by XcodeJunkie** [comment]
I think you are missing the `st-displayed-pages="5"` directive (5 is just an example). You have to tell the plugin how many links max. it should generate.

**Comment by praveenrulz** [comment]
I tried st-displayed-pages="5" as well. But it is not showing the Pages. I am working on a plunkr. Will post it here.

**Comment by lorenzofox3** [comment]
plunker ?
