### ISSUE TITLE
Question: programmatic default sort.

### ISSUE THREAD

**Issue by spt131** [lorenzofox3/Smart-Table#499]
I use smart-table all over, love the project lorenzo.

In this case, I am creating dynamic columns based on the week of the year going on and would like to force a sort for one of them. I could rewrite this without using ng-repeat in this way but wondering if it's possible to st-sort-default programmatically for one of these columns.

`<tr class="light-grey-table-row">
                <th ng-repeat="week in weeks_options" st-sort="{{week.value}}" >Week {{week.value}}</th>
            </tr>`

**Comment by lorenzofox3** [comment]
I don't know actually, if you set up a small example you will likely find out
