### ISSUE TITLE
Responsive behaviour

### ISSUE THREAD

**Issue by Nesse** [lorenzofox3/Smart-Table#500]
Hi,

I was wondering if it's possible to extend smart-table to handle responsive behaviour like footable by adding data-attributes on complex and large tables? (https://github.com/fooplugins/FooTable) 

***DEMO:*** http://fooplugins.com/footable/demos/getting-started.htm (resize browser window)

Best Regards

**Comment by lorenzofox3** [comment]
Hi, 
why not, have you tried ? 
I personally prefer 100% css solutions and using bootstrap ``xs-hidden`` class I don't have any problem

**Comment by Nesse** [comment]
I have not tried this yet, but going to make an attempt. I've also tried to use CSS but still need to show some essential data.
