### ISSUE TITLE
pagination problems with 2.1.3

### ISSUE THREAD

**Issue by victorbstan** [lorenzofox3/Smart-Table#502]
Would there be some changes in pagination between 2.1.2 and 2.1.3 that would break pagination? I'm seeing this in my current implementation, but rolling back to 2.1.2 fixes my pagination issues. Specifically, if I change pages, and load content through AJAX, after the new new content is loaded, the current page number is reset to 1 instead of displaying/highlighting the current page in the pagination html.

**Comment by lorenzofox3** [comment]
https://github.com/lorenzofox3/Smart-Table/issues/477 maybe ?
