### ISSUE TITLE
stSelectMultiple filter produces empty choices when table data comes from server

### ISSUE THREAD

**Issue by XcodeJunkie** [lorenzofox3/Smart-Table#503]
I have a project where I retrieve data from a sqlite database by a service. Everything works fine, table data is getting displayed, `st-safe-src` is correctly set. I now fail to set a multiple filter onto one row. It seems like the collection data is empty in the `bindCollection` function of the filter. I assume the collection needs some like updateEvent after data has been fetched.

See the education filter in this plunker http://plnkr.co/edit/hzCLiS

I am using angular 1.3.15 with smart-table 2.1.3.

**Comment by lorenzofox3** [comment]
To be honest, this not really related to smart-table but more to an example a contributor submitted, so I don't maintain much theses examples. 
but adding a watch on the collection seems to fix your issue http://plnkr.co/edit/xfjPXZ?p=preview

**Comment by XcodeJunkie** [comment]
Thought the scope should be updated after data retrieval. Thanks for your help, `$watch` made it!

**Comment by brunnurs** [comment]
Had the same issue, many thanks!
