### ISSUE TITLE
Pager Usability improvement

### ISSUE THREAD

**Issue by igorlino** [lorenzofox3/Smart-Table#505]
Hey there,

The pager for few results and pages seems fine, but when having lots of data, the user easily loses the visibility of the table. Of course you may use filter to reduce the data sets, but that still does not give a good perspective of the dimension and specially the important last/first result together with some filter or sorting.

So, with that in mind, is there a simple way to extend the pager so that it supports other types of layouts that include, 1st page, last page, and perhaps also show the first 3 and last 3 pages, instead of just putting the first N pages and nothing else.

Thanks in advance

**Comment by lorenzofox3** [comment]
Hi, 
There is a [example](http://plnkr.co/edit/LB2f9P?p=info) on the documentation website called "custom pagination", I think it is what you are looking for. By searching a little bit on the issue section you should find more example

**Comment by igorlino** [comment]
OMG, totally overseen it. Thanks a lot, It really was at the very bottom of the page. I think somehow the menu of the page mislead me a bit, I thought it listed all the sections/titles of page.
(It did help me not looking for all the paging keywords.)
Thanks again.
