### ISSUE TITLE
allow st-sort to be declared function string instead of just function name

### ISSUE THREAD

**Issue by btm1** [lorenzofox3/Smart-Table#506]
the way it is now:

st-sort="calc.somefunctionname"

The down side of this is that you are the only one that can pass anything to this function and right now you're only passing the row value.  If you are looping through some headers you might want to be able to pass some secondary information in order to complete the sorting calculation like the $index of what you're looping on.

The upside for you or doing it the the way you have it right now is that what you do var getter = $parse(stSortAttributeValue) you can check to see if it's a function by doing angular.isFunction(getter(scope)) more easily.

What I want to be able to do is declare it the way angular lets you on other attributes i.e.

st-sort="calc.somefunctionname(val,$index)"

This way I have more control over what's being passed to this function. The downside for you is that you wouldn't be able to do angular.isFunction(getter(scope)) to see if it's a function anymore because it would call the function. I've build other directives in the past and although it might seem kinda jank you could just do this to check to see if the attribute string is a function _.contains(theAttribute,'(') && _.contains(theAttribute,')')

here's an example how how I did something similar:

```
							var field = $(this).attr('st-export'),
								getter = $parse(field),
								v;

                            // in this case field is something like mySortFunction($row)
							if(_.contains(field,'(') && _.contains(field,')')) {
                                // if it's a function than execute it on the scope and pass the current row
								v = getter(scope,{
									$row : row
								});
							} else {
                                // if it's just some dot notation like myfield.total than just get the value of that in the context of the row
								v = getter(row);
							}
                            return v;
```

**Comment by lorenzofox3** [comment]
you can use a technique called "currying",or forcing function arguments using the bind operator of the Function. prototype

```Javascript
function myFunc(index, row){}
```

should be usable as

```
<th st-sort="myFunc.bind(null,$index)"></th>
```

**Comment by btm1** [comment]
true you could do that... although it seems logical to just change the way this works. If you goal is the have it mirror functionality seen in native AngularJS you never declare a function for any built in angular directive by just the name it's always myFunction() not myFunction

**Comment by btm1** [comment]
the other issue with this is that lets say I needed the $index or some other value to zero in on the appropriate sort value based on two nested ng-repeat concepts... you're basing the sorting classes and active header based on the predicate which is this case is the function name.... so unless you have a unique sorting function declared for each table header than it will not understand which header is actively sorting. Let me know if that makes sense...

**Comment by btm1** [comment]
and actually you can't do what you suggested:
```
Error: [$parse:isecff] Referencing call, apply or bind in Angular expressions is disallowed! Expression:
```

**Comment by btm1** [comment]
update: so I found a way around this if anyone else asks but I still think it should be implemented differently so you don't have to do all this:

You can't use .bind in an expression but you can however use lodash curry:

```
$scope.sort = {
    	column: _.curry(function(cohort,group) {
    		return // your sorting thing
    	}),
    };
```

and then on the attribute:

```
<th ng-repeat="cohort in cohorts" st-sort="sort.column(cohort)" st-skip-natural="true">{{cohort}}</th>
```

this still passes the row as the first argument and allows you to pass your own argument second and most importantly doesn't break your sort function in smart-table.js:

```
        function sort () {
          index++;
          predicate = ng.isFunction(getter(scope)) ? getter(scope) : attr.stSort;
       ...
       }
```

ng.isFunction(getter(scope)) would typically call the function if you declare the attribute as st-sort="someFunction(foo)" but for some reason with the _.curry because it creates a wrapper function it doesn't call the function and thus doesn't break anything.

**Comment by lorenzofox3** [comment]
Actually the idea is more to have the same API than orderBy angular filter:
- string as predicate
- function as predicate with the same signature: ``function(item){}``
- array of string/function (not supported in Smart Table)

and avoid hard binding which would create an isolated scope (but that is another story).

As you said, having an expression becomes more tricky to define whether it is a function or string, etc 
And no for me it does not "seem logical to just change the way it works" to support one corner case of one particular use case; I mean if you use the orderBy filter, you will not expect to pass more arguments to the function. One of my main concern with this module is to avoid to make it bloated to please everybody and I prefer having an easy extension mechanism rather than everything in the core. 
Note at anytime you can replace the sort directive by one of yours which would fulfil your requirement.

Also your case is not clear: where does the $index come from ? you have a repeater in your header or you expect it to be injected by smart-table with each row ?

1) in the first case you can workaround your problem by using higher order function
```Javascript
$scope.getters = {
  foo : function(index){
     return function(row){
         // do something with index, row to get the actual predicate
     }
  }
}
```
```Markup
<th st-sort="getters.foo($index)"></th>
```
[example](http://plnkr.co/edit/txude6?p=preview)

PS: I don t know  if you use lodash for this sole purpose but it is not reasonable to have a 50kb library just for that
2) Then if you expect the index to be injected by smart table on the getter function, we actually go back to api design and its not even clear which index we are talking about (in the displayed collection ? it the bound collection ? ). I am not saying that is less relevant to have a signature ``function(item, index){} `` or ``function(item){}``, but I made this choice and I don't see much value added in the first case. And then in two weeks from now, someone will come and say "hey it would be great to have the tablestate as parameter of the function" etc etc

**Comment by btm1** [comment]
No i'm not suggesting you add lodash as a part of your solution ... I used it as a way to solve something that isn't solvable the way you've implemented this. I'm also not asking you to include and index for me because like you said "an index of what?" you'd have no way of knowing that.  The change I've suggesting in no way makes your library more bloated it's simply a slightly different way of implementing this so that YOU decide what to pass to the function instead of being limited to what you're passing from the directive. Personally I see no harm in this and I'm happy to provide an example of why this is relevant:

If i have a table that looks something like this:

```
<table>
	<thead>
		<tr>
			<th ng-repeat="defs in columnDefs" st-sort="defs.field"></th>
		</tr>
	</thead>
	<tbody>
		<tr ng-repeat="row in tableData">
			<td ng-repeat="defs in columnDefs">{{row[defs.field]}}</td>
		</tr>
	</tbody>
</table>
```

You have an array of column defs that describe the headers and describe the cells within each row which store the relevant field to be gotten from each row with the table data.... so this works because the array of heads stores the field. But there are other cases where the array that describes the header isn't an array of objects and it's simply an array of values i.e. ['Q1','Q2','Q3','Q4'] so that being said if we take the same example:

The array that describes the headers doesn't allows have the field and all you have to work with is the index.  That being said you'll need to use a function to sort on st-sort and then it becomes an issue that YOU as the end user have no way of passing the index to this function.

i.e.
```
<table>
	<thead>
		<tr>
			<th ng-repeat="cohort in cohorts" st-sort="column.sort">{{cohort}}</th>
		</tr>
	</thead>
	<tbody>
		<tr ng-repeat="row in tableData">
			<td ng-repeat="cohort in cohorts">{{row.dates[$index]}}</td>
		</tr>
	</tbody>
</table>
```
In the above example column.sort only receives the row value and there is no way for me to pass anything. This is absolutely relevant.

**Comment by lorenzofox3** [comment]
> No i'm not suggesting you add lodash as a part of your solution ... I used it as a way to solve something that isn't solvable the way you've implemented this

Actually I was more referring to your application: I don't think it is worthy to use lodash only for higher order function. 
Again the "problem" is solvable as it is now. Have you looked at the [plunker](http://plnkr.co/edit/txude6?p=preview) ? I even updated it to match your use case, but basically you can create getters like this:

```Javascript
$scope.getter=function(index){
     return function (row) {
        return row[$scope.headers[index]];
     }
}
``` 

> so this works because the array of heads stores the field. But there are other cases where the array that describes the header isn't an array of objects and it's simply an array of values i.e. ['Q1','Q2','Q3','Q4']

Then why not simply setting your headers as objects ...

```Javascript
$scope.headers=[
{ 
  label:'firstname', 
  property:'firstName', 
  someOtherProp:foo, 
  sort:function(row){ 
    //you can event use this.someOtherProp 
    //...
  }
},
{
    // ...
}

]
```

Again I don't think your suggestion will bring anything or fix any "problem" you can't do at the moment. I only see that it will bring breaking change, meaning all the current user of smart-table will have to update their markup for ... nothing. 

Laurent.R
