### ISSUE TITLE
Move pagination out side Smart table angular using ajax call st-pipe

### ISSUE THREAD

**Issue by KinTran** [lorenzofox3/Smart-Table#508]
I have tried to move pagination out side the table, but how can I put st-pipe="callServer" directive to call ajax,
When I put in wrapper div, It can not catch tableState and call callServer function..
<pre> 
$scope.callServer = function callServer(tableState) {
            //code
            });
        }
    }

</pre>
Any suggestion?
<pre>&lt;<span class="pl-ent">div</span> <span class="pl-e">class</span>=<span class="pl-s"><span class="pl-pds">"</span>table-wrapper<span class="pl-pds">"</span></span> <span class="pl-e">st-table</span>=<span class="pl-s"><span class="pl-pds">"</span>analysisTypes<span class="pl-pds">"  st-pipe</span>=<span class="pl-s"><span class="pl-pds">"</span>callServer<span class="pl-pds">"   </span></span> &gt;
    &lt;<span class="pl-ent">div</span> <span class="pl-e">class</span>=<span class="pl-s"><span class="pl-pds">"</span>table-filter<span class="pl-pds">"</span></span>&gt;
        &lt;<span class="pl-ent">input</span> <span class="pl-e">st-search</span> <span class="pl-e">type</span>=<span class="pl-s"><span class="pl-pds">"</span>search<span class="pl-pds">"</span></span>&gt;
    &lt;/<span class="pl-ent">div</span>&gt;
    &lt;<span class="pl-ent">table</span> <span class="pl-e">class</span>=<span class="pl-s"><span class="pl-pds">"</span>table<span class="pl-pds">"</span></span>&gt;
        &lt;<span class="pl-ent">thead</span>&gt;
            ....
        &lt;/<span class="pl-ent">thead</span>&gt;
        &lt;<span class="pl-ent">tbody</span>&gt;
            &lt;<span class="pl-ent">tr</span> <span class="pl-e">ng-repeat</span>=<span class="pl-s"><span class="pl-pds">"</span>item in analysisTypes<span class="pl-pds">"</span></span>&gt;
                ...
            &lt;/<span class="pl-ent">tr</span>&gt;

            &lt;<span class="pl-ent">tr</span> <span class="pl-e">ng-if</span>=<span class="pl-s"><span class="pl-pds">"</span>!analysisTypes.length<span class="pl-pds">"</span></span>&gt;
                &lt;<span class="pl-ent">td</span>&gt;
                    No data to display.
                &lt;/<span class="pl-ent">td</span>&gt;
            &lt;/<span class="pl-ent">tr</span>&gt;
        &lt;/<span class="pl-ent">tbody</span>&gt;
    &lt;/<span class="pl-ent">table</span>&gt;
    &lt;<span class="pl-ent">div</span> <span class="pl-e">st-pagination</span>=<span class="pl-s"><span class="pl-pds">"</span><span class="pl-pds">"</span></span> <span class="pl-e">st-items-by-page</span>=<span class="pl-s"><span class="pl-pds">"</span>15<span class="pl-pds">"</span></span> <span class="pl-e">st-displayed-pages</span>=<span class="pl-s"><span class="pl-pds">"</span>7<span class="pl-pds">"</span></span>&gt;&lt;/<span class="pl-ent">div</span>&gt;
&lt;/<span class="pl-ent">div</span>&gt;</pre>

**Comment by lorenzofox3** [comment]
Actually it should work as long as st-pipe is on the same element than st-table (which does not have to be a table)

If you provide a running example I may be able to spot your problem
