### ISSUE TITLE
Refresh table when collection change one item for another

### ISSUE THREAD

**Issue by peibol16** [lorenzofox3/Smart-Table#510]
I have a form for edit items that manage a copy of item for prevent table updates before item is updated. If server validation or bbdd save operation fails, the changes not reflected in table. When server response is ok and the item is saved I change old item for the updated item and my watcher fires. But when I change table collection ($scope.tableData in my code), smart table watcher not fires.

This is my watcher:

```javascript
$scope.$watchCollection('models', function(newVal, oldVal) {
					if (newVal === oldVal) {
						return;
					}
					if (newVal) {
						$scope.itemsByPage = 10;
						$scope.tableData = [].concat(newVal);
						$scope.totalCount = $scope.tableData.length;
						$scope.tableIsLoading = false;						
					}
});
```

My little hack is change this watcher in stTable:

```javascript
$scope.$watch(function () {
        return safeGetter($scope);
      }, function (newValue, oldValue) {
        if (newValue !== oldValue) {
          updateSafeCopy();
        }
      });
```

for watchCollection:

```javascript
$scope.$watchCollection(function () {
        return safeGetter($scope);
      }, function (newValue, oldValue) {
        if (newValue !== oldValue) {
          updateSafeCopy();
        }
      });
```

Sorry for my bad english.

**Comment by lorenzofox3** [comment]
maybe https://github.com/lorenzofox3/Smart-Table/issues/205 can help ?

**Comment by peibol16** [comment]
Yes, it works. Thanks
