### ISSUE TITLE
disable auto trigger SmartTable pipe and call it only manually

### ISSUE THREAD

**Issue by ilbarzo** [lorenzofox3/Smart-Table#516]
Hi i am using SmartTable with a custom ajax pipe like in your example.
But I need to trigger the pipe function only manually, such on a 'search button' click, and disable the automatic calling from tableState filters changes.
It is possible?
best regards

**Comment by lorenzofox3** [comment]
you can trigger the pipe function yourself by creating a plugin which will call the pipe() or search() function on a given condition (like button click).
you can overwrite the pipe function with one of you own if you want to block it on a given condition

**Comment by TheSachin** [comment]
Any luck @ilbarzo ?

**Comment by ilbarzo** [comment]
@TheSachin , I have resolved attaching a fake pipe function to table, and use a custom pipe function to load data, called on a click event on a button. the fake function doesn't load data, but store the tableState into a globa var. I hope this help you.
