### ISSUE TITLE
How to Change Date filter format

### ISSUE THREAD

**Issue by bluegreenapple** [lorenzofox3/Smart-Table#517]
Hi,

I have a search input field for filtering my table, where I have a date string collumn formatted as dd/mm/yyyy.

The problem is that for me to search for a date, I have to write in input in the format yyyy-mm-dd, which is the default value.

For example, if you write 25/10/2015, you get nothing. I will only work if you write 2015-10-25

Is there a workaround for that? I do intend to maintain that formatting and it should be compatible to the search input field.

Thanks

**Comment by lorenzofox3** [comment]
you can either:
1) write you own search plugin which will call the search api with the input formatted as you wish
2) replace the default angular filter by your own
3) format you data accordingly before binding it to smart table directive

**Comment by bluegreenapple** [comment]
sry for taking long to answer, that´s gonna help thanks!
