### ISSUE TITLE
Pagination not loading custom template Plunkr Live View available

### ISSUE THREAD

**Issue by mettlus** [lorenzofox3/Smart-Table#520]
http://plnkr.co/edit/apR5Aprh05haCPWExon0?p=info

Custom Pagination not working as expected.

**Comment by mettlus** [comment]
http://plnkr.co/edit/apR5Aprh05haCPWExon0?p=info

**Comment by lorenzofox3** [comment]
your version of smart-table is  too old ... http://plnkr.co/edit/6GT12n?p=preview

**Comment by mettlus** [comment]
You are the MAN!! Thank you
