### ISSUE TITLE
search predicate can only be one level deep?

### ISSUE THREAD

**Issue by btm1** [lorenzofox3/Smart-Table#521]
I know you can do st-search="someProp" but I can't seem to get st-search="someProp.subprop" to work... can you shed some light on whether or not this works?

**Comment by lorenzofox3** [comment]
it will do a nested search. Please refer to the [changelog](https://github.com/lorenzofox3/Smart-Table/blob/master/changeLog.md) version 2.1.0

**Comment by btm1** [comment]
@lorenzofox3 oh perf maybe i just need to update thanks
