### ISSUE TITLE
Selecting with a checkbox instead of row click

### ISSUE THREAD

**Issue by bcoble** [lorenzofox3/Smart-Table#522]
I'm working on a project where we need to select rows in a table via a checkbox instead of just a row click. However, the implementation for this required a bit of hacking and I was wondering if we could try either expose internal variables/functions so I can better extend Smart Table or if there is already an implementation that would allow me to use Smart Table with the checkbox selection.

**Comment by lorenzofox3** [comment]
There is a [dummy example](http://lorenzofox3.github.io/smart-table-website/#section-custom) of it on the documentation website. Otherwise I am not sure to understand what is your exact question, which "internal variables/functions" you have in mind ? the controller api offers a method for selection: you can see an example on the custom plugin mentioned above or check the source code of smart-table

**Comment by lneves12** [comment]
here is an example of a selectable rows with a checkbox that I used in a project http://plnkr.co/edit/c6ddZtiZtP4lasofud59?p=preview. The code I used to keep the selected rows is in this pull request https://github.com/lorenzofox3/Smart-Table/pull/495 (Although I am not sure this was the best aproach for it)

**Comment by bcoble** [comment]
Thanks for the pointer to the dummy example - can't believe I missed that. My approach originally had a checkbox that had the <b>isSelected</b> row parameter as the ngModel. This caused some bugs when I then used the smart table's select method with the watches in order to apply the CSS. So my next approach was to use a dummy variable on the checkbox to trigger the smart table select method, but this was getting ugly with pagination and general data integrity (keeping the dummy variable in sync with the row isSelected).

My questions about 'internal variables/functions' is about exposing more variables like lastSelected and the rows that the controller has. There isn't really a way to get for that data for big custom plugins. However, your custom plugin example looks like a much cleaner way to do it than my ugly code.
