### ISSUE TITLE
Avoid deleting added detail rows upon update of Smart-Table

### ISSUE THREAD

**Issue by MarcMueltin** [lorenzofox3/Smart-Table#524]
Hi there, 

I am very happy about Smart-Table and how it works with angularjs like a charm. :)
However, I have a use-case which I have no idea how to tackle yet. I am quite new to Smart-Table and angularjs though:

I use an RPC (remote procedure call) to initially fill the table with status data of some kind. Next to the RPC, I subscribe to updates of the same data source. Now, when I click on a single row in the table, I dynamically insert another detail row which shows detail information about the clicked item. 
As soon as the subscription delivers new updates, the complete table seems to be create anew, resulting in all opened details rows to vanish. This is not user-friendly so I hope you can tell me how to use your API to avoid this behaviour. I just want the items to be updated, not the complete table to be created anew.

Maybe the way I use the collections is not the right way:
$scope.updatedStatusData = statusDataList;  
$scope.displayedCollection = [].concat($scope.updatedStatusData);

I am happy for any helpful hints. :)

**Comment by MarcMueltin** [comment]
Hey there, 

I would really appreciate an answer. :)
Hope you can help me out here.

Best,
Marc

**Comment by MarcMueltin** [comment]
How about support here?

**Comment by lorenzofox3** [comment]
I am in vacation, I'll see next week ;)

**Comment by lorenzofox3** [comment]
but plunker and co from your side would be a good start !

**Comment by MarcMueltin** [comment]
well, I gave an very explicit explanation at the top. what further information do you need?

**Comment by lorenzofox3** [comment]
Really, you think so ?
are you working on watched collection with a st-safe-src? Or do you load data with custom pipe function ? Or none of it ?
how do you update your items ? Do you work on copies or references ? 

I think your problem is pretty easy to solve (maybe #205), but indeed it requires few efforts on your side. You know if everybody follows the "submit an issue" section of the readme 80% of the tickets would not be created and I would not have to spend 20 min of my vacation time debating on why people should follow the guidelines ;)

**Comment by MarcMueltin** [comment]
I use a watched collection with a st-safe-src attribute. No experience with a pipe function.
The above-mentioned statusDataList is updated by a subscription of the WAMP pub/sub mechanism.

# 1. subscriber pushing new data
# 2. statusDataList array is again filled with updated data
# 3. statusDataList is assigned to the scope variable updatedS

Here is a plunkr-example which almost the exact code as in my project (the variables are named differently): http://plnkr.co/edit/5HfeRpc11lbB7MViISuR?p=catalogue

Hope that helps. What do I need to change?

**Comment by lorenzofox3** [comment]
Hello Marc, 

What I mean by plunker (or jsfiddle, or any similar service) is a  **running** example which reproduces your problem (you can mock interactions with the server by using a fake service as it is done on the documentation website section Pipe/Ajax plugin) 

The plunker you provided lacks some code and does not work at all, how am I suppose to help you if I can't understand/reproduce your issue? 

<img width="1277" alt="screen shot 2015-10-18 at 18 13 10" src="https://cloud.githubusercontent.com/assets/2402022/10563841/8b5e55d6-75c4-11e5-8169-f703393bf090.png">

**Comment by MarcMueltin** [comment]
Hi lorenzo, 

ok, I updated my plunker example to be fully functional and added an ordered list to reproduce my issue:http://plnkr.co/edit/5HfeRpc11lbB7MViISuR?p=preview

I found the problem now: 
It is line 31 in script.js where I create a new statusData array to be filled with the updated data. This newly created array will hold the exact same information as the initial data. 
I thought that as long as the data is the same and just some attributes are updated, the rest will stay the same. 
However, smart-table seems to rely on the initial reference of the statusData array. If I hand over a new array object, the complete table is created anew.
I think that is would you were talking about in issue #205.

Hmm, so I guess need to take the original array and make the checks by myself (delete an item if the id is not present any more, update all other items in the array if the id is the same)?

**Comment by lorenzofox3** [comment]
if you add a true to [this watch](https://github.com/lorenzofox3/Smart-Table/blob/master/src/stTable.js#L60), the reference copy will be updated every time any property of any item of the collection changes, but I advice not doing that and relying on references instead. 

So do you still have the issue, I am not sure to understand ?

**Comment by MarcMueltin** [comment]
OK, I avoided to add true and instead just inspect my statusDataList array on every update if an array element with a certain ID already exists. If not, then I create a new array element and push it to the statusDataList, otherwise I just update the existing array element. 

So you can close this issue. Thanks for your help.
