### ISSUE TITLE
Showing record numbers in current page

### ISSUE THREAD

**Issue by Hypocrite** [lorenzofox3/Smart-Table#525]
Is it possible to show a summary of current pages records with pagination?

Let's say that I want to show 20 items per page. So I could display something like:

Showing records 40 of 60 from total records of 181.

I noticed the links where I could get the total record number but stuggling to get the record numbers from the currently selected page:
https://github.com/lorenzofox3/Smart-Table/issues/327

**Comment by lorenzofox3** [comment]
you can get the pagination details from the tablestate.
I do something like this:

```
   .directive('stSummary', function () {
      return {
        restrict: 'E',
        require: '^stTable',
        template: '<span>Showing [[pagination.start +1]] to [[to]] of [[total]] items.</span>',
        scope: {},
        link: function (scope, element, attr, ctrl) {
          var listener = function (val) {
            scope.pagination = ctrl.tableState().pagination;
            scope.to = Math.min(scope.pagination.start + scope.pagination.number, scope.total || 0);
          };
          scope.$watch(ctrl.tableState(), listener, true);
        }
      }
    })
```

Also I suspect you issue is a duplicate, if you search the issue section you will find more examples

**Comment by Hypocrite** [comment]
Sorry to raise a closed issue but I don't seem to get this working.

First part of the template [[pagination.start +1]] works fine when changing pages but the next parts [[to]] and [[total]] don't work at all.

I am not getting any values there.

**Comment by BraveVN** [comment]
Excuse me @lorenzofox3, I have the same problem about the total number of records, the variable `totalItemCount` only work inside `st-pagination`. In my situation, I need to save its value into my own controller dynamically. How can I do that, how can I implement your directive above ?
Thanks.
