### ISSUE TITLE
Search multiple columns

### ISSUE THREAD

**Issue by dawnofthedev** [lorenzofox3/Smart-Table#527]
Unless things have changed recently I think you can only search on 1 column or all columns. This seems silly, e.g. for a table with multiple valid columns to search on but a lot of useless search columns, e.g. numerical data.

**Comment by lorenzofox3** [comment]
see comments in #196

**Comment by dawnofthedev** [comment]
Thanks, the custom filter solution is working well. Just a suggestion for you to take or leave. It feels a bit overkill to define a filter for this in my app. If you can accept a property to filter on, why not an array of them? I don't feel like that harms the 'minimal' nature of the module. I can't think of any table I've created in the past where I wouldn't have wanted that. But thanks anyways for a great module.
