### ISSUE TITLE
How to search table on non-input event

### ISSUE THREAD

**Issue by dawnofthedev** [lorenzofox3/Smart-Table#528]
Right now I have a horrendous directive that watches a hidden st-search input ng-model and triggers an 'input' event on change. This is because I have very custom search needs and will need to set the search value in code sometimes. Is the only way to make the table searchable (using the st-search directive on an input element)? This would surprise me in such an otherwise powerful grid system.

**Comment by lorenzofox3** [comment]
you can call the table controller [search(input, predicate)](https://github.com/lorenzofox3/Smart-Table/blob/master/src/stTable.js#L94) method from your directive. If you search a little bit Stackoverflow and the issue section you will be able to find some examples
