### ISSUE TITLE
Setting smart-table st-pipe option make makes filtering unuseful

### ISSUE THREAD

**Issue by xshaka** [lorenzofox3/Smart-Table#529]
I have been testing the smart-table module and I have a question: does the st-pipe override the pipe function for the Smart Table controller? I see you use the pipe function to do filtering/sorting functionality, so in that case, aren't we removing those functionalities by setting the st-pipe option? How to set the st-pipe value without losing the filtering/sorting?

**Comment by lorenzofox3** [comment]
You are right, using a custom pipe function overwrite the default behaviour. This is for the use case where you want to move the sort/filter/slice logic to a server instead of the browser. 

There is no way to use a custom pipe function with the default pipe function as it does not make much sens :)

What is your use case ?

**Comment by xshaka** [comment]
My idea is to use pagination on scroll (as my backend database will be Cassandra). From your comment I suspect I will need to transport the sorting/filtering logic to my st-pipe function. If you see a more elegant way to do it, please let me know.

**Comment by lorenzofox3** [comment]
so if I understand correctly you want to have a server side pagination but the sort/filter logic on the client. 

In this case I would not use the custom pipe function but:
1) use st-safe-src attribute to watch the datasource (to update the collection whenever more data is loaded
2) "recreate" the pagination without using the smart-table one. You can for example use [lrInifinteScroll](https://github.com/lorenzofox3/lrInfiniteScroll) to add an event handler whenever the scroll reach the end
and in you event handler you update the watch collection with the loaded data
```Javascript
var page = 1;

this.loadMoreData=function(){
  page++;
  $http.get('/data?page='+page).then(function(result){
     this.rowCollection = this.rowCollection.concat(result.data);
  }.bind(this))
}
```

Even better: you could move the sort/filter logic to your server. I think it is bad user experience to have 
the pagination on the server side and the rest on the client: the result of a sort/filter operation will be different depending on how much data the user has already loaded and this can be misleading

**Comment by lorenzofox3** [comment]
#469
