### ISSUE TITLE
An issue with 'st-sort-default' in v2.1.4

### ISSUE THREAD

**Issue by huyph** [lorenzofox3/Smart-Table#530]
Hi lorenzofox3,

Thanks for your update to the codes. v2.1.4 seems to fix #509 :+1: 

Now looks like there is an issue with `st-sort-default`. The issue is the list looks like it redraws itself on initial load, if i have `st-sort-default="reverse"`. Have a look at this: http://plnkr.co/edit/L0asVofR3hhkkp0X22w2?p=preview

Please assist.

Thanks

**Comment by lorenzofox3** [comment]
Yes  a throttle on sort has been introduced to avoid useless calls (to a server for example)
You can change its default value (300ms) in the config phase with stConfig.
See [here](http://plnkr.co/edit/rZIDUJ?p=preview). I am afraid you'll still have a "blinking" though, even if you set the timeout to 0.
If really, you think that is disturbing, I suggest to delay the display of the tbody to make sure the data has been sorted correctly before you display them.

controller
```Javascript
$scope.isDisplayed=false;
$timeout(function(){$scope.isDisplayed=true},10)
```
html
```Markup
<tbody ng-if="isDisplayed">
<!-- .. -->
</tbody>
```
(and you can embed this logic in a directive if you don't want to repeat yourself)

**Comment by huyph** [comment]
I do find it a bit disturbing. And I think we shouldn't do a static timeout like that because response from server, depending on the size, might need less or more than 10.

What about instead of this line:
```javascript
promise = $timeout(func, throttle);
```

We do it this way?
```javascript
          if (throttle == 0) {
            func();
          } else {
            promise = $timeout(func, throttle);
          }
```

**Comment by lorenzofox3** [comment]
sounds good to me :+1:

**Comment by huyph** [comment]
did another test and realised that. Doing that will stop the thing from being to be sorted in the second time.

It should be this instead: what do you think?
```javascript
          if (throttle < 0) {
            func();
            throttle = stConfig.sort.delay || attr.stDelay;
          } else {
            promise = $timeout(func, throttle);
          }
```
