### ISSUE TITLE
Having issue with filter() and st-multiple-select

### ISSUE THREAD

**Issue by OMGapotato** [lorenzofox3/Smart-Table#532]
filtered = tableState.search.predicateObject ? filter(safeCopy, tableState.search.predicateObject) : safeCopy;

If tableState.search.predicateObject is just 1 string, it filters fine(tested with st-distinct-select) but when I pass an array of strings(for multiple select), it doesn't filter.

**Comment by lorenzofox3** [comment]
Hi,

tableState.search.predicateObject is supposed to be an object, so I don't know what you are referring to ?

**Comment by OMGapotato** [comment]
Sorry I wasn't clear. 

Problem: 'filter(safeCopy, tableState.search.predicateObject)' doesn't seem to work when the object contains an array of string. I'm also using st-distinct-select and querying with an object that contains 1 string works fine. I followed this example(http://plnkr.co/edit/xfjPXZ?p=preview) and it seems to produce similar predicateObjects but the results after filtering are different.

Bottom image is my application. After filtering, DATA_PROTECTION_POLICY should be removed.

<img width="1440" alt="screen shot 2015-10-23 at 9 55 44 am" src="https://cloud.githubusercontent.com/assets/7274604/10696414/482526da-796d-11e5-9c78-a297c85e4487.png">
<img width="1378" alt="screen shot 2015-10-23 at 10 02 16 am" src="https://cloud.githubusercontent.com/assets/7274604/10696415/48280dbe-796d-11e5-91d7-86efc35f0fe7.png">
