### ISSUE TITLE
Aggregation/SUM on the column level

### ISSUE THREAD

**Issue by alvachien** [lorenzofox3/Smart-Table#535]
Is it possible to add the feature about supporting Aggregation/SUM/MAX on the column level? Pardon me if this feature already exists.

If you check with UI-GRID, it do provide those information.
It is quite easy for application developer to build such functionality on the whole table, but it becomes complex when the searching/filtering has been applied on the table. 

Thanks and best regards, Hongjun

**Comment by lorenzofox3** [comment]
Hi, 
I suggest you write a plugin which could get access to table controller api. you can find more details in https://github.com/lorenzofox3/Smart-Table/issues/327

**Comment by alvachien** [comment]
Thanks so much, it helps.
