### ISSUE TITLE
Reseting a single row

### ISSUE THREAD

**Issue by kyrylkov** [lorenzofox3/Smart-Table#536]
I am using `smart-table` to display tabular data. One column of the table is editable.  It is displayed and edited in an input field. Each row has a reset button which is supposed to reset edits made in its only input field to the initial state.

How do I reset values of a single row (input field) when using smart-table?

Specifically what needs to be in the following function:

    $scope.resetItem = function(index) {
      // .....
    };

**Comment by lorenzofox3** [comment]
just change the property without changing the reference
```Javascript
$scope.resetItem = function(index){
  var row = $scope.displayedCollection(index);
 var copy = getCopy(index) // coming from directive, service depending on the strategy you follow
 
 angular.extend(row, copy)
}
```

**Comment by kyrylkov** [comment]
@lorenzofox3 `getCopy(index)` should return a value from `rowCollection` used in `st-safe-src`?

**Comment by lorenzofox3** [comment]
nope a copy of it. you can handle it in several way but the idea will always be the same.
1) save a copy of an item before changing it
2) change any prop of it
3) use angular extend to overwrite the property changed by the ones stored in the copy
