### ISSUE TITLE
Default sorting flicker

### ISSUE THREAD

**Issue by kyrylkov** [lorenzofox3/Smart-Table#538]
I have default sorting specified with `st-sort-default` attribute.  However when the table is getting displayed for the first time after page load, for a moment it appears to be in unsorted order before becoming sorted according to `st-sort-default` attribute

What's the way to avoid this flicker and force the table to be shown in sorted order immediately?

**Comment by kyrylkov** [comment]
@lorenzofox3 Any suggestions?

**Comment by lorenzofox3** [comment]
duplicate https://github.com/lorenzofox3/Smart-Table/issues/530

I need to review pr and push new version
