### ISSUE TITLE
Typeahead ability for st-search

### ISSUE THREAD

**Issue by zackiles** [lorenzofox3/Smart-Table#540]
Using angular-ui bootstraps typeahead for the column input search header, with an AJAX based search.

Selecting an option in the typeahead doesn't initiate a table search, possibly due to a conflict in watchers for the input element.

Is there an easy workaround, or does this require a custom directive?

UPDATE: seems custom custom directive is the only way to go here, closing issue.

**Comment by jusopi** [comment]
@zackiles can you provide some insight on the custom directive you may have implemented?
