### ISSUE TITLE
Filtering table rows from external controls doesn't make pagination being updated

### ISSUE THREAD

**Issue by hnguyenec** [lorenzofox3/Smart-Table#541]
I have several comboboxes outside of table st-table, each combobox has a groupTypeId, and subitems of each combobox have groupIds.

The 'selected' object structured from those comboboxe selections will be used to filter table_rows as
```
<tr ng-repeat="row in displayedRows | filter: { GROUP_IDS: selected } : comparator track by $index" st-select-row="row" st-selected="rowSelected(row)">
       <td ng-repeat="column in columns track by $index" ng-bind="row[column.NAME]"></td>
</tr>

And pagination is
<tfoot>
   <tr>
	 <td colspan="{{columns.length}}" class="text-center">
		 <div st-pagination="" st-items-by-page="itemsByPage" st-displayed-pages="numberOfPage"></div>
	 </td>
  </tr>
 </tfoot>
```

when 'selected' object is changed, the filter will compare GROUP_IDS property of each row (which is not being shown as a column) against 'selected' object

The rows are filtered correctly, accept the pagination is not reflexed according to the filtered result

Any idea or solution is really appreciated.

**Comment by lorenzofox3** [comment]
because you are doing the filtering without using smart-table api.
```Markup
<tr> ng-repeat="row in displayedRows | filter: { GROUP_IDS: selected } : comparator track by $index" </tr>
```

you should rather write a plugin which would call [the search method](https://github.com/lorenzofox3/Smart-Table/blob/master/src/stTable.js#L94)
