### ISSUE TITLE
Keys with special characters not being parsed properly

### ISSUE THREAD

**Issue by samy100** [lorenzofox3/Smart-Table#543]
I have a server side query that retrieves objects which the key names are prefixed with @ or $, for example '@value', '$type', etc. Passing this array of objects to your table somehow doesn't render it at all (i.e. st-sort="@value"). Removing the prefixes beforehand fixes the issue but this is very troublesome and computationally inefficient, more so I don't control the API I'm getting the data from. I can post an example at some point but I'm on my mobile. Pardon my brevity. I would appreciate your feedback on this, thanks!

```Sample Error: [$parse:lexerr] Lexer Error: Unexpected next character  at columns 0-0 [@] in expression [@value].```

**Comment by lorenzofox3** [comment]
difficult to say, it looks like more an issue with angular parser, do you know which smart-directive throw the error ? so yes a way to reproduce would be appreciated

**Comment by samy100** [comment]
@lorenzofox3 

I have added the sample [plunker](http://plnkr.co/edit/zzwx2ITkCWVatQ6Flk1N?p=preview).
I was trying to switch from **trNgGrid** as they suggest, but can't due to the bug on smart table and partially **AngularJS**. As you can see, neither the ```st-search``` or the ```st-sort``` works. (There might be others).
I'll see if I can come up with a solution but maybe it's because invoking ```$parse``` on anything that comes through is not a good idea? Maybe ```attrs.$observe``` might be better.
It's a very common use case when using back-end serializers like **GSON** or **Jackson** since they prefix objects keys with @ and $ in many cases by default.

**Comment by lorenzofox3** [comment]
For the sort you can wrap the predicate with single quotes. For the search it will be trickier, the problem comes from https://github.com/lorenzofox3/Smart-Table/blob/master/src/stTable.js#L99 which is required for deep object search. But anyway I think you going into a difficult path. The point is that 
```Javascript
var object = {
   @foo : 'bar'
}
```
is not valid Javascript
and if 
```
var object = {
    "@foo": 'bar
};
```
then ``object.@foo`` is not and you'll have to use string accessor object['@foo'].

I think your best bet is to create an http interceptor which modify the keys of what the api send you. Or you can override the angular $parse service, but again it seems dangerous. There is nothing I can (or rather I want) to do on smart-table side for your use case, I am sorry

**Comment by samy100** [comment]
@lorenzofox3 
I don't think I'm going a difficult path. Dot accessor is not the single and only way to read data, the string accessor is there for that purpose. It's valid JSON than can be parsed into Javascript Objects. In many situations you can't control the data coming in, even less if it's a stream of data encoded in the way I mentioned above. An $http interceptor or overriding the $parse service is not a solution since it adds way too much overhead and dangers, slowing down the entire application depending on the data load. I would leave the issue open since this limits many use cases where tabular data might come in the way I described above, more especially in enterprise environments where you don't have control over all the resources. I would really really like to use your library since the concept is ideal and the flexibility is great. The previous library I was using [trNgGrid](https://github.com/MoonStorm/trNgGrid) had the same issue and he solved the [problem](http://moonstorm.github.io/trNgGrid/release/#/TestSpecialSymbols) probably using a different approach but it still worked. Since trNgGrid is now deprecate and the author recommended yours I would really like to give it a shot. Please reconsider, thanks!

**Comment by lorenzofox3** [comment]
If you say so ... 
I am wondering how you do something as simple as 
```
<li ng-repeat="row in collection | @value:'test'">{{row | json}}</li>
```
?

anyway you can trick the $parse service 
```
<input st-search="this['@value']" placeholder="Search for Value" class="input-sm form-control" type="search" />
```

[plunk](http://plnkr.co/edit/pfQk6T?p=preview)

**Comment by samy100** [comment]
Thanks for spending the time! It would be great to actually document in a corner how to use smart-table with keys like that.

Typically in libraries and a lot of angularJS directives I've gotten it to work just like you mentioned by putting quotes around the key. For example, I did tried quotes on ```st-sort``` and it wasn't working (hence the panic), but I guess I didn't noticed it was working. 

As to:
```
<li ng-repeat="row in collection | @value:'test'">{{row | json}}</li>
```
I've never done that, if you mean filtering out on an ng-repeat, here's what I do:
```
<li ng-repeat="row in collection | filter:{'@value': 'test'}">{{row | json}}</li>
```

As for the ```st-search```, thanks for figuring out how to trick the parse service like that. The behavior seems consistent between 1.3 up to 1.5.
