### ISSUE TITLE
If (value == undefined), make it count as zero

### ISSUE THREAD

**Issue by JeffreyRoosendaal** [lorenzofox3/Smart-Table#546]
When you have a column, lets say 'visitors', with the following rows: *2, 45, 33, 10, undefined, undefined*

It gets sorted as:
**asc:** 2, 10, 33, 45, undefined, undefined
**desc:** undefined, undefined, 45, 33, 10, 2

Which is, especially for desc, not what you want.

I've created a getter function to solve this:
````scope.getter = {
        visitors: function (value) {
            return value.visitors || 0
        }
    }````

Maybe it's an idea to make this default behaviour?

**Comment by lorenzofox3** [comment]
Thanks a lot, but I prefer to rely on default angular filters and let people do what they want for corner cases and custom behaviour. 

Thanks a lot though, this issue might be a reference for later questions !
