### ISSUE TITLE
stPipe not called when table is inside a directive

### ISSUE THREAD

**Issue by shrayasr** [lorenzofox3/Smart-Table#550]
Hi, 

We have a case where the pipe function that makes a HTTP call and gets a page is dependent on a set of inputs. The pipe function doesn't make sense to be executed till those inputs are provided. 

How we've managed to do this so far is to have a `load` variable on the scope which is checked in the pipe function. If `load` isn't set to `true`, the pipe function doesn't proceed. The `load` variable is set to true only when all inputs required for the call to be made, are on the scope. Following this we manually call the pipe function. The reason we are able to do this and manually fire the pipe function again is because on the initial call of the pipe function, we store `tableState` on the scope and pass that in when we make the first call.

Now, we are having a need to abstract this very same component into the directive. The expectation was that it would work straight away but then I noticed that the pipe function **isn't** called when the table was placed inside a directive. I've set up a [Plunker](http://plnkr.co/edit/rMsAfXWzQG17sTMGgB7H?p=preview) to demonstrate this. 

I might be _completely_ wrong in my approach and if you could suggest a better / the right way to go about this, I am all for trying it. 

Additionally do let me know if you need any more information from my side. I will update the plunker as per your requests.

Thanks again for open sourcing this great library. I understand that it will take up a lot of your time and resources. Cheers :beers:

**Comment by lorenzofox3** [comment]
It looks like scoping issue (and scope/controller creation)
I suggest you forget you link function and use a directive controller (which also add the benefit of making your component extensible)
http://plnkr.co/edit/o4qn1g?p=preview

**Comment by shrayasr** [comment]
> It looks like scoping issue (and scope/controller creation)

So should I leave the issue open then? Can I make it better in anyway that would be helpful? One of the things I tried is to edit the source and add a small `console.log` statement in the `postLink` function of the `stPipe` directive. The `console.log` message is being printed which means that the control is getting there but there seems to be some issue when calling `ctrl.pipe()` in the next line. I will try and look into this code as well. 

Hope this helps?

> I suggest you forget you link function and use a directive controller (which also add the benefit of making your component extensible)
> http://plnkr.co/edit/o4qn1g?p=preview

Yes this works but the problem I have with this is that angular docs advise us to use controllers within directives only when functionality needs to be exposed to another directive that `require`s it. 

I don't mind using it as a workaround for now though :+1:

**Comment by lorenzofox3** [comment]
when I said "issue" I meant problem related to the specific requirement of you use case. I don't think there is an issue with smart-table here. 

> Yes this works but the problem I have with this is that angular docs advise us to use controllers within directives only when functionality needs to be exposed to another directive that requires it.

Not sure this advice is actually relevant. When you expose something on scope, inner components will likely have access to this property anyway. Using directive controller allows you to explicit expose an api for extension purpose and is closer to the definition of component angular 2 is promoting (so likely be easier to migrate)

**Comment by shrayasr** [comment]
> when I said "issue" I meant problem related to the specific requirement of your use case. I don't think there is an issue with smart-table here.

I see. Sorry for the misinterpretation. 

> Not sure this advice is actually relevant. When you expose something on scope, inner components will likely have access to this property anyway. Using directive controller allows you to explicitly expose an api for extension purpose and is closer to the definition of component angular 2 is promoting (so likely be easier to migrate)

Allright, makes sense. :+1: 

---

If I may, I have a follow up question though: Why is the function is given to the `st-pipe` attribute **not** called when it is part of the directive's `link` specification but called when it is part of the `controller`? Is there some sort of difference here?

**Comment by lorenzofox3** [comment]
I am not sure, it is related to how angular creates scope and from which other scope it prototypically inherits depending on whereas it is part of an isolated scope, a controller, etc. It is a bit of wizzardy for me and I try to avoid the usage of scope as much as possible

**Comment by shrayasr** [comment]
I see. Appreciate your response :+1:

Many thanks again on the library. Cheers :beers:
