### ISSUE TITLE
Export to Excel or PDF

### ISSUE THREAD

**Issue by asimnzr** [lorenzofox3/Smart-Table#551]
Hi,

I went through different demos of Smart-Table and it looks impressive, but I have a requirement of exporting table data to Excel or PDF. So, is it possible to achieve export functionality directly or indirectly using some plug-in or not?

Thanks in anticipation.

**Comment by lorenzofox3** [comment]
You can use whatever plugin you want, and wrap it in a directive which would access smar-table api to get the currently filtered transactions

something like that: 
```Javascript
app.directive('stExport',['whateverCSVExportPlugin', function(csv){
   return {
     restrict:'E',
     require:'^stTable',
     template:'<button ng-click="export()"></button>',
     link:function(scope, element, smartTable){
         scope.export = function(){
             var filtered = smartTable.getFilteredCollection();
             csv(filtered); 
         }
     }
   }
})
```

```Markup
<table st-table="foo">
   <thead>
      <tr>
          <th><st-export></st-export></th>
      </tr>
  </thead

</table>

```

**Comment by diegomotta** [comment]
a directive 

.directive('stExport',function(){
  return {
    require:'^stTable',
    link:function(scope, element, attr,ctrl){
      element.bind('click',function(){
        alert(ctrl.getFilteredCollection().length);
      })
    }
  }
});

retrieve length = 0, using st-pipe=mc.callServer

**Comment by diegomotta** [comment]
how set setFilteredCollection?????

**Comment by m2pathan** [comment]
Can you please tell me some plugins ("whateverCSVExportPlugin") which we can use with smart-table.

**Comment by lorenzofox3** [comment]
@m2pathan google is programmer's friend ! http://ngmodules.org/modules/ng-csv
