### ISSUE TITLE
Fire event when selecting rows to display data on a  Modal 

### ISSUE THREAD

**Issue by calvinKG** [lorenzofox3/Smart-Table#552]
Hi guys, 

I want to show selected row that on a modal. I was able to display the selected data on my browser console. 

 // fired when table rows are selected
    $scope.$watch('displayedCollection', function(row) {
        // get selected row
        row.filter(function(r) {
            if (r.isSelected) {
                console.log(r);
                //alert(r.campaignName);
            }
        })
    }, true);

**Comment by lorenzofox3** [comment]
see comments at the end of https://github.com/lorenzofox3/Smart-Table/issues/34 thanks
