### ISSUE TITLE
Any interest in a row highlight feature?

### ISSUE THREAD

**Issue by jogjayr** [lorenzofox3/Smart-Table#553]
For a project I'm currently working on, I needed to implement a row highlighting feature. "How is this different from select" you might ask? While they sound similar, they have slightly different (and complementary) use cases:

1. Only a single row can be highlighted at a time. A good example of when this might be useful is in a master-detail view: the table holds a list of records and the currently highlighted record's details are displayed in a separate view.
2. When you need a combination of a master-detail view, as well as multi-selection to operate on the table's records. Eg. A list of records that can be selected individually or all at once with checkboxes, and that can be highlighted one at a time to see details about them.

With an additional directive (that I'm writing but can't release on Github because it's internal company code), one could also use highlight to implement keyboard navigation on the table (up/down to highlight rows)

The highlight feature sets a flag called `isHighlighted` on the model. It can also set the class `st-highlighted` (this directive is currently in my internal project but can be factored out into Smart-Table).

I have working code for this in my fork: https://github.com/jogjayr/Smart-Table and would be very happy to make an example Plunkr, write tests and documentation etc and make a nicely formatted pull request, if this feature is desirable in the main project. Please let me know.

**Comment by lorenzofox3** [comment]
thanks you for sharing this, but I don't think this should be part of the core library and could work as an external plugin

**Comment by Tedko** [comment]
Just wondering how did you implement this keyboard navi function? I am working on that now

**Comment by jogjayr** [comment]
You could do something like this:

1. Make a directive that requires stTable (like the examples provided on the website)
2. The directive listens for keyboard events and takes appropriate action (highlight next, de-highlight previous etc)

You can check out my fork to see how highlighting is done
