### ISSUE TITLE
Working example of smart-table that is IE 8 compatible?

### ISSUE THREAD

**Issue by chaumette** [lorenzofox3/Smart-Table#554]
It's been impossible to find an angular grid that works with IE8...anyone have an example implementation that is compatible with this old browser? Working with both Boostrap and MVC.

**Comment by lneves12** [comment]
I am using smart-table in a project that's need compatibility with IE 8 and it is working.. The only thing i had to be careful was to use de directives as attributes and not elements. Ex: <div st-pagination></div> instead of <st-pagination></st-pagination>

**Comment by chaumette** [comment]
Do you mind sharing Source code?
What versions of angular and smarttable are you using?

Thanks,
Chaumette

**Comment by lneves12** [comment]
Sorry, It is private code, I can't share it with you. But I am using the angular version 1.2.28, It is the last relase that supports IE8.

**Comment by chaumette** [comment]
No problem. Are you using bootstrap as well? What version of jquery?

**Comment by lorenzofox3** [comment]
to be closed ?
