### ISSUE TITLE
problem with st-sort with dynamic columns

### ISSUE THREAD

**Issue by Olivparis93** [lorenzofox3/Smart-Table#555]
Hi,

I use 2 tabs, the first work well but not the second. I have a problem to sort my data with smart table, the global search work well for both cases.

$scope.reports1 = [{fieldsName:['number1','number2','number3'],
                records:[{number1:10,number2:8,number3:40},
                         {number1:1,number2:4,number3:55},
                         {number1:8,number2:10,number3:35},
                         {number1:8,number2:11,number3:44}]}];

$scope.reports2 = [{fieldsName:['number1','number2','number3'],
                records:[{dyn_array:{number1:10,number2:8,number3:40}},
                         {dyn_array:{number1:1,number2:4,number3:55}},
                         {dyn_array:{number1:8,number2:10,number3:35}},
                         {dyn_array:{number1:8,number2:11,number3:44}}
                  ]}];

Here the plunk :http://plnkr.co/edit/AGQqugefnv4RzYTxH8ua?p=preview

My columns are dynamic, that's why I need to create a new dyn_array because I will use others static columns like ID that I don't want to show.

An idea ?

Thanks for your help

**Comment by lorenzofox3** [comment]
the problem is that your data structure does not match what you display
an item (row) is 
```
{dyn_array:{number1:"foo",number2:"bar"}}
```

whereas you ask to sort by "number1" which is property that does not exist on your rows.

You have to specifically provide a getter function to tell orderBy filter on which nested property you want to sort.

see [plunker](http://plnkr.co/edit/ojbbZK?p=preview)

**Comment by Olivparis93** [comment]
Thank you very much !

**Comment by Olivparis93** [comment]
Hello Lorenzo,
I have a new problem but this time on search, i have tried many things but nothing work. On the same plunker, I would like to search only on a specific column, what should I put with st-search ?
I have tried the same fonction but a parse error occured.
