### ISSUE TITLE
can't watch the changes of st-safe-src when one of the row changed

### ISSUE THREAD

**Issue by javeme** [lorenzofox3/Smart-Table#557]
can't watch the changes of st-safe-src when one of the row changed(such as: remove a row,and then append a new row).
https://github.com/lorenzofox3/Smart-Table/blob/master/src/stTable.js#L49

**Comment by lorenzofox3** [comment]
pipe should be triggered 
1. [if first item of the collection changes](https://github.com/lorenzofox3/Smart-Table/blob/master/src/stTable.js#L53) apparently it is necessary if the collection belongs to an external service. Not sure it is actually useful but people offered it as a solution for their problem
2. [if the length of the watched collection changes](https://github.com/lorenzofox3/Smart-Table/blob/master/src/stTable.js#L61) (your use case ?)
3. [if the reference (var pointer) changes](https://github.com/lorenzofox3/Smart-Table/blob/master/src/stTable.js#L68)

So I am not sure why you are facing a problem ? maybe you could follow the "submit an issue" guidelines and provide some way to reproduce your issue. 

PS: if your use case is the update of an item, I suggest you have a look at [this issue](https://github.com/lorenzofox3/Smart-Table/issues/205)

**Comment by javeme** [comment]
my use case:
![Uploading changes-update-not-watch.png…]()

![Uploading changes-update-not-watch.png…]()

**Comment by javeme** [comment]
![changes-not-watched2](https://cloud.githubusercontent.com/assets/9625821/11177817/467ddff6-8c83-11e5-84cd-bc3f85489f82.PNG)

My use case:
There are two tables, table-1 shows the selected item(at most only one item), table-2 shows the items that can be selected. when we click an item in table-2, we need to move it to table-1, and remove the original item from table-1 to table-2.

```
scope.action.addFlavor = function(flavor) {
  scope.canSelectFlavors.remove(flavor);
  scope.canSelectFlavors.extend(scope.selectedFlavors);
  scope.selectedFlavors = [flavor];
};
```

**Comment by lorenzofox3** [comment]
can you please provide a running example (plunker) ?
