### ISSUE TITLE
st-sort-default causes $digest already in progress error

### ISSUE THREAD

**Issue by huyph** [lorenzofox3/Smart-Table#559]
This changes in v2.1.5, `scope.$apply(func);` causes `$digest already in progress` error

If throttle is set to a negative number. This change causes some weird behaviours like the sorting class is not added to the dom.

**Comment by lorenzofox3** [comment]
I have spotted any issue, can you share some plunker ?

**Comment by huyph** [comment]
http://plnkr.co/edit/88DEEr?p=preview 
(with v2.1.5)

Two issues can be spotted here:
1) `$digest already in progress` error in console log
2) First name column which has initial sorting set, does not have the correct arrow.

**Comment by lorenzofox3** [comment]
it looks like it happens only when used with st-sort-default

**Comment by stanleyxu2005** [comment]
The issue does get fixed when you use a safeApply like this
```
function safeApply(scope, fn) {
    (scope.$$phase || scope.$root.$$phase) ? fn() : scope.$apply(fn);
}
```

**Comment by stanleyxu2005** [comment]
@lorenzofox3 Someone might call this approach bad practice. But using `$timeout(func, 0)` still see the flicker. I believe people want to set `stConfig.sort.throttle = -1` know what they are doing. I'm strongly +1 for fixing this issue asap.

**Comment by lorenzofox3** [comment]
> I checked the change history. The first patch was simply func(). I don't know why you've changed it to scope.$apply(func) later.

Because if the change in the sort state comes from a click then angular does not kick the digest cycle. I think a better fix would be to have the apply [here](https://github.com/lorenzofox3/Smart-Table/blob/master/src/stSort.js#L49) and let the func() as it was before

**Comment by stanleyxu2005** [comment]
Thanks and I'm looking forward to a proper fix. This annoying issue troubles me for quite a long time....

**Comment by lorenzofox3** [comment]
I am about to push the change ;)

**Comment by RobzInadE** [comment]
Speaking of this, when i call `ctrl.search...` from another directive that has a require on `stTable`, my `$watch`'s is not getting looked through in the digest cycle. When i later click somewhere on the page, they are ran through like usual. The watches are registered in my routing controller (basically the controller for the page), and as far as i understand, stTable does not introduce any new scopes. Any idea on what the error could be?

I also noticed that my watches doesn't get triggered when doing an `st-search` search. Any one else had this problem?

Thanks again for all the help on my previous questions.
Regards
