### ISSUE TITLE
How to use Smart-Table for grid display?

### ISSUE THREAD

**Issue by ramang16** [lorenzofox3/Smart-Table#563]
Hi,

When I searched for best angular module for table/grid display, I found Smart-Table as the best one. In Smart-Table website there are lot of examples on displaying data in tabular format, but nothing on how to display in grid style.

I have a requirement to display set of images in table/grid style. In table style, I should be able to display them with pagination and in grid format I need all of the images in a single page.

Does anyone know how to use Smart-Table to display data in grid format? Any help would be appreciated.

Thanks

**Comment by lorenzofox3** [comment]
Hello, 
smart-table being declarative you should be able to use whatever markup you want and whatever style you want to have a grid-like display. I don't see any issue here, maybe you could submit your question to more appropriate forums/chats/mailing list to get some help.

Thanks,

Laurent
