### ISSUE TITLE
Searching in table with asynchronious data doesnt work well

### ISSUE THREAD

**Issue by MotherCake** [lorenzofox3/Smart-Table#564]
Hi
I have a table with data from the database. The result of st-search is wrong. It shows rows where doesn't match the pattern.

Here is some code:
```html
<table id="table-modal-user" class="table table-hover table-striped" st-table="displayed" st-safe-src="tableUser">
                                        <thead>
                                            <tr>
                                                <th colspan="2">
                                                    <input st-search="name" placeholder="search" class="input-sm form-control" type="search" />
                                                </th>
                                                <th colspan="7" class="text-right">
                                        <ul class="list-inline table-items">
                                        </ul>
                                        </th>
                                        </tr>
                                        <tr class="active">
                                            <th class="st-sort" st-sort="name">name</th>
                                            <th class="st-sort" st-sort="company">company</th>
                                            <th class="st-sort" st-sort="customerCare">customerCare</th>
                                            <th class="st-sort" st-sort="role">role</th>
                                            <th class="st-sort" st-sort="lastLogin">lastLogin</th>
                                        </tr>
                                        </thead>
                                        <tbody class="l-valign-middle">
                                            <tr ng-repeat="element in displayed">
                                                <td>{{element.name}} <br> {{element.userName}}</td>
                                                <td>{{element.company}}</td>
                                                <td>{{element.customerCare}}</td>
                                                <td>{{element.role}}</td>
                                                <td>{{element.lastLogin}}</td>
                                            </tr>
                                        </tbody>
</table>
                                </div>
```

The result contains always the right rows, but it shows further another rows which doesn't match.
Does anyone face the same problem?

Greets

**Comment by lorenzofox3** [comment]
I don't see anything wrong, can you set up a plunker ?

**Comment by MotherCake** [comment]
Hi
i tried to set up a plunker but i cant get the data into the table. Without the stSafeSrc attribute it works. Maybe you can take you look.
http://plnkr.co/edit/jT9dUwxxDUGG8Sn8Vetx?p=preview

**Comment by lorenzofox3** [comment]
you forgot to include smart table module in your app ...

```Javascript
var app = angular.module('plunker', ['ui', 'smart-table']);
```

[plunk](http://plnkr.co/edit/eGW8AX?p=preview)

**Comment by MotherCake** [comment]
Oh no. sorry for that.
I try to reproduce the actual problem

**Comment by MotherCake** [comment]
I updated the plunker.

if you search for "al" they find one person. As you can see there was no "al" in the shown columns. But there is the username attribute in the json file for that person. They have the value "benutzer.gs@alalal.com". I think thats the reason why this person are listed.

If I change the filter to 
 <input st-search="name" class="form-control" placeholder="global search ..." type="text" />
the result is the same.

**Comment by lorenzofox3** [comment]
You are right, the global search is exactly the same as calling the default angular filter with global predicate ($) so it will run against all the properties of each row (not only the displayed ones). If you want  to work on a subset of the properties you can search the issue section, some issues deals with the problem.

If you use a specific predicate like "name" you should not have any problem. I have bumped the smart-table version of [you plunk](http://plnkr.co/edit/t0x5Fa?p=preview) and it seems to work as expected

**Comment by MotherCake** [comment]
Thx for your help.
