### ISSUE TITLE
Multiple level of subheaders

### ISSUE THREAD

**Issue by anoopov** [lorenzofox3/Smart-Table#566]
Hi,

I have been using custom table for past two year for my product. I have one doubt.
Is it possible to bring multiple level of sub headers to custom table. I Know its possible to upto two levels. 

Main Heading
        Sub Header 1
              Sub Header 2
 
 
Thanks in advance. We are using latest version of smart table

**Comment by lorenzofox3** [comment]
you have the exact same possibilities that native html tables offer

**Comment by anoopov** [comment]
Thank you
