### ISSUE TITLE
How to implement global search outside the table?

### ISSUE THREAD

**Issue by ainilife** [lorenzofox3/Smart-Table#568]
I have look through the document and found that all search inputs are inside the directive 'st-table'。 My problem is How to implement a gloabl search by using a input outside the table?

**Comment by eliavm** [comment]
Vote up

**Comment by lorenzofox3** [comment]
you need to make a plugin to communicate between outside and inside:
```Javascript
app.directive('foo',function(){
    return {
       require:'^stTable'
       scope:{
          foo:'=',
          //and other  var etc
       },
       link:function(scope,element,attr,table){
           scope.$watch('someVar',function(val){
               table.search('somePredicate',val)
           })
       }
    }
})
```

```Markup
<input ng-model="blah"/>
<table st-table="tableList" foo="blah>
</table>
```

if you search a little bit you'll find more examples

**Comment by lorenzofox3** [comment]
note st-table does not have to be on the table element you can put it on a wrapping element

**Comment by mavrick** [comment]
Hey,

I've found a few things.

1 - I had to change my plugin directive to:

```javascript
app.directive('stSearchOutside', function()
{
    return {
       require:'^stTable',
       scope: {
          stSearchOutside:'='
       },

       link: function(scope, element, attr, ctrl)
       {
           scope.$watch('stSearchOutside', function(val)
           {
            return ctrl.search(val);
           });
       }
    }
});
```
2 - I had wrap the ``<table>`` in an ``ng-if="items.length"`` if loading the data in via ``$http``.


```html
<input type="search" placeholder="search" ng-model="search">
<div ng-if="items.length">
<table st-table="items" st-search-outside="search" class="table table-striped">
...
</table>
</div>
```

**Comment by douglas-treadwell** [comment]
You might find the branch I'm trying to pull in helpful.

https://github.com/lorenzofox3/Smart-Table/pull/607

**Comment by Tedko** [comment]
@mavrick Thx for your example!

**Comment by zipper01** [comment]
table.search('somePredicate',val)---Is this a typo for table.search(val, 'somePredicate')? As for version 2.1.8, at smart-table.js line 142 it is `this.search = function search (input, predicate)`. It take me quite a while to figure this out.
