### ISSUE TITLE
Search data based on button click in smart table

### ISSUE THREAD

**Issue by IamNikunj** [lorenzofox3/Smart-Table#570]
Hello friends,

I want to search data based on button click. Right now I am facing difficulty to do that. Can you have any suggestions or ideas, how to perform it?

Thanks in advance.

**Comment by lex-em** [comment]
Hi, I have same problem. Do you resolve it?

**Comment by IamNikunj** [comment]
Yes,

 

What I did is I have made a directive in angular js

 

<div class="crawlhealthshowcontent-right" st-custom-search>

<input type="text" class="crserachinput" placeholder="Page URL" ng-model="stCustomSearchValue" ng-keyup="$event.keyCode == 13 ? OnSearch() : null" />

<button type="button" class="bluebtn" st-custom-search-column="SourceUrl" ng-click="OnSearch()">Search</button>

</div>

 

then at JS side

 

module.directive('stCustomSearch', function () {
      return {
          require: '^stTable',
          link: function ($scope, $element, $attrs, $stTable) {
              $scope.stCustomSearchValue = '';
              $scope.OnSearch = function () {
                  $stTable.search($scope.stCustomSearchValue.trim(), $attrs.stCustomSearchColumn)
              }
          }
      };
  });

 

and it works fine for me.

Let me know if you find any issue.

 

Thanks,

Nikunj Soni

**Comment by IamNikunj** [comment]
Okay.

**Comment by smohammedyasin** [comment]
Paging not showing based on result. what i missed?
