### ISSUE TITLE
Smart Table - Refresh Issue With Change In Data Binding.

### ISSUE THREAD

**Issue by Superman4545** [lorenzofox3/Smart-Table#572]
Ok, I am new to this...   I can get the data to display initially, however, when I try to filter the data, the table is not being updated with the new data.  I have verified, using the developer tools, that the data object that I am setting to the smart table binding objects has the "new" data in it, however, the screen does not refresh.  I have spent about 2 hours last night, and about 4 hours today, trying different things, and still no success.  

FYI -- I have tried dong the .push(data) in place of just setting the object = data;  Same results. 

Here is the HTML for the table part 

        <table st-table="displayedCollection" st-safe-src="rowCollection" class="table table-striped table-bordered table-hover input-sm">
          <thead>
            <tr>
              <th st-sort="inventoryTypeName">Inventory Type</th>
              <th st-sort="model">Year / Make / Model</th>
              <th st-sort="vin">VIN</th>
              <th st-sort="miles">Miles</th>
              <th st-sort="stockNumber">StockNumber</th>
              <th st-sort="inventoryDate">InventoryDate</th>
              <th st-sort="dealerCost">DealerCost</th>
              <th st-sort="reconditioningCost">ReconditioningCost</th>
              <th st-sort="otherCost">OtherCost</th>
              <th st-sort="sellingPrice">SellingPrice</th>
            </tr>

          </thead>
          <tbody>
            <tr data-ng-repeat="row in displayedCollection">
              <td>{{ row.inventoryTypeName }}</td>
              <td>{{ row.model }}</td>
              <td><a class="text-info ng-binding" ui-sref="app.inventories.edit.basic({inventoryId:inventory.inventoryId})">{{ row.vin }}</a></td>
              <td>{{ row.miles }}</td>
              <td>{{ row.stockNumber }}</td>
              <td>{{ row.inventoryDate | date : 'MM/dd/yyyy' }}</td>
              <td>{{ row.dealerCost }}</td>
              <td>{{ row.reconditioningCost }}</td>
              <td>{{ row.otherCost }}</td>
              <td>{{ row.sellingPrice }}</td>
            </tr>
          </tbody>
        </table>

Here is the JS

(function () {
  'use strict';

  angular
      .module("app")
      .controller('inventoryCtrl', ['$scope', '$state', '$filter', 'inventoryResource', 'inventorySearchResource', InventoryCtrl]);

  function InventoryCtrl($scope, $state, $filter, inventoryResource, inventorySearchResource) {
    
    $scope.rowCollection = [];
    $scope.displayedCollection = [].concat($scope.rowCollection);

    $scope.inventoriesearchResource = inventorySearchResource;
    $scope.filters = {
      searchBy: 'Search By',
      searchFor: ''
    };

    if ($state.params.searchBy && $state.params.searchFor) {
      $scope.filters.searchBy = $state.params.searchBy;
      $scope.filters.searchFor = $state.params.searchFor;
    }

    $scope.setSearchBy = function (serachBy) {
      $scope.filters.searchBy = serachBy;
    };

    $scope.filterData = function () {      
      var searchBy = ($scope.filters.searchBy) ? $scope.filters.searchBy : '';
      var searchFor = ($scope.filters.searchFor) ? $scope.filters.searchFor : '';

      if (searchBy && searchFor) {
        inventorySearchResource.query({ searchBy: searchBy, searchFor: searchFor },function (data) {
          $scope.rowCollection = data;
          $scope.displayedCollection = [].concat($scope.rowCollection);
        });
      }
      else {
        inventoryResource.query(function (data) {
          $scope.rowCollection = data;
          $scope.displayedCollection = [].concat($scope.rowCollection);
        });
        
      }

    };

    $scope.addNewInventory = function () {
      $state.go("app.inventories.edit.basic");
    };

    $scope.addNewInventory = function (param) {
      $state.go("app.inventories.edit.basic", { inventoryId: param.inventoryId })
    };

    $scope.filterData();

  }
})();

**Comment by lorenzofox3** [comment]
I am not sure what is wrong (there is a lot of noise: router, service etc). You should try to set up a plunker going step by step until something breaks.

You can use http://plnkr.co/edit/UiPpWX9nUzRXopayLOxY?p=preview as a starter, as it is working as expected

**Comment by Superman4545** [comment]
Thanks, I will do as you suggested…  Appreciate the reply…

**Comment by Superman4545** [comment]
I was able to fix the issue..  The problem was in the markup and NOT the controller.   I had accidentally specified the controller twice on two separate DIVs.. I corrected this and it works great.  Thanks again for your help..

**Comment by lorenzofox3** [comment]
:+1:
