### ISSUE TITLE
st-pipe caused display issue

### ISSUE THREAD

**Issue by chaitujil** [lorenzofox3/Smart-Table#574]
Hi, I am using smart table like below. The issue is when I add st-pipe I can successfully call my controller function but I don't see data in my table. I see an empty table. When I remove it I see my collection. Is there something obvious I am missing here? 

```
<div class="container-fluid" st-table="queueCtrl.displayedCollection"
        st-safe-src="queueCtrl.collectionQueueItems" st-pipe="queueCtrl.setSortColNOrder">

        <div class="row">
            <div class="col-md-12">
                <div>
                    <table
                        class="table table-striped table-bordered table-condensed">
                        <thead>
.
.
.
```

**Comment by chaitujil** [comment]
My ctrl code:

    var vm = this;
    vm.setSortColNOrder = setSortColNOrder;
function setSortColNOrder (tableState) {
    curSortColumn = tableState.sort.predicate;
    if (tableState.sort.reverse === false) {
        curSortOrder = "asc";
    } else {
        curSortOrder = "desc";
    }
}

**Comment by lorenzofox3** [comment]
mmh, if you use custom st-pipe you don't need st-safe-src, as your custom pipe function is supposed to provide the dataset matching a given tablestate in place of the built in logic. In your case, your custom pipe function does not provide any data: you must be doing something wrong here
