### ISSUE TITLE
Adding a search condition using controller variables

### ISSUE THREAD

**Issue by Seiifer** [lorenzofox3/Smart-Table#575]
Is it possible to add a search condition using controller variables ?

For example, I draw my table lines like this :

``` html
<tr ng-repeat="request in r.displayedRequests" ng-if="r.isInArray(r.selectedDevelopers, request.developers)
    && (request.status != 'DEL' && request.status != 'CAN')">
  <td>{{request.id}}</td>
  <td>{{request.projectTitle}}</td>
  <td>{{request.description | limitTo: 120}}{{request.description.length > 120 ? '...' : ''}}</td>
  <td>{{request.regions}}</td>
  <td>{{request.requestDate}}</td>
  <td>{{request.status}}</td>
  <td>{{request.statusDate}}</td>
</tr>
```

This is working, only the lines matching my conditions are displayed but the `r.displayedRequest` is not updated, which makes the pagination fail.

I have read about `st-set-filter` but this would change all the `st-search` behavior. 

In my case I want to keep using `st-search` as it is. (Using it to filter either by global search or column search through different text inputs)

Is it possible to use a custom search function for one specific (hidden) column  for example ?

**Comment by lorenzofox3** [comment]
I believe you could use hidden input (they need to be in the dom however otherwise the directive will not trigger) 
Another thing you could do is add a directive which specifically call search api. 
```
directive('defaultSearch',function(){
    return {
       require:'^stTable',
       scope:{
          // some external conditions ? 
        },
       link:function(scope,element,attr, table){
           table.search(predicate, defaultValue);
       }
    }
})
```

**Comment by Seiifer** [comment]
By using a hidden input, you mean set its value according to my condition and not showing it ?

If so I  don't think I can because I don't want to be restricted to a text search. 

I wanna check the value of a field of the current line and also check if another field (containing an array) contains at least one element of another scope array.

About the directive, I'm not sure how to implement it.

`table.search(predicate, defaultValue);` is the usual search used  by `st-search` ?

How do I handle the condition in the scope object of the directive ? I'm checking the value of my scope variable and what action should I make if the condition is or isn't true ?

**Comment by lorenzofox3** [comment]
> By using a hidden input, you mean set its value according to my condition and not showing it ?

yes

> If so I don't think I can because I don't want to be restricted to a text search.

it does not matter, you should be able to use other input type

> I wanna check the value of a field of the current line and also check if another field (containing an array) contains at least one element of another scope array.

If you have more sophisticated use case I guess the best approach is for you to call directly the table api with whatever predicate you want with whatever value you want depending on whatever condition you want :) 

> About the directive, I'm not sure how to implement it.
you are correct behind the scene st-search directive call this method to update the table state and refresh the displayed collection accordingly to the new table state
https://github.com/lorenzofox3/Smart-Table/blob/master/src/stTable.js#L101.

It helps you providing the right input and right predicate in a declarative way. 
 
> How do I handle the condition in the scope object of the directive ? I'm checking the value of my scope variable and what action should I make if the condition is or isn't true ?

I am sorry, I can't do you work but the idea is to create a directive which requires stTable as the provided example above so you can call the search api with the right input and right predicate depending on whatever logic, binding, etc you want to

**Comment by matthewh** [comment]
@Seiifer 

Try instead of st-search. This will let you bind the input to a model and but still work with smart-table.
```
.directive("mhSearch", ['stConfig', '$timeout','$parse', function (stConfig, $timeout, $parse) {
    /* Like st-search, but relies on the value of ng-model to trigger changes.
     * Usage:
     * <input type="text" placeholder="Search..." ng-model="myCtrl.searchParams.search" mh-search="search" />
     */
    return {
        require: ['^stTable', 'ngModel'],
        link: function(scope, element, attr, ctrls) {
            var tableCtrl = ctrls[0],
                modelCtrl = ctrls[1];
            var promise = null;
            var throttle = attr.stDelay || stConfig.search.delay;

            function triggerSearch() {
                var value = modelCtrl.$modelValue;

                if (promise !== null) {
                    $timeout.cancel(promise);
                }

                promise = $timeout(function () {
                    tableCtrl.search(value, attr.mhSearch || '');
                    promise = null;
                }, throttle);
            }

            scope.$watch(function () { return modelCtrl.$modelValue; }, triggerSearch);
        }
    };
}])
```

**Comment by michahell** [comment]
It is not fully clear how to use the directive above: include the directive, replace the default st-search input (you could hide it, for example) and then use the ```ng-model``` property to set the value you wish to search for. the attribute value of ```mh-search``` reflects the **table property** you wish to search for. **leave empty to search all table fields.**

**Comment by ChristianMMacy** [comment]
@michahell Thank you for taking the time to explain @matthewh 's directive. It saved me some time and was truly appreciated!

**Comment by michahell** [comment]
@ChristianMMacy you're welcome :) good luck!
