### ISSUE TITLE
st-search initialization resets filter values

### ISSUE THREAD

**Issue by martende** [lorenzofox3/Smart-Table#576]
if table has more than 2 search fields they can not be initialised correctly . Only last st-search field passes to filter and the other will be reseted. 

stSearch.js: 

        attr.$observe('stSearch', function (newValue, oldValue) {
          var input = element[0].value;
          if (newValue !== oldValue && input) {
            ctrl.tableState().search = {};
            tableCtrl.search(input, newValue);
          }
        });

**Comment by lorenzofox3** [comment]
Can you please provide a way to reproduce, looking at the [st-persist example](http://plnkr.co/edit/jAjf0l?p=preview), it seems allright

**Comment by martende** [comment]
I have used 2 ng-model with select http://plnkr.co/edit/jpFii40wCKJvIzEPtx4X?p=preview

			<select st-search="firstName" placeholder="firstname" class="input-sm form-control"
			  ng-model="filterVariable1" ng-options="a for a in [1,2,3]"
						 type="search"/>
			<select st-search="firstName" placeholder="firstname" class="input-sm form-control"
			  ng-model="filterVariable1" ng-options="a for a in [1,2,3]"
						 type="search"/>

But from your example I can't reproduce this case :( . When I jump to ' attr.$observe('stSearch', ' handler select has not value yet and "input" variable is empty . But in my home case where I have found the problem select is already initialised from model here and I jump to ctrl.tableState().search = {};

**Comment by martende** [comment]
http://plnkr.co/edit/rKQM94gh808qTVEwxVlL?p=preview

On this case first select value is reseted. (Both should be True by initialisation)

**Comment by lorenzofox3** [comment]
I am sorry but I don't understand your issue, the predicate you set to the st-search do not even exist. Can you please remove extra noise and extra directive and just put code related to smart table and what is the expected result. 
You filter directive seems to add select options based on an attribute, I actually don't understand how one value could be selected by default.
I think you better follow the stPersist strategy, set an initial tablestate and let smart table update the input values
