### ISSUE TITLE
preset filters

### ISSUE THREAD

**Issue by devwheel** [lorenzofox3/Smart-Table#578]
I have a page that saves filters with cookies upon leaving the page.  When I return to the page I put the filter values back.  Smart-Table does not understand programmatic setting of filtered values.  Is this something that there is a workaround for?

**Comment by lorenzofox3** [comment]
you need to restore the table state not the input values (smart table will do it for you) you can have a look at the [stPersist](http://plnkr.co/edit/ekwiNt?p=preview) example for more details
