### ISSUE TITLE
Pagination reset to first page after data updated

### ISSUE THREAD

**Issue by stanleyxu2005** [lorenzofox3/Smart-Table#581]
I have a table with 1000 rows. I use pagination to show 10 rows per page. In background there is a periodically server call (5 seconds) to fetch data updates. When I switch to page 3 and after 5 seconds, after the new data is coming, the table will go back to page 1. How to fix this?

**Comment by lorenzofox3** [comment]
https://github.com/lorenzofox3/Smart-Table/issues/477 ...
don't update the reference to the safe source

**Comment by stanleyxu2005** [comment]
Shall I not use safe source at all? But why there is a safe source?

**Comment by stanleyxu2005** [comment]
https://github.com/lorenzofox3/Smart-Table/commit/d1b715e52e9de62b0455ffe7f43201df9e24056b
stTable.js line 64
`+          tableState.pagination.start = 0;`

I need to use `stSafeSrc` otherwise data will not be rendered very wired. But this line will cause a page reset to 0.

**Comment by lorenzofox3** [comment]
yes and that is the expected behaviour. If you don't want the page to be reset don't change the reference.
```Javascript
scope.rowCollection = newData;
```
but append the data. 

```Javascript
scope.rowCollection.concat(newData)
```

**Comment by stanleyxu2005** [comment]
I fully understand your point now. So I should modify existing rowCollection, if I don't want to reset the current pagination position.

But this has a shortcoming. I have to check all existing code and change `rowCollection = newData` with something like `angular.extend(rowCollection, newData)`. I think it will be better, if this is done in smart-table internally.

Another thing, that I might open an issue: If I have 5000 records, the initialization of the table will be very slow.
```
<table st-table>...
<tbody>
<tr ng-repeat="row in rows track by $index">
...
</tr>
</tbody>
<tfoot>
<tr st-pagination..></tr>
</tfoot>
</table>
```

All records will be rendered first and then show only 10 rows by pagination?

**Comment by lorenzofox3** [comment]
>  So I should modify existing rowCollection, if I don't want to reset the current pagination position.
yes

> I have to check all existing code and change rowCollection = newData with something like angular.extend(rowCollection, newData)

I am sorry for you maybe [this](http://unix.stackexchange.com/questions/112023/how-can-i-replace-a-string-in-a-files) can help ...

> I think it will be better, if this is done in smart-table internally. 

I don't think so. Actually I would be curious to know how a variable assignment could sometimes be considered as a new data source (this actually make sens) and sometimes as the same datasource but with other data ...
Anyway this discussion starts to be a bit annoying, please consider that is the way it works and it will unlikely change.

> Another thing, that I might open an issue: If I have 5000 records, the initialization of the table will be very slow.

I would likely close it quickly. Even without speaking about smart table, try to load 5000 items in memory then sort/filter them and display a slice fo it, I am not sure it would be efficient either, you would need virtualization etc. 
Load you data by chunk so the browser can breathe, or even better: use a server side logic ...

**Comment by stanleyxu2005** [comment]
>> I think it will be better, if this is done in smart-table internally.

> I don't think so. Actually I would be curious to know how a variable assignment could sometimes be considered as a new data source (this actually make sens) and sometimes as the same datasource but with other data ...

Yes, it can be a difficult task to handle variable assignment, because smart-table has only a changed array variable no further context is provided. I'm think, if you can give an option of "resetting pagination to 0" like this:
```
// stTable.js
      $scope.$watch(function () {
        return safeGetter($scope);
      }, function (newValue, oldValue) {
        if (newValue !== oldValue) {
          if (stConfig.resetPaginationOnNewData) {
            tableState.pagination.start = 0;
            updateSafeCopy();
          } else {
            try {
              updateSafeCopy();
            } catch (ex) {
              tableState.pagination.start = 0;
              updateSafeCopy();
            }
          }
        }
      });
```

Question: Assume there is only one row data changed in `rowCollection`, does it have any performance gain by updating the existing `rowCollection` rather than replacing the reference to a `rowCollection1`?

**Comment by rkeshmir** [comment]
> Load you data by chunk so the browser can breathe, or even better: use a server side logic ...

Let's suppose there is a solution like _Springboot paging and sorting_ interface, in each request server receives the requested page size and number of element to be displayed and optionally the column you want to sort by and its sort order. Then what should we have on client site? We just need to know the number of total elements to calculate the number of pages. 
Now the question is why do we need a safe collection? why do people want to go back to the first page when it changes as it comes from the server side and we shouldn't keep it on client side?

**Comment by dhavebarsalote96636677** [comment]
Hello Mr. @lorenzofox3, 

`Nope, in most of the case people want to go back to first page if the data source change (cf issue linked)`

I am not with them who want's to go back to the 1st page when the data source changed by interval. I have this scenario where I happen to use st-search and then the filtered data displayed 2 pages then the item that i was looking for is on the next page, with that I have to navigate to the next page and when the data source refreshed, I turned back to page one which is so annoying. So, even though others want it this way at least you can provide a solution to "others" who needs this feature like me.
