### ISSUE TITLE
 Is there any way to use ui-select as a search option?

### ISSUE THREAD

**Issue by lucianoreis** [lorenzofox3/Smart-Table#583]
Ex: http://nowup.me/vkSIJ/
Imagine list all the user records X or Y
I tried adding st-search = "field" and type = "search" but what is sent to the filter is what I type in the field and not what I select.
In the example of the image it sends the string "mar" and not the 2988 ID that was selected.

**Comment by lorenzofox3** [comment]
maybe you'll need to manually call the search api from a directive which would require the table controller

**Comment by lucianoreis** [comment]
I called the data and select the ID as needed, http://nowup.me/3Orlu/ and move to one input but can not send the value of the last input to the filter

**Comment by lorenzofox3** [comment]
a way to reproduce ... ? (like plunker etc)

**Comment by lucianoreis** [comment]
http://plnkr.co/edit/DRw8Z7RdZU8pW682itfz?p=preview
Here I have the ui-select which will be used as filter option, as you can see when a person selects the input side is filled with the ID to be searched.

**Comment by GodzillaHe** [comment]
@lorenzofox3 i have not a clear idea  to manually call the search api. Can you show me please? :)
