### ISSUE TITLE
stPagination should be able to show totals, and # currently displayed

### ISSUE THREAD

**Issue by RobzInadE** [lorenzofox3/Smart-Table#585]
Hey guys,

I'm using mart-table more and more on my pages, but now, after deciding to write my own pagination template (much like the style of the Gmail pagination), i feel like there are some crucial features missing. My template looks something like this:

![Image of own pagination](http://i.imgur.com/1Ftq3em.png)

So what I'm currently missing is a nice way of getting the **"number of total items in the table"** (Yes I've seen that you can extend stPagination and watching the filtered collection)
And another crucial bit of info is the ability to display **"current # of items on page"**, (something like 1 to 10 of 245 if current page size is 10 and I'm not on the last page. Last page needs to be able to show 240 - 245 of 245)

Any others that miss these features?
Regards

**Comment by stanleyxu2005** [comment]
You can try `stSummary` from the [discussion](https://github.com/lorenzofox3/Smart-Table/issues/440)

**Comment by RobzInadE** [comment]
Hey @stanleyxu2005 , I did try, however when i use st-search to narrow my results, `currentPage` does not get updated and therefor does not cause a re-calculation of my `stRange.from / stRange.to`.

**Comment by stanleyxu2005** [comment]
Maybe my modification can solve your problem.
https://github.com/stanleyxu2005/dashing/blob/master/src/tables/sortable_table/sortable_table.js#L122
