### ISSUE TITLE
Cannot sort assynchronous data

### ISSUE THREAD

**Issue by marquesarthur** [lorenzofox3/Smart-Table#586]
Hi,

I am using st-table with assinchronous data and I cannot sort it. I saw the "st-safe-src" attribute warning, though I do not have a static collection, and I am not so sure how to sort my data.

Currently, when I try to sort the table by a sortable column, I get the following error: 

TypeError: displaySetter is not a function
    at StTableController.pipe (smart-table.min.js:172)
    at StTableController.sortBy (smart-table.min.js:133)
    at angular.js:18460
    at e (angular.js:5815)
    at angular.js:6092

As an example the code snippet causes the described error.

```html
<table st-table="backlogData()" class="table table-striped">
   <thead>
      <tr>
         <th>Bug Status</th>
         <th st-sort="total">Total</th>
      </tr>
   </thead>
   <tbody>
      <tr ng-repeat="row in backlogData()">
         <td>{{row.bugStatus}}</td>
         <td>{{row.total}}</td>
      </tr>
   </tbody>
</table>
```
The full example is available at:
> https://github.com/marquesarthur/python-bugzilla-report-api/
Just clone the repo and open report/report.html

**Comment by lorenzofox3** [comment]
I think the $parse service could not parse the "backlogData()", use an array rather than a function call
