### ISSUE TITLE
Is there a way to get item index while pagination is on?

### ISSUE THREAD

**Issue by qiaoruntao** [lorenzofox3/Smart-Table#588]
I have found "$index" can give the item index in current table.
But it isn't the index in the whole table when there are pagination.
It is like 1-10, 1-10, 1-10 and forever.
So is it possible to get the index in the whole table like 1-10, 11-20, 21-30 etc?

**Comment by stanleyxu2005** [comment]
You might probably need to call `st-page-change="myFunc(newPage)"` 
Please check the [discussion](https://github.com/lorenzofox3/Smart-Table/issues/438)

**Comment by qiaoruntao** [comment]
Solved, st-page-change is great! 
Maintain a variable in controller to store the current pageNum, update it by myFunc and finally use it in the td column like [[$index+1+(ctrl.pageNum-1)*ctrl.pageSize]] to get the item index in the whole table. 
And hope "stCurrentPage" property could be released soon, this would be even more convenient.

**Comment by stanleyxu2005** [comment]
Yes. This works well if data is not sorted. 

But if the data is sorted by particular column, you will need to find correct records by yourself. I don't know how to get the selection (showing records of current page).

**Comment by qiaoruntao** [comment]
Sorry, I don't understand your detailed situation. Maybe you need to reload data while sort the table?
In my situation the table is able to sort too. It is implied by st-sort and the all data is stored in the st-table.
And the sort result is right...

**Comment by stanleyxu2005** [comment]
Okay, I will check.
