### ISSUE TITLE
After replacing data, the pagination does not get rendered

### ISSUE THREAD

**Issue by firecentaur** [lorenzofox3/Smart-Table#593]
Hi there, I have a button in my UI that when pressed, 
calls a function and by passing in the tableState state which then the server and refreshes the table data,

then, I update the table data by:
scope.displayed = response.newData;
tableState.pagination.numberOfPages = response.numberOfPages;

The table data is refreshed, but the page 1, page 2, page 3 icons are not rendered.

**Comment by lorenzofox3** [comment]
can you please provide a running example ?
