### ISSUE TITLE
Share our plugins

### ISSUE THREAD

**Issue by ninjaonsafari** [lorenzofox3/Smart-Table#595]
Hi

Could we somehow share our extensions for your plugin?
I think it would be great, then some people don't have to rewrite stuff already implemented.

**Comment by lorenzofox3** [comment]
yes create a plunker (freeze it) and submit a pull request on the example section of the documentation website

**Comment by lorenzofox3** [comment]
much appreciated

**Comment by ninjaonsafari** [comment]
@lorenzofox3 i cannot find the documentation source. 
But heres the [plunker](http://plnkr.co/edit/NJDkitbfcuEQcEpUy94U?p=preview)  and a [gist](https://gist.github.com/ninjaonsafari/ac25593730b103bf6034)

**Comment by lorenzofox3** [comment]
Thanks

**Comment by Tedko** [comment]
@ninjaonsafari  hey. currently I am using your defaultSelection and try to use it by index (such as $scope.selectedRow = 120, instead of $scope.selectedRow = item); is that possible?

**Comment by ninjaonsafari** [comment]
@Tedko nope it's not possible yet.

**Comment by ninjaonsafari** [comment]
@Tedko i've updated the [gist](https://gist.github.com/ninjaonsafari/ac25593730b103bf6034) and the [plunkr](http://plnkr.co/edit/ImstnnRdtpaL4z1XQGG2).

**Comment by Tedko** [comment]
@ninjaonsafari  Thx!
