### ISSUE TITLE
sorting multiple columns

### ISSUE THREAD

**Issue by nikisbing** [lorenzofox3/Smart-Table#599]
nuub alert! Sorry but I'm new to angular and feeling particularly stupid having to ask this, but ...

I don't seem to be able to sort by more than one column - am I missing something? <cringe>

**Comment by lorenzofox3** [comment]
you are right you can't. On the other hand I am not sure what to except from a functional perspective. What priority would you give to a column if you click on multiple headers ? multiple times ? etc
What you can do however is set the st-sort property as an array to define multiple property to sort with when you click on a given header

**Comment by nikisbing** [comment]
@lorenzofox3 thanx for the st-sort property suggestion.
I would expect the columns clicked to appear in st-sort as an array (in the order clicked) so I can add them to a sql order-by clause. Clicking a column multiple times would cycle through asc/desc/off.
I'm unable to push this forward atm so please close this if it falls outside smart-table remit. I'm new to github so didn't close the issue myself as I wasn't sure if it may be rude to do so.

**Comment by chrisuehlinger** [comment]
@lorenzofox3 I ran into this too (I'm trying to have my "Name" column sort by last name, then first name). I tried passing in the field names as an array like this:

`st-sort="[lastName, firstName]"`

but now it isn't sorting by anything at all. Is there anything I need to change about my syntax to make this work?

**Comment by brenkeys** [comment]
I think you are missing single quotes in your array elements.
