### ISSUE TITLE
please can support card view?

### ISSUE THREAD

**Issue by techbirds** [lorenzofox3/Smart-Table#600]
thanks.

**Comment by lorenzofox3** [comment]
what is a card view ?

**Comment by techbirds** [comment]
<img width="848" alt="cb891171-5815-421e-9750-ae6467e0c384" src="https://cloud.githubusercontent.com/assets/3411696/12381504/1b8fdf96-bdc6-11e5-88c3-f697b390ef55.png">

**Comment by lorenzofox3** [comment]
smart-table is declarative, so you can use whatever markup/layout you want

**Comment by techbirds** [comment]
thanks.
