### ISSUE TITLE
sort data with CJK (Chinese Japanese Korean)?

### ISSUE THREAD

**Issue by Tedko** [lorenzofox3/Smart-Table#601]
Hey, 
I am trying to sort data with `st-sort` and seems like its not working with CJK (or working poorly)

my code:

```html
<table st-table="display_worker_list" st-safe-src="worker_data.worker_list" class="table table-striped" >
	<thead>
	<tr>
		<th st-sort="sortGetter.logname">用户名</th>
		<th st-sort="sortGetter.realname">姓名</th>
		<th st-sort="sortGetter.task_submitted">完成任务</th>
		<th st-sort="sortGetter.total_time_used">总用时</th>
		<th st-sort="">总盈利</th>
	</tr>
	<tr>
		<th colspan="6"><input st-search="" class="form-control" placeholder="搜索 ..." type="text"/></th>
	</tr>
	</thead>
	<tbody>
	<tr st-select-row="worker" st-select-mode="single" ng-repeat="worker in display_worker_list">

		<td>{{worker.logname}}</td>
		<td>{{worker.realname}}</td>
		<td>{{worker.stat[data.taskSelect].task_submitted}}</td>
		<td>{{(worker.stat[data.taskSelect]["total_time_used"]).toFixed(5)}}</td>
		<td>{{}}</td>
		<td>
			<button type="button" ng-click="removeItem(worker)" class="btn btn-sm btn-danger">
				<i class="glyphicon glyphicon-remove-circle">
				</i>
			</button>
		</td>
	</tr>
	</tbody>
	<tfoot>
	<tr>
		<td colspan="6" class="text-center">
			<div st-pagination="" st-items-by-page="15"></div>
		</td>
	</tr>
	</tfoot>
</table>
```
and js:

```js
         var sortGetter = {
             logname: function (value) {
                 return value.logname;
             },
             realname: function (value) {
                 return value.realname;
             },
             task_submitted: function (value) {
                return value.task_submitted;
            }
         };
```

Here, logname is in ASCII, so it works fine 

![2016-01-20 4 59 59](https://cloud.githubusercontent.com/assets/6687437/12468315/46760adc-bf97-11e5-9ca1-495bc4898823.png)

however, the realname filed contains cjk, and  it works poorly:

![2016-01-20 5 01 40](https://cloud.githubusercontent.com/assets/6687437/12468377/daebbe46-bf97-11e5-9db6-f07d028b5008.png)

Seems like it is sorted by unicode? Did you implement your sort func in `.directive('stSort', ['stConfig', '$parse', '$timeout', function (stConfig, $parse, $timeout)`?

I suggest that for cjk,
Chinese: sort by pinyin, such as 安（an）should before 宝（bao）, and all ascii go first.
Japanes: by [五十音図](https://en.wikipedia.org/wiki/Goj%C5%ABon) all ascii go first and then あいうえお順
Korean: similar above. by [Hangul](https://en.wikipedia.org/wiki/Hangul_consonant_and_vowel_tables) 

If I have enough time I could create a pr for Chinese first. Please double check this issue.

**Comment by Tedko** [comment]
Also this problem occurs in many other language. (if i make any mistake correct me)

**Comment by Tedko** [comment]
http://plnkr.co/edit/rxkD5see4YJAqTlFpljp?p=preview

**Comment by timonwong** [comment]
The sort is not related to SmartTable, actually it's a internalization problem.

In backend programming language, you can use ICU's collator to do that, and sorting in the backend will give you better compatibility, because:
Though we have [ECMA-402](http://www.ecma-international.org/ecma-402/1.0/), but with very limited browser support (IE 11+): http://caniuse.com/#feat=internationalization

In your example, you can change your comparator:
```
var collator = new Intl.Collator("zh-CN");
var standardComparator = collator.compare;
```

The code above is a very simple demonstration, though, in real world example, it may be more complex.

**Comment by lorenzofox3** [comment]
Yes I am afraid you'll have to run your own sort logic as the angular default one is alpahNumeric (based on unicode I guess) . See st-set-order. I thinkg there was an issue a while back about accentuated characters which could be somehow related but I can't find it back

**Comment by Tedko** [comment]
@lorenzofox3  So I had made a simple js lib https://github.com/Tedko/tkJSPinyin for sorting Chinese.

**Comment by lorenzofox3** [comment]
great thanks 
:+1:

**Comment by lorenzofox3** [comment]
so can this issue be closed ? I label it to quickly find it if anyone is in need

**Comment by Tedko** [comment]
yeah, sure. Thx!
