### ISSUE TITLE
Suggested way to support in-line editing?

### ISSUE THREAD

**Issue by alvachien** [lorenzofox3/Smart-Table#602]
Searched around the StackOverflow, only got the following Plunker as an example: http://plnkr.co/edit/QQQd2znPqh87X2oQONd9
and the question:
http://stackoverflow.com/questions/12016566/editable-datagrid-in-angularjs

Due to the fact the In-line editing section has been removed in the Smart-Table's website, is there any suggested way to support in-line editing, such as using directive?
Sample code would be much more help.

Thanks very much!
Alva

**Comment by lorenzofox3** [comment]
you can use whatever inline editing directive you want as smart-table is fully declarative 
https://github.com/tameraydin/ng-inline-edit this one could work as many others. There are few examples across different issues of this repository, you just have to search a little bit
