### ISSUE TITLE
sort function run into problem

### ISSUE THREAD

**Issue by sendreams** [lorenzofox3/Smart-Table#603]
<table st-safe-src="tbUsers" st-table="users" class="table table-striped">
                            <thead>
                                <tr>
                                    <th st-sort="id">ID</th>
                                    <th st-sort="name">姓名</th>
                                    <th st-sort="email">邮箱</th>
                                    <th>操作</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr ng-repeat="row in users">
                                    <td>{{row.id}}</td>
                                    <td>{{row.name}}</td>
                                    <td>{{row.email}}</td>
                                    <td><button>修改密码</button><button>更改用户组</button></td>
                                </tr>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="4" class="text-center">
                                        <div st-pagination="" st-items-by-page="4" st-displayed-pages="7"></div>
                                    </td>
                                </tr>
                            </tfoot>
                        </table>

function UsersCtrl($scope, $http, myService){  

```
var promise = $http.get('/auth/user/list');
promise.success(function (data, status) {
    $scope.tbUsers = data.content;
});
```

};

i click the header it does't show sort icon, and sometimes does not sorting. but something can sorting.

the code is so simple, and i think the reason maybe use the server side data. please check it.
i use version 2.1.6

**Comment by lorenzofox3** [comment]
Do you use st-safe-src attributes?

**Comment by sendreams** [comment]
i have allready use st-safe-src attribute.

**Comment by lorenzofox3** [comment]
I think it should work fine. 
for the sort arrow display please refer to https://github.com/lorenzofox3/Smart-Table/issues/259
you might bump into localization issue with Chinese characters https://github.com/lorenzofox3/Smart-Table/issues/601 but this is not really related to smart-table

**Comment by Tedko** [comment]
Just let you know Smart-Table may not working properly with MooTool (so dont include that).
The sorting icon should be written in css, such as
```css
.st-sort-ascent:before{
	content: '\25B2';
}

.st-sort-descent:before{
	content: '\25BC';
}
```

**Comment by lorenzofox3** [comment]
It is already part of the documentation, If you feel this is not clear enough you can click on the "improve this documentation" button where you'll be able to edit the content and submit a pull request. 
Thanks

**Comment by lorenzofox3** [comment]
in order to sort Chinese you can have a look at [this library](https://github.com/Tedko/tkJSPinyin)
