### ISSUE TITLE
st-sort-default="true" is broken with stPersist

### ISSUE THREAD

**Issue by sdebacker** [lorenzofox3/Smart-Table#604]
It seems that this commit caused the bug, but not sure: https://github.com/EventMobi/Smart-Table/commit/96aa98c9aec9e1fca5bd20cefc4567b92401dda7

**Comment by lorenzofox3** [comment]
wrong repo ?

**Comment by sdebacker** [comment]
Yes, wrong repo, but I still have the bug with Smart-Table > 2.1.3 <=2.1.6. Does 2.1.7 fix it?
