### ISSUE TITLE
Error when toggling states that contain the stTable directive. 

### ISSUE THREAD

**Issue by mattymess** [lorenzofox3/Smart-Table#610]
I have a few states that use the `stTable` directive and when I toggle from the default state to a second state, angular is throwing the error: `Error: [$compile:ctreq] Controller 'stTable', required by directive 'stSelectRow', can't be found!`

I was able to recreate the issue on Plnkr using the most recent versions of `ui-router`, `smart-table`, and `angular`, although I'm running Angular 1.2.28 in production.

Please see [this plnkr](https://embed.plnkr.co/A196NxNEvC0k1EnsxMj3/) for an accurate recreation of the issue.

**Comment by lorenzofox3** [comment]
There were couple of bugs in ui-router at some point 
https://github.com/angular-ui/ui-router/issues/832 and https://github.com/angular-ui/ui-router/issues/857 They seem to have been fixed, I am going to see on smart table side if there is anything wrong

**Comment by lorenzofox3** [comment]
seems that removing st-select-row solve the problem, so there might be an issue with this directive

**Comment by douglas-treadwell** [comment]
@mattymess if you have any ideas about what might be causing this problem please let me know... I'm investigating it but I don't see any obvious cause.  I do notice that you're loading ui-view with some default content and then replacing it with table2 in your plunkr... Perhaps try this with one parent view with a blank ui-view and two separate child views, and see if the problem continues?

**Comment by Fredo182** [comment]
would changing the require to the following fix it?

require: '?^stTable'
