### ISSUE TITLE
select filter in strict mode filtering doesn't work on documentation website

### ISSUE THREAD

**Issue by indr** [lorenzofox3/Smart-Table#611]
The strict select filter on the [documentation website](https://lorenzofox3.github.io/smart-table-website/#filter-strict-mode) doesn't work. Are there any known issues or is there already an investigation ongoing?

**Comment by kirkone** [comment]
This only works in Google Chrome. I tested it with Internet Explorer and Edge.
I have no clue why this is the case.

**Comment by kirkone** [comment]
Hi,
I got this working!
After having a look here:
https://mark.zealey.org/2015/07/08/angular-smart-table-and-drop-down-select
I saw in the example that there is a " st-input-event="change"" missing.

This is my working Markup:

```
<select st-search="valueToFilter" st-input-event="change" st-delay="0">
  <option ng-repeat="filter in controller.filters" value="{{ filter.filter }}">
    {{ filter.name }}
  </option>
</select>

```

**Comment by ricard33** [comment]
Perfect. Thank you. It works for me too, just adding  `st-input-event="change"` in my declaration.
