### ISSUE TITLE
server called twice initially when using pipe

### ISSUE THREAD

**Issue by Venex** [lorenzofox3/Smart-Table#617]
I have a table with data using st-pipe and the server returns a paged result (just enough items for one page and the total count)
I found out my server is called twice initially. 

When debugging I see pipe is called and after that, slice (function splice), which again call's pipe.

This would seem to be an overhead

**Comment by lorenzofox3** [comment]
yes you are right. However there is already an issue opened https://github.com/lorenzofox3/Smart-Table/issues/388. Unfortunately I have not found the time to fix it ... A quick workaround is to use the $http cache or a flag you use in your pipe function (the problem should only happen when the table is initialized)

**Comment by Venex** [comment]
Thank you for your reply and sorry I did post a duplicate
