### ISSUE TITLE
Setting table header's preferred sort order when clicking over it

### ISSUE THREAD

**Issue by nmrm** [lorenzofox3/Smart-Table#618]
Which directive to use to set table header's (th) preferred starting sort order when clicking over it?

**Comment by lorenzofox3** [comment]
st-sort-default ? I don't understand the question actually. But I think if you read the documentation, you should find your answer

**Comment by nmrm** [comment]
I mean a directive that let's me specify when I click over a table header which order is best showed first: ascending, then descending, then none; or descending, then ascending, then none.
That feature would be nice.

**Comment by lorenzofox3** [comment]
ah ! Lately merged :) it is by default ascending, then descending then none.
you can change it to descending first using the attribute ``st-descending-first=true`` (https://github.com/lorenzofox3/Smart-Table/blob/master/dist/smart-table.js#L348).

**Comment by nmrm** [comment]
ah ! perfect.. great feature. thanks.
