### ISSUE TITLE
Custom filtering with serach outside table

### ISSUE THREAD

**Issue by SushantKadam008** [lorenzofox3/Smart-Table#621]
Hi,
I need to filter my smart table with values from a text-box outside the smart table.
Something like this 
http://plnkr.co/edit/UkUypF?p=preview 

But i need to select the column first on which to apply filtering and then pass the value in textbox.

Is there any sample demonstrating the same ?

**Comment by lorenzofox3** [comment]
https://github.com/lorenzofox3/Smart-Table/issues/220, https://github.com/lorenzofox3/Smart-Table/issues/541, Please note that I can't do you research job on every issue you open,

Thanks for being considerate toward open source project communities ...

**Comment by SushantKadam008** [comment]
Hi,
Extremely sorry for the inconvenience.
I used smart table for the first time and needed few functionalities on high priority and hence posted it before doing much research.

Thanks a lot for your help :)
