### ISSUE TITLE
Updating model does not update table data

### ISSUE THREAD

**Issue by jaredmahan** [lorenzofox3/Smart-Table#623]
I am using smart tables in my angular app and I have run into an issue.

I am using the following:
- using `st-table`
- using `st-safe-src`
- Sorting and Search is working properly

When I update the underlying model data using the following code the change is not reflected in the table data for the smart table.

`$scope.modelList[index] = dataFromService;`

I have found that if the first item in the modelList is updated the table data is updated and my table is updated, but if the index is greater than 0 then the update is not pushed to the table data.

I have attached an image of the data and can attempt to create in plunkr if need be, but wanted to try this first to see if there was an easy resolution.

In the image below you can see that the second item in the array was updated in the model but the changes did not sync over to the table data.
![smart-table-issue](https://cloud.githubusercontent.com/assets/1036698/12901491/af0546fa-ce81-11e5-8670-64916f99d0a3.png)

**Comment by lorenzofox3** [comment]
Hi,
you are right, for perf reason. Update your data without updating the reference. Please refer to https://github.com/lorenzofox3/Smart-Table/issues/205

**Comment by jaredmahan** [comment]
Awesome thanks for the update that fixed my issue!
