### ISSUE TITLE
[pagination] Add $event parameter to selectPage() scope method

### ISSUE THREAD

**Issue by bigb6611** [lorenzofox3/Smart-Table#624]
In selectPage method body, adding the typical 

`if ($event) {
  $event.preventDefault();
}`

prevents the pagenavigating to anchor if ng-href="#" directive is used on pager buttons in a custom template. The use of this directive displays the cursor mouse pointer instead of the text mouse pointer, which is desirable.

**Comment by lorenzofox3** [comment]
preventing event bubbling at library level is not a good idea, you never know how the user wants to handle the event. use a directive which prevent it instead. [example](http://qloo.github.io/angular-prevent-default/angular-prevent-default.html)
