### ISSUE TITLE
Navigation on rows with arrow keys

### ISSUE THREAD

**Issue by chriso86** [lorenzofox3/Smart-Table#626]
Hi there,

I was wondering would it be possible to extend this to navigate rows using arrow keys?

If not or if this is something I will need to struggle with javascript for then please -1 this and I will figure it out.

I haven't seen anything covering this for smart table as of yet.

Kind regards.

**Comment by chriso86** [comment]
Just saw the issue raised before now, apologies for not being too attentive.

Closing this.

**Comment by lorenzofox3** [comment]
thanks :)
