### ISSUE TITLE
Custom sort on column click

### ISSUE THREAD

**Issue by SushantKadam008** [lorenzofox3/Smart-Table#628]
Hi,
I have a table with status column as follows:

![image](https://cloud.githubusercontent.com/assets/7605326/12989217/b2547594-d104-11e5-8862-6c74c151c8b6.png)

I need to change the default sort behaviour for this column.
When I click on the status column, the order should get reversed in the order All paid, Due and Delayed. and when I click the column again I should get Delayed,due and All paid.

Can a custom function be called on column header click ? Please help

**Comment by Tedko** [comment]
Yes, several ways. 
such as

```js
        var sortGetter = {
            logname: function (value) {
                return value.logname;
            },
            realname: function (value) {

                var pinyin = new Pinyin(false, 'lower');
                var pinyinOut = pinyin.getFullChars(value.realname);
                if (pinyinOut) {
                    pinyinOut = pinyinOut.replace(/\s+/g, '');
                }
                return pinyinOut;
            },
        };
```
and the html should be
```h5
        <th st-ratio="20" st-sort="sortGetter.logname" st-sort-default="true">用户名</th>
        <th st-ratio="16" st-sort="sortGetter.realname">姓名</th>
```

**Comment by SushantKadam008** [comment]
Hi,
Could you please add a plunker showing how to solve the issue ?

**Comment by Tedko** [comment]
instead of just use st-sort="sth", add a wrapped sortGetter for each of your sort. If you want to sort "Good" "Medium" "Bad" , you can let the getter return 0 for good, etc

**Comment by SushantKadam008** [comment]
Also Can I have just 2 sort orders,
viz descending and ascending.
Could you please upload a sample for the same.
Your help can be very useful.

Please

**Comment by Tedko** [comment]
What does "2 orders" mean?

**Comment by lorenzofox3** [comment]
please refer to documentation with custom getter
