### ISSUE TITLE
Showing descending sort icon by default on column

### ISSUE THREAD

**Issue by SushantKadam008** [lorenzofox3/Smart-Table#631]
Hi,
I want to show a sort icon by default on the column header.
My Income column is by default sorted in reverse order and hence I want to show a descending sort icon by default on that column.

I added st-sort-descent to the th of the corresponding Income column .
It did not work.

Can any one please help on this ?

**Comment by lorenzofox3** [comment]
Please there are already few issues about the matter. can you please make your research a little bit ? 

thank you
