### ISSUE TITLE
Have only 2 sort orders

### ISSUE THREAD

**Issue by SushantKadam008** [lorenzofox3/Smart-Table#632]
Hi,
By default smart table has 3 sort order, viz : ascending, descending and primary order.
I just want to maintain 2 orders ascending and descending. So when the user clicks once it should be ascending and then descending and the ascending again.

Is there any way to achieve this ?

**Comment by lorenzofox3** [comment]
please refer to [documentation website](http://lorenzofox3.github.io/smart-table-website/#section-sort) st-skip-natural-order
