### ISSUE TITLE
Performance issue with latest angular JS 1.5.0

### ISSUE THREAD

**Issue by huyph** [lorenzofox3/Smart-Table#633]
I noticed a dramatic slowness when upgrading angular JS from 1.4.9 to 1.5.0 (latest stable) (try a list with very big number of data)

I have a look at their release notes (https://github.com/angular/angular.js/blob/master/CHANGELOG.md) and I can't spot anything that could cause this. Any idea?

**Comment by lorenzofox3** [comment]
I am sorry, I have no idea

**Comment by JeremyBYU** [comment]
I dont know if this will help but I'll show something that I found, however its not really specific to angular 1.5.   

I am trying to load thousands of records using smart table, but noticed a huge performance issue when using a custom pagination template, like 5 seconds to load and display data (custom template from the official website).  However I noticed the built in pagination was still extremely fast.  I realized that smart table is using the $templateCache function to load its pagination template.

To make it short I loaded custom template with $templateCache and performance is _extremely_ fast now.

Heres a plunker with angular 1.5 and the custom templates: [link](http://plnkr.co/edit/4yyoQZ?p=preview).  You can play around with it to notice the difference.

Hope it helps.
