### ISSUE TITLE
Pagination does not work with Angular 1.5

### ISSUE THREAD

**Issue by webTTW** [lorenzofox3/Smart-Table#635]
Hi there, 

after some hours of searching, I found an issue. 

Pagination is displayed, if I use version 1.2.x of angular. 
If I switch to 1.5.0 the pagination buttons are not displayed anymore. 

Does anyone know a solution for that?

Thanks.

**Comment by jbanken** [comment]
Having the same issue here.

**Comment by webTTW** [comment]
I have no solution

**Comment by jbanken** [comment]
Walked through the stPagination directive and noticed I was missing  tableState.pagination.numberOfPages = [[my total pages]]. The page is now displaying the pagination but not paging once i click on the page button.
