### ISSUE TITLE
Bower installing the wrong version

### ISSUE THREAD

**Issue by gabrihellmateus** [lorenzofox3/Smart-Table#644]
I want the 2.1.7 version, but even if I specify this new version bower will install the old one.

`.bower.json`
```json
"angular-smart-table": "~2.1.7",
```
Not working
```
$ bower install angular-smart-table#2.1.7
```
Not working

ps: I already cleaned bower cache.

**Comment by sylvainpolletvillard** [comment]
@lorenzofox3  Could you please publish 2.1.7 to npm ? It would be really appreciated. Thanks
