### ISSUE TITLE
Infinite Scroll

### ISSUE THREAD

**Issue by jhonmacaraig** [lorenzofox3/Smart-Table#647]
Hello Guys,
 Good day!
Question:
1. Is it possible to have a Infinite Scroll but instead of having request of ajax it would be local.
for instance. 
    lets say i made a request of 15000 collection.
would it be possible and i don't want to use ajax pagination

Cheers and Many thanks,

Jhon

**Comment by lorenzofox3** [comment]
Yes it is possible
