### ISSUE TITLE
Save and restore table state

### ISSUE THREAD

**Issue by trajano** [lorenzofox3/Smart-Table#649]
Is it possible to save and restore the table state in between transitions with ui-router?

**Comment by lorenzofox3** [comment]
I think so, look at the example with stPersist directive

**Comment by trajano** [comment]
Thanks for the tip.  The keyword was "persist" to search for in the documentation and I looked at the plunkr

http://plnkr.co/edit/ekwiNt?p=preview

Seemed doable, BUT... if I don't use pipe() and  I use the angular way of ng-repeat with a scope, how would I get this working.

On the bright side I finally understood what the `st-pipe` does and I may change my code to use that style in the future. 

Just going through the code to see if there's a "change table state" method because `tableState()` is a function.
