### ISSUE TITLE
Extra action columns (view,edit,delete buttons)

### ISSUE THREAD

**Issue by kabasakalis** [lorenzofox3/Smart-Table#65]
Congrats for your great work!
How can I add extra action columns (view,edit,delete buttons) in every data row, for CRUD?
Thanks in  advance

**Comment by RazvanCosmeanu** [comment]
I am extremely late for this. I'm creating a directive for my rows and ng-repeating it. I reference actions from my scope with '&{action}' inside of my directive declaration scope object. This seems cleaner than relying on the cell template.
