### ISSUE TITLE
Is there any way to use md-select as a search option?

### ISSUE THREAD

**Issue by marchage** [lorenzofox3/Smart-Table#653]
Is there a way to use` <md-select> `instead of `<select>` to filter/search a table and to use the `st-search` and `st-input-event` attributes on?

For example:
```HTML
<md-input-container class="md-block" flex-gt-sm>
  <label>Processed</label>
  <md-select ng-model="someModel" st-search="processed" st-input-event="change">
    <md-option value="">All</md-option>
    <md-option>No</md-option>
    <md-option>Yes</md-option>
  </md-select>
</md-input-container>
```

**Comment by marchage** [comment]
Newbe mistake.

**Comment by marchage** [comment]
Is there a way to use` <md-select> `instead of `<select>` to filter/search a table and to use the `st-search` and `st-input-event` attributes on?

For example:
```HTML
<md-input-container class="md-block" flex-gt-sm>
  <label>Processed</label>
  <md-select ng-model="someModel" st-search="processed" st-input-event="change">
    <md-option value="">All</md-option>
    <md-option>No</md-option>
    <md-option>Yes</md-option>
  </md-select>
</md-input-container>
```

**Comment by lorenzofox3** [comment]
to be honest I don't know

**Comment by marchage** [comment]
thanks

**Comment by marchage** [comment]
a solution could be to use custom directives template property. As a custom directive you could use the example of stSelectDistinct.

**Comment by gaelcancre** [comment]
angular.module('app').directive('stMdSelect', [function () {
        return {
            restrict: 'EA',
            require: '^stTable',
            scope: {
                listItems: '=',
                stSearch: '@'
            },
            template: '<md-select ng-model="selectedOption"><md-option>Aucun</md-option><md-option ng-repeat="item in listItems" ng-value="item.id">{{item.libelle}}</md-option></md-select>',
            link: function(scope, element, attr, table) {

                scope.selectedOption = undefined;

                scope.$watch('selectedOption', function (selectedOption) {
                    if (!angular.isUndefined(selectedOption)) {
                        table.search(selectedOption, scope.stSearch);
                    }
                });
            }
        }
    }]);
