### ISSUE TITLE
Select ng-model update

### ISSUE THREAD

**Issue by IvanPrytsko** [lorenzofox3/Smart-Table#654]
Hi, I'm working with smart-table and it's has great functionality.
The issue I'm stacked is how to update Table then i change in code `ng-model` on `<select st-search>`
If I change `vm.selectedCategory = 20` somewhere in controller, the value on `select` changes, but table not updates.

Here is my code:
`<select st-search="Category.Id"
     id="categorySelect"
     class="form-control input-sm"
     ng-options="item.Id as item.Name for item in vm.categoryCollection"
     ng-model="vm.selectedCategory">
     <option></option>
</select>`

I'm also tried to add custom search options to saved `tableState` like this: 
` vm.tableState.search = {
                predicateObject: {
                    Category: {
                        Id: '20'
                    }
               }
           };`
and execute CallServer(vm.tableState), filtering works, but selected value becomes blank.
Please help! Thanks

**Comment by lorenzofox3** [comment]
https://mark.zealey.org/2015/07/08/angular-smart-table-and-drop-down-select ?

**Comment by IvanPrytsko** [comment]
@lorenzofox3 I'm tried this example, but it's still not trigger table update.

`<select st-search="Category.Id" st-input-event="change" st-delay=0 ng-model="vm.selectedCategory" class="form-control input-sm">
                                    <option value="">
                                        All items
                                    </option>
                                    <option ng-repeat="item in vm.categoryCollection" value="{{ item.Id }}">
                                        {{ item.Name }}
                                    </option>
                                </select>`

**Comment by lorenzofox3** [comment]
Then please provide a plunker

**Comment by IvanPrytsko** [comment]
Actually I found how to solve my issue.
At first I save `smTable` from function `callServer(tableState, smTable)`
Then I create custom search params: 
`vm.tableState.search.predicateObject = {
                    Category: {
                        Id: vm.selectedCategory
                    }
                };`
After that, just call smTable.pipe(); and table update with new search params.

Thanks for quick reply for my issue
