### ISSUE TITLE
How to use Smart-table along with AngularPrint with as part of feature

### ISSUE THREAD

**Issue by elangesk** [lorenzofox3/Smart-Table#658]
Hi,

I am facing issue to implement AngularPrint with Smart-table to print entire table. Since I am facing issue I put another smart table with  st-safe-src="smapleData" st-table="chkDisplayed" search-watch-model="search" and proceeding. Put this approach lead to page load performance issue.
```
<div print-section print-only>
 <div st-safe-src="smapleData" st-table="chkDisplayed" search-watch-model="search">
            <table class="table table-responsive table-striped" print-table="chkDisplayed" print-landscape>
</table>
</div>
</div>
```

Could  please advise the right approach to use print entire table rows as formatted way. If possible please provide Plunker code base as sample.

Regards,
Elan

**Comment by elangesk** [comment]
@ lorenzofox3
could you please provide your advice on this issue.

**Comment by lorenzofox3** [comment]
I am sorry. 

I don't know AngularStrap, I don't know search-watch-model and this is not relevant for the issue section template of smart-table. 

As the issue template suggests open an issue when you find a bug or if you have a well defined problem, which can be reproducible.

Thanks for your cooperation.

PS: if the goal is to display something different for print I would simply use [css media queries](https://developer.mozilla.org/en-US/docs/Web/CSS/@media)

regards Laurent

**Comment by elangesk** [comment]
@lorenzofox3 
Thanks for your reply.
My issue is **How to print entire table rows data to printer** even we implemented pagination for smart table.

I have use angularPrint feature for time being. If you provide sample snippet in Plunker code base will support more.
