### ISSUE TITLE
Filtering (Searching) Timestamps by String Representation 

### ISSUE THREAD

**Issue by sean-perkins** [lorenzofox3/Smart-Table#659]
Angular Version: 1.4.9
Smart Table Version: 2.1.7

The angular filter function used in the `pipe` function of `stTableController` does a direct value comparison for filtering results. This is ideal for text based results, but when dealing with timestamps, the filter function will not match "March" up against a timestamp for the March timeframe.

The only viable solution that I have been able to produce, is manipulating the data set and inserting a string based representation of the timestamp, as another key on the object.

For Example:
```
var obj = {
    created_at: 1456929654000,
    created_at_search: '03/02/2016'
};
```

Is there a better solution out there for this concept? It seems extraneous to have to manipulate all timestamps to have an additional property on the object; especially when dealing with large datasets.

It's also not applicable to just send the timestamp as a string representation, as for sorting; the numeric representation accurately handles ascending and descending order and the string representation would not be as accurate. Also, it is notable that the server's interpretation of the timezone, may not reflect the client's timezone (if handling the pre-rendered text server side). 

It would be ideal to have the controller understand the built in angular filters, as their rendered text:
```
<td>{{ ::obj.created_at | date : 'MM/dd/yyyy' }}</td>
```

**Comment by lorenzofox3** [comment]
unfortunately there is no magic, behind the scene smart table uses default angular filter filter with its pros and its cons. 

You can as you said transform your dataSet 
```Javascript
scope.dataSet = data.map(v => Object.assign(v,{string_date:(new Date(v.created_at)).toString())
```
I don't think that is big deal

or use you own better filter with stSetFilter attribute (note it will be applied globally)

Finally you can use another search directive which transform the input and call the table api itself
```Javascript
link:function(scope,element,attr, table){
    element.bind('change',event => {
      // transform value
     //  ...
     
    scope.$apply(function(){
        // call table api
        table.search(transformedValue, predicate);
    })
   })
}
```

**Comment by sean-perkins** [comment]
Thanks for the response. I believe the `stSetFilter` is the best use-case for this example. I mocked up a quick filter example utilizing underscore, in case others run into a similar issue. Thanks again and awesome work on smart table. 

```
(function() {
    'use strict';

    angular
        .module('smart-table')
        .filter('smartTableFilter', smartTableFilter);

    /** @ngInject */
    function smartTableFilter(_) {
        return function (array, expression) {
            return _.filter(array, function(object) {
                var values = _.values(object);
                return _.find(values, function(value) {
                    if(angular.isUndefined(expression.$))
                        return true;
                    if(angular.isArray(value))
                        value = value.join(', ');
                    if(angular.isString(value))
                        return value.toLowerCase().indexOf(expression.$.toLowerCase()) !== -1;
                    if(angular.isNumber(value)) {
                        var dateValue = Date.parse(value);
                        if(isNaN(dateValue))
                            return value.toString().indexOf(expression.$.toLowerCase()) !== -1;
                        else
                            return dateValue.indexOf(expression.$.toLowerCase()) !== -1;
                    }
                    return false;
                });
            });
        }
    }
    
})();
```

```
<table st-table="vm.displayedRows" st-safe-src="vm.rows" st-set-filter="smartTableFilter"></table>
````
