### ISSUE TITLE
No documentation on `st-table.search(filter, predicate)`

### ISSUE THREAD

**Issue by chevalierc** [lorenzofox3/Smart-Table#666]
I was trying to follow the plunker: [Strict and multiselect filters](http://plnkr.co/edit/SOcUk1)

The filter does not return any data and I am unsure how to find the problem. I've traced it down to the `table.search()` method on the smart table object. I can not find documentation on `st-table.search(filter, predicate)`. I'm unsure why it is not working correctly. I am passing it the object:
`query.matchAny.items` which is an array

**Comment by lorenzofox3** [comment]
not intended to be documented. Note a good thing about open source is that anytime you can read the source code...
