### ISSUE TITLE
Maintaining column sort when sorted column data is updated for a row?

### ISSUE THREAD

**Issue by whutchtwo** [lorenzofox3/Smart-Table#670]
version: 2.1.8
angular: 1.2

Is there a way to maintain the sort order when the sorted column data is updated for a row?
For example I have a table with a column that is sorted by status. If the status of my first row is B and the status of my second row is C and I change the status of my second row from C to A it will not automatically be moved to the top row.

I have been searching, but am not able to find a solution.

Thanks,

**Comment by lorenzofox3** [comment]
smart-table will resync in the following cases (using st-safe-src)
* reference to source collection change
* length of source collection change
* first item ref of source collection change

I think your best bet is in your update function to splice the source collection and re insert the updated item
