### ISSUE TITLE
Manually Trigger

### ISSUE THREAD

**Issue by jhonmacaraig** [lorenzofox3/Smart-Table#673]
Hello Guys,
     Good Day!
I've search everything in the stackoverflow.
Just Quick question. I have a st-search in the <th> table.
My Issue is that how do i manually trigger the search? Currently when i try to do a 
keypress, keydown, keyup trigger it's not working.

smart-table version: @version 2.1.5
angular version:@license AngularJS v1.4.9

Thank you  in advance.

Sincerely yours,

Jhon

**Comment by lorenzofox3** [comment]
any directive that require stTable can call the controller api itself:
```Javascript
module.directive('foo',function(){
    return {
       require:'stTable',
       link:function(scope, elem, attr, tableCtrl){
           tableCtrl.search(...) //
           tableCtrl.sort( ... ) // etc 
       }
    }
})
