### ISSUE TITLE
Multiple condition on st-search

### ISSUE THREAD

**Issue by ruisilva450** [lorenzofox3/Smart-Table#676]
Hi,
I have a table with this type of data:
col1&nbsp;&nbsp;&nbsp;&nbsp;| col2&nbsp;&nbsp;&nbsp;&nbsp;| col3
item 1&nbsp;| true&nbsp;&nbsp;&nbsp;&nbsp;| true
item 2&nbsp;| **false**&nbsp;&nbsp;| true
item 3 | true&nbsp;&nbsp;&nbsp;&nbsp;| **false**

I need to be able to make a search that only shows the **item 2** and **item 3**
because they satisfy the premise **!(col2 || col3)**

The current custom implementation uses the vanilla 

``` javascript
ctrl.search(searchValue, predicate);
```

but this doesn't work with conditional predicate like I want.

if I do the search for both predicates (col2 and col3) separately:

``` javascript
$scope.model.thisControl.change(null, 'col2');
$scope.model.thisControl.change(null, 'col3');
```

The search translates to the premise **!(col2 && col3)**

**Comment by ruisilva450** [comment]
Any reason for this issue to be closed like that?

**Comment by lorenzofox3** [comment]
I was cleaning old issues. This one is one year old ! More over it does not follow the guidelines. 
Having a OR clause is not supported by angular filter filter (which smart table rely on) as far as I know. You'll need to use your custom filter. A 2min search gave me [this so quesion](https://stackoverflow.com/questions/39554350/angularjs-filter-with-or-condition), I'll you investigate further for your usecase
