### ISSUE TITLE
Angular 2 and Roadmap

### ISSUE THREAD

**Issue by LeonardoGentile** [lorenzofox3/Smart-Table#677]
Hello,
this is not an issue but a question about the roadmap of this package.
First of all I'd like to thank you very much for your work, I found this directive extremely useful.

For this I'd like to ask you if there is any plan for migrating the functionalities to Angular2 now that  they have released the first RC.

Thanks

**Comment by u26726** [comment]
any answer?

**Comment by u26726** [comment]
+1

**Comment by lorenzofox3** [comment]
For the moment there is **no** plan to support angular 2

**Comment by hoveytech** [comment]
I started repository [https://github.com/hoveytech/ng2-power-table](https://github.com/hoveytech/ng2-power-table) for Angular2 support, and it is modeled after smart-table with some structural changes leveraging TypeScript.

As of this post documentation is still in progress.
