### ISSUE TITLE
Quick Sample Question

### ISSUE THREAD

**Issue by bobwiller** [lorenzofox3/Smart-Table#678]
Several people have asked if the source code (or any other tutorial) is available for the sample that is shown in the YouTube clip, specifically the filter panel.  Not sure if that was answered anywhere as I didn't see it either on StackOverflow or here.  I am considering moving from angular-datatables and this is some intriguing functionality.

Thanks,
Bob

**Comment by lorenzofox3** [comment]
https://github.com/lorenzofox3/Smart-Table/issues/637 sorry :)
