### ISSUE TITLE
st-sort callback event when sorting column is clicked

### ISSUE THREAD

**Issue by mehulkaklotar** [lorenzofox3/Smart-Table#679]
I have smart table implementation. I want to do something when sorting is done like select the first row as current row and show user some things. How can I do it? Is there anything that I can do after sorting has been done?
Angular v1.5.0
Smart table v2.1.6

**Comment by lorenzofox3** [comment]
just hook an event handler on ng-click on the header. Or watch the tableState from a directive requiring the table (have a look at stPersist for more details)
