### ISSUE TITLE
Customizing Search

### ISSUE THREAD

**Issue by nkamenar** [lorenzofox3/Smart-Table#680]
Does anyone know a way to customize search to multiple fields but not every field? For example I have json data used to populate a table but only some of the information is displayed as some data is not important to the user. Using the global search doesn't always filter like I anticipate because sometimes it finds back end data. Is there a way to do something like st-search="firstName,lastName...etc" where I can specify which data should be searched within the json array?

Thanks,
-Nathan

**Comment by nkamenar** [comment]
If this is a duplicate could you please point me in the direction of the original? I have searched several times now and can't seem to find an answer to this question. Thanks, I appreciate it.

**Comment by lorenzofox3** [comment]
https://github.com/lorenzofox3/Smart-Table/issues/196 ,https://github.com/lorenzofox3/Smart-Table/issues/196.

Basically
1) map/clean your collection before you bind it to smart table
```Javascript
$scope.rowCollection = data.map(d=>Object.assign({},{propWanted:d.propWanted, ... });
```
2) or use a custom filter which map for you depending on whatever condition you want to use
```Javascript
function customFilter(array, predicateExpression){
   const searchable = data.map(d=>Object.assign({},{propWanted:d.propWanted, ... });
   return $filter('filter')(searchable,predicateExpression);
}
```

**Comment by raysunqi** [comment]
Hi lorenzofox3, I prefer your first solution to map the collection before bind to smart-table, however, I don't know how to NOT include the hidden properties, especially "id", which is needed in the smart-table for "edit" and "delete" buttons, but they should not be searchable, please advise if there is an easier way to handle it. I think it will be nice to have a "non-predicate" feature. 
Thanks
