### ISSUE TITLE
st-set-filter

### ISSUE THREAD

**Issue by annelatsko** [lorenzofox3/Smart-Table#682]
I have an object that's set up like this {id_number1: [item1, item2, ...], id_number2: [item1, item2, ...] ...} and I need to search through the keys. I know that a custom filter is required. This is my attempt at creating one.

`filtersList.filter('KeySearch', [function () {

return function(array, expression){

      array = Object.keys(array[0]); //this gets the information in the form above

      console.log(array);

      return array;

    }

}]);`

All I really need to do is take the object, retrieve the keys from it with Object.keys(array), and search with that array as opposed to the original object discussed above. How should I do this?

I apologize for any formatting issues.

**Comment by lorenzofox3** [comment]
Hello,

sorry, this is not related to smart-table but to angular filters. Please ask you question in a more relevant place (stackoverflow "angular filter to search through item keys" ). This section should only be used for **bug tracking** related to **smart-table**. 

> I apologize for any formatting issues.

You can always edit your message and format it correctly. 

Thanks.
