### ISSUE TITLE
Smart- Table Nested Data

### ISSUE THREAD

**Issue by mail2gopinath** [lorenzofox3/Smart-Table#684]
Hello,
   I have an object with  nested data and am binding the data with ng-repeat-start for each level data. Looks fine. I have used the st-safe-src attribute for the source data, but the sorting is not happening.  Can you please guide me the approach for sorting with the nested data. 

Below is plunker for it.
http://plnkr.co/edit/xVi7M6tNcbozOO03eK9H?p=preview

Thanks

**Comment by lorenzofox3** [comment]
you should use getters (cf documentation)
