### ISSUE TITLE
Sort by many columns?

### ISSUE THREAD

**Issue by Qavai** [lorenzofox3/Smart-Table#688]
How?

I need to sort by one column, but next i need to sort by another column.

if a use this

                    	$scope.getters = {
                            type: function (value) {
                                return value.type;
                            }
                        };

please explain, what i need to return?

                    	$scope.getters = {
                            type: function (value) {
                                return value.type; // value.created?

                            }
                        };

**Comment by lorenzofox3** [comment]
the returned value is what will be passed to angular orderBy filter for comparison. Please refer to [angular order by documentation](https://docs.angularjs.org/api/ng/filter/orderBy#!) (getter section)

**Comment by Qavai** [comment]
no, thanks
already used ui-grid, instead of your crafts
bye

**Comment by lorenzofox3** [comment]
thank you for your kind words, always a pleasure to deal with helpful people ...
