### ISSUE TITLE
Angular Smart Tables st-sort function with parameters

### ISSUE THREAD

**Issue by sarveshbathija** [lorenzofox3/Smart-Table#692]
I'm currently trying to use the sort functionality with smart tables. Currently the setup we have is what we are passing to smart tables is just an identifier (this is not the real example - so ignore if this certain example can be optimized, its hypothetical to get the point across):

`[{'id': 1},{'id':4},{'id': 3},{'id':4} }]
`
Now based on this, we display say the type in 1 column and a description in another. Both of these are looked up in a different object. I'd like to know how can I sort using a generic getter function that I can pass the object lookup to sort on instead of creating several customized getter functions.

Right now I have to do this:

```
<table>
    <tr>
       <th st-sort="sortByTypeDescription">
       </th>
       <th st-sort="sortByTypeName">
       </th>
    </tr>
</table>

$scope.sortByTypeDescription = function(row) {
      return $scope.descriptions[row.id].description;
}

$scope.sortByTypeName = function(row) {
      return $scope.name[row.id].name;
}
```

I was wondering if there is something like this I can do OR send in the extra parameters in a separate attribute so the function is dynamic:

```
<table>
    <tr>
       <th st-sort="sortColumn(descriptions,description)">
       </th>
       <th st-sort="sortColumn(name,name)">
       </th>
    </tr>
</table>

$scope.sortByTypeName = function(row,a,b) {
      return $scope.[a][row.id][b];
}
```

**Comment by lorenzofox3** [comment]
currying ? 

```Javascript
$scope.sortByTypeName =function(namespace,property){
   return function(row){
      return row[namespace][prop];
   }
}
```

**Comment by mryechkin** [comment]
I have a similar use case and currying does work for this, however I am now running into the problem described in issues #285 and #405. Even when using named functions, still seeing that issue where active sorted column is not showing correctly:

```javascript
$scope.sort = function sortParam(index) {
    return function sortValue(value) {
        return value[index];
    };
};
```

Doing this WITHOUT currying is working as expected:

```javascript
$scope.sort1 = function sortValue1(value) {
        return value[1];
    };
};

$scope.sort2 = function sortValue2(value) {
        return value[2];
    };
};
```

I have [modified a Plunk](http://plnkr.co/edit/vgwE5P?p=preview) from issue #405, where you can see it broken.

Can you please provide any feedback? Thanks

**Comment by akirpichnikov** [comment]
Unfortunately this issue is still not fixed. I also can't use st-table with arbitrary data when I don't know exact columns names.
