### ISSUE TITLE
server side pagination not working.

### ISSUE THREAD

**Issue by pruthvi224** [lorenzofox3/Smart-Table#693]
Hi, I am very much new to this angular js and this is my fiirst job, my company has assigned me to create a grid by using the smart table, I am working on the server side pagination, I have followed the guide lines mentioned in server sample branch to create a column, now my question is how to get the json data in to the table, i have created the pagination by using the client side pagination and it is working fine, now i want to make it server side pagination.

**Comment by Dekamerron** [comment]
What have you tried? Can you show us a plunker? We can't  imagine your code and tell you a solution tho.

**Comment by pruthvi224** [comment]
for the server side pagination, I haven't done anything, I saw in the server sample branch they are using the dummy data which is generated randomly, I want to use the data from the JSON, here is my JSON data. I have uploaded the files which I am using, please help me in loading the JSON data in the sample server sample branch example. I have uploaded the screenshots how my HTML page looks, and want to load the JSON data. I dont know angular js and learning it and doing the task assigned to me. please help. If atleast let me know how to load the json data in the same serve sample branch example instead of random data generated it would be helpful for me.
[smart.zip](https://github.com/lorenzofox3/Smart-Table/files/349944/smart.zip)



https://plnkr.co/edit/gFxq1S9Tbo6rbdtnP6Bz?p=catalogue

**Comment by pruthvi224** [comment]
Can you please help me how the same JSON data can be loaded in the example given below instead of the random generated data

https://github.com/lorenzofox3/Smart-Table/tree/server-sample
