### ISSUE TITLE
st-pagination always set the first page as active

### ISSUE THREAD

**Issue by brazorf** [lorenzofox3/Smart-Table#694]
- [x] I have searched through the issue section and on [stackoverflow](http://stackoverflow.com/questions/tagged/smart-table?sort=newest&pageSize=30) if my issue has already been raised. 
- [x] I have provided Angular version.
- [x] I have provided Smart table version.
- [x] I have set a precise description of my problem, mentioning the expected result.
- [x] I have given a way to reproduce my issue, by providing a <strong>running example</strong>, I can use [plunkr](http://plnkr.co/). Note if you want to mimic ajax loading behaviour you can use [$timeout](https://docs.angularjs.org/api/ng/service/$timeout) angular service or [$httpBackend](https://docs.angularjs.org/api/ng/service/$httpBackend).

Angular version 1.5.7

Smart Table version 2.1.8

My markup: 
```
<tfoot>
<tr>
	<td class="text-center" st-pagination="" colspan="7"></td>
</tr>
</tfoot>
```

My Controller:
```javascript

// Omit the rest, however i'm inside a pipe callback function.

var page = Math.ceil(tableData.pagination.start / tableData.pagination.number) + 1
$http.get('things?page=' + page).then(function(response){
        
	$scope.usersList = response.data;
	$scope.safeUsers = response.data;
	
    // Number of pages is set properly, seen on console.log().
	tableData.pagination.numberOfPages = $scope.paginator.numberOfPages;
});
```

What seems to be broken is the `ng-class` within the `st-pagination` directive, always resulting set to the first page. If i click the paginator links the table does update properly, but i always get the `active` class on the first item. I think this is related to the `currentPage` variable in the directive scope.

This is a plunker that reproduces this issue: https://plnkr.co/edit/daP8FR7WvztouISgCaO2?p=preview

Note that i've copy-pasted the 2.1.8 minified src since it wasn't available in plunker libraries.

**Comment by brazorf** [comment]
Any news about this?

**Comment by lorenzofox3** [comment]
The problem is that you use st-safe-src with your own pipe function. 
As you use you own data loading logic, that does not make sense to ask smart-table to synchronize whenever the data set change: whatever you load with you own logic will be the displayed data. 

https://plnkr.co/edit/6DQ62zNK4aafoG4n8jn3?p=preview

**Comment by brazorf** [comment]
Thank you. 

I think it's not entirely clear to me when i should update the safe source, and when not to do it. Can you provide some detail or link to the related docs?
