### ISSUE TITLE
responsive smart table 

### ISSUE THREAD

**Issue by pruthvi224** [lorenzofox3/Smart-Table#695]
## Hello contributor ! 

Please before you submit your issue, make sure all the below can be checked (note if anything is expected, you can simply add it under the relevant checkbox)

- [x] I have searched through the issue section and on [stackoverflow](http://stackoverflow.com/questions/tagged/smart-table?sort=newest&pageSize=30) if my issue has already been raised. 
- [x] I have provided Angular version.
- [x] I have provided Smart table version.
- [x] I have set a precise description of my problem, mentioning the expected result.
- [x] I have given a way to reproduce my issue, by providing a <strong>running example</strong>, I can use [plunkr](http://plnkr.co/). Note if you want to mimic ajax loading behaviour you can use [$timeout](https://docs.angularjs.org/api/ng/service/$timeout) angular service or [$httpBackend](https://docs.angularjs.org/api/ng/service/$httpBackend).

Note that it not all the above checkbox can be marked as checked the issue will immediately be closed. Thanks for your understanding.

And don't forget to close you issue when it is solved !

Thanks again for your contribution.

**Comment by pruthvi224** [comment]
Can we make a smart table responsive

**Comment by lorenzofox3** [comment]
smart table use regular table markup. You are free to use any css you want
