### ISSUE TITLE
Searched records count displaying

### ISSUE THREAD

**Issue by shweta-bb** [lorenzofox3/Smart-Table#698]
## Hello contributor ! 

Please before you submit your issue, make sure all the below can be checked (note if anything is expected, you can simply add it under the relevant checkbox)

- [yes ] I have searched through the issue section and on [stackoverflow](http://stackoverflow.com/questions/tagged/smart-table?sort=newest&pageSize=30) if my issue has already been raised. 
- [ ] I have provided Angular version.
- [ ] I have provided Smart table version.
- [ ] I have set a precise description of my problem, mentioning the expected result.
- [ ] I have given a way to reproduce my issue, by providing a <strong>running example</strong>, I can use [plunkr](http://plnkr.co/). Note if you want to mimic ajax loading behaviour you can use [$timeout](https://docs.angularjs.org/api/ng/service/$timeout) angular service or [$httpBackend](https://docs.angularjs.org/api/ng/service/$httpBackend).

Note that it not all the above checkbox can be marked as checked the issue will immediately be closed. Thanks for your understanding.

And don't forget to close you issue when it is solved !

Thanks again for your contribution.

**Comment by lorenzofox3** [comment]
already discussed thoroughly. Please search issue section for "stSummary"
