### ISSUE TITLE
Does Smart-table have beforeSelectionChange and afterSelectionChange event?

### ISSUE THREAD

**Issue by KavyaShetty** [lorenzofox3/Smart-Table#699]
Is there a way to disable the smart table grid selection once some row is clicked i.e. in beforeSelectionChange and once my selection change action is performed I enable it back in afterSelectionChange.

**Comment by lorenzofox3** [comment]
you can watch the isSelected property of the items. Or even easier add a ng-click on the rows with you custom logic
