### ISSUE TITLE
Fire event when selecting rows

### ISSUE THREAD

**Issue by ChristianWeyer** [lorenzofox3/Smart-Table#7]
We need an event when selecting a row so that we can act accordingly (without having to do our own $watch over and over).

**Comment by jmcollin78** [comment]
In my case it was:

    $scope.$watch(function() {
            return _.filter($scope.displayedElts, function (elt) {  return elt.isSelected;  }).length;
          }, function(newValue, oldValue) {
             $log.debug('Number of selected elts has change oldValue="%d" newValue="%d"', oldValue, newValue);
          });

**Comment by astsiapanay** [comment]
It doesn't work for 2.1.3:
$scope.$watch('displayedCollection', function(newVal) {
    console.log("selected items: " + newVal.filter(function(item) {
        return item.isSelected;
    }).length);
}, true);
It seems Angular can't see changes any longer for bound collections.

**Comment by lildukedana** [comment]
I am having the same issue when trying to send a selected row to a new table in a bootstrap modal.
I'm putting a watch on the collection, but it is not keeping track of anything. I also put a second function in ng-click, and pass the row as a parameter to a function but the function does not get called.

```javascript
//Here's the markup 
<tr ng-click="row.isSelected = !row.isSelected; test(a)" ng-class="{'st-selected':row.isSelected}" st-selected-row="row" st-select-mode="multiple"
                                        ng-repeat="a in smertAccountTabe" ng-show="!acc.isloading">

   //here are the functions in the controllers
   $scope.test = function () {
           //no dialog popping up 
           alert("test worked on click");
       }
       
       $scope.$watch('smertAccountTabe', function (row) {
           //get selected row
          //alert("test this filter");

           row.filter(function (r) {
              
               if (r.isSelected) {
                   alert("test the watch");
                   console.log(r);
                   return r;
               }
               
           })
       }, true);

//here is the CSS for row selection 
.table-striped>tbody>tr.st-selected:nth-child(odd)>td,
.table-striped>tbody>tr.st-selected:nth-child(even)>td {
background-color: #001A67 !important;
color: #fefefe!important;

}

**Comment by KavyaShetty** [comment]
Has anyone found a solution for this?

**Comment by jmcollin78** [comment]
@KavyaShetty This snippet does the trick for me: 

```
$scope.$watch(function() {
        return _.filter($scope.displayedElts, function (elt) {  return elt.isSelected;  }).length;
      }, function(newValue, oldValue) {
         $log.debug('Number of selected elts has change oldValue="%d" newValue="%d"', oldValue, newValue);
      });
```

**Comment by totallytotallyamazing** [comment]
Hey Ya'll anyone can help me? I've been trying this and it works but errors in browser console this, "Error: row is undefined".

    $scope.$watch('displayedCollection', function(row) {
      // get selected row
      row.filter(function(r) {
         if (r.isSelected) {
           console.log(r);
         }
      })
    }, true);
