### ISSUE TITLE
Can we disable smart-table grid

### ISSUE THREAD

**Issue by KavyaShetty** [lorenzofox3/Smart-Table#701]
On row click I want to perform some data manipulation but when this is going on I do not want user to select some other row. Can I disable the smart -table.

**Comment by KavyaShetty** [comment]
Does anyone know about it?

**Comment by KavyaShetty** [comment]
Guys any idea on this?? I still need it.

**Comment by lorenzofox3** [comment]
I don't understand, I am sorry

**Comment by KavyaShetty** [comment]
Is there any way I could disable smart table when there is some action being performed on row click.
