### ISSUE TITLE
Tbody Td width equal to fixed td column header width.

### ISSUE THREAD

**Issue by 1Jesper1** [lorenzofox3/Smart-Table#702]
Hello, I would like to improve the fixed header example in the documentation.

In the current example the header column width is not the same as the tbody element width. This is because of the vertical scrolling bar. 
I have created another directive for the td elements in the tbody.
In this directive I search for the width of the column in the header and give the td element in tbody this width. 
I also added overflow-x: hidden to the css of tbody.

```
#objectSearchTable > tbody {
    overflow-y: auto;
    overflow-x: hidden;
}

.directive('stRatio',`` function () {
    return {
        link: function (scope, element, attr) {
            var ratio = +(attr.stRatio);

            element.css('width', ratio + '%');
        }
    };
}).directive('stRatio1', function () {
    return {
        link: function (scope, element, attr) {
            var ratio = +(attr.stRatio1);
            var trHeaderWidth = $('#objectSearchTable thead tr:first-child').width();
            var finalWidth = (trHeaderWidth * ratio) / 100;

            element.css("cssText", "min-width:" + finalWidth + "px;");
        }
    };
});
```

**Comment by lorenzofox3** [comment]
thanks.
