### ISSUE TITLE
Smart-Table refresh data from server after CRUD action

### ISSUE THREAD

**Issue by ardennext99** [lorenzofox3/Smart-Table#703]
I have a smart table that show rows from server using st-pipe to call the "CallServer" method and get paged rows. it work, but I have to implement functionality of add, delete, modify rows. and I need to call the "CallServer" when one of the crud action ended.

How can i get the tableState inside my crud function, so i can pass it to the "Callserver" function to refresh the data and amntain the same order/filter?

    $scope.CallServer = function callServer(tableState) {
      var start = tableState.pagination.start || 0;
      var ItemNumber = tableState.pagination.number || 10;
      var PageIndex = (start / ItemNumber) + 1;

      //Gestione ordinamento
      var ColumnName = "AspNetUserID";
      if (typeof tableState.sort.predicate != 'undefined') {
        ColumnName = tableState.sort.predicate;
      } else {
        tableState.sort.predicate = "AspNetUserID";
      }

      var ColumnSortDirection = 0;
      if (typeof tableState.sort.reverse != 'undefined') {
        ColumnSortDirection = tableState.sort.reverse ? 1 : 0;
      } else {
        tableState.sort.reverse = 0;
      }

      var promise = AccountsService.GetAccountsSqueezed_OST(PageIndex, ItemNumber, ColumnName, ColumnSortDirection);
      promise.then(function (results) {
        $scope.rowCollection = results.data.DataObjectList;
        tableState.pagination.numberOfPages = Math.ceil(results.data.DataObjectTotalCount / ItemNumber);
      });
    };

**Comment by lorenzofox3** [comment]
you should probably wrap your logic in a directive that requires smart table controller 

```Javascript
app.directive('refresh',['crudService',function(crud){
   return {
     requires:'stTable'
     link:function(scope,elem,attr,table){
       scope.addItem = function(){
           //do something with crud
           refresh()
       }
       // ...etc

      function refresh(){
        const tableState = table.getTableState();
        table.pipe(tableState);  
      }
     
     }
   }

}]);
```

or you can simply change the table state (setting the page to the first one, etc)

**Comment by ardennext99** [comment]
Sorry but i've not understand.
I think that should be an easy way to get the tableState from a external function, or call a refresh with the same pagination settings.

How can i change the state (es: page to first one) if i cannot reach the tablestate?


there is a way to call directly the pipe() from my crud functions controller?
or get the tableState directly from my crud functions controller so i can pass it to the "Callserver"?

i've read all the post on the argument bu not yet find a simple solution.
thank you so much.

**Comment by lorenzofox3** [comment]
> How can i change the state (es: page to first one) if i cannot reach the tablestate?

As any angular directive with a controller you can require that controller from a child directive and call its API. Have a look at the source codes of the built in directives for more details (stSort, stSearch, stPagination). The table state and the table will be updated accordingly. 

> there is a way to call directly the pipe() from my crud functions controller?

There is a way but that is not recommended as it is not the normal flow (a la Flux). user interact -> tableState change -> pipe -> table is updated.

you'll need to create a directive to access tabel api and communicate with your controller

```Javascript
app.directive('refresh',['crudService',function(crud){
   return {
     requires:'stTable',
     scope:{
        // use binding here to communicate with the external world
     }
     link:function(scope,elem,attr,table){
        
         var ts = table.tableState()  // get access to the table state
         // table.search()
         // table.sortBy()
         // table.slice()
        // ... any function offered by the api
        //table.pipe(ts)
     
     }
   }

}]);
```
