### ISSUE TITLE
slow render performance with custom pagination and large datasets

### ISSUE THREAD

**Issue by ericdecarli** [lorenzofox3/Smart-Table#704]
angular version: tested with **1.2.x, 1.4.x, and 1.5.x**
smart table version: **2.1.8**

table renders slowly with large data set and custom pagination template.  only happens if the data is already loaded or cached.  if the page loads and then data is loaded asynchronously, or if you use $timeout with even 100ms delay, this is not an issue

i think this happens because, when using a custom pagination template, there seems to be some delay in smart-table recognizing pagination is enabled... 

line 176 `displaySetter($scope, output || filtered);`

when the table is rendered, `output` (paginated output) does not exist yet so it is using `filtered`.  you can see this as the table loads because the the table tries to load the entire recordset in to the DOM before correctly slicing the array and showing just the paged results

a hack i used to fix this issue is `displaySetter($scope, output);` which is obviously not a real fix since it always assumes pagination.  

with that hack
https://plnkr.co/edit/XGh7vLcynwWxtZnhXy5L?p=info
for me, fully runs/loads in ~3 seconds from clicking "run"

without that hack:
https://plnkr.co/edit/4UYHOuzwJFhWKKozXfYl?p=info
for me, fully runs/loads in ~7 seconds from clicking "run". more than double the time as with the hack

there is probably a much better solution, but for now if anyone else is running in to this issue, you could add a pagination boolean to the top level smart-table directive and then line 176 would become something like

`ctrl.paginateTrue ? displaySetter($scope, output) : displaySetter($scope, filtered);`

or if you don't want to mess with the smart-table code, just use a $timeout to add a small delay which also seems to fix the render issue

instead of `$scope.rowCollection = someService.cachedData;`

`$timeout(function(){
  $scope.rowCollection = someService.cachedData;
},100);`

**Comment by sojukrishna** [comment]
Check a similar issue reported #633: In this you can try @JeremyBYU's comment with templateCache
