### ISSUE TITLE
Access the table node in a directive with "require: '^stTable'"

### ISSUE THREAD

**Issue by moshfeu** [lorenzofox3/Smart-Table#705]
I want to access the table **node** within the directive. I could easily use `element` but the `st-table` directive is no a wrapper `div` but not the table.

In the `link` function I have the parameter `smartTable` for example, but I have not there a reference to the table node. Is there a way to access? 

<pre>
link: function (scope, element, attrs, smartTable) {
    console.log(smartTable);
    /* output:
    {
	    getFilteredCollection: function(),
	    pipe: function(),
	    preventPipeOnWatch:function(),
	    search:function(e,a),
	    select:function(t,n),
	    setFilterFunction:function(t),
	    setSortFunction:function(t),
	    slice:function(t,e),
	    sortBy:function(e,a),
	    tableState:function()
    }
   */
}
</pre>

Thanks

**Comment by lorenzofox3** [comment]
element.parentNode (or .children) etc ?
