### ISSUE TITLE
Setting a data inside an st-search input on load doesn't refresh the smart-table datas.

### ISSUE THREAD

**Issue by gwenaellarmet** [lorenzofox3/Smart-Table#708]
I'm trying to set a data inside the search input of my Smart table, but when I set the data directly inside the input with **ng-model**, smart table doesn't trigger **.search().**
I want my smart table to do the search once it load, Is there a way to achieve this behaviour ? 
 
> Angular version : 1.4.10
> smart-table version : 2.1.8
> Plunker with the issue : https://embed.plnkr.co/y6dB3HndVj4P0N9puPj3/

**Comment by lorenzofox3** [comment]
you have to call directly the table api .search() function. By default smart-table is unidirectional and does not need ngModel (to avoid sophisticated/complex bidirectional state sync). If you want to do so, I suggest you wrap your behaviour in a directive watching for model change and calling table api

**Comment by lorenzofox3** [comment]
see [SO](http://stackoverflow.com/questions/39332703/smart-table-angular-filter-not-updating-the-page)

**Comment by gwenaellarmet** [comment]
I saw that I'm not the only one asking for Smart table to use ng-model, could this be an options ? I'm willing to develop the PR for this purpose. (It will still be an options like 'st-unidirectional = true/false' added in the <table> tag.
If you're okay with this development for smart-table I could work on it right away.

**Comment by lorenzofox3** [comment]
thanks but no. I believe it is easy enough to come up with your own directive without touching ST code base. 
You can however make a pull request on the example section of the documentation website with a better impl that the one I provided on SO

**Comment by gwenaellarmet** [comment]
It's only so smart-table can go further, if you get several issues open on this matter, it's certainly because it's a needed features. I will open a PR if it can help anyone.

**Comment by lorenzofox3** [comment]
still not thanks

**Comment by gwenaellarmet** [comment]
All right I quit trying to develop this PR, thanks for your help.

**Comment by gwenaellarmet** [comment]
I imagine that you will not be willing to do this development yourself ? (In case you just don't want anyone to touch your code)

**Comment by lorenzofox3** [comment]
nope it just goes against ST philosophy. Code base should be kept simple providing simple set of features but easy extension mechanism. What you want to do can be achieved without touching ST and is probably not something all the users will want anyway, there is no reason to bloat smart table for no reason
