### ISSUE TITLE
Exposing StTableController to Directives Outside Table's DOM Structure

### ISSUE THREAD

**Issue by jusopi** [lorenzofox3/Smart-Table#720]
Currerntly Using
- angular v1.5.x
- smart-table v2.1.8

In cases where I want to create directives that interact with a particular table, I am forced to design them such that they are nested within the table's DOM structure.  

Currently the only way to interact with the smart-table controller is to define a child component/directive that resides within the table's DOM structure.  Then we expose the controller API via `require: '^stTable'`.

In this example, this works as expected since the `st-toggle-list` directive is implemented within the table:
```
<table st-table="$filtered">
    <thead>
        <tr>
            <th st-toggle-list></>
```

In this example, I want to declare something relevant to the table **without** having to programmatically define it, rather I want to declare an object to expose to the table.  Because `st-table-object` is not valid HTML within the table itself, the HTML engine will remove it from the table.  This happens before linking takes place such that the required `^stTable` controller can't be found since our new component is not a child of the table element.

```
<st-table-object table="#tbl1"/>

<table st-table="$filtered" id="tbl1">...</>
```

An easy fix to this is create an inherited scope for the `st-table` directive and provide it a `controllerAs` value:

```
.directive('stTable', function () {
    return {
      scope: true,
      restrict: 'A',
      controllerAs: 'stTable',
      controller: 'stTableController',
      link: function (scope, element, attr, ctrl) {

        scope.stTable = ctrl

        if (attr.stSetFilter) {
          ctrl.setFilterFunction(attr.stSetFilter);
        }

        if (attr.stSetSort) {
          ctrl.setSortFunction(attr.stSetSort);
        }
      }
    };
  });
```
After modifying my local source, you can see it exposed in batarang.   
![image](https://cloud.githubusercontent.com/assets/560458/18887511/61fc433e-84c2-11e6-9f24-85d30b653743.png)

**Comment by admin4x4asie** [comment]
This is not a good idea as you would break encapsulation. 

The recommended way (see Angular doc website) to share data through components is to use service.

If you still want to use scope/binding to share data you can create a directive to put inside table to communicate with the external world.

```Javascript
app.directive('stBinding',function(){
    return {
        require:'^stTable',
        scope:{
           //define binding here... cautious the table may not sync if you decide to set yourself some data whitout going through table.api => better being readonly 
           table:'='
        },
        link:function(scope,elem,  attr, table){
             scope.table = table
        }
    };
});
```

**Comment by lorenzofox3** [comment]
see @admin4x4asie comment
