### ISSUE TITLE
New Feature Request :: Select All Button with the Table

### ISSUE THREAD

**Issue by harshild** [lorenzofox3/Smart-Table#722]
Hi,

This talks about the similar concerns as mentioned here :- https://github.com/lorenzofox3/Smart-Table/issues/270

The provided directive also works like a charm.

But, i am wondering if it possible to include an auto-selection button with the library and then may be toggling its usages with the help of property.

I searched quite a bit but not found any such request made earlier. You can discard it if something like this has already been adressed

**Comment by harshild** [comment]
It's would be really great if it could be closed with a reason

**Comment by lorenzofox3** [comment]
This is not something I want to be included in the core library as this specific corner case can be done externally without the need to add more lines of code to the library !
