### ISSUE TITLE
smart-table with pagination st-table collection item count

### ISSUE THREAD

**Issue by kedar10** [lorenzofox3/Smart-Table#726]
I started integrating smart-table in my code and I have a column that I'm displaying a checkbox.

When I'm trying to get the count of the collection that's assigned to st-table it's only returning the count of items displayed on the table rather than entire collection count.

Following is the HTML code for smart-table .

<table style="border:thick" st-set-filter="customFilter" st-safe-src="vm.dataToCompare" st-table="vm.displayed" class="table table-striped">

I also need to get the collection of items that I have checked or unchecked on multiple pages. Below is the code that I'm using to get that collection.

var resultTrue = $filter('filter')(vm.displayed, { yes_no: true });

This returns resultTrue collection only on the current page. What I'm doing wrong that I'm not getting the correct or desired collection from multiple pages?

I'm using angular v1.2.22.

**Comment by lorenzofox3** [comment]
Please look for other issues, there are plenty of example. Check for "stSummary" for example
