### ISSUE TITLE
http://lorenzofox3.github.io/smart-table-website not working

### ISSUE THREAD

**Issue by ihorskyi** [lorenzofox3/Smart-Table#732]
Going to http://lorenzofox3.github.io/smart-table-website/ returns 404

![screen shot 2016-11-21 at 10 49 56 am](https://cloud.githubusercontent.com/assets/6171149/20489368/5c467356-afd8-11e6-8b2e-a0e2f1b5b1ec.png)

**Comment by ChristopheBraud** [comment]
It works now ! You can close this issue, but I think it's better to wait for the reason of the downtime.
