### ISSUE TITLE
Smart Table pagging refreshing Issue

### ISSUE THREAD

**Issue by hemrajrav** [lorenzofox3/Smart-Table#736]
Hi,
how can i control page refreshing in smart table on refill inside angular controller when any action perform.
for exa : - I am on page no 6 and i claim an order then control comes on first page when refill smart table.
so how can be control this refresh...please provide me solution immediately.

Thanks in advance
Hemraj Rav

**Comment by MrWook** [comment]
Hello @hemrajrav,

I don't know if I got it right, but i think you want to controle the events for search, sort etc?

Maybe you can use the pipeline if you trigger the search event it will go over the pipeline.
If you already use the pipeline i guess it's your own code that provide the pagination and what happens to the data. 
Maybe you can provide me with an plunker example?
