### ISSUE TITLE
Unable to initialize multiple search fields

### ISSUE THREAD

**Issue by cbayleyball** [lorenzofox3/Smart-Table#740]
I've done the search and didn't find anything that seemed to match my problem.  I am using Smart Table 2.0.1 and Angular 1.3.16.  Unfortunately I cannot provide a plunkr since my application is being developed on a closed system, but I will try to describe it as much as possible.

My smart table has multiple column search fields defined as follows:

<input id="field1" ng-model="field1" st-search="field1" type="search>
<input id="field2" ng-model="field2" st-search="field2" type="search>

The search fields work beautifully but I want to add a default value to both of them (based on parameters passed to the page) and initially filter the table.  So I added the following to the angular controller:

$("#field1").val("Field 1 default value");
$("#field1").trigger("input");
$("#field2").val("Field 2 default value");
$("#field2").trigger("input");

When I print out the filter values in my custom filter directive, all I see is field 1.  I tried removing the field1 trigger statement but then all I see is the field2 data and field1 disappears from the input box.  I saw posts about st-persist but I don't think the version I'm using contains that feature (and upgrading is not possible due to the lengthy approval process needed to install new software on our system).  Also, I'm not wanting the search filters to persist, just be able to initialize them.

How can I get around this problem?  I looked into trying to chain the trigger events but that didn't work.  Basically I would just like a way to initially set the search predicate field used in the smart-table code (the jQuery .val() will display the value and I was only using the .trigger() to force the filtering).

Thank you for the assistance.

**Comment by MrWook** [comment]
Hello @cbayleyball,

do you use the pipe system?
If so you can manual  set the search value in the tableState
`this.callServer = function callServer(tableState) {`
`...some code`
`//in the first request the pipe predicateObject is undefined `
`if(tableState.search.predicateObject == undefined){`
`tableState.search.predicateObject = {};`
`tableState.search.predicateObject.field1 = "Field 1 default value" `
`tableState.search.predicateObject.field2 = "Field 2 default value" `
`} `
`...somemore code`
 ` };`

With this you don't need to trigger the input field and u don't have three request to the server also it write the value into the input field.

If you don't use the pipe i cant provide you with help but i think it's better if you throw that jquery away when you use angular.
Better use the ng-model system with:
`$scope.field1 = "Field 1 default value";`
But this won't trigger the SmartTable but at least this is a better way to write something in the input field.

**Comment by cbayleyball** [comment]
Thank you for the response.  I do not use the pipe system.  I initially tried doing the $scope.field1 = but the value was disappearing when I did the trigger so I went to the jQuery route.

**Comment by cbayleyball** [comment]
I was able to workaround the issue in a very kludgey way (no choice based on my project time constraints).  Basically since the stSearch directive has access to the scope, I added a check if a scope variable was defined and if so, used that as the search predicate.  In my controller, I setup the initial predicate variable as needed.  This seems to be working for me.
