### ISSUE TITLE
st-sort-default overwrites st-persist state

### ISSUE THREAD

**Issue by angustus** [lorenzofox3/Smart-Table#742]
**Working example:**
http://plnkr.co/edit/UI5r9r?p=preview
It's a fork of the `st-persist` example; I've added `st-sort-default` field and updated `smart-table` to `v2.1.8` (master as of now).

**Reproduction:**
1. Use pagination and sort by any column.
2. refresh preview

**Result:**
The persisted state is applied before the default sort order is applied.
**Expected:**
Persisted state should be applied last thus overwriting default state order.

**Comment by foxdog05000** [comment]
Hi, when is the conclusion ? I have the same problem and I would like to know if something is envied ?
