### ISSUE TITLE
st-sort with function returning a promise

### ISSUE THREAD

**Issue by skidvd** [lorenzofox3/Smart-Table#744]
Hi,

I am using angular v1.5.9 and smart-table v2.1.0.  I have searched for answers to my question below, but have not been able to find any that address the specific promise/async attributes of it - apologies if this has been addressed somewhere and/or is a duplicate - if so, kindly please refer me there.

I have been using both st-table="displayedItems" and st-safe-src="items" directives in combination with st-sort.  This combination successfully and reliably works for nearly all conditions I have run across.  This includes scenarios where the st-sort is function based.  However, I recently encountered an need to have a function based st-sort that returns a promise instead of the value directly (i.e. the function will asynchronously resolve the value, at a slightly later time - when it becomes available).

My question is, should the st-sort be expected to produce a predictable ordering of the rows in that case?  If so, it does not appear to be.  I am theorizing that this may be do to the fact that the associated values are not available to the sort algorithm all up front - but rather straggle in in an unpredictable order and time frame.  By the way, no errors or other indications are returned that a problem may exist.  Should I expect this to work, or is this a known limitation?  Are there additional items that can be done to make it work on my part or otherwise - if so, I'd greatly appreciate any tips or thoughts you may have?

TIA!

**Comment by lorenzofox3** [comment]
Hi,

First of all, thanks for your language ! 👍 
Unfortunately, st-sort was not thought to interpret Promises and I am not sure your use case can be handled with smart-table. 

If you could provide a running example of you use case, I would definitely have a look and try to find a solution (without touching smart-table code however, I am not really keen in changing the core to handle such a specific use case) 

Cheers

**Comment by skidvd** [comment]
That is what I was suspecting.  My plans at present are to modify the code so that the data will be pre loaded and as such will be available in the normal manner for st-sort, etc.  This is not ideal as it means making extra calls to the BE and loading data into memory for rows that may never be displayed and/or sorted, but it will be workable.  If you have any thoughts on a better approach, I'd appreciate hearing about them.  Thank you.
