### ISSUE TITLE
Programmatically trigger sorting

### ISSUE THREAD

**Issue by zaksmolen** [lorenzofox3/Smart-Table#745]
Hi, I'm using angular 1.5.0 and smart table 2.1.2. 

I am trying set up something where I can programmatically select the sort column, but I haven't been able to find any real solution to do something like that. Is it possible to do that without modifying the smart table source? The only solution I have seen that showed any promise was manually triggering click events but that seems super hacky. I'm pretty open to implementation options but I would like to save that as a final fallback option. 

Thanks!

**Comment by lorenzofox3** [comment]
you can call table controller [api sort](https://github.com/lorenzofox3/Smart-Table/blob/master/src/stTable.js#L82) method:

```Javascript
app.directive('customSort',function(){
  return {
      require:'^stTable',
      link:function(scope, el, attr, table){
           //
          table.sort('foo',false)
          //
      }
  };
})
```

there are plenty of examples of custom directive on the net/issues/chat/stackoverflow
