### ISSUE TITLE
edit row with popup

### ISSUE THREAD

**Issue by smohammedyasin** [lorenzofox3/Smart-Table#746]
How can i edit table row using angularjs popup [here](https://github.com/dwmkerr/angular-modal-service) or bootstrap popup. any tips please

**Comment by MrWook** [comment]
Hello @smohammedyasin,
`<tr ng-repeat="row in rowCollection"  ng-click="edit(row)">`
`	<td>{{row.id}}</td>`
`        <td>{{row.firstName}}</td>`
`</tr>`
or
`<tr ng-repeat="row in rowCollection">`
`	<td>{{row.id}}</td>`
`        <td>{{row.firstName}}</td>`
`        <td><button ng-click="edit(row)" type="button">Edit</button></td>`
`</tr>`

add a ng-click event to the row or add a new column "edit" and insert a button into this new column with a ng-click event. In the function for the click event you open the modal window with the plugin you provided or the ui-bootstrap modal window. 
In the modal window you can use input fields or radio buttons or what ever.
Both plugins have a callback function when you close the modal window. 
In this callback you can transfer the changed columns into the smart-table controller and override the old row data.
