### ISSUE TITLE
st-persist example is not working with st-pipe

### ISSUE THREAD

**Issue by johnico** [lorenzofox3/Smart-Table#748]
Hi . this example is not working at all with server pagination 
http://plnkr.co/edit/ekwiNt?p=preview

it saved only the data of first page and default sort in local storage and did not update the table

my pipe function :

`    this.callServer = function callServer(tableState) {

        vm.isLoading = true;
        var pagination = tableState.pagination;
        var start = pagination.start || 0;  
        var number = pagination.number || 10

        vm.submit = function (){
            vm.isLoading = true;

            $scope.filtersForm.$setPristine();
            serverCall(0, 10, tableState,searchObj);
            tableState.pagination.start = 0;
        }
        serverCall(start, number, tableState,searchObj);

      };
`

**Comment by lorenzofox3** [comment]
Not sure to understand with only what you have provided. But the st-persist directive only saves the table state, not the data, so it can be restored when the table is created. However the pipe function should be called with that persisted state when you recreate your table. 

Note: st-persist is more an example on how to approach the issue, not a bullet proof module. Your use case might need some adjustments
