### ISSUE TITLE
Pagination issue

### ISSUE THREAD

**Issue by wipronaveen21** [lorenzofox3/Smart-Table#749]
I have created angular js ng table and chnaging the state on click of a row.

Issue: If i click on the row of second page(3rd or 4th etc ) of the ngtable, ngtable is again showing the first page.

Please let the fix for this.

My js file.

$scope.tableParams = new NgTableParams({count: 5, sorting: {name: 'asc'}   
            }, { counts:[5, 10, 15], dataset: $scope.tableData});

         
  
My HTML file.

    <table ng-table="tableParams" class="table table table-striped table-hover table-bordered lctable" show-filter="true">
        <tr ng-repeat="lcData in $data" ng-class="{'selected-row':$index == selectedRow}" ui-sref=".lcTabs({id: lcData.id})" ui-sref-opts="{reload: true}" >

**Comment by MrWook** [comment]
Hello @wipronaveen21,

i think you are in the wrong repository.
This is SmartTable not [ngTable](https://github.com/esvit/ng-table)

**Comment by lorenzofox3** [comment]
Thanks @MrWook . I see you are quite helpful with the issues, would you like to drop me an email so I can contact you? I can't find a public email of yours. Thanks

**Comment by wipronaveen21** [comment]
Please let me your email id

**Comment by lorenzofox3** [comment]
Hi, As @MrWook said, you are in the wrong repository. I don't know ng-table, you should ask your question in their repository
