### ISSUE TITLE
Using st-sort with dynamic field name

### ISSUE THREAD

**Issue by bgadiel** [lorenzofox3/Smart-Table#751]
Hi,
My issue is related to issue #381.
I am using st-sort with complete dynamic data - I dont know what would be the titles, nor coulmns count. I am able to show the data fine, but when I try to sort, it fails over table header where there is a space.

Example:
when the title is 'Annual Revenue', than the following line fails (in stSort directive):
`var getter = $parse(predicate); //predicate = 'Annual Revenue''`

Which results in the following error:
Error:[$parse:syntax] Syntax Error: Token 'Revenue' is an unexpected token at column 8 of the expression [Annual Revenue] starting at [Revenue].

If I change st-sort="{{ title }}" to st-sort="title " than the sorting is not working.

Can anyone help me on this plz?

[Plnkr](http://plnkr.co/edit/Yb0M8yumCWl0H6e2ywFh?p=preview): http://plnkr.co/edit/Yb0M8yumCWl0H6e2ywFh?p=preview
{{ row[title] }} does not work in this plnkr (??), but it works on my app, so I just put the complete row in each iteraion

HTML:
```
<table st-table="vm.preview_data.data" st-safe-src="vm.table_data" class="table table-striped" mtgo-search-watch="vm.search" width="100%">
            <thead class="table-header">
            <tr>
                <th class="text-center"
                    st-sort="{{ title }}"
                    st-class-ascent="icon min-icon-up-open-mini"
                    st-class-descent="icon min-icon-down-open-mini"
                    width="{{100/vm.preview_data.titles.length}}%"
                    ng-repeat="title in vm.preview_data.titles">{{ title }}
                </th>
            </tr>
            </thead>
            <tbody>
            <tr ng-repeat="row in vm.preview_data.data">
                <td class="text-center" ng-repeat="title in vm.preview_data.titles">{{ row[title]}}</td>
            </tr>
            </tbody>
            <tfoot>
            <tr>
                <td colspan="10" class="text-center">
                    <div st-pagination="" st-items-by-page="10" st-displayed-pages="5"
                         st-template="st-pagination.html"></div>
                </td>
            </tr>
            </tfoot>
        </table>
```

Angular version: 1.6.2
Smart table version: 2.1.8

**Comment by MrWook** [comment]
Hello @bgadiel,

the error occures because of the whitespace inside the key name 'Annual Revenue'. Get rid of whitespaces  inside of key names and it should work fine

**Comment by bgadiel** [comment]
Thanks.
Could you elaborate what is causing this bug and if there's a way to workaround this on the directive level? 
Sorry, but I don't have control over the key names coming from the server. It also could be a 3-word title with whitespace.

**Comment by MrWook** [comment]
Hello @bgadiel,

The problem get cause by plain Javascript. An Object key name in Javascript is not allowed to have a whitespace in it because if you have a $scope variable "test 2" you can't access it by using the Object decleration `$scope.test 2` but you could acces it by the associative array decleration `$scope["test 2"]`.
Unfortunately the angular $parser is using Object's, so it can't handle whitespace in key names.

I hope that you understand this explanation even if my english isn't that well.

The only thing you can do is to change the data you receive before it get transmittet to the smartTable.

**Comment by bgadiel** [comment]
thank you very much for detailed explanation!
