### ISSUE TITLE
input data is updated only on current page

### ISSUE THREAD

**Issue by bgadiel** [lorenzofox3/Smart-Table#757]
Hello,
I use st-table where one on the table data is a checkbox.
I wish to implement a 'Reset' functionality, which updates this checkbox to false for all table.
My issue is that the button is only updating the values for the active page when I click the button and not updating the rest of the pages. i.e - if I click the Reset button on Page #2 than Page #1 is not updated.
Any ideas please?
plnkr: [https://plnkr.co/edit/f9nEBnBu8bPsiZYgSiCx?p=preview](https://plnkr.co/edit/f9nEBnBu8bPsiZYgSiCx?p=preview)

**Comment by MrWook** [comment]
Hello @bgadiel 

you need to delete `scope.rowCollection` from the script.js
The data is binded over the `st-safe-src` attribute

[plnkr](https://plnkr.co/edit/np5ZVs6NW4psVDUPIpSl?p=preview)

**Comment by bgadiel** [comment]
Thanks a lot!
