### ISSUE TITLE
'WWAHost.exe' (Script): Unloaded 'Sourcemap (ms-appx-web://com.yxz.pqr/www/vendor/angular-smart-table/dist/smart-table.js)'

### ISSUE THREAD

**Issue by MilindSuryawanshi** [lorenzofox3/Smart-Table#758]
I am facing above error, while Running my cordova app for windows 10.
I can run the app, and see splash loading and then my login screen for fraction of second. After that white screen is appearing. 

**Detailed-**
So as soon as I run the app on simulator, I can see Log-1, which looks fine (as the smart table is loaded). however as soon as my login screen got visible, Log-2 prints on the console and I can see the blank screen on simulator.

 
Log-1. 'WWAHost.exe' (Script): Loaded 'Sourcemap (ms-appx-web://com.xyz.pqr/www/vendor/angular-smart-table/dist/smart-table.js)'. 

Log-2. 'WWAHost.exe' (Script): Unloaded 'Sourcemap (ms-appx-web://com.xyz.pqr/www/vendor/angular-smart-table/dist/smart-table.js)'
The program '[25340] WWAHost.exe' has exited with code 1 (0x1).

I am using "angular-smart-table": "~2.0.1", declare in my bower.json
My Angualr version is "angular": "~1.3",

Can any one help me in it ?

**Comment by lorenzofox3** [comment]
I don't think that is related to this repository
