### ISSUE TITLE
st-template does not work with webpack

### ISSUE THREAD

**Issue by Pyrolistical** [lorenzofox3/Smart-Table#765]
Smart table version 2.1.8
Angular version any

st-template only takes in an url, which is harder to use with webpack. Webpack is easier to work with when you are only dealing with content, so if st-template took a string containing the html, then it would work well with webpack.

I propose we add st-template-url, warn if an url is given to st-template and accept html string to st-template.

**Comment by MrWook** [comment]
Hello @Pyrolistical,

isn't webpack a bundler? Why is it harder to use st-template with a bundler? The url is for angular routing so you define a template with:
```html
<script type="text/ng-template" id="template_test">
    <div>
         <span>I am a template</span>
    </div>
</script>
```
You can just add this code snippet under your smart-table html

After that you can use "template_test" as an "url" for st-template. I don't see a problem there
