### ISSUE TITLE
Fixed header row during loading

### ISSUE THREAD

**Issue by johnico** [lorenzofox3/Smart-Table#766]
Hi - im using pipe to loading data from server but on click on sort or on pagination the header row (th) did not fixed , and its looks bad (will try to share plunker, is not possible right now) .
what is want is that the header row will always fit to the width - because when there is a data the width is different the the table is empty and we show just loading.

**Comment by MrWook** [comment]
Hello @johnico,

i have no idea what you talking about....
Can you create a plunker for your problem and check the guidelines. So your "issue" won't be closed

**Comment by johnico** [comment]
Hi just meant that i what the header row will be fixed even when I click on sort or server pagaintaion. 
thx

**Comment by MrWook** [comment]
Hello @johnico,

i guess you mean like the example from  [Smart-Table](http://lorenzofox3.github.io/smart-table-website/#section-sort). 
Just add a fixed width for it or use another icon for no sorting like this from [Font Awsome](http://fontawesome.io/icon/sort/).
In addition you could change the placement from the icon from `before `to `after`.

Or do you mean the loading from the body like in the example from [Smart-Table](http://lorenzofox3.github.io/smart-table-website/#section-pipe) but here is the header fixed so i'm really not sure what you talking about sorry
