### ISSUE TITLE
Sorting with asynchronously received data

### ISSUE THREAD

**Issue by blackhearted** [lorenzofox3/Smart-Table#769]
If data is received asynchronously and not available at the moment of table creation - table is sorted differently.

Data "received"
$scope.displayed.push({
        firstName: "A1",
        balance: 300
      });
      $scope.displayed.push({
        firstName: "A2",
        balance: 200
      });
      $scope.displayed.push({
        firstName: "A3",
        balance: 100
      });

If it is within $timeout table will look like. Note sorting icon on balance column is wrong:
http://plnkr.co/edit/8B0Jy8bq1BDPdnU6bFGl?p=preview
first name	balance
A1	                300
A2	                200
A3	                100

If it is synchronous:
http://plnkr.co/edit/ruf2LunDF3pQUMXCD0Zz?p=preview
first name	balance
A3	                100
A2	                200
A1	                300

**Comment by MrWook** [comment]
Hello @blackhearted,

In the Sort section of the [documentation ](http://lorenzofox3.github.io/smart-table-website/#section-sort) you can see that st-sort-default can have "true" or "reverse" as a value not "default" like in your example.
Also if you want to use a asynchronously call to receive data you need to use `st-safe-src` like in the second section of [The Basic](http://lorenzofox3.github.io/smart-table-website/#section-basics)
