### ISSUE TITLE
Filter with click of a button

### ISSUE THREAD

**Issue by Fossil01** [lorenzofox3/Smart-Table#770]
I would like to filter some table columns by the click of a button. Is this possible and if so, how?

Lets say I have a column USERS with 3 rows: John, John, William.

Now I have a button:
`<button ng-click="filter('John')">John</button>`
This should make the table only show Users.John.

This button would preferably be placed outside of the table.

**Comment by MrWook** [comment]
Hello @Fossil01,

if you are using the pipeline you could adjust the `tablestate` by yourself.

It would be good if you provide us with some more informations about your situation, a plunker would be perfect.
