### ISSUE TITLE
Refresh table with with out page load

### ISSUE THREAD

**Issue by smohammedyasin** [lorenzofox3/Smart-Table#772]
Hello,

This is not an issue,

I want to know how to refresh table with out reload complete page. and i'm using http$ for CRUD

please give me any example which is using server side data.

Appreciate for quick and best response.

**Comment by MrWook** [comment]
Hello @smohammedyasin,

if you'r using the pipeline just trigger it again and if you don't use the pipeline just update the variable with the data. 
At the end it's two way databinding everything you do with the variable will be displayed in the table if you are using the smartTable right
