### ISSUE TITLE
Smart Table paging is showing more pages than expected

### ISSUE THREAD

**Issue by mostafaasad** [lorenzofox3/Smart-Table#774]
I am using Smart table in angularjs application. In the pagination it is showing extra pages which don't have the data. How can I display the exact number of pages instead of extra pages?

For clarification, I have 94 records, 15 per page so there will be 7 pages , but the pagination is showing 10 pages, after 7th page there is no data in 8-10th pages.
Please suggest how can I resolve this.

**Comment by MrWook** [comment]
Hello @mostafaasad,

can you provide us with more information?
Like do you use a pipeline or not? A plunker with an example of your problem would be perfect

**Comment by mostafaasad** [comment]
Hi @MrWook,
I am using st-table in angularjs view and using the pagination where the pages are being displayed more than what the actual pages are. Extra pages with empty data are being displayed.
BTW, I am using server side data in the view.

Regards,
Mostafa

**Comment by MrWook** [comment]
Hello @mostafaasad,

unfortunately this doesn't answer my question. You wrote the same things as before except that you mentioned that you get the data from a Server. This could mean that you using a pipeline or that you use a normal http request. I'm still lacking of information.
I just assume that you are using a [pipeline](http://lorenzofox3.github.io/smart-table-website/#section-pipe) if that's the case:

>  you must set in your pipe function, the total number of pages as smart-table has no clue about your dataset and this information has to come from your server.

If you don't use the pipeline be sure that you are using the st-safe-src when you get the data asynchronously.
Also you can set the items by page with `st-items-by-page` and the displayed pages with `st-displayed-pages,` pls look into the [documentation](http://lorenzofox3.github.io/smart-table-website/#section-pagination)

**Comment by kvharish** [comment]
Hello @mostafaasad , 

Since you are using pipeline, I would recommend you to get the total number of records from the api response.

You are showing 15 records per page so in your html you will be including st-items-by-page="15"

Say you are getting the total number of records as 94 in your api response then tableState.pagination.numberOfPages = Math.ceil(data.totalNumbersOfRecords / itemsByPage);

Hope it helps.
