### ISSUE TITLE
Angular 1.5 x  component and accessing smart-table object via ctrl argument.

### ISSUE THREAD

**Issue by cwoodland** [lorenzofox3/Smart-Table#776]
Hello,
This is more of a question than an issue.
I am running angular 1.5.
Smart-table version 2.1.8
I am using angular 1.5 components and want to get to the exposed smart-table object so I can adjust the search predicate.
In the instructions, in the link function, smart-table is exposed via the ctrl argument when using a directive.
Is there a way to grab this same object within a component?

Thanks

**Comment by cwoodland** [comment]
Thanks

**Comment by lorenzofox3** [comment]
Sorry, I am not very familiar with "component". Hope you have found a solution
