### ISSUE TITLE
Smart Table compatibility with Angular 4.

### ISSUE THREAD

**Issue by alokpandeyrc** [lorenzofox3/Smart-Table#781]
## Hello contributor ! 

Does Smart Table works with Angular 4  ?.

☑ I have searched through the issue section and on [stackoverflow](http://stackoverflow.com/questions/tagged/smart-table?sort=newest&pageSize=30) if my issue has already been raised. 
☑ I have provided Angular version.
☑ I have provided Smart table version.
☑I have set a precise description of my problem, mentioning the expected result.
☑ I have given a way to reproduce my issue, by providing a <strong>running example</strong>, I can use [plunkr](http://plnkr.co/). Note if you want to mimic ajax loading behaviour you can use [$timeout](https://docs.angularjs.org/api/ng/service/$timeout) angular service or [$httpBackend](https://docs.angularjs.org/api/ng/service/$httpBackend).

Note that it not all the above checkbox can be marked as checked the issue will immediately be closed. Thanks for your understanding.

And don't forget to close you issue when it is solved !

Thanks again for your contribution.

**Comment by lorenzofox3** [comment]
It is not supported yet. It will likely come as a binding for https://smart-table.github.io/www/dist/ but I have not plan to work on it at the moment
