### ISSUE TITLE
I am getting 404 (Not Found) while calling Pagination.html  file

### ISSUE THREAD

**Issue by haribansh** [lorenzofox3/Smart-Table#787]
## Hello contributor ! 

Please before you submit your issue, make sure all the below can be checked (note if anything is expected, you can simply add it under the relevant checkbox)

- [ X] I have searched through the issue section and on [stackoverflow](http://stackoverflow.com/questions/tagged/smart-table?sort=newest&pageSize=30) if my issue has already been raised. 
- [X ] I have provided Angular version. 1.6.4
- [ X] I have provided Smart table version. 2.1.8
- [X ] I have set a precise description of my problem, mentioning the expected result.
I am using MVC model with Angularjs and razor view. I am trying to call Pagination.html under st-template. But it is showing 404 not found error.Please someone help me and let me know, i can i call .html page under st-template (razor view page) in MVC model. Sorry, I am new to github tool. so I have no idea how to post issues.
- [x] I have given a way to reproduce my issue, by providing a <strong>running example</strong>, I can use [plunkr](http://plnkr.co/). Note if you want to mimic ajax loading behaviour you can use [$timeout](https://docs.angularjs.org/api/ng/service/$timeout) angular service or [$httpBackend](https://docs.angularjs.org/api/ng/service/$httpBackend).

Note that it not all the above checkbox can be marked as checked the issue will immediately be closed. Thanks for your understanding.
![image](https://user-images.githubusercontent.com/12287100/28340768-e2c8a224-6bde-11e7-8d4a-b197187ac654.png)

And don't forget to close you issue when it is solved !

Thanks again for your contribution.

**Comment by lorenzofox3** [comment]
it is just that the url pagination.html to your custom template file is wrong
