### ISSUE TITLE
Any plans for a smart-table version compatible with Angular?

### ISSUE THREAD

**Issue by OhioGuy67** [lorenzofox3/Smart-Table#790]
Is there any plans to create a smart-table version that is compatible with the latest Angular (aka Angular 4 I believe)?

**Comment by MrWook** [comment]
Hello @OhioGuy67,

look what lorenzofox3 wrote in #781.
It's only 26 days ago that he answerd this question, please use the search function.

**Comment by OhioGuy67** [comment]
I did do a search but for some reason I didn't see that post.  Thanks for the info.
