### ISSUE TITLE
CheckBox disable in ng2 smart table

### ISSUE THREAD

**Issue by jeevitha8123** [lorenzofox3/Smart-Table#793]
Hello  ! 
in table list i need to disable checkbox once the status(yes,no) is yes . The status option in drop down 
anyone please help me for this issue 
my angular code is 

<div class="tile-body overflow-x-scroll" >
		<img *ngIf = "loading"  src={{global.image.load}}  height="25px" style="margin-left: 420px;"/>
		
		<ng2-smart-table [settings]="settings" [source]="source" (edit)="editPreleveur($event)" (delete)="deletePreleveur($event)" (userRowSelect)="onUserRowSelect($event)" (onMultipleSelectRow)="onMultipleSelectRow(row)" 
            *ngIf = "source"></ng2-smart-table>

		<div class="row">
			<div class="input-field col s1.5">
				<select class="browser-default" name = "" (change)="bulkActionStatus($event.target.value)">
					<option value="" disabled selected>Select</option>
					<option *ngFor = "let n of listStockStatuses" [value] = "n.id" >{{n.name}}</option>					
				</select> 
			</div>
			
		</div>
	</div>

**Comment by MrWook** [comment]
Hello @jeevitha8123,

SmartTable is a module for Angular 1, didn't know you can use those so freely in Angular 2.

I don't think that i really understand what you are trying to achieve there.

Do you want to disable checkboxes that are in a column of the SmartTable when the status of the dropdown is "yes"?
And this dropdown is outside of the SmartTable?

But i think you could add this to the checkbox html, i guess...?
```html
*ngDisabled="`DROPDOWNMODEL` == 'yes'"
```

**Comment by lorenzofox3** [comment]
wrong repo https://github.com/akveo/ng2-smart-table
