### ISSUE TITLE
CallServer fired moving through inputs when placeholder is set

### ISSUE THREAD

**Issue by ardennext99** [lorenzofox3/Smart-Table#798]
## Hello contributor ! 

Hi, first thanks for your work.
I notice an unwanted behavior when filter's placeholder is set.
Moving through input filters with placeholder set to some value (without typing anything) the  "pipe" event is fired, and the "CallServer" method is launched. Moving through input filters with placeholder set to "" that does not happen.
I expect that if the input filters not change, the pipe event souldn't be fired in both situations.

AngularJS v1.6.5
SmartTable v2.1.8

**Comment by lorenzofox3** [comment]
Hi, can you provide a reproducible example please ?
