### ISSUE TITLE
Did you drop the support of bower in 2.1.9?

### ISSUE THREAD

**Issue by Getz85** [lorenzofox3/Smart-Table#802]
AngularJS 1.6.6
SmartTable 2.1.9

My grunt build task doesn't inject the line  `<script src="bower_components/angular-smart-table/dist/smart-table.js"></script>` in my html file as it did with the version 2.1.8.

After a quick look in the commit, it seems that you removed the bower.json file. I know bower is being deprecated, but if you really want to drop bower support, maybe you should release a major version instead of a bug fix, because it breaks an existing feature. In addition, the README is still indicating to install smart-table that
> The easiest way is to run bower install angular-smart-table

**Comment by foxdog05000** [comment]
I couldn't agree more!

**Comment by RajShah94** [comment]
💯 spent all night yesterday trying to find what went wrong with bower!

**Comment by ouranos** [comment]
:100: 
Same here, our build is completely broken and it took me a while to figure out why smart-table was not picked up by wiredep...

**Comment by BrunoChauvet** [comment]
We had similar issue, wasting time to figure out what went out of whack

**Comment by alexnoox** [comment]
This is very confusing as the README still promote bower to install smart-table. Could we simply revert this file?

**Comment by foxdog05000** [comment]
Indeed the Readme is not up to date! If in 2.1.9 you remove the Bower support! Remember to mention it prominently!

**Comment by SimonLissack** [comment]
This tripped me up as well, the quick fix (apart from downgrading) was to put this in overrides in bower.json:

```
    "angular-smart-table" : {
        "main": [
            "dist/smart-table.js"
        ]
    }
```

(You can also use dist/smart-table.min.js for the minified version)

**Comment by foxdog05000** [comment]
It works very well, but it's like putting in a patch. The end of the Bower support must be provided correctly in a well-defined version. And mostly mentioned somewhere!

**Comment by isaachinman** [comment]
Also experienced a broken build - production site unexpectedly taken offline due to the poor management of this project. At 16k downloads per month you'd think the maintainers would understand semver.

**Comment by lorenzofox3** [comment]
Sorry that was not on purpose (it is actually an [older commit](https://github.com/lorenzofox3/Smart-Table/commit/743914ed9e10b020112f3b753aa3241c233a967d))

@isaachinman Instead of insulting OS maintainer who spend their free time on providing module you can use on your commercial projects you should thank them... 
 and by the same occasion review your continuous deployment system because if a dependency issue makes your production go down, well I am not sure your product can be trusted !

**Comment by SimonLissack** [comment]
thanks @lorenzofox3 is deprecating bower in the pipeline, should we prepare for it?
