### ISSUE TITLE
Displayed Collection always empty even when safe src (base) is populated 

### ISSUE THREAD

**Issue by karanaditya993** [lorenzofox3/Smart-Table#807]
Angular Version: 1.4.3
Smart Table Version: 2.1.6

Hello,

I am experiencing an issue with smart table where I am loading data through an st-safe-src attribute via api. The safe-src base collection is being populated, however, the st-table displayed collection is always an empty array. **Note**: I have declared the displayed collection as an empty array on controller initialization, which I thought may be causing the issue. However, I removed this declaration and am still seeing that the displayed collection is always empty while the base collection is populated upon api success. Has anyone else experienced this issue? If so, how did you resolve it? Thanks very much.

**Comment by lorenzofox3** [comment]
Hi, can you provide a running example ?
