### ISSUE TITLE
Issues injecting this dependency with wiredep

### ISSUE THREAD

**Issue by gchamon** [lorenzofox3/Smart-Table#812]
We are currently migrating away from bower, but as it is a rather complex task with a lot of refactoring, we decided for now to resolve the packages using Yarn and to link the new installation folder with symlinks, as is the result of using `bower-away`, effectively linking all the dependencies with `wiredep`. But this is just for context. A similar issue happens when using bower to install this dependency.
The file `bower.json` is missing completetly when resolving with yarn. When resolving with bower, there is indeed a `.bower.json` (notice it is a hidden file) but this file doesn't have a `main` field indicating the path to `./dist/smart-table.js`.
`wiredep` uses those files to wire these dependencies correctly.
We link a lot of dependencies (not a good thing, sure, but we are a small team and we need to get things done fast =/ ) and this is the only one that doesn't pull the `bower.json` file.
I saw there was a closed issue indicating that the related file was deleted in a commit and then reverted back, but I am still not being able to pull this file.

Is there something I can do to force downloading the required file?

**Comment by lorenzofox3** [comment]
Hello, to be honest I don't. It must be something related to a cache. Have you tried clearing local caches ? 
Note that the package is also available through npm which could make things easier for you
