### ISSUE TITLE
Pagination reset to first page after removing row from second page

### ISSUE THREAD

**Issue by syeddk** [lorenzofox3/Smart-Table#815]
Hi,

I have 27 rows table with 25 max rows per page, when i try to delete a row from second page pagination is reset to first page. 

i have splice in delete method
ex: resultarray.splice(26, 1);
<p-dataTable  [value]="resultarray" [rows]="25" paginator="true" paginatorPosition="top" pageLinks="0">

i am using angular 2.3.1 and primeng 2.0.3 versions

Any suggestions please

**Comment by lorenzofox3** [comment]
Hi, I don't see how I can possibly help you. Moreover, I have no idea what your markup refers to, dataTable ? 
please provide a running example
