### ISSUE TITLE
Smart Table st-search=“” searching in the whole array, not on the displayed table

### ISSUE THREAD

**Issue by Poloten** [lorenzofox3/Smart-Table#818]
I have a JSON data array, (array.id, array.name, array.telephone), I display several values in the table using AngularJS {{array.id}} and {{array.name}}. But if I add a search with st-search = "" it searches for the whole array (including array.phone). How do I search only on the displayed values on a table (array.id, array.name) not the whole array?

**Comment by lorenzofox3** [comment]
I am unfraid this is not possible, you'll need to "prepare" you data before you bind it to smart-table in your controller.
```Javascript
const yourData =[ /*...*/];
const toBind = yourData.map(({id,name}) => ({id, name}))

```

**Comment by Poloten** [comment]
Can I search for the some columns ( 'id' 'name')? `st-search="( 'id' 'name')" `
What I can do for it?
