### ISSUE TITLE
st-sort-default="true" not working when table first loads.

### ISSUE THREAD

**Issue by trishala1234** [lorenzofox3/Smart-Table#830]
Hi,

I am using angular version 1.3.5 
Smart table version is 1.4.5

I am using smart table to display data that is received dynamically using ajax call.
I wish to sort the table coloumns and am using st-sort for the same. When clicking on the sorting icons, the sorting works correctly, as expected, both ascending and descending order.

However, when the table first loads, the requirement is to sort the  coloums in ascending order by default. For this am using **st-sort-default="true"** 

But this does not work. When the table is loaded for the first time, it displays the data in the coloum in natural  order(without any sorting).

The below is the piece of code am using
<tr>
						<th ng-repeat="column in columns" width="{{column.width}}" ng-class="column.filter" st-sort-default="true" st-sort="{{column.field}}"  st-skip-natural="true" data-name="{{column.field}}"> {{column.displayName}}</th>
					</tr>

Could you please help me know what is the issue. Just reiterating, the sorting works correctly when clicking on the sorting icons on the column header.

**Comment by lorenzofox3** [comment]
can you please provide a running example? thanks

**Comment by supervos** [comment]
Are you using the stSafeSrc attribute?

I had the same issues with the first load of the table and using this attribute fixed the issue.
